export const ANSWER_STATUSES = Object.freeze({
  VERIFIED: "verified",
  COMPUTED: "computed",
  TO_BE_VERIFIED: "to_be_verified",
  OMITTED_FOR_TEMPLATE: "omitted_for_template",
  HUMAN_REVIEWED: "human_reviewed",
  BLOCKED_VISUAL_DEPENDENCY: "blocked_visual_dependency",
  INVALID: "invalid"
});

export const VALIDATOR_ASSIGNABLE_ANSWER_STATUSES = Object.freeze([
  ANSWER_STATUSES.COMPUTED,
  ANSWER_STATUSES.TO_BE_VERIFIED,
  ANSWER_STATUSES.OMITTED_FOR_TEMPLATE,
  ANSWER_STATUSES.BLOCKED_VISUAL_DEPENDENCY,
  ANSWER_STATUSES.INVALID
]);

export const FORBIDDEN_VALIDATOR_ANSWER_STATUSES = Object.freeze([
  ANSWER_STATUSES.VERIFIED,
  ANSWER_STATUSES.HUMAN_REVIEWED
]);
