export const WARNING_CODES = Object.freeze({
  W_CHINESE_NUMERAL_VARIANT: "W_CHINESE_NUMERAL_VARIANT",
  W_TEXT_FALLBACK_ONLY: "W_TEXT_FALLBACK_ONLY",
  W_HUMAN_REVIEW_RECOMMENDED: "W_HUMAN_REVIEW_RECOMMENDED",
  W_RUNTIME_GENERATED_NOT_STORED: "W_RUNTIME_GENERATED_NOT_STORED"
});

export const WARNING_CODE_VALUES = Object.freeze(Object.values(WARNING_CODES));
