import test from "node:test";
import assert from "node:assert/strict";
import {BATCH_A_SELECTOR_AVAILABILITY,auditP03F35PublicSelectorComposition,listBatchAKnowledgePointAvailabilityBySource} from "../../site/modules/curriculum/registry/batch-a-selector-p03f35-extension.js";
import {G4B_U06_P03F35_KP_ID,G4B_U06_P03F35_PATTERN_GROUP_ID,G4B_U06_P03F35_PATTERN_SPEC_ID,P03F35_REQUIRED_CAPABILITY_IDS,auditG4BU06P03F35SelectorProjection} from "../../site/modules/curriculum/registry/g4b-u06-rank9-decimal-scale-selector-projection-p03f35.js";
import {validateP03F35PatternDefinitions} from "../../site/modules/curriculum/batch-a/source-pattern-full-product-p03f35-extension.js";
import {buildBatchABrowserPlan} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p03f35.js";
import {generateBatchABrowserQuestions} from "../../site/modules/curriculum/batch-a/batch-a-browser-question-router-p03f35.js";
import {validateBatchABrowserPlan,validateBatchABrowserQuestions} from "../../site/modules/curriculum/batch-a/batch-a-browser-validator-p03f35.js";

test("P03F35 readback locks current 3/3 and successor 4/2 with 32/231 global inventory",()=>{assert.equal(auditG4BU06P03F35SelectorProjection().ok,true);assert.equal(auditP03F35PublicSelectorComposition().ok,true);assert.deepEqual([BATCH_A_SELECTOR_AVAILABILITY.sourceCount,BATCH_A_SELECTOR_AVAILABILITY.visibleCount],[32,231]);const availability=listBatchAKnowledgePointAvailabilityBySource("g4b_u06_4b06");assert.deepEqual([availability.visibleCount,availability.hiddenPendingCount,availability.notSelectableCount],[4,2,0]);});

test("P03F35 target plan binds one numeric PatternSpec and exact three-capability union",()=>{assert.equal(validateP03F35PatternDefinitions().ok,true);const plan=buildBatchABrowserPlan({sourceId:"g4b_u06_4b06",selectedKnowledgePointIds:[G4B_U06_P03F35_KP_ID],selectedPatternGroupIds:[G4B_U06_P03F35_PATTERN_GROUP_ID],questionCount:24,generationSeed:"p03f35-core"});assert.deepEqual(plan.patternSpecIds,[G4B_U06_P03F35_PATTERN_SPEC_ID]);assert.equal(plan.questionMode,"numeric");assert.equal(plan.genericFallbackAllowed,false);assert.equal(validateBatchABrowserPlan(plan).ok,true);});

test("P03F35 generates 24 exact decimal scale witnesses balanced across four scale factors",()=>{const result=generateBatchABrowserQuestions({sourceId:"g4b_u06_4b06",selectedKnowledgePointIds:[G4B_U06_P03F35_KP_ID],selectedPatternGroupIds:[G4B_U06_P03F35_PATTERN_GROUP_ID],questionCount:24,generationSeed:"p03f35-core"});assert.equal(result.ok,true);assert.equal(result.questions.length,24);assert.equal(validateBatchABrowserQuestions(result.questions).ok,true);const counts=Object.fromEntries(["10","100","0.1","0.01"].map((factor)=>[factor,result.questions.filter((q)=>q.scaleFactor===factor).length]));assert.deepEqual(counts,{"10":6,"100":6,"0.1":6,"0.01":6});for(const question of result.questions){assert.equal(question.metadata.knowledgePointId,G4B_U06_P03F35_KP_ID);assert.equal(question.metadata.patternGroupId,G4B_U06_P03F35_PATTERN_GROUP_ID);assert.deepEqual(question.metadata.requiredCapabilityIds,P03F35_REQUIRED_CAPABILITY_IDS);assert.equal(question.metadata.applicationClassification,"APPLICATION_NOT_APPLICABLE");assert.equal(question.metadata.globalContextAuthorityPath,null);assert.equal(question.globalContextProduction,null);assert.equal(question.answerType,"decimal");assert.equal(question.finalAnswer.exact,true);}});

test("P03F35 mixed same-source target+prior generation delegates old PatternSpec to predecessor runtime",()=>{const priorSpec="ps_g4b_u06_two_decimal_times_integer_product_numeric";const result=generateBatchABrowserQuestions({sourceId:"g4b_u06_4b06",patternSpecIds:[priorSpec,G4B_U06_P03F35_PATTERN_SPEC_ID],selectedKnowledgePointIds:["kp_g4b_u06_two_decimal_times_integer",G4B_U06_P03F35_KP_ID],questionCount:8,generationSeed:"p03f35-mixed"});assert.equal(result.ok,true);assert.equal(result.questions.length,8);assert.equal(result.questions.some((q)=>q.patternSpecId===priorSpec),true);assert.equal(result.questions.some((q)=>q.patternSpecId===G4B_U06_P03F35_PATTERN_SPEC_ID),true);assert.equal(validateBatchABrowserQuestions(result.questions).ok,true);});
