import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const manifest = JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p03f/slice018-product-admission.manifest.json", import.meta.url), "utf8"));
const claim = JSON.parse(readFileSync(new URL("../../data/curriculum/final-milestone-claims/p03f-w3-slice018-e6-d0-v1.json", import.meta.url), "utf8"));

test("P03F18 D0 closeout binds core current-surface E6 Pixel evidence and preserves Slice019 boundary", () => {
  assert.equal(manifest.status, "PASS_D0_CLOSEOUT_CANDIDATE");
  assert.equal(manifest.admissionState, "E6_ARTIFACT_ACCEPTED_D0");
  assert.equal(manifest.admissionDecision.status, "ADMITTED_D0");
  assert.equal(manifest.expectedCounts.queuePosition, 18);
  assert.equal(manifest.expectedCounts.sourceNodeCount, 1);
  assert.equal(manifest.expectedCounts.newPublicSourceCount, 0);
  assert.equal(manifest.expectedCounts.knowledgePointCount, 1);
  assert.equal(manifest.expectedCounts.patternGroupCount, 1);
  assert.equal(manifest.expectedCounts.patternSpecCount, 1);
  assert.equal(manifest.expectedCounts.numericPatternSpecCount, 1);
  assert.equal(manifest.expectedCounts.applicationPatternSpecCount, 0);
  assert.equal(manifest.expectedCounts.globalContextBindingCount, 0);
  assert.equal(manifest.expectedCounts.requiredCapabilityCount, 2);
  assert.equal(manifest.expectedCounts.publicVisibleKnowledgePointCountForSource, 2);
  assert.equal(manifest.expectedCounts.questionWitnessCount, 18);
  assert.equal(manifest.expectedCounts.answerKeyWitnessCount, 18);
  assert.equal(manifest.exactAcceptance.coreImplementationPrNumber, 522);
  assert.equal(manifest.exactAcceptance.coreImplementationMergeSha, "34282b6282365b1f8b5b4bb8d8e2088523bbdce3");
  assert.equal(manifest.exactAcceptance.coreNodeWorkflowRunId, 30790392563);
  assert.equal(manifest.exactAcceptance.coreNodeWorkflowJobId, 91612479885);
  assert.equal(manifest.exactAcceptance.coreNodeConclusion, "success");
  assert.equal(manifest.exactAcceptance.currentSurfacePrNumber, 523);
  assert.equal(manifest.exactAcceptance.currentSurfaceMergeSha, "b678f5d1fc985d66f291d5e473dac19305824422");
  assert.equal(manifest.exactAcceptance.currentSurfaceNodeWorkflowRunId, 30791255848);
  assert.equal(manifest.exactAcceptance.currentSurfaceNodeWorkflowJobId, 91615071408);
  assert.equal(manifest.exactAcceptance.currentSurfaceNodeConclusion, "success");
  assert.equal(manifest.exactAcceptance.glmS07WorkflowRunId, 30791255843);
  assert.equal(manifest.exactAcceptance.glmS07RecoveredShardJobId, 91618448152);
  assert.equal(manifest.exactAcceptance.glmS07RecoveredShardConclusion, "success");
  assert.equal(manifest.exactAcceptance.glmS07AggregateJobId, 91618633999);
  assert.equal(manifest.exactAcceptance.glmS07AggregateConclusion, "success");
  assert.equal(manifest.exactAcceptance.glmS07ScenarioCount, 90);
  assert.equal(manifest.exactAcceptance.acceptancePrNumber, 524);
  assert.equal(manifest.exactAcceptance.acceptanceWorkflowRunId, 30793658443);
  assert.equal(manifest.exactAcceptance.acceptanceWorkflowJobId, 91622334211);
  assert.equal(manifest.exactAcceptance.acceptanceArtifactId, 8848015560);
  assert.equal(manifest.exactAcceptance.acceptanceArtifactDigest, "sha256:0d0b33c26615acbe06cc636f23019ab0af9bc9d379a97dadae2bfbe9eae46f21");
  assert.equal(manifest.exactAcceptance.acceptancePdfPageCount, 4);
  assert.equal(manifest.exactAcceptance.acceptancePdfByteLength, 21678);
  assert.equal(manifest.exactAcceptance.acceptanceScreenshotCount, 4);
  assert.equal(manifest.exactAcceptance.acceptanceQuestionCount, 18);
  assert.equal(manifest.exactAcceptance.acceptanceAnswerKeyCount, 18);
  assert.deepEqual(manifest.exactAcceptance.acceptancePatternSpecWitnessCounts, {
    ps_g4a_u09_decimal_compose_decompose_decimal_numeric: 18,
  });
  assert.equal(manifest.exactAcceptance.acceptanceDuplicatePromptFindingCount, 0);
  assert.equal(manifest.exactAcceptance.acceptanceOverflowFindingCount, 0);
  assert.equal(manifest.exactAcceptance.acceptanceConsoleErrorCount, 0);
  assert.equal(manifest.exactAcceptance.acceptancePageErrorCount, 0);
  assert.equal(manifest.exactAcceptance.acceptanceSemanticScopeFindingCount, 0);
  assert.equal(manifest.exactAcceptance.acceptanceVisualReview, "PASS");
  assert.equal(manifest.exactAcceptance.acceptanceSemanticReview, "PASS");
  assert.equal(manifest.exactAcceptance.acceptanceAnswerKeyReview, "PASS");
  assert.equal(manifest.exactAcceptance.temporaryAcceptanceWorkflowRetired, true);
  assert.equal(manifest.exactAcceptance.acceptanceCleanupMergeSha, "cd5d9290366bdad3471aa3d3cd8c3018bb8e4c8d");
  assert.equal(manifest.exactAcceptance.acceptanceCleanupNodeConclusion, "success");
  assert.equal(manifest.exactAcceptance.pixelRepairPrNumber, 525);
  assert.equal(manifest.exactAcceptance.pixelRepairMergeSha, "9d10f8bd07c8eddc93806242811d3e1c19c902c8");
  assert.equal(manifest.exactAcceptance.pixelRepairNodeWorkflowRunId, 30795336068);
  assert.equal(manifest.exactAcceptance.pixelRepairNodeWorkflowJobId, 91627566495);
  assert.equal(manifest.exactAcceptance.pixelRepairNodeConclusion, "success");
  assert.equal(manifest.exactAcceptance.finalNodeWorkflowConclusion, "success");
  assert.equal(manifest.mainlineBoundary.queuePositionConsumed, 18);
  assert.equal(manifest.mainlineBoundary.nextQueuePositionStarted, false);
  assert.equal(manifest.mainlineBoundary.newPublicSourceAdded, false);
  assert.equal(manifest.mainlineBoundary.decimalCompareAdded, false);
  assert.equal(manifest.mainlineBoundary.decimalSequenceAdded, false);
  assert.equal(manifest.mainlineBoundary.missingDigitReasoningAdded, false);
  assert.equal(manifest.mainlineBoundary.decimalArithmeticAdded, false);
  assert.equal(manifest.mainlineBoundary.applicationExpansionAdded, false);
  assert.equal(manifest.mainlineBoundary.globalContextExpanded, false);
  assert.equal(manifest.mainlineBoundary.parallelRuntimePipelineAdded, false);
  assert.equal(manifest.mainlineBoundary.nextTask, "P03F_W3DirectProductVerticalSlice019Implementation");

  assert.equal(claim.status, "PASS_D0_CLOSEOUT_CANDIDATE");
  assert.equal(claim.goalDistance, "D0");
  assert.deepEqual(claim.authority.knowledgePointIds, ["kp_g4a_u09_decimal_compose_decompose"]);
  assert.deepEqual(claim.authority.patternSpecIds, ["ps_g4a_u09_decimal_compose_decompose_decimal_numeric"]);
  assert.deepEqual(claim.authority.requiredCapabilityIds, ["cap_decimal_domain_validator", "cap_decimal_number_system"]);
  assert.equal(claim.productResult.d0Complete, true);
  assert.equal(claim.productResult.newPublicSourceCount, 0);
  assert.equal(claim.productResult.classicPublicSurface, "PASS");
  assert.equal(claim.productResult.pixelPublicSurface, "PASS");
  assert.equal(claim.boundaries.slice019Started, false);
});
