import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p03f37.js";
import {parseQueryState} from "../../site/assets/browser/state/query-state.js";
import {listPublicPatternGroupChoices} from "../../site/assets/browser/state/public-pattern-group-selection.js";
import {getCurrentPixelRegistrySnapshot} from "../../site/pixel/pixel-registry-bridge.js";
import {buildBatchABrowserWorksheetDocument} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-r2e-entry.js";
import {G5A_U04_P03F37_GROUP_ID,G5A_U04_P03F37_KP_ID,G5A_U04_P03F37_SOURCE_ID,G5A_U04_P03F37_SPEC_IDS} from "../../site/modules/curriculum/registry/g5a-u04-rank9-equivalent-mixed-selector-projection-p03f37.js";
const sourceText=(path)=>fs.readFileSync(new URL(`../../${path}`,import.meta.url),"utf8");
function search(sourceId=G5A_U04_P03F37_SOURCE_ID){const params=new URLSearchParams({sourceId,selectionMode:"singleKnowledgePoint",questionCount:"24",ordering:"groupedByPattern",answerKey:"1",generationSeed:"p03f37-pages-e2e",columns:"2",rowsPerPage:"4"});params.append("kp",G5A_U04_P03F37_KP_ID);params.append("pg",G5A_U04_P03F37_GROUP_ID);return`?${params.toString()}`;}
test("P03F37 Classic fallback404 and Pixel expose target numeric binding",()=>{for(const surfaceId of["classic","fallback404","pixel"]){const binding=resolvePublicUiCapabilityBinding({sourceId:G5A_U04_P03F37_SOURCE_ID,surfaceId,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G5A_U04_P03F37_KP_ID]});assert.equal(binding.blocked,false);assert.deepEqual(binding.selectedKnowledgePointIds,[G5A_U04_P03F37_KP_ID]);assert.equal(binding.questionType,"numeric");assert.deepEqual(binding.compatiblePatternGroupIds,[G5A_U04_P03F37_GROUP_ID]);assert.deepEqual(binding.depthOptions,[]);assert.deepEqual(binding.contextOptions,[]);}});
test("P03F37 current query-state preserves target KP and PatternGroup deep link",()=>{const state=parseQueryState(search());assert.equal(state.sourceId,G5A_U04_P03F37_SOURCE_ID);assert.equal(state.selectionMode,"singleKnowledgePoint");assert.deepEqual(state.selectedKnowledgePointIds,[G5A_U04_P03F37_KP_ID]);assert.deepEqual(state.selectedPatternGroupIds,[G5A_U04_P03F37_GROUP_ID]);assert.deepEqual(state.selectorWarnings,[]);assert.equal(state.questionCount,24);assert.equal(state.includeAnswerKey,true);});
test("P03F37 query-state stays source-scoped fail closed",()=>{const state=parseQueryState(search("g4b_u05_4b05"));assert.equal(state.selectionMode,"sourceUnit");assert.deepEqual(state.selectedKnowledgePointIds,[]);assert.deepEqual(state.selectedPatternGroupIds,[]);assert.ok(state.selectorWarnings.some((entry)=>entry.code==="selector_id_dropped"));});
test("P03F37 pattern group exposes exactly three target specs while current registry advances through Slice051 to 34/255",()=>{const choices=listPublicPatternGroupChoices([G5A_U04_P03F37_KP_ID]);assert.equal(choices.length,1);assert.equal(choices[0].patternGroupId,G5A_U04_P03F37_GROUP_ID);assert.deepEqual(choices[0].patternSpecIds,G5A_U04_P03F37_SPEC_IDS);const snapshot=getCurrentPixelRegistrySnapshot();assert.equal(snapshot.sourceCount,34);assert.equal(snapshot.visibleKnowledgePointCount,255);assert.equal(snapshot.bySourceId[G5A_U04_P03F37_SOURCE_ID].visibleKnowledgePoints.length,6);assert.equal(snapshot.bySourceId[G5A_U04_P03F37_SOURCE_ID].hiddenPendingCount,1);});
test("P03F37 current worksheet entry generates 24 target questions and 6 logical pages",()=>{const result=buildBatchABrowserWorksheetDocument({sourceId:G5A_U04_P03F37_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G5A_U04_P03F37_KP_ID],selectedPatternGroupIds:[G5A_U04_P03F37_GROUP_ID],patternSpecIds:G5A_U04_P03F37_SPEC_IDS,questionMode:"numeric",questionCount:24,generationSeed:"p03f37-public",includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showQuestionNumbers:true,showAnswerKeyPage:true}});assert.equal(result.ok,true,JSON.stringify(result.errors));assert.equal(result.worksheetDocument.generatedQuestions.length,24);assert.equal(result.worksheetDocument.questionPages.length,3);assert.equal(result.worksheetDocument.answerKeyPages.length,3);assert.equal(result.worksheetDocument.metadata.worksheetAdapter.parallelPipeline,false);});
test("P03F37 current Classic Pixel query-state and worksheet consumers point to P03F51 successors",()=>{assert.match(sourceText("site/assets/browser/public-capability-ui.js"),/public-ui-capability-binding-p03f51\.js/);assert.match(sourceText("site/assets/browser/state/public-pattern-group-selection.js"),/batch-a-selector-p03f51-extension\.js/);assert.match(sourceText("site/assets/browser/state/query-state.js"),/batch-a-selector-p03f51-extension\.js/);assert.match(sourceText("site/pixel/pixel-public-capability-ui.js"),/public-ui-capability-binding-p03f51\.js/);assert.match(sourceText("site/pixel/pixel-registry-bridge.js"),/batch-a-selector-p03f51-extension\.js/);assert.match(sourceText("site/modules/curriculum/registry/batch-a-selector-extension.js"),/batch-a-selector-p03f51-extension\.js/);assert.match(sourceText("site/modules/curriculum/batch-a/batch-a-browser-worksheet-r2e-entry.js"),/batch-a-browser-worksheet-p03f51-extension\.js/);});
test("P03F37 capability audit is gap-free",()=>{const audit=auditPublicUiCapabilityBinding();assert.equal(audit.ok,true,JSON.stringify(audit.errors));assert.ok(audit.slice037AuditCaseCount>0);});
