import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { buildBatchABrowserPlan } from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p03f47.js";
import { generateBatchABrowserQuestions } from "../../site/modules/curriculum/batch-a/batch-a-browser-question-router-p03f47.js";
import { validateBatchABrowserQuestions } from "../../site/modules/curriculum/batch-a/batch-a-browser-validator-p03f47.js";
import { buildBatchABrowserWorksheetDocument } from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p03f47-extension.js";
import { validateP03F47PatternDefinitions } from "../../site/modules/curriculum/batch-a/source-pattern-full-product-p03f47-extension.js";
import { auditP03F47PublicSelectorComposition,listBatchAKnowledgePointAvailabilityBySource,listVisibleBatchAKnowledgePoints } from "../../site/modules/curriculum/registry/batch-a-selector-p03f47-extension.js";
import { G6B_U01_P03F47_KP_ID,G6B_U01_P03F47_SOURCE_ID,G6B_U01_P03F47_SPEC_ID,P03F47_HIDDEN_SIBLING_KP_IDS } from "../../site/modules/curriculum/registry/g6b-u01-rank10-mixed-decimal-fraction-add-sub-selector-projection-p03f47.js";

const authority=JSON.parse(fs.readFileSync("data/curriculum/full-product/p03f/slice047-g6b-u01-rank10-mixed-decimal-fraction-add-sub-authority.json","utf8"));
const single={sourceId:G6B_U01_P03F47_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G6B_U01_P03F47_KP_ID],questionMode:"numeric",questionCount:24,generationSeed:"p03f47-source-witness",includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showQuestionNumbers:true,showAnswerKeyPage:true}};

function gcd(a,b){let x=a<0n?-a:a,y=b<0n?-b:b;while(y){const r=x%y;x=y;y=r;}return x||1n;}
function reduce(numerator,denominator){const g=gcd(numerator,denominator);return {numerator:numerator/g,denominator:denominator/g};}
function decimalRational(text){const [whole,fraction=""]=String(text).split(".");const denominator=10n**BigInt(fraction.length),numerator=BigInt(`${whole}${fraction}`);return reduce(numerator,denominator);}
function fractionRational(question){return reduce(BigInt(question.fractionNumerator),BigInt(question.fractionDenominator));}
function exactExpected(question){const decimal=decimalRational(question.decimal),fraction=fractionRational(question),left=question.decimalLeft?decimal:fraction,right=question.decimalLeft?fraction:decimal;const numerator=question.action==="ADD"?left.numerator*right.denominator+right.numerator*left.denominator:left.numerator*right.denominator-right.numerator*left.denominator;assert.ok(numerator>=0n,"subtraction must remain nonnegative");return reduce(numerator,left.denominator*right.denominator);}

test("P03F47 frozen authority is q047 only and q046 is D0 predecessor",()=>{assert.equal(authority.queueAuthority.queuePosition,47);assert.equal(authority.queueAuthority.sliceId,"p03e_q047_r10_g6b_u01_6b01_profile_mixed_number_domain_c1");assert.equal(authority.queueAuthority.previousSliceD0Complete,true);assert.equal(authority.queueAuthority.previousSliceCloseoutEvidence.acceptedState,"PASS_D0_CLOSED");assert.deepEqual(authority.knowledgePointIds,[G6B_U01_P03F47_KP_ID]);assert.equal(authority.patternSurfaces.length,1);assert.equal(authority.patternSurfaces[0].patternSpecId,G6B_U01_P03F47_SPEC_ID);assert.equal(authority.productBoundary.expectedPublicSourceCountAfterAdmission,33);assert.equal(authority.productBoundary.expectedCurrentPublicKnowledgePointCountAfterAdmission,248);assert.equal(authority.productBoundary.expectedSourceVisibleCountAfterAdmission,3);assert.equal(authority.productBoundary.expectedSourceHiddenCountAfterAdmission,2);assert.equal(authority.productBoundary.expectedSourceNotSelectableCountAfterAdmission,2);assert.equal(authority.changeImpactGate.preflightLevel,"L3");assert.equal(authority.changeImpactGate.full793RouteReplayRequired,false);});

test("P03F47 selector and PatternSpec promote exactly one KP while q047 later-wave siblings stay hidden",()=>{const selectorAudit=auditP03F47PublicSelectorComposition(),patternAudit=validateP03F47PatternDefinitions();assert.equal(selectorAudit.ok,true,selectorAudit.errors.join("\n"));assert.equal(patternAudit.ok,true,patternAudit.errors.join("\n"));assert.equal(selectorAudit.counts.publicSources,33);assert.equal(selectorAudit.counts.publicKnowledgePoints,248);assert.equal(selectorAudit.counts.currentSourceKnowledgePoints,3);assert.equal(selectorAudit.counts.hiddenSiblings,2);assert.equal(patternAudit.patternSpecCount,1);const availability=listBatchAKnowledgePointAvailabilityBySource(G6B_U01_P03F47_SOURCE_ID);assert.equal(availability.visibleCount,3);assert.equal(availability.hiddenPendingCount,2);assert.equal(availability.notSelectableCount,2);assert.deepEqual(new Set(availability.hiddenPendingKnowledgePointIds),new Set(P03F47_HIDDEN_SIBLING_KP_IDS));const visibleIds=new Set(listVisibleBatchAKnowledgePoints().map((row)=>row.knowledgePointId));for(const hiddenId of P03F47_HIDDEN_SIBLING_KP_IDS)assert.equal(visibleIds.has(hiddenId),false);});

test("P03F47 generates 24 unique exact mixed-domain add/sub questions with balanced operations",()=>{const plan=buildBatchABrowserPlan(single),result=generateBatchABrowserQuestions({...single,plan}),validation=validateBatchABrowserQuestions(result.questions??[]);assert.equal(result.ok,true,result.errors?.map((error)=>error.code).join("\n"));assert.equal(validation.ok,true,validation.errors.map((error)=>error.code).join("\n"));assert.deepEqual(plan.patternSpecIds,[G6B_U01_P03F47_SPEC_ID]);assert.equal(plan.genericFallbackAllowed,false);assert.equal(result.questions.length,24);assert.equal(new Set(result.questions.map((question)=>question.blankedDisplayText)).size,24);assert.equal(result.questions.filter((question)=>question.action==="ADD").length,12);assert.equal(result.questions.filter((question)=>question.action==="SUBTRACT").length,12);for(const question of result.questions){assert.equal(question.patternSpecId,G6B_U01_P03F47_SPEC_ID);assert.notEqual(question.leftDomain,question.rightDomain);assert.equal(question.finalAnswer.exact,true);assert.equal(question.globalContextProduction,null);const expected=exactExpected(question);assert.equal(BigInt(question.resultNumerator),expected.numerator);assert.equal(BigInt(question.resultDenominator),expected.denominator);assert.equal(BigInt(question.finalAnswer.numerator),expected.numerator);assert.equal(BigInt(question.finalAnswer.denominator),expected.denominator);}});

test("P03F47 source witness preserves 1.8 + 1 3/4 as direct-source arithmetic evidence",()=>{const result=generateBatchABrowserQuestions(single);assert.equal(result.ok,true,result.errors?.map((error)=>error.code).join("\n"));const witness=result.questions[0];assert.equal(witness.promptText,"1.8 + 1 3/4 = ?");assert.equal(witness.answerText,"3 11/20");assert.equal(witness.action,"ADD");assert.equal(witness.metadata.sourceWitness,true);assert.equal(witness.metadata.sourceAuthorityMode,"R02_DIRECT_SOURCE_ARITHMETIC");assert.equal(witness.metadata.directSourcePromptVerbatim,false);});

test("P03F47 sourceUnit composes conversion, comparison and add/sub through one shared router",()=>{const options={...single,selectionMode:"sourceUnit",selectedKnowledgePointIds:[],generationSeed:"p03f47-source-unit"},plan=buildBatchABrowserPlan(options),result=generateBatchABrowserQuestions({...options,plan}),validation=validateBatchABrowserQuestions(result.questions??[]);assert.equal(result.ok,true,result.errors?.map((error)=>error.code).join("\n"));assert.equal(validation.ok,true,validation.errors.map((error)=>error.code).join("\n"));assert.equal(plan.patternSpecIds.length,4);assert.equal(new Set(plan.patternSpecIds).size,4);assert.equal(new Set(result.questions.map((question)=>question.patternSpecId)).size,4);for(const patternSpecId of plan.patternSpecIds)assert.equal(result.questions.filter((question)=>question.patternSpecId===patternSpecId).length,6);const kpIds=new Set(result.questions.map((question)=>question.metadata?.knowledgePointId));assert.equal(kpIds.size,3);assert.equal(kpIds.has(G6B_U01_P03F47_KP_ID),true);});

test("P03F47 worksheet stays on shared pagination and excludes multiplication/division, mixed-expression and q048 expansion",()=>{const result=buildBatchABrowserWorksheetDocument(single);assert.equal(result.ok,true,result.errors?.map((error)=>error.code).join("\n"));assert.equal(result.worksheetDocument.questionCount,24);assert.equal(result.worksheetDocument.questionPages.length,3);assert.equal(result.worksheetDocument.answerKeyPages.length,3);assert.equal(result.worksheetDocument.metadata.applicationExpansion,false);assert.equal(result.worksheetDocument.metadata.globalContextExpansion,false);assert.equal(result.worksheetDocument.metadata.multiplicationDivisionExpansion,false);assert.equal(result.worksheetDocument.metadata.mixedExpressionExpansion,false);assert.equal(result.worksheetDocument.metadata.slice048Expansion,false);assert.equal(result.p03f47WorksheetAdapter.sharedP03F32MixedDomainNormalizer,true);assert.equal(result.p03f47WorksheetAdapter.sharedDecimalArithmetic,true);assert.equal(result.p03f47WorksheetAdapter.sharedFractionArithmetic,true);assert.equal(result.p03f47WorksheetAdapter.parallelPipeline,false);});
