import test from "node:test";
import assert from "node:assert/strict";
import { auditP03F20PublicSelectorComposition,listBatchAKnowledgePointAvailabilityBySource,resolveVisiblePatternSpecIdsForKnowledgePoint } from "../../site/modules/curriculum/registry/batch-a-selector-p03f20-extension.js";
import { buildBatchABrowserWorksheetDocument } from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p03f20-extension.js";
import { getCurrentPixelSourceSummary } from "../../site/pixel/pixel-registry-bridge.js";
const options={sourceId:"g4b_u08_4b08",selectedKnowledgePointIds:["kp_g4b_u08_fraction_decimal_conversion"],selectedPatternGroupIds:["pg_g4b_u08_fraction_decimal_conversion_numeric"],questionMode:"numeric",questionCount:20,generationSeed:"p03f20-current",includeAnswerKey:true,printLayout:{columns:2,rowsPerPage:6,showAnswerKeyPage:true}};
test("P03F20 Classic selector monotonically advances G4B-U08 to three visible KPs",()=>{assert.equal(auditP03F20PublicSelectorComposition().ok,true);assert.deepEqual(listBatchAKnowledgePointAvailabilityBySource("g4b_u08_4b08").visibleCount,3);assert.equal(resolveVisiblePatternSpecIdsForKnowledgePoint(options.selectedKnowledgePointIds[0]).length,2);});
test("P03F20 shared worksheet balances both specs and emits questions plus answer keys",()=>{const result=buildBatchABrowserWorksheetDocument(options);assert.equal(result.ok,true,JSON.stringify(result.errors));assert.equal(result.worksheetDocument.questionCount,20);assert.equal(result.worksheetDocument.answerKeyItems.length,20);assert.deepEqual(result.generation.allocation.map(r=>r.questionCount),[10,10]);assert.equal(result.worksheetDocument.metadata.applicationExpansion,false);});
test("P03F20 Pixel current registry uses the same three-KP successor",()=>{const summary=getCurrentPixelSourceSummary("g4b_u08_4b08");assert.equal(summary.visibleKnowledgePoints.length,3);assert.ok(summary.visibleKnowledgePoints.some(r=>r.knowledgePointId==="kp_g4b_u08_fraction_decimal_conversion"));});
