import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { PUBLIC_UI_SURFACES,auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding } from "../../site/modules/curriculum/public/public-ui-capability-binding-p03f47.js";
import { listVisibleBatchAKnowledgePoints } from "../../site/modules/curriculum/registry/batch-a-selector-p03f47-extension.js";
import { G6B_U01_P03F47_GROUP_ID,G6B_U01_P03F47_KP_ID,G6B_U01_P03F47_SOURCE_ID,P03F47_HIDDEN_SIBLING_KP_IDS } from "../../site/modules/curriculum/registry/g6b-u01-rank10-mixed-decimal-fraction-add-sub-selector-projection-p03f47.js";

test("P03F47 public capability binding is valid on every current surface",()=>{const audit=auditPublicUiCapabilityBinding();assert.equal(audit.ok,true,audit.errors.join("\n"));for(const surfaceId of Object.values(PUBLIC_UI_SURFACES)){const binding=resolvePublicUiCapabilityBinding({sourceId:G6B_U01_P03F47_SOURCE_ID,surfaceId,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G6B_U01_P03F47_KP_ID]});assert.equal(binding.blocked,false);assert.equal(binding.questionType,"numeric");assert.deepEqual(binding.selectedKnowledgePointIds,[G6B_U01_P03F47_KP_ID]);assert.deepEqual(binding.compatiblePatternGroupIds,[G6B_U01_P03F47_GROUP_ID]);assert.equal(binding.depthOptions.length,0);assert.equal(binding.contextOptions.length,0);}});

test("P03F47 sourceUnit binding exposes three visible G6B-U01 KPs and three groups",()=>{const binding=resolvePublicUiCapabilityBinding({sourceId:G6B_U01_P03F47_SOURCE_ID,surfaceId:PUBLIC_UI_SURFACES.CLASSIC,selectionMode:"sourceUnit"});assert.equal(binding.blocked,false);assert.equal(binding.selectedKnowledgePointCount,3);assert.equal(binding.compatiblePatternGroupIds.length,3);assert.equal(new Set(binding.compatiblePatternGroupIds).size,3);assert.equal(binding.selectedKnowledgePointIds.includes(G6B_U01_P03F47_KP_ID),true);assert.equal(binding.availableSelectionModes.find((row)=>row.value==="mixedKnowledgePointsSameUnit")?.enabled,true);});

test("P03F47 mixed-same-unit binding composes q047 with existing conversion and comparison without later-wave leakage",()=>{const rows=listVisibleBatchAKnowledgePoints().filter((row)=>row.sourceId===G6B_U01_P03F47_SOURCE_ID),other=rows.find((row)=>row.knowledgePointId!==G6B_U01_P03F47_KP_ID);assert.ok(other);const binding=resolvePublicUiCapabilityBinding({sourceId:G6B_U01_P03F47_SOURCE_ID,surfaceId:PUBLIC_UI_SURFACES.PIXEL,selectionMode:"mixedKnowledgePointsSameUnit",selectedKnowledgePointIds:[other.knowledgePointId,G6B_U01_P03F47_KP_ID]});assert.equal(binding.blocked,false);assert.equal(binding.selectedKnowledgePointCount,2);assert.equal(binding.compatiblePatternGroupIds.length,2);assert.equal(binding.compatiblePatternGroupIds.includes(G6B_U01_P03F47_GROUP_ID),true);const serialized=JSON.stringify(binding);for(const hiddenId of P03F47_HIDDEN_SIBLING_KP_IDS)assert.equal(serialized.includes(hiddenId),false);});

test("P03F47 current Classic, Pixel and query-state consumers are cut over to the same successor selector/binding",()=>{const files={classic:fs.readFileSync("site/assets/browser/public-capability-ui.js","utf8"),patternState:fs.readFileSync("site/assets/browser/state/public-pattern-group-selection.js","utf8"),queryState:fs.readFileSync("site/assets/browser/state/query-state.js","utf8"),selectorEntry:fs.readFileSync("site/modules/curriculum/registry/batch-a-selector-extension.js","utf8"),pixelBinding:fs.readFileSync("site/pixel/pixel-public-capability-ui.js","utf8"),pixelRegistry:fs.readFileSync("site/pixel/pixel-registry-bridge.js","utf8")};assert.match(files.classic,/public-ui-capability-binding-p03f47\.js/);assert.match(files.patternState,/batch-a-selector-p03f47-extension\.js/);assert.match(files.queryState,/batch-a-selector-p03f47-extension\.js/);assert.match(files.selectorEntry,/batch-a-selector-p03f47-extension\.js/);assert.match(files.pixelBinding,/public-ui-capability-binding-p03f47\.js/);assert.match(files.pixelRegistry,/batch-a-selector-p03f47-extension\.js/);});
