
import test from "node:test";
import assert from "node:assert/strict";
import { materializeP03FSlice006ProductAdmission } from "../../src/curriculum/full-product/p03f-slice006-product-admission.mjs";
import { validateP03FSlice006ProductAdmission } from "../../tools/curriculum/validate-p03f-slice006-product-admission.mjs";
import { generateG3AU08SameDenominatorCompareQuestions, validateG3AU08SameDenominatorCompareQuestion, P03F6_APPLICATION_AUTHORITY } from "../../site/modules/curriculum/batch-a/same-denominator-fraction-compare-runtime.js";
import { buildWorksheetDocumentFromPlan } from "../../site/assets/browser/pipeline/build-worksheet-document.js";
import { listVisibleBatchAKnowledgePoints, listBatchAKnowledgePointAvailabilityBySource } from "../../site/modules/curriculum/registry/batch-a-selector-p03f6-extension.js";
import { getCurrentPixelRegistrySnapshot, listPixelKnowledgePointsForSource } from "../../site/pixel/pixel-registry-bridge.js";
const SOURCE = "g3a_u08_3a08", KP = "kp_g3a_u08_same_denominator_compare";
const plan = (mode = "numeric") => ({ sourceId: SOURCE, selectionMode: "singleKnowledgePoint", selectedKnowledgePointIds: [KP], selectedPatternGroupIds: [mode === "application" ? "pg_g3a_u08_same_denominator_compare_application" : "pg_g3a_u08_same_denominator_compare_numeric"], questionMode: mode, questionCount: 6, ordering: "groupedByPattern", includeAnswerKey: true, generationSeed: `p03f6-${mode}`, printLayout: { paperSize: "A4", columns: 2, rowsPerPage: 3, showQuestionNumbers: true, showAnswerKeyPage: true } });
test("P03F6 consumes exact queue position 6 after slice005 D0", () => { const e = materializeP03FSlice006ProductAdmission(); assert.equal(e.slice.queuePosition, 6); assert.equal(e.slice.sliceId, "p03e_q006_r6_g3a_u08_3a08_profile_fraction_c1"); assert.equal(e.predecessorPassed, true); assert.deepEqual(e.slice.requiredW3CapabilityIds, ["cap_fraction_domain_validator", "cap_fraction_number_system"]); });
for (const mode of ["numeric", "application"]) test(`P03F6 ${mode} generates deterministic relation and compare-one coverage`, () => { const first = generateG3AU08SameDenominatorCompareQuestions(plan(mode)); const second = generateG3AU08SameDenominatorCompareQuestions(plan(mode)); assert.equal(first.ok, true, JSON.stringify(first.errors)); assert.deepEqual(first.questions, second.questions); assert.equal(first.questions.length, 6); assert.deepEqual([...new Set(first.questions.map((q) => q.comparison))].sort(), ["<", "=", ">"].sort()); assert.deepEqual([...new Set(first.questions.map((q) => q.comparisonTarget))].sort(), ["one", "pair"]); for (const q of first.questions) { assert.equal(q.leftDenominator, q.rightDenominator); assert.equal(validateG3AU08SameDenominatorCompareQuestion(q).ok, true); } if (mode === "application") { assert.equal(first.questions.every((q) => q.metadata.bindingCandidateId === P03F6_APPLICATION_AUTHORITY.bindingCandidateId), true); } });
test("P03F6 validator rejects denominator, answer and context tampering", () => { const n = generateG3AU08SameDenominatorCompareQuestions(plan("numeric")).questions[0]; assert.equal(validateG3AU08SameDenominatorCompareQuestion({ ...n, rightDenominator: n.rightDenominator + 1 }).ok, false); assert.equal(validateG3AU08SameDenominatorCompareQuestion({ ...n, answerText: ">" }).ok, false); const a = generateG3AU08SameDenominatorCompareQuestions(plan("application")).questions[0]; assert.equal(validateG3AU08SameDenominatorCompareQuestion({ ...a, metadata: { ...a.metadata, bindingCandidateId: "wrong" } }).ok, false); });
test("P03F6 current Classic and Pixel preserve four G3A-U08 KPs while successor sources extend", () => { const rows = listVisibleBatchAKnowledgePoints().filter((r) => r.sourceId === SOURCE); assert.equal(rows.length, 4); assert.ok(rows.some((r) => r.knowledgePointId === KP)); const availability = listBatchAKnowledgePointAvailabilityBySource(SOURCE); assert.equal(availability.visibleCount, 4); assert.equal(availability.hiddenPendingCount, 3); assert.equal(listPixelKnowledgePointsForSource(SOURCE).length, 4); assert.equal(getCurrentPixelRegistrySnapshot().sourceCount, 32); });
for (const mode of ["numeric", "application"]) test(`P03F6 ${mode} shared worksheet has six questions and answer keys`, () => { const result = buildWorksheetDocumentFromPlan(plan(mode)); assert.equal(result.ok, true, JSON.stringify(result.errors)); assert.equal(result.worksheetDocument.generatedQuestions.length, 6); assert.equal(result.worksheetDocument.answerKeyItems.length, 6); assert.equal(result.worksheetDocument.questionPages.length, 1); assert.equal(result.worksheetDocument.answerKeyPages.length, 1); });
test("P03F6 committed aggregate is production admitted after reviewed artifacts", () => { const result = validateP03FSlice006ProductAdmission(); assert.equal(result.ok, true, JSON.stringify(result.errors)); assert.equal(result.productAdmissionState, "PRODUCTION_ADMITTED_D0"); assert.equal(result.d0Complete, true); assert.equal(result.metrics.questionWitnessCount, 12); assert.equal(result.metrics.newProductAdmissionCount, 1); assert.equal(result.metrics.cumulativeW3ProductAdmissionCount, 7); assert.equal(result.metrics.remainingDirectSliceCount, 47); assert.equal(result.metrics.remainingDirectKnowledgePointCount, 75); });