import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {G6A_U04_P03F51_SPEC_ID} from "../../site/modules/curriculum/registry/g6a-u04-rank11-decimal-divided-by-decimal-selector-projection-p03f51.js";
import {G6A_U04_P03F52_PRECISION_SPEC_ID,G6A_U04_P03F52_RATE_SPEC_ID,G6A_U04_P03F52_SHIFT_SPEC_ID} from "../../site/modules/curriculum/registry/g6a-u04-rank12-shift-precision-rate-selector-projection-p03f52.js";
import {G6A_U04_P03F53_ROUNDING_KP_ID,G6A_U04_P03F53_ROUNDING_SPEC_ID,G6A_U04_P03F53_SOURCE_ID,auditG6AU04P03F53SelectorProjection} from "../../site/modules/curriculum/registry/g6a-u04-rank13-rounding-selector-projection-p03f53.js";
import {BATCH_A_SELECTOR_AVAILABILITY,auditP03F53PublicSelectorComposition,listBatchAKnowledgePointAvailabilityBySource,listVisibleBatchAKnowledgePoints} from "../../site/modules/curriculum/registry/batch-a-selector-p03f53-extension.js";
import {P03F53_SOURCE_PATTERN_EXTENSION,getBatchASourcePatternDefinition} from "../../site/modules/curriculum/batch-a/source-pattern-full-product-p03f53-extension.js";
import {generateG6AU04P03F53Questions,roundRationalHalfUp,validateG6AU04P03F53Question} from "../../site/modules/curriculum/batch-a/g6a-u04-rank13-rounding-runtime-p03f53.js";
import {buildBatchABrowserPlan} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p03f53.js";
import {generateBatchABrowserQuestions} from "../../site/modules/curriculum/batch-a/batch-a-browser-question-router-p03f53.js";
import {validateBatchABrowserPlan,validateBatchABrowserQuestions} from "../../site/modules/curriculum/batch-a/batch-a-browser-validator-p03f53.js";
import {buildBatchABrowserWorksheetDocument} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p03f53-extension.js";
import {PUBLIC_UI_SURFACES,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p03f53.js";
import {getCurrentPixelRegistrySnapshot} from "../../site/pixel/pixel-registry-bridge.js";
const readJson=relativePath=>JSON.parse(readFileSync(new URL(relativePath,import.meta.url),"utf8"));
const authority=readJson("../../data/curriculum/full-product/p03f/slice053-g6a-u04-rank13-rounding-authority.json"),resolution=readJson("../../data/curriculum/full-product/p03f/slice053-g6a-u04-direct-source-witness-resolution.json"),q052Claim=readJson("../../data/curriculum/final-milestone-claims/p03f-w3-slice052-e6-d0-v1.json");
function decimalFraction(text){const raw=String(text),[whole,fraction=""]=raw.split(".");return{numerator:BigInt(`${whole}${fraction}`),denominator:10n**BigInt(fraction.length)};}
function quotient(a,b){return{numerator:a.numerator*b.denominator,denominator:a.denominator*b.numerator};}
function expectedHalfUp(dividend,divisor,scale){const q=quotient(decimalFraction(dividend),decimalFraction(divisor)),factor=10n**BigInt(scale),scaled=q.numerator*factor,kept=scaled/q.denominator,remainder=scaled%q.denominator,rounded=kept+(remainder*2n>=q.denominator&&remainder!==0n?1n:0n),digits=rounded.toString();if(scale===0)return digits;const padded=digits.padStart(scale+1,"0");return`${padded.slice(0,-scale)}.${padded.slice(-scale)}`;}
test("P03F53 authority binds exact final q053 with direct source evidence",()=>{assert.equal(q052Claim.status,"PASS_D0_CLOSED");assert.equal(resolution.status,"PASS_DIRECT_SOURCE_WITNESS_RESOLVED");assert.equal(authority.queueAuthority.queuePosition,53);assert.equal(authority.queueAuthority.sliceId,"p03e_q053_r13_g6a_u04_6a04_profile_decimal_c1");assert.deepEqual(authority.queueAuthority.knowledgePointIds,[G6A_U04_P03F53_ROUNDING_KP_ID]);assert.equal(authority.queueAuthority.nextSliceId,null);assert.equal(authority.sourceAuthority.decimalRoundingDirectTextbookWitness,true);assert.equal(authority.sourceAuthority.quotientRequestedPlaceDirectTextbookWitness,true);assert.equal(authority.sourceAuthority.operatorApprovedExtensionRequired,false);assert.equal(authority.implementationBoundary.queueMutationAllowed,false);assert.equal(authority.implementationBoundary.globalContextExpansionAllowed,false);});
test("P03F53 selector and PatternSpec close G6A-U04 to 5/0/0 on 34/259",()=>{assert.equal(auditG6AU04P03F53SelectorProjection().ok,true);assert.equal(auditP03F53PublicSelectorComposition().ok,true);assert.equal(BATCH_A_SELECTOR_AVAILABILITY.sourceCount,34);assert.equal(BATCH_A_SELECTOR_AVAILABILITY.visibleCount,259);const availability=listBatchAKnowledgePointAvailabilityBySource(G6A_U04_P03F53_SOURCE_ID);assert.deepEqual([availability.visibleCount,availability.hiddenPendingCount,availability.notSelectableCount],[5,0,0]);assert.deepEqual(availability.hiddenPendingKnowledgePointIds,[]);assert.deepEqual(availability.notSelectableKnowledgePointIds,[]);assert.ok(listVisibleBatchAKnowledgePoints().some(row=>row.knowledgePointId===G6A_U04_P03F53_ROUNDING_KP_ID));assert.equal(P03F53_SOURCE_PATTERN_EXTENSION.addedPatternSpecCount,1);const spec=getBatchASourcePatternDefinition(G6A_U04_P03F53_ROUNDING_SPEC_ID);assert.ok(spec);assert.equal(spec.answerType,"decimal_approximation");assert.equal(spec.exactRationalRoundingRequired,true);assert.equal(spec.halfUpRoundingRequired,true);assert.equal(spec.approximationMarkerRequired,true);assert.equal(spec.floatingPointAuthorityAllowed,false);assert.equal(spec.operatorApprovedExtension,false);});
test("P03F53 exact half-up helper handles below-half, tie, above-half and fixed scales",()=>{assert.equal(roundRationalHalfUp({numerator:11n,denominator:9n},0).roundingRelation,"LESS_THAN_HALF");assert.equal(roundRationalHalfUp({numerator:1n,denominator:2n},0).roundedText,"1");assert.equal(roundRationalHalfUp({numerator:1n,denominator:2n},0).roundingRelation,"EXACT_HALF");assert.equal(roundRationalHalfUp({numerator:11n,denominator:3n},0).roundingRelation,"GREATER_THAN_HALF");assert.equal(roundRationalHalfUp({numerator:5n,denominator:4n},1).roundedText,"1.3");assert.equal(roundRationalHalfUp({numerator:5n,denominator:8n},2).roundedText,"0.63");});
test("P03F53 generator covers three requested places and all half-up decision classes",()=>{const result=generateG6AU04P03F53Questions({sourceId:G6A_U04_P03F53_SOURCE_ID,patternSpecIds:[G6A_U04_P03F53_ROUNDING_SPEC_ID],questionMode:"numeric",questionCount:27,generationSeed:"p03f53-rounding-focused"});assert.equal(result.ok,true);assert.equal(result.questions.length,27);assert.deepEqual(new Set(result.questions.map(q=>q.requestedScale)),new Set([0,1,2]));assert.deepEqual(new Set(result.questions.map(q=>q.roundingRelation)),new Set(["LESS_THAN_HALF","EXACT_HALF","GREATER_THAN_HALF"]));assert.equal(new Set(result.questions.map(q=>q.blankedDisplayText)).size,27);for(const q of result.questions){assert.equal(validateG6AU04P03F53Question(q).ok,true);assert.equal(q.answerText,expectedHalfUp(q.decimalDividend,q.decimalDivisor,q.requestedScale));assert.ok(q.promptText.includes("四捨五入"));assert.ok(q.promptText.includes("概數"));assert.ok(q.blankedDisplayText.includes("≈"));assert.equal(q.finalAnswer.exact,false);assert.equal(q.finalAnswer.roundingMethod,"HALF_UP");assert.equal(q.metadata.directTextbookRoundingWitness,true);assert.equal(q.metadata.operatorApprovedExtension,false);assert.equal(q.metadata.floatingPointAuthorityUsed,false);assert.equal(q.metadata.globalContextExpansion,false);}});
test("P03F53 source-unit numeric planning includes q051/q052/q053 but excludes application rate",()=>{const plan=buildBatchABrowserPlan({sourceId:G6A_U04_P03F53_SOURCE_ID,selectionMode:"sourceUnit",questionMode:"numeric",questionCount:32,generationSeed:"p03f53-source-unit"});assert.equal(validateBatchABrowserPlan(plan).ok,true);for(const spec of[G6A_U04_P03F51_SPEC_ID,G6A_U04_P03F52_SHIFT_SPEC_ID,G6A_U04_P03F52_PRECISION_SPEC_ID,G6A_U04_P03F53_ROUNDING_SPEC_ID])assert.ok(plan.patternSpecIds.includes(spec),`missing ${spec}`);assert.equal(plan.patternSpecIds.includes(G6A_U04_P03F52_RATE_SPEC_ID),false);const generation=generateBatchABrowserQuestions({plan,questionCount:32,generationSeed:"p03f53-source-unit"});assert.equal(generation.ok,true);assert.equal(generation.questions.length,32);assert.equal(validateBatchABrowserQuestions(generation.questions).ok,true);assert.ok(generation.questions.some(q=>q.patternSpecId===G6A_U04_P03F53_ROUNDING_SPEC_ID));});
test("P03F53 direct single-KP planning stays on one numeric rounding PatternSpec",()=>{const plan=buildBatchABrowserPlan({sourceId:G6A_U04_P03F53_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G6A_U04_P03F53_ROUNDING_KP_ID],questionMode:"numeric",questionCount:24,generationSeed:"p03f53-single"});assert.deepEqual(plan.patternSpecIds,[G6A_U04_P03F53_ROUNDING_SPEC_ID]);assert.equal(validateBatchABrowserPlan(plan).ok,true);const generation=generateBatchABrowserQuestions({plan,questionCount:24,generationSeed:"p03f53-single"});assert.equal(generation.ok,true);assert.equal(generation.questions.every(q=>q.patternSpecId===G6A_U04_P03F53_ROUNDING_SPEC_ID),true);assert.equal(validateBatchABrowserQuestions(generation.questions).ok,true);});
test("P03F53 public binding exposes five G6A-U04 KPs and treats rounding as direct numeric",()=>{const source=resolvePublicUiCapabilityBinding({sourceId:G6A_U04_P03F53_SOURCE_ID,surfaceId:PUBLIC_UI_SURFACES.CLASSIC,selectionMode:"sourceUnit"});assert.equal(source.blocked,false);assert.equal(source.selectedKnowledgePointCount,5);assert.deepEqual(new Set(source.availableQuestionTypeOptions.map(row=>row.value)),new Set(["numeric","application"]));assert.equal(source.questionType,"numeric");const rounding=resolvePublicUiCapabilityBinding({sourceId:G6A_U04_P03F53_SOURCE_ID,surfaceId:PUBLIC_UI_SURFACES.PIXEL,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G6A_U04_P03F53_ROUNDING_KP_ID]});assert.equal(rounding.blocked,false);assert.equal(rounding.questionType,"numeric");assert.equal(rounding.compatiblePatternGroupIds.length,1);assert.equal(rounding.operatorApprovedExtension,false);assert.equal(rounding.directTextbookRoundingWitness,true);});
test("P03F53 worksheet renders 24 rounding questions and matching answers on shared path",()=>{const result=buildBatchABrowserWorksheetDocument({sourceId:G6A_U04_P03F53_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G6A_U04_P03F53_ROUNDING_KP_ID],patternSpecIds:[G6A_U04_P03F53_ROUNDING_SPEC_ID],questionMode:"numeric",questionCount:24,generationSeed:"p03f53-worksheet",includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showQuestionNumbers:true,showAnswerKeyPage:true}});assert.equal(result.ok,true);const doc=result.worksheetDocument;assert.equal(doc.questionCount,24);assert.equal(doc.answerKeyItems.length,24);assert.equal(doc.summary.roundingQuestionCount,24);assert.equal(doc.metadata.roundingExpansion,true);assert.equal(doc.metadata.slice053Expansion,true);assert.equal(doc.metadata.roundingDirectTextbookWitness,true);assert.equal(doc.metadata.roundingOperatorApprovedExtension,false);assert.equal(doc.metadata.globalContextExpansion,false);assert.equal(doc.metadata.worksheetAdapter.sharedExactRationalNormalizer,true);assert.equal(doc.metadata.worksheetAdapter.sharedDecimalDivisionFamily,true);assert.equal(doc.metadata.worksheetAdapter.sharedPagination,true);assert.equal(doc.metadata.worksheetAdapter.sharedRenderer,true);for(let i=0;i<24;i++){assert.equal(doc.questionDisplayModels[i].questionId,doc.answerKeyItems[i].questionId);assert.equal(doc.generatedQuestions[i].answerText,doc.answerKeyItems[i].answerText);}});
test("P03F53 current Pixel authority is 34/259 and G6A-U04 is fully visible",()=>{const pixel=getCurrentPixelRegistrySnapshot();assert.equal(pixel.sourceCount,34);assert.equal(pixel.visibleKnowledgePointCount,259);const source=pixel.bySourceId[G6A_U04_P03F53_SOURCE_ID];assert.ok(source);assert.equal(source.visibleKnowledgePoints.length,5);assert.equal(source.hiddenPendingCount,0);assert.equal(source.notSelectableCount,0);assert.ok(source.visibleKnowledgePoints.some(row=>row.knowledgePointId===G6A_U04_P03F53_ROUNDING_KP_ID));});
