import test from "node:test";
import assert from "node:assert/strict";
import {PUBLIC_UI_SURFACES,auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p03f40.js";
import {parseQueryState} from "../../site/assets/browser/state/query-state.js";
import {G5B_U06_P03F40_GROUP_ID,G5B_U06_P03F40_KP_ID,G5B_U06_P03F40_SOURCE_ID} from "../../site/modules/curriculum/registry/g5b-u06-rank9-integer-division-decimal-quotient-selector-projection-p03f40.js";
test("P03F40 Classic fallback404 and Pixel expose the target as numeric only",()=>{for(const surfaceId of Object.values(PUBLIC_UI_SURFACES)){const b=resolvePublicUiCapabilityBinding({sourceId:G5B_U06_P03F40_SOURCE_ID,surfaceId,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G5B_U06_P03F40_KP_ID]});assert.equal(b.blocked,false,`${surfaceId}:${b.blockedReasons?.join("|")}`);assert.deepEqual(b.selectedKnowledgePointIds,[G5B_U06_P03F40_KP_ID]);assert.equal(b.questionType,"numeric");assert.deepEqual(b.compatiblePatternGroupIds,[G5B_U06_P03F40_GROUP_ID]);assert.deepEqual(b.depthOptions,[]);assert.deepEqual(b.contextOptions,[]);}});
test("P03F40 sourceUnit binding resolves the sole visible KP and mixed mode remains disabled",()=>{const b=resolvePublicUiCapabilityBinding({sourceId:G5B_U06_P03F40_SOURCE_ID,surfaceId:PUBLIC_UI_SURFACES.PIXEL,selectionMode:"sourceUnit"});assert.equal(b.blocked,false);assert.deepEqual(b.selectedKnowledgePointIds,[G5B_U06_P03F40_KP_ID]);assert.equal(b.availableSelectionModes.find(r=>r.value==="mixedKnowledgePointsSameUnit")?.enabled,false);});
test("P03F40 query-state preserves the new-source single-KP deep link",()=>{const search=`?sourceId=${G5B_U06_P03F40_SOURCE_ID}&selectionMode=singleKnowledgePoint&kp=${G5B_U06_P03F40_KP_ID}&pg=${G5B_U06_P03F40_GROUP_ID}&questionCount=24&answerKey=1`;const s=parseQueryState(search);assert.equal(s.sourceId,G5B_U06_P03F40_SOURCE_ID);assert.equal(s.selectionMode,"singleKnowledgePoint");assert.deepEqual(s.selectedKnowledgePointIds,[G5B_U06_P03F40_KP_ID]);assert.deepEqual(s.selectedPatternGroupIds,[G5B_U06_P03F40_GROUP_ID]);assert.deepEqual(s.selectorWarnings,[]);});
test("P03F40 public capability audit remains gap-free",()=>{const audit=auditPublicUiCapabilityBinding();assert.equal(audit.ok,true,JSON.stringify(audit.errors));assert.ok(audit.slice040AuditCaseCount>0);});
