import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {G5B_U06_P03F40_GROUP_ID,G5B_U06_P03F40_HIDDEN_SIBLING_KP_IDS,G5B_U06_P03F40_KP_ID,G5B_U06_P03F40_SOURCE_ID,G5B_U06_P03F40_SPEC_ID,P03F40_REQUIRED_CAPABILITY_IDS,auditG5BU06P03F40SelectorProjection} from "../../site/modules/curriculum/registry/g5b-u06-rank9-integer-division-decimal-quotient-selector-projection-p03f40.js";
import {BATCH_A_SELECTOR_AVAILABILITY,auditP03F40PublicSelectorComposition,listBatchAKnowledgePointAvailabilityBySource,listVisibleBatchAKnowledgePoints} from "../../site/modules/curriculum/registry/batch-a-selector-p03f40-extension.js";
import {validateP03F40PatternDefinitions} from "../../site/modules/curriculum/batch-a/source-pattern-full-product-p03f40-extension.js";
import {generateG5BU06P03F40Questions,validateG5BU06P03F40Question} from "../../site/modules/curriculum/batch-a/g5b-u06-rank9-integer-division-decimal-quotient-runtime-p03f40.js";
import {exactFractionToDecimal} from "../../site/modules/curriculum/public/shared-mixed-domain-normalizer-p03f32.js";
import {buildBatchABrowserWorksheetDocument} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-r2e-entry.js";
import {getCurrentPixelRegistrySnapshot} from "../../site/pixel/pixel-registry-bridge.js";
import {listCurrentFullProductPublicSourceUnits} from "../../site/modules/curriculum/batch-a/source-units.js";
// P03F40 exact-head CI retrigger after deterministic bot-authored reconciliation; no contract change.
const predecessor=JSON.parse(readFileSync(new URL("../../data/curriculum/final-milestone-claims/p03f-w3-slice039-e6-d0-v1.json",import.meta.url),"utf8"));
const options={sourceId:G5B_U06_P03F40_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G5B_U06_P03F40_KP_ID],selectedPatternGroupIds:[G5B_U06_P03F40_GROUP_ID],patternSpecIds:[G5B_U06_P03F40_SPEC_ID],questionMode:"numeric",questionCount:24,generationSeed:"p03f40-focused",includeAnswerKey:true,ordering:"groupedByPattern",printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showQuestionNumbers:true,showAnswerKeyPage:true}};
test("P03F40 follows Slice039 D0 and binds exact frozen q040 scope",()=>{assert.equal(predecessor.status,"PASS_D0_CLOSED");assert.equal(predecessor.goalDistance,"D0");assert.equal(predecessor.progression.nextResumeTask,"P03F_W3DirectProductVerticalSlice040Implementation");assert.equal(auditG5BU06P03F40SelectorProjection().ok,true);assert.equal(validateP03F40PatternDefinitions().ok,true);assert.deepEqual(P03F40_REQUIRED_CAPABILITY_IDS,["cap_decimal_arithmetic","cap_decimal_domain_validator","cap_decimal_number_system"]);});
test("P03F40 historical selector stays 33/238 and G5B-U06 1/4/4 while current Pixel advances through Slice048 to 33/249",()=>{assert.equal(auditP03F40PublicSelectorComposition().ok,true);assert.deepEqual([BATCH_A_SELECTOR_AVAILABILITY.sourceCount,BATCH_A_SELECTOR_AVAILABILITY.publicSourceCount,BATCH_A_SELECTOR_AVAILABILITY.visibleCount],[33,33,238]);assert.equal(listCurrentFullProductPublicSourceUnits().length,33);const a=listBatchAKnowledgePointAvailabilityBySource(G5B_U06_P03F40_SOURCE_ID);assert.deepEqual([a.visibleCount,a.hiddenPendingCount,a.notSelectableCount],[1,4,4]);const rows=listVisibleBatchAKnowledgePoints().filter(r=>r.sourceId===G5B_U06_P03F40_SOURCE_ID);assert.deepEqual(rows.map(r=>r.knowledgePointId),[G5B_U06_P03F40_KP_ID]);for(const hidden of G5B_U06_P03F40_HIDDEN_SIBLING_KP_IDS)assert.equal(rows.some(r=>r.knowledgePointId===hidden),false);const pixel=getCurrentPixelRegistrySnapshot();assert.deepEqual([pixel.sourceCount,pixel.visibleKnowledgePointCount],[33,249]);});
test("P03F40 generates 24 unique exact terminating decimal quotients with <1 and >1 witnesses",()=>{const g=generateG5BU06P03F40Questions(options);assert.equal(g.ok,true,JSON.stringify(g.errors));assert.equal(g.questions.length,24);assert.equal(new Set(g.questions.map(q=>q.blankedDisplayText)).size,24);assert.ok(g.magnitudeCounts.belowOne>0);assert.ok(g.magnitudeCounts.aboveOne>0);for(const q of g.questions){assert.equal(validateG5BU06P03F40Question(q).ok,true);const exact=exactFractionToDecimal({numerator:q.integerDividend,denominator:q.integerDivisor});assert.equal(q.answerText,exact.canonicalValue.canonicalText);assert.ok(exact.canonicalValue.scale>0);assert.equal(q.questionMode,"numeric");assert.equal(q.globalContextProduction,null);}});
test("P03F40 rejects integer quotient, wrong answer and application leakage",()=>{const q=generateG5BU06P03F40Questions({...options,questionCount:2}).questions[0];assert.equal(validateG5BU06P03F40Question({...q,answerText:"999"}).ok,false);assert.equal(validateG5BU06P03F40Question({...q,integerDividend:q.integerDivisor*2,answerText:"2",quotient:"2",finalAnswer:{canonicalText:"2",scale:0,exact:true}}).ok,false);assert.equal(validateG5BU06P03F40Question({...q,globalContextProduction:{contextId:"forbidden"}}).ok,false);});
test("P03F40 shared worksheet emits 24Q/24A on 3+3 pages without parallel pipeline",()=>{const r=buildBatchABrowserWorksheetDocument(options);assert.equal(r.ok,true,JSON.stringify(r.errors));const d=r.worksheetDocument;assert.deepEqual([d.questionCount,d.answerKeyItems.length,d.questionPages.length,d.answerKeyPages.length],[24,24,3,3]);assert.equal(d.metadata.worksheetAdapter.sharedP03F32ExactRationalNormalizer,true);assert.equal(d.metadata.worksheetAdapter.sharedPagination,true);assert.equal(d.metadata.worksheetAdapter.sharedRenderer,true);assert.equal(d.metadata.worksheetAdapter.parallelPipeline,false);});
