import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import {auditP04F22PublicSelectorComposition,listBatchAKnowledgePointAvailabilityBySource} from "../../site/modules/curriculum/registry/batch-a-selector-p04f22-extension.js";
import {G5B_U09_P04F22_SOURCE_ID,G5B_U09_P04F22_KP_ID,G5B_U09_P04F22_GROUP_ID,G5B_U09_P04F22_SPEC_ID,P04F22_REQUIRED_W4_CAPABILITY_IDS,P04F22_REQUIRED_PRODUCT_CAPABILITY_IDS} from "../../site/modules/curriculum/registry/g5b-u09-time-quantity-times-integer-selector-projection-p04f22.js";
import {G5B_U09_P04F18_KP_ID,G5B_U09_P04F18_SPEC_ID} from "../../site/modules/curriculum/registry/g5b-u09-time-mixed-unit-normalization-selector-projection-p04f18.js";
import {getBatchASourcePatternDefinition} from "../../site/modules/curriculum/batch-a/source-pattern-full-product-p04f22-extension.js";
import {generateG5BU09P04F22QuestionSet,generateG5BU09P04F22TimeTimesIntegerQuestions,validateG5BU09P04F22Question} from "../../site/modules/curriculum/batch-a/time-system-runtime-p04f22.js";
import {buildBatchABrowserPlan} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p04f22.js";
import {validateBatchABrowserPlan,validateBatchABrowserQuestions} from "../../site/modules/curriculum/batch-a/batch-a-browser-validator-p04f22.js";
import {buildBatchABrowserWorksheetDocument} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-r2e-entry.js";
import {PUBLIC_UI_SURFACES,auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p04f22.js";
import {getCurrentPixelRegistrySnapshot} from "../../site/pixel/pixel-registry-bridge.js";
import {listCurrentFullProductPublicSourceUnits} from "../../site/modules/curriculum/batch-a/source-units-p04f19-extension.js";
const singlePlan=count=>buildBatchABrowserPlan({sourceId:G5B_U09_P04F22_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G5B_U09_P04F22_KP_ID],selectedPatternGroupIds:[G5B_U09_P04F22_GROUP_ID],patternSpecIds:[G5B_U09_P04F22_SPEC_ID],questionMode:"numeric",questionCount:count,generationSeed:"p04f22-test"});

test("P04F22 authority locks exact R02 page-1 duration-times-integer semantics",()=>{const a=JSON.parse(fs.readFileSync("data/curriculum/full-product/p04f/slice022-g5b-u09-time-quantity-times-integer-authority.json","utf8"));assert.equal(a.queue.sliceId,"p04e_q022_r3_g5b_u09_5b09_profile_time_c1");assert.equal(a.source.sourceNodeId,G5B_U09_P04F22_SOURCE_ID);assert.deepEqual(a.source.primaryWitnessPages,[1]);assert.equal(a.knowledgePoints[0].knowledgePointId,G5B_U09_P04F22_KP_ID);assert.equal(a.formalMapping.relationFamilyId,"TIME_QUANTITY_TIMES_INTEGER");assert.equal(a.formalMapping.targetRoleId,"TOTAL_DURATION");assert.deepEqual(a.formalMapping.requiredW4CapabilityIds,P04F22_REQUIRED_W4_CAPABILITY_IDS);assert.deepEqual(a.formalMapping.requiredProductCapabilityIds,P04F22_REQUIRED_PRODUCT_CAPABILITY_IDS);assert.equal(a.implementationBoundary.q023Touched,false);assert.equal(a.implementationBoundary.q025Touched,false);assert.equal(a.implementationBoundary.q029Touched,false);});

test("P04F22 selector promotes exactly one existing-source KP to 42/292",()=>{const audit=auditP04F22PublicSelectorComposition(),availability=listBatchAKnowledgePointAvailabilityBySource(G5B_U09_P04F22_SOURCE_ID);assert.equal(audit.ok,true,JSON.stringify(audit.errors));assert.deepEqual(audit.counts,{sources:42,knowledgePoints:292,g5bU09Visible:2,g5bU09Hidden:0,g5bU09NotSelectable:0});assert.equal(availability.visibleCount,2);assert.equal(availability.visibleKnowledgePointIds.includes(G5B_U09_P04F18_KP_ID),true);assert.equal(availability.visibleKnowledgePointIds.includes(G5B_U09_P04F22_KP_ID),true);});

test("P04F22 source pattern is numeric duration multiplication and forbids successor semantics",()=>{const d=getBatchASourcePatternDefinition(G5B_U09_P04F22_SPEC_ID);assert.ok(d);assert.equal(d.mode,"numeric");assert.equal(d.questionMode,"numeric");assert.equal(d.relationFamilyId,"TIME_QUANTITY_TIMES_INTEGER");assert.equal(d.targetRoleId,"TOTAL_DURATION");assert.equal(d.clockTimeMultiplicationAllowed,false);assert.equal(d.timeDivisionAllowed,false);assert.equal(d.repeatedScheduleAllowed,false);assert.equal(d.averageTimeAllowed,false);assert.equal(d.globalContextRequired,false);assert.equal(d.pblProjectionAllowed,false);});

test("P04F22 single-KP runtime proves 24 distinct exact normalized products",()=>{const plan=singlePlan(24),r=generateG5BU09P04F22TimeTimesIntegerQuestions({plan,questionCount:24,generationSeed:"p04f22-capacity"});assert.equal(r.ok,true,JSON.stringify(r.errors));assert.equal(r.questions.length,24);assert.equal(new Set(r.questions.map(q=>q.id)).size,24);assert.equal(new Set(r.questions.map(q=>q.promptText)).size,24);for(const q of r.questions){assert.equal(validateG5BU09P04F22Question(q).ok,true,JSON.stringify(q));assert.equal(q.metadata.sourceVisualAuthority,"R02_FULL_PAGE_VISUAL_READBACK");assert.deepEqual(q.metadata.sourceEvidencePages,[1]);assert.equal(q.metadata.timeMultiplication,true);assert.equal(q.metadata.timeDivision,false);assert.equal(q.metadata.repeatedSchedule,false);assert.equal(q.metadata.averageTime,false);assert.equal(q.metadata.resultTotalSeconds,q.metadata.singleDurationSeconds*q.metadata.integerCount);}});

test("P04F22 sourceUnit composes q018 and q022 without a parallel runtime",()=>{const plan=buildBatchABrowserPlan({sourceId:G5B_U09_P04F22_SOURCE_ID,selectionMode:"sourceUnit",questionMode:"numeric",questionCount:24,generationSeed:"p04f22-source"});assert.deepEqual(new Set(plan.patternSpecIds),new Set([G5B_U09_P04F18_SPEC_ID,G5B_U09_P04F22_SPEC_ID]));assert.equal(validateBatchABrowserPlan(plan).ok,true);const r=generateG5BU09P04F22QuestionSet({plan,questionCount:24,generationSeed:"p04f22-source"});assert.equal(r.ok,true,JSON.stringify(r.errors));assert.equal(r.questions.length,24);assert.equal(r.allocation.length,2);assert.equal(r.allocation.reduce((n,row)=>n+row.questionCount,0),24);assert.equal(r.questions.some(q=>q.patternSpecId===G5B_U09_P04F18_SPEC_ID),true);assert.equal(r.questions.some(q=>q.patternSpecId===G5B_U09_P04F22_SPEC_ID),true);assert.equal(validateBatchABrowserQuestions(r.questions).ok,true);});

test("P04F22 validator rejects answer, multiplier, successor and pipeline mutations",()=>{const r=generateG5BU09P04F22TimeTimesIntegerQuestions({plan:singlePlan(1),questionCount:1,generationSeed:"p04f22-negative"}),q=r.questions[0];assert.equal(validateG5BU09P04F22Question({...q,answer:"錯",answerText:"錯",finalAnswer:"錯"}).ok,false);for(const metadata of [{...q.metadata,integerCount:0},{...q.metadata,timeDivision:true},{...q.metadata,repeatedSchedule:true},{...q.metadata,averageTime:true},{...q.metadata,q023RepeatedSchedule:true},{...q.metadata,q025TimeDivision:true},{...q.metadata,q029AverageTime:true},{...q.metadata,globalContextExpansion:true},{...q.metadata,pblProjection:true},{...q.metadata,parallelTimeEngine:true},{...q.metadata,sourceEvidencePages:[2]}])assert.equal(validateG5BU09P04F22Question({...q,metadata}).ok,false);});

test("P04F22 worksheet builds 24 numeric questions and answers on shared time path",()=>{const r=buildBatchABrowserWorksheetDocument({sourceId:G5B_U09_P04F22_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G5B_U09_P04F22_KP_ID],selectedPatternGroupIds:[G5B_U09_P04F22_GROUP_ID],patternSpecIds:[G5B_U09_P04F22_SPEC_ID],questionMode:"numeric",questionCount:24,generationSeed:"p04f22-worksheet",includeAnswerKey:true});assert.equal(r.ok,true,JSON.stringify(r.errors));assert.equal(r.worksheetDocument.generatedQuestions.length,24);assert.equal(r.worksheetDocument.answerKeyItems.length,24);assert.equal(r.worksheetDocument.summary.timeQuantityTimesIntegerQuestionCount,24);assert.equal(r.p04f22WorksheetAdapter.sharedTimeRuntime,true);assert.equal(r.p04f22WorksheetAdapter.parallelPipeline,false);assert.equal(r.p04f22WorksheetAdapter.parallelTimeEngine,false);assert.equal(r.p04f22WorksheetAdapter.timeDivision,false);});

test("P04F22 UI exposes two-KP numeric G5B-U09 sourceUnit and q022 single-KP",()=>{const source=resolvePublicUiCapabilityBinding({sourceId:G5B_U09_P04F22_SOURCE_ID,surfaceId:PUBLIC_UI_SURFACES.CLASSIC,selectionMode:"sourceUnit"});assert.ok(source);assert.equal(source.blocked,false);assert.equal(source.questionType,"numeric");assert.deepEqual(new Set(source.selectedKnowledgePointIds),new Set([G5B_U09_P04F18_KP_ID,G5B_U09_P04F22_KP_ID]));assert.equal(source.compatiblePatternGroupIds.length,2);assert.equal(source.questionCount.max,24);const single=resolvePublicUiCapabilityBinding({sourceId:G5B_U09_P04F22_SOURCE_ID,surfaceId:PUBLIC_UI_SURFACES.CLASSIC,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G5B_U09_P04F22_KP_ID]});assert.ok(single);assert.equal(single.questionType,"numeric");assert.deepEqual(single.compatiblePatternGroupIds,[G5B_U09_P04F22_GROUP_ID]);assert.equal(auditPublicUiCapabilityBinding().ok,true);});

test("P04F22 Pixel/current inventory reads 42 / 292 and two G5B-U09 KPs",()=>{const units=listCurrentFullProductPublicSourceUnits(),registry=getCurrentPixelRegistrySnapshot(),source=registry.bySourceId[G5B_U09_P04F22_SOURCE_ID];assert.equal(units.length,42);assert.equal(units.filter(u=>u.sourceId===G5B_U09_P04F22_SOURCE_ID).length,1);assert.equal(registry.sourceCount,42);assert.equal(registry.visibleKnowledgePointCount,292);assert.equal(source.visibleKnowledgePoints.length,2);assert.equal(source.visibleKnowledgePoints.some(r=>r.knowledgePointId===G5B_U09_P04F22_KP_ID),true);assert.equal(source.hiddenPendingCount,0);assert.equal(source.notSelectableCount,0);});
