import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";

import {auditP04F8PublicSelectorComposition} from "../../site/modules/curriculum/registry/batch-a-selector-p04f8-extension.js";
import {G3B_U03_P04F3_KP_ID,G3B_U03_P04F3_SPEC_ID,G3B_U03_P04F3_UNIT_CONVERSION_KP_ID,G3B_U03_P04F3_UNIT_CONVERSION_SPEC_ID} from "../../site/modules/curriculum/registry/g3b-u03-time-12-24-conversion-selector-projection-p04f3.js";
import {G3B_U03_P04F8_SOURCE_ID,G3B_U03_P04F8_ELAPSED_KP_ID,G3B_U03_P04F8_ELAPSED_SPEC_ID,G3B_U03_P04F8_ARITHMETIC_KP_ID,G3B_U03_P04F8_ARITHMETIC_SPEC_ID,P04F8_REQUIRED_W4_CAPABILITY_IDS} from "../../site/modules/curriculum/registry/g3b-u03-elapsed-time-regrouping-selector-projection-p04f8.js";
import {buildBatchABrowserPlan,requestsP04F8} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p04f8.js";
import {generateBatchABrowserQuestions} from "../../site/modules/curriculum/batch-a/batch-a-browser-question-router-p04f8.js";
import {validateBatchABrowserPlan,validateBatchABrowserQuestions} from "../../site/modules/curriculum/batch-a/batch-a-browser-validator-p04f8.js";
import {buildBatchABrowserWorksheetDocument} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p04f8-extension.js";
import {resolvePublicUiCapabilityBinding,PUBLIC_UI_SURFACES} from "../../site/modules/curriculum/public/public-ui-capability-binding-p04f8.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";

const sourceOptions={sourceId:G3B_U03_P04F8_SOURCE_ID,selectionMode:"sourceUnit",questionMode:"numeric",questionCount:8,generationSeed:"p04f8-focused",includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showAnswerKeyPage:true}};

test("P04F8 authority locks q008 to same-day elapsed and duration regrouping while reserving q014",()=>{const authority=JSON.parse(fs.readFileSync("data/curriculum/full-product/p04f/slice008-g3b-u03-elapsed-time-regrouping-authority.json","utf8"));assert.equal(authority.queue.sliceId,"p04e_q008_r1_g3b_u03_3b03_profile_time_c1");assert.equal(authority.queue.previousSliceId,"p04e_q007_r1_g3b_u02_3b02_profile_quantity_measurement_c1");assert.equal(authority.source.sourcePdfTitle,"meow911_3b03_time.pdf");assert.deepEqual(authority.source.reviewedPages,[1,2]);assert.deepEqual(authority.source.primaryWitnessPages,[1]);assert.equal(authority.source.page2ReservedKnowledgePointId,"kp_schedule_start_end_duration");assert.deepEqual(authority.knowledgePoints.map(row=>row.knowledgePointId),[G3B_U03_P04F8_ELAPSED_KP_ID,G3B_U03_P04F8_ARITHMETIC_KP_ID]);assert.deepEqual(authority.formalMapping.requiredW4CapabilityIds,[...P04F8_REQUIRED_W4_CAPABILITY_IDS]);assert.equal(authority.formalMapping.timeUnitFactors.minutesPerHour,60);assert.equal(authority.formalMapping.scheduleStartEndDurationTriad,false);assert.equal(authority.formalMapping.reservedSuccessorKnowledgePointId,"kp_schedule_start_end_duration");assert.deepEqual(authority.patternSpecs.map(row=>row.patternSpecId),[G3B_U03_P04F8_ELAPSED_SPEC_ID,G3B_U03_P04F8_ARITHMETIC_SPEC_ID]);assert.equal(authority.knowledgePoints.every(row=>row.implementationBoundary.scheduleStartEndDurationTriadAllowed===false),true);});

test("P04F8 selector adds two KPs on existing G3B-U03 source",()=>{const audit=auditP04F8PublicSelectorComposition();assert.equal(audit.ok,true,JSON.stringify(audit.errors));assert.deepEqual(audit.counts,{sources:39,knowledgePoints:271,g3bU03Visible:4,g3bU03Hidden:0,g3bU03NotSelectable:0});});

test("P04F8 source-unit coordinator preserves q003 and adds both q008 specs",()=>{const plan=buildBatchABrowserPlan(sourceOptions);assert.deepEqual(new Set(plan.patternSpecIds),new Set([G3B_U03_P04F3_SPEC_ID,G3B_U03_P04F3_UNIT_CONVERSION_SPEC_ID,G3B_U03_P04F8_ELAPSED_SPEC_ID,G3B_U03_P04F8_ARITHMETIC_SPEC_ID]));assert.deepEqual(new Set(plan.requestedKnowledgePointIds),new Set([G3B_U03_P04F3_KP_ID,G3B_U03_P04F3_UNIT_CONVERSION_KP_ID,G3B_U03_P04F8_ELAPSED_KP_ID,G3B_U03_P04F8_ARITHMETIC_KP_ID]));assert.equal(validateBatchABrowserPlan(plan).ok,true);const generation=generateBatchABrowserQuestions({...sourceOptions,plan});assert.equal(generation.ok,true,JSON.stringify(generation.errors));assert.equal(generation.questions.length,8);for(const specId of [G3B_U03_P04F3_SPEC_ID,G3B_U03_P04F3_UNIT_CONVERSION_SPEC_ID,G3B_U03_P04F8_ELAPSED_SPEC_ID,G3B_U03_P04F8_ARITHMETIC_SPEC_ID])assert.equal(generation.questions.filter(q=>q.patternSpecId===specId).length,2);assert.deepEqual(new Set(generation.questions.filter(q=>q.patternSpecId===G3B_U03_P04F8_ARITHMETIC_SPEC_ID).map(q=>q.metadata.operationDirection)),new Set(["ADD","SUBTRACT"]));assert.equal(validateBatchABrowserQuestions(generation.questions).ok,true);});

test("P04F8 leaves q003 single-KP route on the existing q003 implementation",()=>{const options={...sourceOptions,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G3B_U03_P04F3_KP_ID],questionCount:8,generationSeed:"p04f8-q003-preserve"};assert.equal(requestsP04F8(options),false);const plan=buildBatchABrowserPlan(options);assert.deepEqual(plan.patternSpecIds,[G3B_U03_P04F3_SPEC_ID]);const generation=generateBatchABrowserQuestions({...options,plan});assert.equal(generation.ok,true,JSON.stringify(generation.errors));assert.equal(generation.questions.length,8);assert.equal(generation.questions.every(q=>q.patternSpecId===G3B_U03_P04F3_SPEC_ID),true);assert.equal(validateBatchABrowserQuestions(generation.questions).ok,true);});

test("P04F8 same-day elapsed KP has 24 distinct recomputable cases without q014 semantics",()=>{const options={...sourceOptions,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G3B_U03_P04F8_ELAPSED_KP_ID],questionCount:24,generationSeed:"p04f8-elapsed-24"},plan=buildBatchABrowserPlan(options);assert.deepEqual(plan.patternSpecIds,[G3B_U03_P04F8_ELAPSED_SPEC_ID]);const generation=generateBatchABrowserQuestions({...options,plan});assert.equal(generation.ok,true,JSON.stringify(generation.errors));assert.equal(generation.questions.length,24);assert.equal(new Set(generation.questions.map(q=>q.blankedDisplayText)).size,24);for(const q of generation.questions){assert.equal(q.metadata.endTotalMinutes>q.metadata.startTotalMinutes,true);assert.equal(q.metadata.endTotalMinutes<1440,true);assert.equal(q.metadata.elapsedMinutes,q.metadata.endTotalMinutes-q.metadata.startTotalMinutes);const h=Math.floor(q.metadata.elapsedMinutes/60),m=q.metadata.elapsedMinutes%60;assert.equal(q.answerText,`${h}時${m}分`);assert.equal(q.metadata.sameDayElapsedDuration,true);assert.equal(q.metadata.crossDayElapsed,false);assert.equal(q.metadata.scheduleReasoning,false);assert.equal(q.metadata.scheduleStartEndDurationTriad,false);assert.equal(q.metadata.solveForStartTime,false);assert.equal(q.metadata.solveForEndTime,false);assert.doesNotMatch(q.blankedDisplayText,/班次|火車|電影|求開始時刻|求結束時刻|時刻表/);}assert.equal(validateBatchABrowserQuestions(generation.questions).ok,true);});

test("P04F8 duration arithmetic has 24 distinct carry and borrow cases",()=>{const options={...sourceOptions,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G3B_U03_P04F8_ARITHMETIC_KP_ID],questionCount:24,generationSeed:"p04f8-arithmetic-24"},plan=buildBatchABrowserPlan(options);assert.deepEqual(plan.patternSpecIds,[G3B_U03_P04F8_ARITHMETIC_SPEC_ID]);const generation=generateBatchABrowserQuestions({...options,plan});assert.equal(generation.ok,true,JSON.stringify(generation.errors));assert.equal(generation.questions.length,24);assert.equal(new Set(generation.questions.map(q=>q.blankedDisplayText)).size,24);assert.deepEqual(new Set(generation.questions.map(q=>q.metadata.operationDirection)),new Set(["ADD","SUBTRACT"]));assert.deepEqual(new Set(generation.questions.map(q=>q.metadata.regroupingKind)),new Set(["CARRY_MINUTES_TO_HOUR","BORROW_HOUR_TO_MINUTES"]));for(const q of generation.questions){const expected=q.metadata.operationDirection==="ADD"?q.metadata.leftTotalMinutes+q.metadata.rightTotalMinutes:q.metadata.leftTotalMinutes-q.metadata.rightTotalMinutes;assert.equal(q.metadata.resultTotalMinutes,expected);assert.equal(q.metadata.regroupingRequired,true);if(q.metadata.operationDirection==="ADD")assert.equal(q.metadata.leftMinutes+q.metadata.rightMinutes>=60,true);else assert.equal(q.metadata.leftMinutes<q.metadata.rightMinutes,true);const h=Math.floor(expected/60),m=expected%60;assert.equal(q.answerText,`${h}時${m}分`);assert.equal(q.metadata.durationArithmetic,true);assert.equal(q.metadata.clockTimeAddition,false);assert.equal(q.metadata.scheduleReasoning,false);assert.equal(q.metadata.scheduleStartEndDurationTriad,false);assert.doesNotMatch(q.blankedDisplayText,/班次|火車|電影|開始時刻|結束時刻|時刻表/);}assert.equal(validateBatchABrowserQuestions(generation.questions).ok,true);});

test("P04F8 keeps legal one-question boundary and rejects 25-question q008 plan",()=>{const one={...sourceOptions,questionCount:1,generationSeed:"p04f8-one"},onePlan=buildBatchABrowserPlan(one);assert.equal(validateBatchABrowserPlan(onePlan).ok,true);assert.equal(generateBatchABrowserQuestions({...one,plan:onePlan}).questions.length,1);const tooMany={...sourceOptions,questionCount:25,generationSeed:"p04f8-too-many"},tooManyPlan=buildBatchABrowserPlan(tooMany);assert.equal(validateBatchABrowserPlan(tooManyPlan).ok,false);});

test("P04F8 worksheet keeps four source KPs aligned across questions and answers",()=>{const result=buildBatchABrowserWorksheetDocument(sourceOptions);assert.equal(result.ok,true,JSON.stringify(result.errors));const doc=result.worksheetDocument;assert.equal(doc.questionCount,8);assert.equal(doc.questionPages.length,1);assert.equal(doc.answerKeyPages.length,1);assert.equal(doc.summary.timeSystemConversionQuestionCount,2);assert.equal(doc.summary.timeUnitConversionQuestionCount,2);assert.equal(doc.summary.sameDayElapsedQuestionCount,2);assert.equal(doc.summary.timeRegroupingArithmeticQuestionCount,2);assert.equal(doc.answerKeyItems.length,8);for(let i=0;i<8;i++){assert.equal(doc.answerKeyItems[i].questionId,doc.generatedQuestions[i].id);assert.equal(doc.answerKeyItems[i].answerText,doc.generatedQuestions[i].answerText);assert.equal(doc.questionDisplayModels[i].promptText,doc.generatedQuestions[i].blankedDisplayText);}assert.equal(doc.metadata.scheduleReasoning,false);assert.equal(doc.metadata.scheduleStartEndDurationTriad,false);assert.equal(doc.metadata.reservedQ014KnowledgePointId,"kp_schedule_start_end_duration");const html=renderWorksheetDocumentToHtml(doc,{stylesheetHref:""});assert.match(html,/經過|計算/);assert.doesNotMatch(html,/班次|時刻表|求開始時刻|求結束時刻/);});

test("P04F8 public binding exposes sourceUnit and each single KP only",()=>{for(const surfaceId of Object.values(PUBLIC_UI_SURFACES)){const source=resolvePublicUiCapabilityBinding({sourceId:G3B_U03_P04F8_SOURCE_ID,surfaceId,selectionMode:"sourceUnit"});assert.equal(source.blocked,false);assert.equal(source.selectedKnowledgePointIds.length,4);assert.equal(source.compatiblePatternGroupIds.length,4);assert.equal(source.questionCount.max,24);assert.equal(source.q014ScheduleSemanticsReserved,true);for(const kpId of [G3B_U03_P04F3_KP_ID,G3B_U03_P04F3_UNIT_CONVERSION_KP_ID,G3B_U03_P04F8_ELAPSED_KP_ID,G3B_U03_P04F8_ARITHMETIC_KP_ID]){const single=resolvePublicUiCapabilityBinding({sourceId:G3B_U03_P04F8_SOURCE_ID,surfaceId,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[kpId]});assert.equal(single.blocked,false);assert.equal(single.selectedKnowledgePointIds[0],kpId);assert.equal(single.compatiblePatternGroupIds.length,1);assert.equal(single.questionCount.max,24);}assert.equal(source.availableSelectionModes.find(row=>row.value==="mixedKnowledgePointsSameUnit").enabled,false);assert.equal(source.availableSelectionModes.find(row=>row.value==="mixedKnowledgePointsCrossUnit").enabled,false);}});
