import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";

import {auditP04F7PublicSelectorComposition} from "../../site/modules/curriculum/registry/batch-a-selector-p04f7-extension.js";
import {G3B_U02_P04F2_KP_ID,G3B_U02_P04F2_SPEC_ID} from "../../site/modules/curriculum/registry/g3b-u02-capacity-unit-identity-selector-projection-p04f2.js";
import {G3B_U02_P04F7_SOURCE_ID,G3B_U02_P04F7_SCALE_KP_ID,G3B_U02_P04F7_SCALE_SPEC_ID,G3B_U02_P04F7_CONVERSION_KP_ID,G3B_U02_P04F7_CONVERSION_SPEC_ID,P04F7_REQUIRED_W4_CAPABILITY_IDS} from "../../site/modules/curriculum/registry/g3b-u02-capacity-scale-conversion-selector-projection-p04f7.js";
import {buildBatchABrowserPlan} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p04f7.js";
import {generateBatchABrowserQuestions} from "../../site/modules/curriculum/batch-a/batch-a-browser-question-router-p04f7.js";
import {validateBatchABrowserPlan,validateBatchABrowserQuestions} from "../../site/modules/curriculum/batch-a/batch-a-browser-validator-p04f7.js";
import {buildBatchABrowserWorksheetDocument} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p04f7-extension.js";
import {resolvePublicUiCapabilityBinding,PUBLIC_UI_SURFACES} from "../../site/modules/curriculum/public/public-ui-capability-binding-p04f7.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";

const sourceOptions={sourceId:G3B_U02_P04F7_SOURCE_ID,selectionMode:"sourceUnit",questionMode:"numeric",questionCount:8,generationSeed:"p04f7-focused",includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showAnswerKeyPage:true}};

test("P04F7 authority locks q007 to capacity scale reading and L/mL conversion",()=>{const authority=JSON.parse(fs.readFileSync("data/curriculum/full-product/p04f/slice007-g3b-u02-capacity-scale-conversion-authority.json","utf8"));assert.equal(authority.queue.sliceId,"p04e_q007_r1_g3b_u02_3b02_profile_quantity_measurement_c1");assert.equal(authority.queue.previousSliceId,"p04e_q006_r1_g3a_u04_3a04_profile_quantity_measurement_c1");assert.equal(authority.source.sourcePdfTitle,"meow911_3b02_l_ml.pdf");assert.deepEqual(authority.source.reviewedPages,[1]);assert.deepEqual(authority.knowledgePoints.map(row=>row.knowledgePointId),[G3B_U02_P04F7_SCALE_KP_ID,G3B_U02_P04F7_CONVERSION_KP_ID]);assert.deepEqual(authority.formalMapping.requiredW4CapabilityIds,[...P04F7_REQUIRED_W4_CAPABILITY_IDS]);assert.equal(authority.formalMapping.millilitresPerLitre,1000);assert.deepEqual(authority.patternSpecs.map(row=>row.patternSpecId),[G3B_U02_P04F7_SCALE_SPEC_ID,G3B_U02_P04F7_CONVERSION_SPEC_ID]);assert.equal(authority.knowledgePoints.every(row=>row.implementationBoundary.capacityEstimationAllowed===false&&row.implementationBoundary.mixedUnitComparisonAllowed===false&&row.implementationBoundary.mixedUnitArithmeticAllowed===false),true);});

test("P04F7 selector adds two KPs on existing G3B-U02 source",()=>{const audit=auditP04F7PublicSelectorComposition();assert.equal(audit.ok,true,JSON.stringify(audit.errors));assert.deepEqual(audit.counts,{sources:39,knowledgePoints:269,g3bU02Visible:3,g3bU02Hidden:0,g3bU02NotSelectable:0});});

test("P04F7 source-unit coordinator preserves q002 and adds both q007 specs",()=>{const plan=buildBatchABrowserPlan(sourceOptions);assert.deepEqual(new Set(plan.patternSpecIds),new Set([G3B_U02_P04F2_SPEC_ID,G3B_U02_P04F7_SCALE_SPEC_ID,G3B_U02_P04F7_CONVERSION_SPEC_ID]));assert.deepEqual(new Set(plan.requestedKnowledgePointIds),new Set([G3B_U02_P04F2_KP_ID,G3B_U02_P04F7_SCALE_KP_ID,G3B_U02_P04F7_CONVERSION_KP_ID]));assert.equal(validateBatchABrowserPlan(plan).ok,true);const generation=generateBatchABrowserQuestions({...sourceOptions,plan});assert.equal(generation.ok,true,JSON.stringify(generation.errors));assert.equal(generation.questions.length,8);assert.equal(generation.questions.filter(q=>q.patternSpecId===G3B_U02_P04F2_SPEC_ID).length,3);assert.equal(generation.questions.filter(q=>q.patternSpecId===G3B_U02_P04F7_SCALE_SPEC_ID).length,3);assert.equal(generation.questions.filter(q=>q.patternSpecId===G3B_U02_P04F7_CONVERSION_SPEC_ID).length,2);assert.deepEqual(new Set(generation.questions.filter(q=>q.patternSpecId===G3B_U02_P04F7_CONVERSION_SPEC_ID).map(q=>q.metadata.conversionDirection)),new Set(["ML_TO_L_ML","L_ML_TO_ML"]));assert.equal(validateBatchABrowserQuestions(generation.questions).ok,true);});

test("P04F7 scale-reading KP has 24 distinct recomputable measurement-scale cases",()=>{const options={...sourceOptions,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G3B_U02_P04F7_SCALE_KP_ID],questionCount:24,generationSeed:"p04f7-scale-24"},plan=buildBatchABrowserPlan(options);assert.deepEqual(plan.patternSpecIds,[G3B_U02_P04F7_SCALE_SPEC_ID]);const generation=generateBatchABrowserQuestions({...options,plan});assert.equal(generation.ok,true,JSON.stringify(generation.errors));assert.equal(generation.questions.length,24);assert.equal(new Set(generation.questions.map(q=>q.blankedDisplayText)).size,24);for(const q of generation.questions){assert.equal(q.numberLine.kind,"measurement_scale");assert.equal(q.numberLine.unitId,"millilitre");assert.equal(q.metadata.pointerValue,q.metadata.stepValue*q.metadata.pointerTickIndex);assert.equal(q.answer,q.metadata.pointerValue);assert.equal(q.answerText,`${q.metadata.pointerValue} 毫升`);assert.equal(q.metadata.capacityEstimation,false);assert.equal(q.metadata.mixedUnitComparison,false);assert.equal(q.metadata.mixedUnitArithmetic,false);assert.doesNotMatch(q.blankedDisplayText,/估算|比較|比大小|加法|減法|進位|退位/);}assert.equal(validateBatchABrowserQuestions(generation.questions).ok,true);});

test("P04F7 L/mL conversion has 24 distinct exact cases in both legal directions",()=>{const options={...sourceOptions,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G3B_U02_P04F7_CONVERSION_KP_ID],questionCount:24,generationSeed:"p04f7-conversion-24"},plan=buildBatchABrowserPlan(options);assert.deepEqual(plan.patternSpecIds,[G3B_U02_P04F7_CONVERSION_SPEC_ID]);const generation=generateBatchABrowserQuestions({...options,plan});assert.equal(generation.ok,true,JSON.stringify(generation.errors));assert.equal(generation.questions.length,24);assert.equal(new Set(generation.questions.map(q=>q.blankedDisplayText)).size,24);assert.deepEqual(new Set(generation.questions.map(q=>q.metadata.conversionDirection)),new Set(["ML_TO_L_ML","L_ML_TO_ML"]));for(const q of generation.questions){assert.equal(q.metadata.millilitresPerLitre,1000);assert.equal(q.metadata.totalMillilitres,q.metadata.litres*1000+q.metadata.remainderMillilitres);const expected=q.metadata.conversionDirection==="ML_TO_L_ML"?`${q.metadata.litres} 公升 ${q.metadata.remainderMillilitres} 毫升`:`${q.metadata.totalMillilitres} 毫升`;assert.equal(q.answerText,expected);assert.equal(q.answer,expected);assert.equal(q.metadata.capacityEstimation,false);assert.equal(q.metadata.mixedUnitComparison,false);assert.equal(q.metadata.mixedUnitArithmetic,false);assert.doesNotMatch(q.blankedDisplayText,/估算|比較|比大小|加法|減法|進位|退位/);}assert.equal(validateBatchABrowserQuestions(generation.questions).ok,true);});

test("P04F7 keeps legal one-question boundary and rejects 25-question q007 plan",()=>{const one={...sourceOptions,questionCount:1,generationSeed:"p04f7-one"},onePlan=buildBatchABrowserPlan(one);assert.equal(validateBatchABrowserPlan(onePlan).ok,true);assert.equal(generateBatchABrowserQuestions({...one,plan:onePlan}).questions.length,1);const tooMany={...sourceOptions,questionCount:25,generationSeed:"p04f7-too-many"},tooManyPlan=buildBatchABrowserPlan(tooMany);assert.equal(validateBatchABrowserPlan(tooManyPlan).ok,false);});

test("P04F7 worksheet keeps three source KPs aligned across questions and answers",()=>{const result=buildBatchABrowserWorksheetDocument(sourceOptions);assert.equal(result.ok,true,JSON.stringify(result.errors));const doc=result.worksheetDocument;assert.equal(doc.questionCount,8);assert.equal(doc.questionPages.length,1);assert.equal(doc.answerKeyPages.length,1);assert.equal(doc.summary.capacityUnitIdentityQuestionCount,3);assert.equal(doc.summary.capacityScaleReadingQuestionCount,3);assert.equal(doc.summary.capacityConversionQuestionCount,2);assert.equal(doc.answerKeyItems.length,8);for(let i=0;i<8;i++){assert.equal(doc.answerKeyItems[i].questionId,doc.generatedQuestions[i].id);assert.equal(doc.answerKeyItems[i].answerText,doc.generatedQuestions[i].answerText);assert.equal(doc.questionDisplayModels[i].promptText,doc.generatedQuestions[i].blankedDisplayText);}assert.equal(doc.questionDisplayModels.filter(row=>row.numberLine?.kind==="measurement_scale").length,3);const html=renderWorksheetDocumentToHtml(doc,{stylesheetHref:""});assert.match(html,/毫升/);assert.doesNotMatch(html,/容量的加法|容量的減法|比大小|估算大概/);});

test("P04F7 public binding exposes sourceUnit and each single KP only",()=>{for(const surfaceId of Object.values(PUBLIC_UI_SURFACES)){const source=resolvePublicUiCapabilityBinding({sourceId:G3B_U02_P04F7_SOURCE_ID,surfaceId,selectionMode:"sourceUnit"});assert.equal(source.blocked,false);assert.equal(source.selectedKnowledgePointIds.length,3);assert.equal(source.compatiblePatternGroupIds.length,3);assert.equal(source.questionCount.max,24);for(const kpId of [G3B_U02_P04F2_KP_ID,G3B_U02_P04F7_SCALE_KP_ID,G3B_U02_P04F7_CONVERSION_KP_ID]){const single=resolvePublicUiCapabilityBinding({sourceId:G3B_U02_P04F7_SOURCE_ID,surfaceId,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[kpId]});assert.equal(single.blocked,false);assert.equal(single.selectedKnowledgePointIds[0],kpId);assert.equal(single.compatiblePatternGroupIds.length,1);assert.equal(single.questionCount.max,24);}assert.equal(source.availableSelectionModes.find(row=>row.value==="mixedKnowledgePointsSameUnit").enabled,false);assert.equal(source.availableSelectionModes.find(row=>row.value==="mixedKnowledgePointsCrossUnit").enabled,false);}});
