import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";

import {materializeP04EW4DirectProductVerticalSliceQueue} from "../../src/curriculum/full-product/p04e-w4-direct-product-vertical-slice-queue.mjs";
import {auditP04F3PublicSelectorComposition} from "../../site/modules/curriculum/registry/batch-a-selector-p04f3-extension.js";
import {G3B_U03_P04F3_KP_ID,G3B_U03_P04F3_SOURCE_ID,G3B_U03_P04F3_SPEC_ID,P04F3_REQUIRED_W4_CAPABILITY_IDS} from "../../site/modules/curriculum/registry/g3b-u03-time-12-24-conversion-selector-projection-p04f3.js";
import {buildBatchABrowserPlan} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p04f3.js";
import {generateBatchABrowserQuestions} from "../../site/modules/curriculum/batch-a/batch-a-browser-question-router-p04f3.js";
import {validateBatchABrowserPlan,validateBatchABrowserQuestion,validateBatchABrowserQuestions} from "../../site/modules/curriculum/batch-a/batch-a-browser-validator-p04f3.js";
import {buildBatchABrowserWorksheetDocument,P04F3_WORKSHEET_ADAPTER} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p04f3-extension.js";
import {listBatchASourcePatternDefinitions} from "../../site/modules/curriculum/batch-a/source-pattern-full-product-p04f3-extension.js";
import {listCurrentFullProductPublicSourceUnits} from "../../site/modules/curriculum/batch-a/source-units-p04f3-extension.js";
import {PUBLIC_UI_SURFACES,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p04f3.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";

const options={sourceId:G3B_U03_P04F3_SOURCE_ID,selectionMode:"sourceUnit",questionMode:"numeric",questionCount:8,generationSeed:"p04f3-focused",includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showAnswerKeyPage:true}};
const forbidden=/跨日|隔天|經過時間|多久|幾小時|幾分鐘|幾秒|日換時|時換分|分換秒|加法|減法|加減|進位|退位|借位|時刻表|行程/;

test("P04F3 frozen queue and authority lock q003 to 12/24-hour conversion",()=>{const queue=materializeP04EW4DirectProductVerticalSliceQueue();const q003=queue.queueEntries.find(row=>row.queuePosition===3);assert.ok(q003);assert.equal(q003.sliceId,"p04e_q003_r0_g3b_u03_3b03_profile_time_c1");assert.equal(q003.primarySourceNodeId,G3B_U03_P04F3_SOURCE_ID);assert.equal(q003.primaryRuntimeProfileId,"profile_time");assert.deepEqual(q003.knowledgePointIds,[G3B_U03_P04F3_KP_ID]);assert.deepEqual(q003.requiredW4CapabilityIds,[...P04F3_REQUIRED_W4_CAPABILITY_IDS]);const authority=JSON.parse(fs.readFileSync("data/curriculum/full-product/p04f/slice003-g3b-u03-time-12-24-hour-conversion-authority.json","utf8"));assert.equal(authority.queue.sliceId,q003.sliceId);assert.equal(authority.source.sourcePdfTitle,"meow911_3b03_time.pdf");assert.deepEqual(authority.source.primaryWitnessPages,[1]);assert.equal(authority.knowledgePoint.knowledgePointId,G3B_U03_P04F3_KP_ID);assert.equal(authority.patternSpec.patternSpecId,G3B_U03_P04F3_SPEC_ID);assert.deepEqual(authority.formalMapping.requiredW4CapabilityIds,q003.requiredW4CapabilityIds);assert.equal(authority.knowledgePoint.implementationBoundary.crossDayConversionAllowed,false);assert.equal(authority.knowledgePoint.implementationBoundary.elapsedTimeAllowed,false);assert.equal(authority.knowledgePoint.implementationBoundary.durationUnitConversionAllowed,false);assert.equal(authority.knowledgePoint.implementationBoundary.timeArithmeticAllowed,false);assert.equal(authority.knowledgePoint.implementationBoundary.scheduleReasoningAllowed,false);});

test("P04F3 selector and source inventory add exactly one source and KP",()=>{const audit=auditP04F3PublicSelectorComposition();assert.equal(audit.ok,true,JSON.stringify(audit.errors));assert.deepEqual(audit.counts,{sources:37,knowledgePoints:262,g3bU03Visible:1,g3bU03Hidden:0,g3bU03NotSelectable:0});const sources=listCurrentFullProductPublicSourceUnits();assert.equal(sources.length,37);assert.ok(sources.some(row=>row.sourceId===G3B_U03_P04F3_SOURCE_ID&&row.unitCode==="3B-U03"&&row.title==="時間"));});

test("P04F3 pattern materialization remains one direct numeric time-system spec",()=>{const rows=listBatchASourcePatternDefinitions().filter(row=>row.sourceId===G3B_U03_P04F3_SOURCE_ID);assert.equal(rows.length,1);const row=rows[0];assert.equal(row.knowledgePointId,G3B_U03_P04F3_KP_ID);assert.equal(row.patternSpecId,G3B_U03_P04F3_SPEC_ID);assert.equal(row.applicationClassification,"DIRECT_SOURCE_TIME_SYSTEM_CONVERSION");assert.deepEqual(row.requiredCapabilityIds,[...P04F3_REQUIRED_W4_CAPABILITY_IDS]);assert.equal(row.crossDayConversion,false);assert.equal(row.elapsedTime,false);assert.equal(row.durationUnitConversion,false);assert.equal(row.timeArithmetic,false);assert.equal(row.scheduleReasoning,false);assert.equal(row.operatorApprovedExtension,false);});

test("P04F3 planner generator and validator cover both directions without scope leak",()=>{const plan=buildBatchABrowserPlan(options);assert.equal(plan.sourceId,G3B_U03_P04F3_SOURCE_ID);assert.deepEqual(plan.patternSpecIds,[G3B_U03_P04F3_SPEC_ID]);assert.equal(plan.questionMode,"numeric");assert.equal(plan.genericFallbackAllowed,false);const pv=validateBatchABrowserPlan(plan);assert.equal(pv.ok,true,JSON.stringify(pv.errors));const generation=generateBatchABrowserQuestions({...options,plan});assert.equal(generation.ok,true,JSON.stringify(generation.errors));assert.equal(generation.questions.length,8);assert.equal(new Set(generation.questions.map(q=>q.blankedDisplayText)).size,8);assert.deepEqual(new Set(generation.questions.map(q=>q.metadata.conversionDirection)),new Set(["12_TO_24","24_TO_12"]));for(const q of generation.questions){assert.equal(q.metadata.crossDayConversion,false);assert.equal(q.metadata.elapsedTime,false);assert.equal(q.metadata.durationUnitConversion,false);assert.equal(q.metadata.timeArithmetic,false);assert.equal(q.metadata.scheduleReasoning,false);assert.doesNotMatch(q.blankedDisplayText,forbidden);assert.equal(validateBatchABrowserQuestion(q).ok,true);}const validation=validateBatchABrowserQuestions(generation.questions);assert.equal(validation.ok,true,JSON.stringify(validation.errors));});

test("P04F3 full 24-case capacity covers morning afternoon zero and twelve boundaries",()=>{const plan=buildBatchABrowserPlan({...options,questionCount:24,generationSeed:"p04f3-full-capacity"});const generation=generateBatchABrowserQuestions({...options,questionCount:24,generationSeed:"p04f3-full-capacity",plan});assert.equal(generation.ok,true,JSON.stringify(generation.errors));assert.equal(generation.questions.length,24);assert.equal(new Set(generation.questions.map(q=>q.blankedDisplayText)).size,24);assert.ok(generation.questions.some(q=>q.metadata.period==="上午"));assert.ok(generation.questions.some(q=>q.metadata.period==="下午"));assert.ok(generation.questions.some(q=>q.metadata.hour24===0));assert.ok(generation.questions.some(q=>q.metadata.hour24===12));const validation=validateBatchABrowserQuestions(generation.questions);assert.equal(validation.ok,true,JSON.stringify(validation.errors));});

test("P04F3 generation is deterministic by seed and changes order with a different seed",()=>{const planA=buildBatchABrowserPlan({...options,generationSeed:"seed-A"});const a1=generateBatchABrowserQuestions({...options,generationSeed:"seed-A",plan:planA});const a2=generateBatchABrowserQuestions({...options,generationSeed:"seed-A",plan:planA});const planB=buildBatchABrowserPlan({...options,generationSeed:"seed-B"});const b=generateBatchABrowserQuestions({...options,generationSeed:"seed-B",plan:planB});assert.deepEqual(a1.questions.map(q=>q.blankedDisplayText),a2.questions.map(q=>q.blankedDisplayText));assert.notDeepEqual(a1.questions.map(q=>q.blankedDisplayText),b.questions.map(q=>q.blankedDisplayText));});

test("P04F3 fail-closes tampered answer count and forbidden later-scope content",()=>{const plan=buildBatchABrowserPlan(options);const generation=generateBatchABrowserQuestions({...options,plan});const first=generation.questions[0];const badAnswer={...first,answer:"錯誤",answerText:"錯誤",finalAnswer:"錯誤"};const answerValidation=validateBatchABrowserQuestion(badAnswer);assert.equal(answerValidation.ok,false);assert.ok(answerValidation.errors.some(e=>e.code==="p04f3_answer_mismatch"));const over=generateBatchABrowserQuestions({...options,questionCount:25,plan:{...plan,questionCount:25}});assert.equal(over.ok,false);assert.ok(over.errors.some(e=>e.code==="p04f3_question_count_invalid"));const badScope={...first,metadata:{...first.metadata,elapsedTime:true}};const scopeValidation=validateBatchABrowserQuestion(badScope);assert.equal(scopeValidation.ok,false);assert.ok(scopeValidation.errors.some(e=>e.code==="p04f3_scope_leak"));const badPrompt={...first,blankedDisplayText:"跨日後經過時間是多少？",promptText:"跨日後經過時間是多少？"};const wordingValidation=validateBatchABrowserQuestion(badPrompt);assert.equal(wordingValidation.ok,false);assert.ok(wordingValidation.errors.some(e=>e.code==="p04f3_scope_wording_leak"));});

test("P04F3 worksheet and answer key preserve exact time conversions on shared renderer",()=>{const result=buildBatchABrowserWorksheetDocument(options);assert.equal(result.ok,true,JSON.stringify(result.errors));const doc=result.worksheetDocument;assert.equal(doc.questionCount,8);assert.equal(doc.questionDisplayModels.length,8);assert.equal(doc.answerKeyItems.length,8);assert.equal(doc.questionPages.length,1);assert.equal(doc.answerKeyPages.length,1);assert.equal(doc.metadata.crossDayConversion,false);assert.equal(doc.metadata.elapsedTime,false);assert.equal(doc.metadata.durationUnitConversion,false);assert.equal(doc.metadata.timeArithmetic,false);assert.equal(doc.metadata.scheduleReasoning,false);assert.equal(P04F3_WORKSHEET_ADAPTER.sharedPagination,true);assert.equal(P04F3_WORKSHEET_ADAPTER.sharedRenderer,true);assert.equal(P04F3_WORKSHEET_ADAPTER.parallelPipeline,false);for(let i=0;i<doc.generatedQuestions.length;i++)assert.equal(doc.answerKeyItems[i].answerText,doc.generatedQuestions[i].answerText);const html=renderWorksheetDocumentToHtml(doc,{stylesheetHref:""});assert.match(html,/十二小時制|二十四小時制/);assert.doesNotMatch(html,forbidden);});

test("P04F3 Classic and Pixel capability binding expose sourceUnit and single-KP modes",()=>{for(const surfaceId of [PUBLIC_UI_SURFACES.CLASSIC,PUBLIC_UI_SURFACES.PIXEL]){const sourceBinding=resolvePublicUiCapabilityBinding({sourceId:G3B_U03_P04F3_SOURCE_ID,surfaceId,selectionMode:"sourceUnit"});assert.equal(sourceBinding.blocked,false);assert.equal(sourceBinding.questionType,"numeric");assert.equal(sourceBinding.questionCount.max,24);assert.deepEqual(sourceBinding.selectedKnowledgePointIds,[G3B_U03_P04F3_KP_ID]);const singleBinding=resolvePublicUiCapabilityBinding({sourceId:G3B_U03_P04F3_SOURCE_ID,surfaceId,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G3B_U03_P04F3_KP_ID]});assert.equal(singleBinding.blocked,false);assert.deepEqual(singleBinding.selectedKnowledgePointIds,[G3B_U03_P04F3_KP_ID]);}});
