import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";

import {materializeP04EW4DirectProductVerticalSliceQueue} from "../../src/curriculum/full-product/p04e-w4-direct-product-vertical-slice-queue.mjs";
import {auditP04F3PublicSelectorComposition} from "../../site/modules/curriculum/registry/batch-a-selector-p04f3-extension.js";
import {G3B_U03_P04F3_KP_ID,G3B_U03_P04F3_SOURCE_ID,G3B_U03_P04F3_SPEC_ID,G3B_U03_P04F3_UNIT_CONVERSION_KP_ID,G3B_U03_P04F3_UNIT_CONVERSION_SPEC_ID,P04F3_REQUIRED_W4_CAPABILITY_IDS,P04F3_TIME_SYSTEM_REQUIRED_CAPABILITY_IDS,P04F3_UNIT_CONVERSION_REQUIRED_CAPABILITY_IDS} from "../../site/modules/curriculum/registry/g3b-u03-time-12-24-conversion-selector-projection-p04f3.js";
import {buildBatchABrowserPlan} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p04f3.js";
import {generateBatchABrowserQuestions} from "../../site/modules/curriculum/batch-a/batch-a-browser-question-router-p04f3.js";
import {validateBatchABrowserPlan,validateBatchABrowserQuestion,validateBatchABrowserQuestions} from "../../site/modules/curriculum/batch-a/batch-a-browser-validator-p04f3.js";
import {buildBatchABrowserWorksheetDocument,P04F3_WORKSHEET_ADAPTER} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p04f3-extension.js";
import {listBatchASourcePatternDefinitions} from "../../site/modules/curriculum/batch-a/source-pattern-full-product-p04f3-extension.js";
import {listCurrentFullProductPublicSourceUnits} from "../../site/modules/curriculum/batch-a/source-units-p04f3-extension.js";
import {PUBLIC_UI_SURFACES,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p04f3.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";

const options={sourceId:G3B_U03_P04F3_SOURCE_ID,selectionMode:"sourceUnit",questionMode:"numeric",questionCount:8,generationSeed:"p04f3-focused",includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showAnswerKeyPage:true}};
const laterScope=/跨日|隔天|經過時間|多久|秒|加法|減法|加減|進位|退位|借位|時刻表|行程|開始|結束/;
const singleOptions=(kpId,count=8,seed="p04f3-single")=>({...options,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[kpId],questionCount:count,generationSeed:seed});

test("P04F3 frozen queue and authority lock q003 to both time KPs",()=>{const queue=materializeP04EW4DirectProductVerticalSliceQueue();const q003=queue.queueEntries.find(row=>row.queuePosition===3);assert.ok(q003);assert.equal(q003.sliceId,"p04e_q003_r0_g3b_u03_3b03_profile_time_c1");assert.equal(q003.primarySourceNodeId,G3B_U03_P04F3_SOURCE_ID);assert.equal(q003.primaryRuntimeProfileId,"profile_time");assert.deepEqual(q003.knowledgePointIds,[G3B_U03_P04F3_KP_ID,G3B_U03_P04F3_UNIT_CONVERSION_KP_ID]);assert.deepEqual(q003.requiredW4CapabilityIds,[...P04F3_REQUIRED_W4_CAPABILITY_IDS]);const authority=JSON.parse(fs.readFileSync("data/curriculum/full-product/p04f/slice003-g3b-u03-time-12-24-hour-conversion-authority.json","utf8"));assert.equal(authority.queue.sliceId,q003.sliceId);assert.equal(authority.queue.knowledgePointCount,2);assert.equal(authority.source.sourcePdfTitle,"meow911_3b03_time.pdf");assert.deepEqual(authority.source.primaryWitnessPages,[1]);assert.deepEqual(authority.knowledgePoints.map(row=>row.knowledgePointId),q003.knowledgePointIds);assert.deepEqual(authority.patternSpecs.map(row=>row.patternSpecId),[G3B_U03_P04F3_SPEC_ID,G3B_U03_P04F3_UNIT_CONVERSION_SPEC_ID]);assert.deepEqual(authority.formalMapping.requiredW4CapabilityIds,q003.requiredW4CapabilityIds);assert.deepEqual(authority.formalMapping.knowledgePointCapabilityRequirements[G3B_U03_P04F3_KP_ID],[...P04F3_TIME_SYSTEM_REQUIRED_CAPABILITY_IDS]);assert.deepEqual(authority.formalMapping.knowledgePointCapabilityRequirements[G3B_U03_P04F3_UNIT_CONVERSION_KP_ID],[...P04F3_UNIT_CONVERSION_REQUIRED_CAPABILITY_IDS]);assert.equal(authority.knowledgePoints[0].implementationBoundary.durationUnitConversionAllowed,false);assert.equal(authority.knowledgePoints[1].implementationBoundary.secondUnitConversionAllowed,false);assert.equal(authority.knowledgePoints[1].implementationBoundary.elapsedTimeAllowed,false);assert.equal(authority.knowledgePoints[1].implementationBoundary.timeArithmeticAllowed,false);});

test("P04F3 selector and source inventory add exactly one source and two KPs",()=>{const audit=auditP04F3PublicSelectorComposition();assert.equal(audit.ok,true,JSON.stringify(audit.errors));assert.deepEqual(audit.counts,{sources:37,knowledgePoints:263,g3bU03Visible:2,g3bU03Hidden:0,g3bU03NotSelectable:0});const sources=listCurrentFullProductPublicSourceUnits();assert.equal(sources.length,37);assert.ok(sources.some(row=>row.sourceId===G3B_U03_P04F3_SOURCE_ID&&row.unitCode==="3B-U03"&&row.title==="時間"));});

test("P04F3 pattern materialization has one numeric spec per frozen KP",()=>{const rows=listBatchASourcePatternDefinitions().filter(row=>row.sourceId===G3B_U03_P04F3_SOURCE_ID);assert.equal(rows.length,2);assert.deepEqual(rows.map(row=>row.knowledgePointId),[G3B_U03_P04F3_KP_ID,G3B_U03_P04F3_UNIT_CONVERSION_KP_ID]);assert.deepEqual(rows.map(row=>row.patternSpecId),[G3B_U03_P04F3_SPEC_ID,G3B_U03_P04F3_UNIT_CONVERSION_SPEC_ID]);assert.equal(rows[0].applicationClassification,"DIRECT_SOURCE_TIME_SYSTEM_CONVERSION");assert.equal(rows[1].applicationClassification,"DIRECT_SOURCE_TIME_UNIT_CONVERSION");assert.deepEqual(rows[0].requiredCapabilityIds,[...P04F3_TIME_SYSTEM_REQUIRED_CAPABILITY_IDS]);assert.deepEqual(rows[1].requiredCapabilityIds,[...P04F3_UNIT_CONVERSION_REQUIRED_CAPABILITY_IDS]);assert.equal(rows[0].durationUnitConversion,false);assert.equal(rows[1].durationUnitConversion,true);assert.equal(rows[1].secondsAllowed,false);assert.ok(rows.every(row=>row.operatorApprovedExtension===false));});

test("P04F3 source-unit planner generator and validator cover both frozen KPs without later-scope leak",()=>{const plan=buildBatchABrowserPlan(options);assert.equal(plan.sourceId,G3B_U03_P04F3_SOURCE_ID);assert.deepEqual(plan.patternSpecIds,[G3B_U03_P04F3_SPEC_ID,G3B_U03_P04F3_UNIT_CONVERSION_SPEC_ID]);assert.deepEqual(plan.requestedKnowledgePointIds,[G3B_U03_P04F3_KP_ID,G3B_U03_P04F3_UNIT_CONVERSION_KP_ID]);assert.equal(plan.questionMode,"numeric");assert.equal(plan.genericFallbackAllowed,false);const pv=validateBatchABrowserPlan(plan);assert.equal(pv.ok,true,JSON.stringify(pv.errors));const generation=generateBatchABrowserQuestions({...options,plan});assert.equal(generation.ok,true,JSON.stringify(generation.errors));assert.equal(generation.questions.length,8);assert.equal(new Set(generation.questions.map(q=>q.blankedDisplayText)).size,8);assert.deepEqual(generation.allocation.map(row=>row.questionCount),[4,4]);assert.deepEqual(new Set(generation.questions.map(q=>q.knowledgePointId)),new Set([G3B_U03_P04F3_KP_ID,G3B_U03_P04F3_UNIT_CONVERSION_KP_ID]));for(const q of generation.questions){assert.equal(q.metadata.crossDayConversion,false);assert.equal(q.metadata.elapsedTime,false);assert.equal(q.metadata.timeArithmetic,false);assert.equal(q.metadata.scheduleReasoning,false);assert.doesNotMatch(q.blankedDisplayText,laterScope);assert.equal(validateBatchABrowserQuestion(q).ok,true);}const validation=validateBatchABrowserQuestions(generation.questions);assert.equal(validation.ok,true,JSON.stringify(validation.errors));});

test("P04F3 clock KP preserves 24-case capacity and 0/12 boundaries",()=>{const clockOptions=singleOptions(G3B_U03_P04F3_KP_ID,24,"p04f3-clock-capacity");const plan=buildBatchABrowserPlan(clockOptions);assert.deepEqual(plan.patternSpecIds,[G3B_U03_P04F3_SPEC_ID]);const generation=generateBatchABrowserQuestions({...clockOptions,plan});assert.equal(generation.ok,true,JSON.stringify(generation.errors));assert.equal(generation.questions.length,24);assert.equal(new Set(generation.questions.map(q=>q.blankedDisplayText)).size,24);assert.ok(generation.questions.some(q=>q.metadata.period==="上午"));assert.ok(generation.questions.some(q=>q.metadata.period==="下午"));assert.ok(generation.questions.some(q=>q.metadata.hour24===0));assert.ok(generation.questions.some(q=>q.metadata.hour24===12));assert.equal(validateBatchABrowserQuestions(generation.questions).ok,true);});

test("P04F3 day-hour-minute KP has 24 distinct conversions and mixed-unit normalization",()=>{const unitOptions=singleOptions(G3B_U03_P04F3_UNIT_CONVERSION_KP_ID,24,"p04f3-unit-capacity");const plan=buildBatchABrowserPlan(unitOptions);assert.deepEqual(plan.patternSpecIds,[G3B_U03_P04F3_UNIT_CONVERSION_SPEC_ID]);const generation=generateBatchABrowserQuestions({...unitOptions,plan});assert.equal(generation.ok,true,JSON.stringify(generation.errors));assert.equal(generation.questions.length,24);assert.equal(new Set(generation.questions.map(q=>q.blankedDisplayText)).size,24);assert.deepEqual(new Set(generation.questions.map(q=>q.metadata.conversionDirection)),new Set(["DAY_TO_HOUR","HOUR_TO_DAY_HOUR","HOUR_TO_MINUTE","MINUTE_TO_HOUR_MINUTE"]));assert.ok(generation.questions.some(q=>q.answerText.includes("日")&&q.answerText.includes("時")));assert.ok(generation.questions.some(q=>q.answerText.includes("時")&&q.answerText.includes("分")));assert.ok(generation.questions.every(q=>q.metadata.secondsAllowed===false));assert.equal(validateBatchABrowserQuestions(generation.questions).ok,true);});

test("P04F3 generation is deterministic by seed and changes order with a different seed",()=>{const planA=buildBatchABrowserPlan({...options,generationSeed:"seed-A"});const a1=generateBatchABrowserQuestions({...options,generationSeed:"seed-A",plan:planA});const a2=generateBatchABrowserQuestions({...options,generationSeed:"seed-A",plan:planA});const planB=buildBatchABrowserPlan({...options,generationSeed:"seed-B"});const b=generateBatchABrowserQuestions({...options,generationSeed:"seed-B",plan:planB});assert.deepEqual(a1.questions.map(q=>q.blankedDisplayText),a2.questions.map(q=>q.blankedDisplayText));assert.notDeepEqual(a1.questions.map(q=>q.blankedDisplayText),b.questions.map(q=>q.blankedDisplayText));});

test("P04F3 fail-closes tampered answers count and forbidden later-scope content",()=>{const clockOptions=singleOptions(G3B_U03_P04F3_KP_ID);const clockPlan=buildBatchABrowserPlan(clockOptions);const clock=generateBatchABrowserQuestions({...clockOptions,plan:clockPlan}).questions[0];const badClock={...clock,answer:"錯誤",answerText:"錯誤",finalAnswer:"錯誤"};assert.ok(validateBatchABrowserQuestion(badClock).errors.some(e=>e.code==="p04f3_answer_mismatch"));const unitOptions=singleOptions(G3B_U03_P04F3_UNIT_CONVERSION_KP_ID);const unitPlan=buildBatchABrowserPlan(unitOptions);const unit=generateBatchABrowserQuestions({...unitOptions,plan:unitPlan}).questions[0];const badUnit={...unit,answer:"錯誤",answerText:"錯誤",finalAnswer:"錯誤"};assert.ok(validateBatchABrowserQuestion(badUnit).errors.some(e=>e.code==="p04f3_unit_answer_mismatch"));const over=generateBatchABrowserQuestions({...options,questionCount:25,plan:{...buildBatchABrowserPlan(options),questionCount:25}});assert.equal(over.ok,false);const badScope={...clock,metadata:{...clock.metadata,elapsedTime:true}};assert.ok(validateBatchABrowserQuestion(badScope).errors.some(e=>e.code==="p04f3_scope_leak"));const badPrompt={...unit,blankedDisplayText:"把60分換成幾秒？",promptText:"把60分換成幾秒？"};assert.ok(validateBatchABrowserQuestion(badPrompt).errors.some(e=>e.code==="p04f3_unit_scope_wording_leak"));});

test("P04F3 worksheet and answer key preserve both time conversion KPs on shared renderer",()=>{const result=buildBatchABrowserWorksheetDocument(options);assert.equal(result.ok,true,JSON.stringify(result.errors));const doc=result.worksheetDocument;assert.equal(doc.questionCount,8);assert.equal(doc.questionDisplayModels.length,8);assert.equal(doc.answerKeyItems.length,8);assert.equal(doc.questionPages.length,1);assert.equal(doc.answerKeyPages.length,1);assert.deepEqual(doc.metadata.knowledgePointIds,[G3B_U03_P04F3_KP_ID,G3B_U03_P04F3_UNIT_CONVERSION_KP_ID]);assert.deepEqual(doc.metadata.patternSpecIds,[G3B_U03_P04F3_SPEC_ID,G3B_U03_P04F3_UNIT_CONVERSION_SPEC_ID]);assert.equal(doc.metadata.crossDayConversion,false);assert.equal(doc.metadata.elapsedTime,false);assert.equal(doc.metadata.durationUnitConversion,true);assert.equal(doc.metadata.mixedUnitNormalization,true);assert.equal(doc.metadata.secondsAllowed,false);assert.equal(doc.metadata.timeArithmetic,false);assert.equal(doc.metadata.scheduleReasoning,false);assert.equal(P04F3_WORKSHEET_ADAPTER.sharedPagination,true);assert.equal(P04F3_WORKSHEET_ADAPTER.sharedRenderer,true);assert.equal(P04F3_WORKSHEET_ADAPTER.parallelPipeline,false);assert.equal(doc.summary.timeSystemConversionQuestionCount,4);assert.equal(doc.summary.timeUnitConversionQuestionCount,4);for(let i=0;i<doc.generatedQuestions.length;i++)assert.equal(doc.answerKeyItems[i].answerText,doc.generatedQuestions[i].answerText);const html=renderWorksheetDocumentToHtml(doc,{stylesheetHref:""});assert.match(html,/十二小時制|二十四小時制/);assert.match(html,/日|時|分/);assert.doesNotMatch(html,laterScope);});

test("P04F3 Classic and Pixel binding expose sourceUnit plus either frozen KP in single-KP mode",()=>{for(const surfaceId of [PUBLIC_UI_SURFACES.CLASSIC,PUBLIC_UI_SURFACES.PIXEL]){const sourceBinding=resolvePublicUiCapabilityBinding({sourceId:G3B_U03_P04F3_SOURCE_ID,surfaceId,selectionMode:"sourceUnit"});assert.equal(sourceBinding.blocked,false);assert.equal(sourceBinding.questionType,"numeric");assert.equal(sourceBinding.questionCount.max,24);assert.deepEqual(sourceBinding.selectedKnowledgePointIds,[G3B_U03_P04F3_KP_ID,G3B_U03_P04F3_UNIT_CONVERSION_KP_ID]);assert.equal(sourceBinding.compatiblePatternGroupIds.length,2);for(const kpId of[G3B_U03_P04F3_KP_ID,G3B_U03_P04F3_UNIT_CONVERSION_KP_ID]){const singleBinding=resolvePublicUiCapabilityBinding({sourceId:G3B_U03_P04F3_SOURCE_ID,surfaceId,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[kpId]});assert.equal(singleBinding.blocked,false);assert.deepEqual(singleBinding.selectedKnowledgePointIds,[kpId]);assert.equal(singleBinding.compatiblePatternGroupIds.length,1);}}});
