import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";

import {auditP04F6PublicSelectorComposition} from "../../site/modules/curriculum/registry/batch-a-selector-p04f6-extension.js";
import {G3A_U04_P04F1_KP_ID,G3A_U04_P04F1_SPEC_ID} from "../../site/modules/curriculum/registry/g3a-u04-ruler-reading-selector-projection-p04f1.js";
import {G3A_U04_P04F6_SOURCE_ID,G3A_U04_P04F6_KP_ID,G3A_U04_P04F6_SPEC_ID} from "../../site/modules/curriculum/registry/g3a-u04-cm-mm-conversion-selector-projection-p04f6.js";
import {buildBatchABrowserPlan} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p04f6.js";
import {generateBatchABrowserQuestions} from "../../site/modules/curriculum/batch-a/batch-a-browser-question-router-p04f6.js";
import {validateBatchABrowserPlan,validateBatchABrowserQuestions} from "../../site/modules/curriculum/batch-a/batch-a-browser-validator-p04f6.js";
import {buildBatchABrowserWorksheetDocument} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p04f6-extension.js";
import {resolvePublicUiCapabilityBinding,PUBLIC_UI_SURFACES} from "../../site/modules/curriculum/public/public-ui-capability-binding-p04f6.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";

const sourceOptions={sourceId:G3A_U04_P04F6_SOURCE_ID,selectionMode:"sourceUnit",questionMode:"numeric",questionCount:8,generationSeed:"p04f6-focused",includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showAnswerKeyPage:true}};

test("P04F6 authority is locked to q006 cm/mm conversion only",()=>{const authority=JSON.parse(fs.readFileSync("data/curriculum/full-product/p04f/slice006-g3a-u04-cm-mm-conversion-authority.json","utf8"));assert.equal(authority.queue.sliceId,"p04e_q006_r1_g3a_u04_3a04_profile_quantity_measurement_c1");assert.equal(authority.source.sourcePdfTitle,"meow911_3a04_mm_number_line.pdf");assert.deepEqual(authority.source.reviewedPages,[1,2]);assert.equal(authority.knowledgePoint.knowledgePointId,G3A_U04_P04F6_KP_ID);assert.equal(authority.patternSpec.patternSpecId,G3A_U04_P04F6_SPEC_ID);assert.equal(authority.formalMapping.millimetersPerCentimeter,10);assert.deepEqual(authority.patternSpec.constraints.allowedDirections,["CM_TO_MM","MM_TO_CM"]);assert.deepEqual(authority.knowledgePoint.implementationBoundary.excludedKnowledgePointIds,["kp_length_mixed_unit_compare","kp_length_mixed_unit_add_sub"]);});

test("P04F6 selector adds one KP on the existing public source",()=>{const audit=auditP04F6PublicSelectorComposition();assert.equal(audit.ok,true,JSON.stringify(audit.errors));assert.deepEqual(audit.counts,{sources:39,knowledgePoints:267,g3aU04Visible:2,g3aU04Hidden:0,g3aU04NotSelectable:0});});

test("P04F6 source-unit coordinator preserves q001 and q006 together",()=>{const plan=buildBatchABrowserPlan(sourceOptions);assert.deepEqual(new Set(plan.patternSpecIds),new Set([G3A_U04_P04F1_SPEC_ID,G3A_U04_P04F6_SPEC_ID]));assert.deepEqual(new Set(plan.requestedKnowledgePointIds),new Set([G3A_U04_P04F1_KP_ID,G3A_U04_P04F6_KP_ID]));assert.equal(validateBatchABrowserPlan(plan).ok,true);const generation=generateBatchABrowserQuestions({...sourceOptions,plan});assert.equal(generation.ok,true,JSON.stringify(generation.errors));assert.equal(generation.questions.length,8);assert.equal(generation.questions.filter(q=>q.patternSpecId===G3A_U04_P04F1_SPEC_ID).length,4);assert.equal(generation.questions.filter(q=>q.patternSpecId===G3A_U04_P04F6_SPEC_ID).length,4);const validation=validateBatchABrowserQuestions(generation.questions);assert.equal(validation.ok,true,JSON.stringify(validation.errors));});

test("P04F6 source-unit coordinator accepts the legal one-question boundary",()=>{const options={...sourceOptions,questionCount:1,generationSeed:"p04f6-one"};const plan=buildBatchABrowserPlan(options);assert.equal(validateBatchABrowserPlan(plan).ok,true);const generation=generateBatchABrowserQuestions({...options,plan});assert.equal(generation.ok,true,JSON.stringify(generation.errors));assert.equal(generation.questions.length,1);assert.equal(generation.questions[0].patternSpecId,G3A_U04_P04F1_SPEC_ID);assert.equal(validateBatchABrowserQuestions(generation.questions).ok,true);});

test("P04F6 conversion single-KP has 24 distinct exact integer cases",()=>{const options={...sourceOptions,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G3A_U04_P04F6_KP_ID],questionCount:24,generationSeed:"p04f6-capacity"};const plan=buildBatchABrowserPlan(options);assert.deepEqual(plan.patternSpecIds,[G3A_U04_P04F6_SPEC_ID]);const generation=generateBatchABrowserQuestions({...options,plan});assert.equal(generation.ok,true,JSON.stringify(generation.errors));assert.equal(generation.questions.length,24);assert.equal(new Set(generation.questions.map(q=>q.blankedDisplayText)).size,24);assert.deepEqual(new Set(generation.questions.map(q=>q.metadata.conversionDirection)),new Set(["CM_TO_MM","MM_TO_CM"]));for(const q of generation.questions){assert.equal(q.metadata.millimetersPerCentimeter,10);assert.equal(q.metadata.mixedUnitComparison,false);assert.equal(q.metadata.mixedUnitArithmetic,false);assert.doesNotMatch(q.blankedDisplayText,/比較|加減|相差|總長|直尺|刻度/);}assert.equal(validateBatchABrowserQuestions(generation.questions).ok,true);});

test("P04F6 low-count conversion alternates both legal directions",()=>{const options={...sourceOptions,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G3A_U04_P04F6_KP_ID],questionCount:2,generationSeed:"p04f6-two-directions"};const plan=buildBatchABrowserPlan(options);const generation=generateBatchABrowserQuestions({...options,plan});assert.equal(generation.ok,true,JSON.stringify(generation.errors));assert.deepEqual(new Set(generation.questions.map(q=>q.metadata.conversionDirection)),new Set(["CM_TO_MM","MM_TO_CM"]));});

test("P04F6 worksheet keeps q001 ruler and q006 conversion on one question plus one answer page",()=>{const result=buildBatchABrowserWorksheetDocument(sourceOptions);assert.equal(result.ok,true,JSON.stringify(result.errors));const doc=result.worksheetDocument;assert.equal(doc.questionCount,8);assert.equal(doc.questionPages.length,1);assert.equal(doc.answerKeyPages.length,1);assert.equal(doc.summary.rulerReadingQuestionCount,4);assert.equal(doc.summary.cmMmConversionQuestionCount,4);assert.equal(doc.answerKeyItems.length,8);const html=renderWorksheetDocumentToHtml(doc,{stylesheetHref:""});assert.match(html,/worksheet-measurement-ruler/);assert.match(html,/公分|毫米/);assert.doesNotMatch(html,/混合量比較|混合量加減/);});

test("P04F6 public binding exposes sourceUnit plus each single KP without cross-unit mixing",()=>{for(const surfaceId of Object.values(PUBLIC_UI_SURFACES)){const source=resolvePublicUiCapabilityBinding({sourceId:G3A_U04_P04F6_SOURCE_ID,surfaceId,selectionMode:"sourceUnit"});assert.equal(source.blocked,false);assert.equal(source.selectedKnowledgePointIds.length,2);assert.equal(source.compatiblePatternGroupIds.length,2);assert.equal(source.questionCount.max,24);const ruler=resolvePublicUiCapabilityBinding({sourceId:G3A_U04_P04F6_SOURCE_ID,surfaceId,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G3A_U04_P04F1_KP_ID]});assert.equal(ruler.questionCount.max,39);const conversion=resolvePublicUiCapabilityBinding({sourceId:G3A_U04_P04F6_SOURCE_ID,surfaceId,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G3A_U04_P04F6_KP_ID]});assert.equal(conversion.questionCount.max,24);assert.equal(source.availableSelectionModes.find(row=>row.value==="mixedKnowledgePointsSameUnit").enabled,false);}}
