import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import {auditP04F32PublicSelectorComposition,listBatchAKnowledgePointAvailabilityBySource} from "../../site/modules/curriculum/registry/batch-a-selector-p04f32-extension.js";
import {auditG5BU02P04F32SelectorProjection,G5B_U02_P04F32_SOURCE_ID,G5B_U02_P04F32_MULTI_KP_ID,G5B_U02_P04F32_SIMPLIFY_KP_ID,G5B_U02_P04F32_QUANTITY_KP_ID,G5B_U02_P04F32_INTEGER_TIMES_KP_ID,G5B_U02_P04F32_MULTI_GROUP_ID,G5B_U02_P04F32_SIMPLIFY_GROUP_ID,G5B_U02_P04F32_QUANTITY_GROUP_ID,G5B_U02_P04F32_INTEGER_TIMES_GROUP_ID,G5B_U02_P04F32_MULTI_SPEC_ID,G5B_U02_P04F32_SIMPLIFY_SPEC_ID,G5B_U02_P04F32_QUANTITY_SPEC_ID,G5B_U02_P04F32_INTEGER_TIMES_SPEC_ID,G5B_U02_P04F32_ALL_PUBLIC_IDS} from "../../site/modules/curriculum/registry/g5b-u02-fraction-rank8-selector-projection-p04f32.js";
import {G5B_U02_P04F31_KP_ID,G5B_U02_P04F31_SPEC_ID} from "../../site/modules/curriculum/registry/g5b-u02-fraction-times-integer-selector-projection-p04f31.js";
import {buildBatchABrowserPlan} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p04f32.js";
import {generateG5BU02P04F32QuestionSet,validateG5BU02P04F32Question,P04F32_DISTINCT_CAPACITY_BY_SPEC} from "../../site/modules/curriculum/batch-a/g5b-u02-fraction-runtime-p04f32.js";
import {resolvePublicUiCapabilityBinding,auditPublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p04f32.js";
import {buildBatchABrowserWorksheetDocument} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-r2e-entry.js";
const read=p=>JSON.parse(fs.readFileSync(new URL(`../../${p}`,import.meta.url),"utf8")),authority=read("data/curriculum/full-product/p04f/slice032-g5b-u02-fraction-rank8-preflight-authority.json");
const NEW=[
  {kp:G5B_U02_P04F32_MULTI_KP_ID,group:G5B_U02_P04F32_MULTI_GROUP_ID,spec:G5B_U02_P04F32_MULTI_SPEC_ID,relation:"FRACTION_MULTI_STEP_CALCULATION"},
  {kp:G5B_U02_P04F32_SIMPLIFY_KP_ID,group:G5B_U02_P04F32_SIMPLIFY_GROUP_ID,spec:G5B_U02_P04F32_SIMPLIFY_SPEC_ID,relation:"FRACTION_PRODUCT_SIMPLIFICATION"},
  {kp:G5B_U02_P04F32_QUANTITY_KP_ID,group:G5B_U02_P04F32_QUANTITY_GROUP_ID,spec:G5B_U02_P04F32_QUANTITY_SPEC_ID,relation:"FRACTION_OF_QUANTITY"},
  {kp:G5B_U02_P04F32_INTEGER_TIMES_KP_ID,group:G5B_U02_P04F32_INTEGER_TIMES_GROUP_ID,spec:G5B_U02_P04F32_INTEGER_TIMES_SPEC_ID,relation:"FRACTION_TIMES_INTEGER_PRODUCT"}
];
function optionsFor(row,count,seed){return{sourceId:G5B_U02_P04F32_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[row.kp],selectedPatternGroupIds:[row.group],patternSpecIds:[row.spec],questionMode:"numeric",questionCount:count,generationSeed:seed};}
test("P04F32 q032 exact four-KP FormalMapping and PatternSpec authority is preserved",()=>{assert.equal(authority.queue.sliceId,"p04e_q032_r8_g5b_u02_5b02_profile_fraction_c1");assert.deepEqual(authority.queue.knowledgePointIds,NEW.map(row=>row.kp));assert.equal(authority.formalMappings.length,4);assert.deepEqual(authority.formalMappings.map(row=>row.relationFamilyId),NEW.map(row=>row.relation));assert.equal(authority.reconciliation.activeRelationReuseCount,2);assert.equal(authority.reconciliation.newRelationCandidateCount,2);assert.equal(auditG5BU02P04F32SelectorProjection().ok,true);});
test("P04F32 promotes q032 on the existing G5B-U02 source at 43 sources / 305 visible KPs",()=>{const audit=auditP04F32PublicSelectorComposition(),availability=listBatchAKnowledgePointAvailabilityBySource(G5B_U02_P04F32_SOURCE_ID);assert.equal(audit.ok,true,JSON.stringify(audit.errors));assert.deepEqual(audit.counts,{sources:43,knowledgePoints:305,g5bU02Visible:5,g5bU02Hidden:0,g5bU02NotSelectable:0});assert.equal(availability.visibleKnowledgePointIds.length,5);for(const id of G5B_U02_P04F32_ALL_PUBLIC_IDS.knowledgePointIds)assert.ok(availability.visibleKnowledgePointIds.includes(id));});
test("P04F32 public capability binding exposes sourceUnit, single KP and mixed same-unit at max 240",()=>{const audit=auditPublicUiCapabilityBinding();assert.equal(audit.ok,true,JSON.stringify(audit.errors));const source=resolvePublicUiCapabilityBinding({sourceId:G5B_U02_P04F32_SOURCE_ID,selectionMode:"sourceUnit"});assert.equal(source.blocked,false);assert.equal(source.questionType,"numeric");assert.equal(source.questionCount.max,240);assert.equal(source.selectedKnowledgePointIds.length,5);assert.equal(source.compatiblePatternGroupIds.length,5);const mixed=resolvePublicUiCapabilityBinding({sourceId:G5B_U02_P04F32_SOURCE_ID,selectionMode:"mixedKnowledgePointsSameUnit",selectedKnowledgePointIds:[G5B_U02_P04F31_KP_ID,G5B_U02_P04F32_INTEGER_TIMES_KP_ID,G5B_U02_P04F32_SIMPLIFY_KP_ID]});assert.equal(mixed.blocked,false);assert.equal(mixed.selectedKnowledgePointIds.length,3);assert.equal(mixed.compatiblePatternGroupIds.length,3);});
for(const row of NEW)test(`P04F32 ${row.kp} generates and validates 24 exact numeric questions`,()=>{const options=optionsFor(row,24,`p04f32-24-${row.kp}`),plan=buildBatchABrowserPlan(options),result=generateG5BU02P04F32QuestionSet({plan,questionCount:24,generationSeed:options.generationSeed});assert.equal(result.ok,true,JSON.stringify(result.errors));assert.equal(result.questions.length,24);assert.equal(new Set(result.questions.map(q=>q.blankedDisplayText)).size,24);assert.equal(result.questions.every(q=>q.knowledgePointId===row.kp&&q.patternSpecId===row.spec&&q.metadata.relationFamilyId===row.relation&&q.questionMode==="numeric"),true);assert.equal(result.questions.every(q=>validateG5BU02P04F32Question(q).ok),true);});
for(const row of NEW)test(`P04F32 ${row.kp} proves 240 distinct public capacity`,()=>{assert.ok(P04F32_DISTINCT_CAPACITY_BY_SPEC[row.spec]>=240);const options=optionsFor(row,240,`p04f32-240-${row.kp}`),binding=resolvePublicUiCapabilityBinding(options),plan=buildBatchABrowserPlan(options),result=generateG5BU02P04F32QuestionSet({plan,questionCount:240,generationSeed:options.generationSeed});assert.equal(binding.questionCount.max,240);assert.equal(result.ok,true,JSON.stringify(result.errors));assert.equal(result.questions.length,240);assert.equal(new Set(result.questions.map(q=>q.blankedDisplayText)).size,240);assert.equal(result.questions.every(q=>validateG5BU02P04F32Question(q).ok),true);});
test("P04F32 sourceUnit generates 240 distinct questions balanced across q031 + four q032 PatternSpecs",()=>{const options={sourceId:G5B_U02_P04F32_SOURCE_ID,selectionMode:"sourceUnit",questionMode:"numeric",questionCount:240,generationSeed:"p04f32-source-240"},plan=buildBatchABrowserPlan(options),result=generateG5BU02P04F32QuestionSet({plan,questionCount:240,generationSeed:options.generationSeed});assert.equal(result.ok,true,JSON.stringify(result.errors));assert.equal(result.questions.length,240);assert.equal(new Set(result.questions.map(q=>q.blankedDisplayText)).size,240);assert.equal(result.allocation.length,5);assert.deepEqual(result.allocation.map(row=>row.questionCount),[48,48,48,48,48]);assert.equal(new Set(result.questions.map(q=>q.knowledgePointId)).size,5);assert.equal(result.questions.every(q=>validateG5BU02P04F32Question(q).ok),true);assert.equal(result.questions.some(q=>q.patternSpecId===G5B_U02_P04F31_SPEC_ID),true);assert.equal(result.questions.some(q=>q.metadata?.q033Touched===true),false);});
test("P04F32 preserves q031 single-KP semantics through the q032 successor wrapper",()=>{const options={sourceId:G5B_U02_P04F32_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G5B_U02_P04F31_KP_ID],questionMode:"numeric",questionCount:24,generationSeed:"p04f32-q031-regression"},plan=buildBatchABrowserPlan(options),result=generateG5BU02P04F32QuestionSet({plan,questionCount:24,generationSeed:options.generationSeed});assert.equal(result.ok,true,JSON.stringify(result.errors));assert.equal(result.questions.length,24);assert.equal(result.questions.every(q=>q.knowledgePointId===G5B_U02_P04F31_KP_ID&&q.patternSpecId===G5B_U02_P04F31_SPEC_ID&&q.metadata.relationFamilyId==="FRACTION_TIMES_INTEGER_PRODUCT"),true);assert.equal(result.questions.every(q=>validateG5BU02P04F32Question(q).ok),true);});
test("P04F32 sourceUnit worksheet materializes 40 questions / answers across five KPs on shared pagination",()=>{const result=buildBatchABrowserWorksheetDocument({sourceId:G5B_U02_P04F32_SOURCE_ID,selectionMode:"sourceUnit",questionMode:"numeric",questionCount:40,generationSeed:"p04f32-worksheet-40",includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showQuestionNumbers:true,showAnswerKeyPage:true}});assert.equal(result.ok,true,JSON.stringify(result.errors));const doc=result.worksheetDocument;assert.equal(doc.generatedQuestions.length,40);assert.equal(doc.answerKeyItems.length,40);assert.equal(doc.questionPages.length,5);assert.equal(doc.answerKeyPages.length,5);assert.equal(new Set(doc.generatedQuestions.map(q=>q.knowledgePointId)).size,5);assert.equal(doc.metadata.q033Touched,false);assert.equal(doc.summary.numericQuestionCount,40);assert.equal(doc.summary.applicationQuestionCount,0);});
