import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import {auditG5BU02P04F32SelectorProjection,G5B_U02_P04F32_ALL_PUBLIC_IDS,G5B_U02_P04F32_MULTI_KP_ID,G5B_U02_P04F32_SIMPLIFY_KP_ID,G5B_U02_P04F32_QUANTITY_KP_ID,G5B_U02_P04F32_INTEGER_TIMES_KP_ID,G5B_U02_P04F32_MULTI_SPEC_ID,G5B_U02_P04F32_SIMPLIFY_SPEC_ID,G5B_U02_P04F32_QUANTITY_SPEC_ID,G5B_U02_P04F32_INTEGER_TIMES_SPEC_ID} from "../../site/modules/curriculum/registry/g5b-u02-fraction-rank8-selector-projection-p04f32.js";
import {auditP04F32PublicSelectorComposition,BATCH_A_SELECTOR_AVAILABILITY,listBatchAKnowledgePointAvailabilityBySource,listVisibleBatchAKnowledgePoints} from "../../site/modules/curriculum/registry/batch-a-selector-p04f32-extension.js";
import {G5B_U02_P04F31_KP_ID,G5B_U02_P04F31_SPEC_ID} from "../../site/modules/curriculum/registry/g5b-u02-fraction-times-integer-selector-projection-p04f31.js";
import {P04F32_DISTINCT_CAPACITY_BY_SPEC,generateG5BU02P04F32IntegerTimesFractionQuestions,generateG5BU02P04F32SimplificationQuestions,generateG5BU02P04F32FractionOfQuantityQuestions,generateG5BU02P04F32MultiStepQuestions,validateG5BU02P04F32Question} from "../../site/modules/curriculum/batch-a/g5b-u02-fraction-runtime-p04f32.js";
import {buildBatchABrowserPlan} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p04f32.js";
import {buildBatchABrowserWorksheetDocument} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p04f32-extension.js";
import {resolvePublicUiCapabilityBinding,auditPublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p04f32.js";
const read=p=>JSON.parse(fs.readFileSync(new URL(`../../${p}`,import.meta.url),"utf8"));
const authority=read("data/curriculum/full-product/p04f/slice032-g5b-u02-fraction-rank8-preflight-authority.json");
const SOURCE="g5b_u02_5b02",NEW_KPS=[G5B_U02_P04F32_MULTI_KP_ID,G5B_U02_P04F32_SIMPLIFY_KP_ID,G5B_U02_P04F32_QUANTITY_KP_ID,G5B_U02_P04F32_INTEGER_TIMES_KP_ID],NEW_SPECS=[G5B_U02_P04F32_MULTI_SPEC_ID,G5B_U02_P04F32_SIMPLIFY_SPEC_ID,G5B_U02_P04F32_QUANTITY_SPEC_ID,G5B_U02_P04F32_INTEGER_TIMES_SPEC_ID],ALL_KPS=[G5B_U02_P04F31_KP_ID,...NEW_KPS],ALL_SPECS=[G5B_U02_P04F31_SPEC_ID,...NEW_SPECS];
const singleOptions=kpId=>({sourceId:SOURCE,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[kpId],questionMode:"numeric",questionCount:24,generationSeed:`p04f32-test-${kpId}`,includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showQuestionNumbers:true,showAnswerKeyPage:true}});
function assertApprovedQuestionIdentity(q){assert.equal(q.sourceId,SOURCE);assert.ok(ALL_KPS.includes(q.knowledgePointId),`unexpected KP ${q.knowledgePointId}`);assert.ok(ALL_SPECS.includes(q.patternSpecId),`unexpected PatternSpec ${q.patternSpecId}`);assert.equal(String(q.knowledgePointId).startsWith("kp_g6a_u02_"),false,"q033 KP leak");assert.equal(String(q.patternSpecId).startsWith("ps_g6a_u02_"),false,"q033 PatternSpec leak");if(q.knowledgePointId===G5B_U02_P04F31_KP_ID){assert.equal(q.patternSpecId,G5B_U02_P04F31_SPEC_ID);assert.equal(q.metadata.q032Touched,false);}else{assert.ok(NEW_KPS.includes(q.knowledgePointId));assert.ok(NEW_SPECS.includes(q.patternSpecId));assert.equal(q.metadata.q033Touched,false);}}
function assertQuestionSet(result,count,kpId){assert.equal(result.ok,true,JSON.stringify(result.errors));assert.equal(result.questions.length,count);assert.equal(new Set(result.questions.map(q=>q.blankedDisplayText)).size,count);for(const q of result.questions){assert.equal(q.knowledgePointId,kpId);const validation=validateG5BU02P04F32Question(q);assert.equal(validation.ok,true,JSON.stringify(validation.errors));assertApprovedQuestionIdentity(q);assert.equal(q.metadata.roundingUsed,false);}}
test("q032 exact four-row FormalMapping is materialized into four numeric PatternSpecs",()=>{const audit=auditG5BU02P04F32SelectorProjection();assert.equal(audit.ok,true,JSON.stringify(audit.errors));assert.deepEqual(audit.counts,{knowledgePoints:4,patternGroups:4,patternSpecs:4,numeric:4,application:0});assert.deepEqual(authority.queue.knowledgePointIds,NEW_KPS);const mappings=authority.formalMappings;assert.equal(mappings.length,4);assert.equal(mappings.find(m=>m.knowledgePointId===G5B_U02_P04F32_QUANTITY_KP_ID).relationFamilyId,"FRACTION_OF_QUANTITY");assert.equal(mappings.find(m=>m.knowledgePointId===G5B_U02_P04F32_INTEGER_TIMES_KP_ID).relationFamilyId,"FRACTION_TIMES_INTEGER_PRODUCT");assert.equal(mappings.find(m=>m.knowledgePointId===G5B_U02_P04F32_SIMPLIFY_KP_ID).relationFamilyId,"FRACTION_PRODUCT_SIMPLIFICATION");assert.equal(mappings.find(m=>m.knowledgePointId===G5B_U02_P04F32_MULTI_KP_ID).relationFamilyId,"FRACTION_MULTI_STEP_CALCULATION");});
test("q032 selector promotes four KPs on existing G5B-U02 source",()=>{const audit=auditP04F32PublicSelectorComposition();assert.equal(audit.ok,true,JSON.stringify(audit.errors));assert.equal(BATCH_A_SELECTOR_AVAILABILITY.sourceCount,43);assert.equal(BATCH_A_SELECTOR_AVAILABILITY.visibleCount,305);const source=listBatchAKnowledgePointAvailabilityBySource(SOURCE);assert.equal(source.visibleCount,5);assert.equal(source.hiddenPendingCount,0);assert.equal(source.notSelectableCount,0);assert.deepEqual(new Set(source.visibleKnowledgePointIds),new Set(ALL_KPS));const rows=listVisibleBatchAKnowledgePoints().filter(row=>row.sourceId===SOURCE);assert.equal(rows.length,5);});
test("each new q032 KP proves 240 distinct exact questions",()=>{const cases=[
  [G5B_U02_P04F32_MULTI_KP_ID,G5B_U02_P04F32_MULTI_SPEC_ID,generateG5BU02P04F32MultiStepQuestions],
  [G5B_U02_P04F32_SIMPLIFY_KP_ID,G5B_U02_P04F32_SIMPLIFY_SPEC_ID,generateG5BU02P04F32SimplificationQuestions],
  [G5B_U02_P04F32_QUANTITY_KP_ID,G5B_U02_P04F32_QUANTITY_SPEC_ID,generateG5BU02P04F32FractionOfQuantityQuestions],
  [G5B_U02_P04F32_INTEGER_TIMES_KP_ID,G5B_U02_P04F32_INTEGER_TIMES_SPEC_ID,generateG5BU02P04F32IntegerTimesFractionQuestions]
];for(const [kpId,specId,generator] of cases){assert.ok(P04F32_DISTINCT_CAPACITY_BY_SPEC[specId]>=240,`${specId} capacity`);const result=generator({questionCount:240,generationSeed:`capacity-${kpId}`});assertQuestionSet(result,240,kpId);}});
test("q032 public binding supports all five singles, same-unit mixed, and sourceUnit at max 240",()=>{const audit=auditPublicUiCapabilityBinding();assert.equal(audit.ok,true,JSON.stringify(audit.errors));for(const kpId of ALL_KPS){const binding=resolvePublicUiCapabilityBinding({sourceId:SOURCE,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[kpId]});assert.equal(binding.blocked,false);assert.equal(binding.questionType,"numeric");assert.equal(binding.questionCount.max,240);assert.equal(binding.selectedKnowledgePointIds.length,1);assert.equal(binding.compatiblePatternGroupIds.length,1);}const mixed=resolvePublicUiCapabilityBinding({sourceId:SOURCE,selectionMode:"mixedKnowledgePointsSameUnit",selectedKnowledgePointIds:ALL_KPS});assert.equal(mixed.blocked,false);assert.equal(mixed.selectedKnowledgePointIds.length,5);assert.equal(mixed.compatiblePatternGroupIds.length,5);assert.equal(mixed.questionCount.max,240);const source=resolvePublicUiCapabilityBinding({sourceId:SOURCE,selectionMode:"sourceUnit"});assert.equal(source.blocked,false);assert.equal(source.selectedKnowledgePointIds.length,5);assert.equal(source.compatiblePatternGroupIds.length,5);assert.equal(source.questionCount.max,240);});
test("q032 sourceUnit produces 240 distinct questions across all five KPs",()=>{const options={sourceId:SOURCE,selectionMode:"sourceUnit",questionMode:"numeric",questionCount:240,generationSeed:"p04f32-source-capacity"},plan=buildBatchABrowserPlan(options);assert.deepEqual(new Set(plan.patternSpecIds),new Set(G5B_U02_P04F32_ALL_PUBLIC_IDS.patternSpecIds));const result=buildBatchABrowserWorksheetDocument({...options,includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showQuestionNumbers:true,showAnswerKeyPage:true}});assert.equal(result.ok,true,JSON.stringify(result.errors));const doc=result.worksheetDocument;assert.equal(doc.generatedQuestions.length,240);assert.equal(doc.answerKeyItems.length,240);assert.equal(new Set(doc.generatedQuestions.map(q=>q.blankedDisplayText)).size,240);assert.deepEqual(new Set(doc.generatedQuestions.map(q=>q.knowledgePointId)),new Set(ALL_KPS));assert.deepEqual(new Set(doc.generatedQuestions.map(q=>q.patternSpecId)),new Set(ALL_SPECS));assert.equal(result.generation.allocation.length,5);for(const q of doc.generatedQuestions){assert.equal(validateG5BU02P04F32Question(q).ok,true);assertApprovedQuestionIdentity(q);}});
test("q031 single-KP behavior remains valid through q032 successor worksheet",()=>{const result=buildBatchABrowserWorksheetDocument(singleOptions(G5B_U02_P04F31_KP_ID));assert.equal(result.ok,true,JSON.stringify(result.errors));assert.equal(result.worksheetDocument.generatedQuestions.length,24);assert.equal(new Set(result.worksheetDocument.generatedQuestions.map(q=>q.knowledgePointId)).size,1);assert.equal(result.worksheetDocument.generatedQuestions[0].knowledgePointId,G5B_U02_P04F31_KP_ID);assert.equal(result.worksheetDocument.generatedQuestions[0].patternSpecId,G5B_U02_P04F31_SPEC_ID);for(const q of result.worksheetDocument.generatedQuestions){assert.equal(validateG5BU02P04F32Question(q).ok,true);assertApprovedQuestionIdentity(q);}});
test("q032 four single-KP worksheet paths are answer-key aligned and q033 untouched",()=>{for(const kpId of NEW_KPS){const result=buildBatchABrowserWorksheetDocument(singleOptions(kpId));assert.equal(result.ok,true,JSON.stringify(result.errors));const doc=result.worksheetDocument;assert.equal(doc.generatedQuestions.length,24);assert.equal(doc.answerKeyItems.length,24);assert.equal(doc.questionPages.length,3);assert.equal(doc.answerKeyPages.length,3);for(let i=0;i<24;i+=1){assert.equal(doc.answerKeyItems[i].questionId,doc.generatedQuestions[i].id);assert.equal(doc.answerKeyItems[i].answerText,doc.generatedQuestions[i].answerText);assertApprovedQuestionIdentity(doc.generatedQuestions[i]);}}});
