import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";

import {materializeP04EW4DirectProductVerticalSliceQueue} from "../../src/curriculum/full-product/p04e-w4-direct-product-vertical-slice-queue.mjs";
import {auditP04F4PublicSelectorComposition} from "../../site/modules/curriculum/registry/batch-a-selector-p04f4-extension.js";
import {G3B_U06_P04F4_SOURCE_ID,G3B_U06_P04F4_INDIRECT_KP_ID,G3B_U06_P04F4_INDIRECT_SPEC_ID,G3B_U06_P04F4_SCALE_KP_ID,G3B_U06_P04F4_SCALE_SPEC_ID,P04F4_REQUIRED_W4_CAPABILITY_IDS,P04F4_INDIRECT_REQUIRED_CAPABILITY_IDS,P04F4_SCALE_REQUIRED_CAPABILITY_IDS} from "../../site/modules/curriculum/registry/g3b-u06-mass-selector-projection-p04f4.js";
import {buildBatchABrowserPlan} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p04f4.js";
import {generateBatchABrowserQuestions} from "../../site/modules/curriculum/batch-a/batch-a-browser-question-router-p04f4.js";
import {buildP04F4QuestionIdentity,validateBatchABrowserPlan,validateBatchABrowserQuestion,validateBatchABrowserQuestions} from "../../site/modules/curriculum/batch-a/batch-a-browser-validator-p04f4.js";
import {buildBatchABrowserWorksheetDocument,P04F4_WORKSHEET_ADAPTER} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p04f4-extension.js";
import {listBatchASourcePatternDefinitions} from "../../site/modules/curriculum/batch-a/source-pattern-full-product-p04f4-extension.js";
import {listCurrentFullProductPublicSourceUnits} from "../../site/modules/curriculum/batch-a/source-units-p04f4-extension.js";
import {PUBLIC_UI_SURFACES,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p04f4.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";
import {parseQueryState} from "../../site/assets/browser/state/query-state.js";

const options={sourceId:G3B_U06_P04F4_SOURCE_ID,selectionMode:"sourceUnit",questionMode:"numeric",questionCount:8,generationSeed:"p04f4-focused",includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showAnswerKeyPage:true}};
const forbidden=/換算|加法|減法|乘法|進位|退位|公斤換公克|公克換公斤/;
const singleOptions=(kpId,count=8,seed="p04f4-single")=>({...options,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[kpId],questionCount:count,generationSeed:seed});

test("P04F4 frozen queue and authority lock q004 to both mass KPs",()=>{const queue=materializeP04EW4DirectProductVerticalSliceQueue();const q004=queue.queueEntries.find(row=>row.queuePosition===4);assert.ok(q004);assert.equal(q004.sliceId,"p04e_q004_r0_g3b_u06_3b06_profile_quantity_measurement_c1");assert.equal(q004.primarySourceNodeId,G3B_U06_P04F4_SOURCE_ID);assert.equal(q004.primaryRuntimeProfileId,"profile_quantity_measurement");assert.deepEqual(q004.knowledgePointIds,[G3B_U06_P04F4_INDIRECT_KP_ID,G3B_U06_P04F4_SCALE_KP_ID]);assert.deepEqual(q004.requiredW4CapabilityIds,[...P04F4_REQUIRED_W4_CAPABILITY_IDS]);const authority=JSON.parse(fs.readFileSync("data/curriculum/full-product/p04f/slice004-g3b-u06-mass-indirect-scale-reading-authority.json","utf8"));assert.equal(authority.queue.sliceId,q004.sliceId);assert.equal(authority.source.sourcePdfTitle,"meow911_3b06_kg_g.pdf");assert.deepEqual(authority.source.primaryWitnessPages,[1]);assert.deepEqual(authority.knowledgePoints.map(row=>row.knowledgePointId),q004.knowledgePointIds);assert.deepEqual(authority.formalMapping.requiredW4CapabilityIds,q004.requiredW4CapabilityIds);assert.deepEqual(authority.formalMapping.knowledgePointCapabilityRequirements[G3B_U06_P04F4_INDIRECT_KP_ID],[...P04F4_INDIRECT_REQUIRED_CAPABILITY_IDS]);assert.deepEqual(authority.formalMapping.knowledgePointCapabilityRequirements[G3B_U06_P04F4_SCALE_KP_ID],[...P04F4_SCALE_REQUIRED_CAPABILITY_IDS]);assert.ok(authority.knowledgePoints.every(row=>row.implementationBoundary.kgGConversionAllowed===false&&row.implementationBoundary.massArithmeticAllowed===false));assert.equal(authority.acceptance.duplicateQuestionIdentityRejected,true);assert.equal(authority.acceptance.representationBoundPromptIdentity,true);});

test("P04F4 selector and source inventory add exactly one source and two KPs",()=>{const audit=auditP04F4PublicSelectorComposition();assert.equal(audit.ok,true,JSON.stringify(audit.errors));assert.deepEqual(audit.counts,{sources:38,knowledgePoints:265,g3bU06Visible:2,g3bU06Hidden:0,g3bU06NotSelectable:0});const sources=listCurrentFullProductPublicSourceUnits();assert.equal(sources.length,38);assert.ok(sources.some(row=>row.sourceId===G3B_U06_P04F4_SOURCE_ID&&row.unitCode==="3B-U06"&&row.title==="公斤與公克"));});

test("P04F4 pattern materialization binds one source-backed spec per frozen KP",()=>{const rows=listBatchASourcePatternDefinitions().filter(row=>row.sourceId===G3B_U06_P04F4_SOURCE_ID);assert.equal(rows.length,2);assert.deepEqual(rows.map(row=>row.knowledgePointId),[G3B_U06_P04F4_INDIRECT_KP_ID,G3B_U06_P04F4_SCALE_KP_ID]);assert.deepEqual(rows.map(row=>row.patternSpecId),[G3B_U06_P04F4_INDIRECT_SPEC_ID,G3B_U06_P04F4_SCALE_SPEC_ID]);assert.equal(rows[0].applicationClassification,"DIRECT_SOURCE_MASS_INDIRECT_COMPARISON");assert.equal(rows[1].applicationClassification,"DIRECT_SOURCE_MASS_SCALE_READING");assert.deepEqual(rows[0].requiredCapabilityIds,[...P04F4_INDIRECT_REQUIRED_CAPABILITY_IDS]);assert.deepEqual(rows[1].requiredCapabilityIds,[...P04F4_SCALE_REQUIRED_CAPABILITY_IDS]);assert.ok(rows.every(row=>row.operatorApprovedExtension===false&&row.kgGConversion===false&&row.massArithmetic===false));});

test("P04F4 source-unit plan generator and validator cover both frozen KPs without later-scope leak",()=>{const plan=buildBatchABrowserPlan(options);assert.equal(plan.sourceId,G3B_U06_P04F4_SOURCE_ID);assert.deepEqual(plan.patternSpecIds,[G3B_U06_P04F4_INDIRECT_SPEC_ID,G3B_U06_P04F4_SCALE_SPEC_ID]);assert.deepEqual(plan.requestedKnowledgePointIds,[G3B_U06_P04F4_INDIRECT_KP_ID,G3B_U06_P04F4_SCALE_KP_ID]);assert.equal(plan.genericFallbackAllowed,false);assert.equal(validateBatchABrowserPlan(plan).ok,true);const generation=generateBatchABrowserQuestions({...options,plan});assert.equal(generation.ok,true,JSON.stringify(generation.errors));assert.equal(generation.questions.length,8);assert.deepEqual(generation.allocation.map(row=>row.questionCount),[4,4]);assert.equal(new Set(generation.questions.map(buildP04F4QuestionIdentity)).size,8);assert.deepEqual(new Set(generation.questions.map(q=>q.knowledgePointId)),new Set([G3B_U06_P04F4_INDIRECT_KP_ID,G3B_U06_P04F4_SCALE_KP_ID]));for(const q of generation.questions){assert.equal(q.metadata.kgGConversion,false);assert.equal(q.metadata.mixedUnitComparison,false);assert.equal(q.metadata.massArithmetic,false);assert.equal(q.metadata.massTimesInteger,false);assert.doesNotMatch(q.blankedDisplayText,forbidden);assert.equal(validateBatchABrowserQuestion(q).ok,true);}assert.equal(validateBatchABrowserQuestions(generation.questions).ok,true);});

test("P04F4 indirect comparison has 24 distinct cases and all three relations",()=>{const opts=singleOptions(G3B_U06_P04F4_INDIRECT_KP_ID,24,"p04f4-indirect-capacity"),plan=buildBatchABrowserPlan(opts),generation=generateBatchABrowserQuestions({...opts,plan});assert.equal(generation.ok,true,JSON.stringify(generation.errors));assert.equal(generation.questions.length,24);assert.equal(new Set(generation.questions.map(buildP04F4QuestionIdentity)).size,24);assert.deepEqual(new Set(generation.questions.map(q=>q.answer)),new Set(["<",">","="]));assert.ok(generation.questions.every(q=>q.numberLine===undefined));assert.equal(validateBatchABrowserQuestions(generation.questions).ok,true);});

test("P04F4 scale reading has 24 distinct representation-bound cases with gram and kilogram instrument models",()=>{const opts=singleOptions(G3B_U06_P04F4_SCALE_KP_ID,24,"p04f4-scale-capacity"),plan=buildBatchABrowserPlan(opts),generation=generateBatchABrowserQuestions({...opts,plan});assert.equal(generation.ok,true,JSON.stringify(generation.errors));assert.equal(generation.questions.length,24);assert.equal(new Set(generation.questions.map(buildP04F4QuestionIdentity)).size,24);assert.deepEqual(new Set(generation.questions.map(q=>q.metadata.unitId)),new Set(["gram","kilogram"]));assert.ok(generation.questions.every(q=>q.numberLine?.kind==="measurement_scale"&&q.metadata.scaleInstrument===true));assert.equal(validateBatchABrowserQuestions(generation.questions).ok,true);});

test("P04F4 generation is deterministic by seed and changes order with another seed",()=>{const planA=buildBatchABrowserPlan({...options,generationSeed:"seed-A"}),a1=generateBatchABrowserQuestions({...options,generationSeed:"seed-A",plan:planA}),a2=generateBatchABrowserQuestions({...options,generationSeed:"seed-A",plan:planA}),planB=buildBatchABrowserPlan({...options,generationSeed:"seed-B"}),b=generateBatchABrowserQuestions({...options,generationSeed:"seed-B",plan:planB});assert.deepEqual(a1.questions.map(buildP04F4QuestionIdentity),a2.questions.map(buildP04F4QuestionIdentity));assert.notDeepEqual(a1.questions.map(buildP04F4QuestionIdentity),b.questions.map(buildP04F4QuestionIdentity));});

test("P04F4 fail-closes tampered answers, scope metadata and over-capacity",()=>{const indirectOpts=singleOptions(G3B_U06_P04F4_INDIRECT_KP_ID),indirect=generateBatchABrowserQuestions({...indirectOpts,plan:buildBatchABrowserPlan(indirectOpts)}).questions[0],badAnswer={...indirect,answer:"=",answerText:"=",finalAnswer:"="};if(indirect.answer!=="=")assert.ok(validateBatchABrowserQuestion(badAnswer).errors.some(e=>e.code==="p04f4_indirect_answer_mismatch"));const scaleOpts=singleOptions(G3B_U06_P04F4_SCALE_KP_ID),scale=generateBatchABrowserQuestions({...scaleOpts,plan:buildBatchABrowserPlan(scaleOpts)}).questions[0],badScale={...scale,answer:999,answerText:"999 公克",finalAnswer:"999 公克"};assert.ok(validateBatchABrowserQuestion(badScale).errors.some(e=>e.code==="p04f4_scale_answer_mismatch"));const badScope={...scale,metadata:{...scale.metadata,kgGConversion:true}};assert.ok(validateBatchABrowserQuestion(badScope).errors.some(e=>e.code==="p04f4_scope_leak"));const duplicateVisualIdentity={...scale,id:`${scale.id}-duplicate`};assert.ok(validateBatchABrowserQuestions([scale,duplicateVisualIdentity]).errors.some(e=>e.code==="p04f4_duplicate_prompt_detected"));const over=generateBatchABrowserQuestions({...options,questionCount:25,plan:{...buildBatchABrowserPlan(options),questionCount:25}});assert.equal(over.ok,false);});

test("P04F4 worksheet answer key and shared HTML renderer preserve scale representation",()=>{const result=buildBatchABrowserWorksheetDocument(options);assert.equal(result.ok,true,JSON.stringify(result.errors));const doc=result.worksheetDocument;assert.equal(doc.questionCount,8);assert.equal(doc.answerKeyItems.length,8);assert.equal(doc.questionPages.length,1);assert.equal(doc.answerKeyPages.length,1);assert.deepEqual(doc.metadata.knowledgePointIds,[G3B_U06_P04F4_INDIRECT_KP_ID,G3B_U06_P04F4_SCALE_KP_ID]);assert.deepEqual(doc.metadata.patternSpecIds,[G3B_U06_P04F4_INDIRECT_SPEC_ID,G3B_U06_P04F4_SCALE_SPEC_ID]);assert.equal(P04F4_WORKSHEET_ADAPTER.sharedPagination,true);assert.equal(P04F4_WORKSHEET_ADAPTER.sharedRenderer,true);assert.equal(P04F4_WORKSHEET_ADAPTER.parallelPipeline,false);assert.equal(doc.summary.massIndirectComparisonQuestionCount,4);assert.equal(doc.summary.massScaleReadingQuestionCount,4);for(let i=0;i<doc.generatedQuestions.length;i++)assert.equal(doc.answerKeyItems[i].answerText,doc.generatedQuestions[i].answerText);const html=renderWorksheetDocumentToHtml(doc,{stylesheetHref:""});assert.match(html,/重量|磅秤/);assert.match(html,/data-representation="measurement-scale"/);assert.doesNotMatch(html,forbidden);});

test("P04F4 Classic Pixel binding and query-state expose q004 sourceUnit and single-KP routes",()=>{for(const surfaceId of[PUBLIC_UI_SURFACES.CLASSIC,PUBLIC_UI_SURFACES.PIXEL]){const sourceBinding=resolvePublicUiCapabilityBinding({sourceId:G3B_U06_P04F4_SOURCE_ID,surfaceId,selectionMode:"sourceUnit"});assert.equal(sourceBinding.blocked,false);assert.equal(sourceBinding.questionCount.max,24);assert.deepEqual(sourceBinding.selectedKnowledgePointIds,[G3B_U06_P04F4_INDIRECT_KP_ID,G3B_U06_P04F4_SCALE_KP_ID]);for(const kpId of[G3B_U06_P04F4_INDIRECT_KP_ID,G3B_U06_P04F4_SCALE_KP_ID]){const single=resolvePublicUiCapabilityBinding({sourceId:G3B_U06_P04F4_SOURCE_ID,surfaceId,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[kpId]});assert.equal(single.blocked,false);assert.deepEqual(single.selectedKnowledgePointIds,[kpId]);assert.equal(single.compatiblePatternGroupIds.length,1);}}const parsed=parseQueryState(`?sourceId=${G3B_U06_P04F4_SOURCE_ID}&selectionMode=singleKnowledgePoint&kp=${G3B_U06_P04F4_SCALE_KP_ID}`);assert.equal(parsed.sourceId,G3B_U06_P04F4_SOURCE_ID);assert.equal(parsed.selectionMode,"singleKnowledgePoint");assert.deepEqual(parsed.selectedKnowledgePointIds,[G3B_U06_P04F4_SCALE_KP_ID]);});
