import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import {auditP04F28PublicSelectorComposition,listBatchAKnowledgePointAvailabilityBySource} from "../../site/modules/curriculum/registry/batch-a-selector-p04f28-extension.js";
import {G5A_U04_P04F28_KP_ID,G5A_U04_P04F28_GROUP_ID,G5A_U04_P04F28_PER_GROUP_SPEC_ID,G5A_U04_P04F28_GROUP_COUNT_SPEC_ID,G5A_U04_P04F28_SPEC_IDS} from "../../site/modules/curriculum/registry/g5a-u04-fraction-measurement-segments-selector-projection-p04f28.js";
import {buildBatchABrowserPlan} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p04f28.js";
import {generateG5AU04P04F28FractionMeasurementSegmentQuestions,validateG5AU04P04F28Question} from "../../site/modules/curriculum/batch-a/fraction-measurement-segments-runtime-p04f28.js";
import {buildBatchABrowserWorksheetDocument} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-r2e-entry.js";
import {resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p04f28.js";
import {getCurrentPixelRegistrySnapshot} from "../../site/pixel/pixel-registry-bridge.js";
const authority=JSON.parse(fs.readFileSync(new URL("../../data/curriculum/full-product/p04f/slice028-g5a-u04-fraction-measurement-segments-formal-mapping-authority.json",import.meta.url),"utf8"));
const overrides=JSON.parse(fs.readFileSync(new URL("../../data/curriculum/full-product/p02e/quantity-semantic-role-overrides.json",import.meta.url),"utf8"));
const q028=(count=24)=>({sourceId:"g5a_u04_5a04",selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G5A_U04_P04F28_KP_ID],selectedPatternGroupIds:[G5A_U04_P04F28_GROUP_ID],patternSpecIds:G5A_U04_P04F28_SPEC_IDS,questionMode:"application",questionCount:count,generationSeed:"p04f28-focused",includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showQuestionNumbers:true,showAnswerKeyPage:true}});

test("P04F28 authority preserves slice-local FormalMapping while materializing exactly two source-declared PatternSpecs",()=>{assert.equal(authority.formalMapping.authorityMode,"P04F_SLICE_LOCAL_EXACT");assert.equal(authority.formalMapping.relationFamilyId,"SOURCE_DECLARED_QUANTITY_RELATION");assert.deepEqual(authority.formalMapping.allowedTargetRoleIds,["PER_GROUP_QUANTITY","GROUP_COUNT"]);assert.deepEqual(authority.patternSpecs.map((row)=>row.patternSpecId),G5A_U04_P04F28_SPEC_IDS);assert.deepEqual(authority.patternSpecs.map((row)=>row.targetRoleId),["PER_GROUP_QUANTITY","GROUP_COUNT"]);assert.equal(authority.authorityBoundary.patternSpecMaterialized,true);assert.equal(authority.authorityBoundary.generatorMaterialized,true);assert.equal(authority.authorityBoundary.selectorPromoted,true);assert.equal(authority.authorityBoundary.worksheetEnabled,true);assert.equal(authority.authorityBoundary.p02eExactOverrideRequired,false);assert.equal(authority.authorityBoundary.p02eConsumerResolutionRequired,false);assert.equal(authority.authorityBoundary.q029Touched,false);assert.equal(overrides.bindings.some((row)=>row.knowledgePointId===G5A_U04_P04F28_KP_ID),false);});

test("P04F28 selector promotes G5A-U04 from 6/1/1 to 7/0/0 and current inventory to 42/298",()=>{const audit=auditP04F28PublicSelectorComposition(),availability=listBatchAKnowledgePointAvailabilityBySource("g5a_u04_5a04");assert.equal(audit.ok,true,JSON.stringify(audit.errors));assert.deepEqual(audit.counts,{sources:42,knowledgePoints:298,g5aU04Visible:7,g5aU04Hidden:0,g5aU04NotSelectable:0});assert.equal(availability.visibleKnowledgePointIds.includes(G5A_U04_P04F28_KP_ID),true);assert.equal(availability.hiddenPendingKnowledgePointIds.includes(G5A_U04_P04F28_KP_ID),false);assert.equal(availability.notSelectableKnowledgePointIds.includes(G5A_U04_P04F28_KP_ID),false);});

test("P04F28 generates 24 unique exact quotient applications balanced 12/12 across both source-declared targets",()=>{const plan=buildBatchABrowserPlan(q028()),result=generateG5AU04P04F28FractionMeasurementSegmentQuestions({...q028(),plan});assert.equal(result.ok,true,JSON.stringify(result.errors));assert.equal(result.questions.length,24);assert.equal(new Set(result.questions.map((question)=>question.blankedDisplayText)).size,24);assert.equal(result.questions.filter((q)=>q.patternSpecId===G5A_U04_P04F28_PER_GROUP_SPEC_ID).length,12);assert.equal(result.questions.filter((q)=>q.patternSpecId===G5A_U04_P04F28_GROUP_COUNT_SPEC_ID).length,12);for(const question of result.questions){assert.equal(validateG5AU04P04F28Question(question).ok,true);assert.equal(question.metadata.exactRationalArithmetic,true);assert.equal(question.metadata.roundingUsed,false);assert.equal(question.metadata.wholeContainerRounding,false);assert.equal(question.metadata.p02eConsumerResolutionRequired,false);assert.equal(question.metadata.q029Touched,false);assert.deepEqual(question.metadata.sourceEvidencePages,[2]);}});

test("P04F28 fail-closed validator rejects GROUP_COUNT rounding/coercion and target-role drift",()=>{const plan=buildBatchABrowserPlan(q028(24)),result=generateG5AU04P04F28FractionMeasurementSegmentQuestions({...q028(24),plan});const source=result.questions.find((q)=>q.patternSpecId===G5A_U04_P04F28_GROUP_COUNT_SPEC_ID&&q.finalAnswer.denominator!==1);assert.ok(source);const rounded=structuredClone(source);rounded.answerText=`${Math.floor(rounded.metadata.totalQuantity/rounded.metadata.divisionDenominator)} 桶`;rounded.finalAnswer.canonicalText=String(Math.floor(rounded.metadata.totalQuantity/rounded.metadata.divisionDenominator));rounded.metadata.wholeContainerRounding=true;assert.equal(validateG5AU04P04F28Question(rounded).ok,false);const drift=structuredClone(source);drift.metadata.targetRoleId="PER_GROUP_QUANTITY";assert.equal(validateG5AU04P04F28Question(drift).ok,false);});

test("P04F28 shared worksheet renders 24Q/24A on 3+3 pages with shared exact fraction renderer",()=>{const result=buildBatchABrowserWorksheetDocument(q028());assert.equal(result.ok,true,JSON.stringify(result.errors));const document=result.worksheetDocument;assert.equal(document.generatedQuestions.length,24);assert.equal(document.answerKeyItems.length,24);assert.equal(document.questionPages.length,3);assert.equal(document.answerKeyPages.length,3);assert.equal(document.metadata.worksheetAdapter.sharedFractionArithmetic,true);assert.equal(document.metadata.worksheetAdapter.sharedQuantitySemantics,true);assert.equal(document.metadata.worksheetAdapter.sharedRenderer,true);assert.equal(document.metadata.worksheetAdapter.parallelPipeline,false);assert.equal(document.metadata.worksheetAdapter.parallelFractionEngine,false);assert.equal(document.metadata.worksheetAdapter.parallelQuantityEngine,false);assert.equal(document.answerKeyItems.some((row)=>row.answerInlineMath!=null),true);});

test("P04F28 preserves existing G5A-U04 sourceUnit route instead of silently injecting q028",()=>{const sourceUnit=buildBatchABrowserPlan({sourceId:"g5a_u04_5a04",selectionMode:"sourceUnit",questionCount:20,generationSeed:"p04f28-sourceunit"});assert.equal(sourceUnit.patternSpecIds.includes(G5A_U04_P04F28_PER_GROUP_SPEC_ID),false);assert.equal(sourceUnit.patternSpecIds.includes(G5A_U04_P04F28_GROUP_COUNT_SPEC_ID),false);assert.equal((sourceUnit.selectedKnowledgePointIds??[]).includes(G5A_U04_P04F28_KP_ID),false);});

test("P04F28 public UI exposes the promoted q028 KP as one application group with max 24",()=>{const binding=resolvePublicUiCapabilityBinding({sourceId:"g5a_u04_5a04",surfaceId:"classic",selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G5A_U04_P04F28_KP_ID]});assert.equal(binding.blocked,false);assert.equal(binding.questionType,"application");assert.deepEqual(binding.selectedKnowledgePointIds,[G5A_U04_P04F28_KP_ID]);assert.deepEqual(binding.compatiblePatternGroupIds,[G5A_U04_P04F28_GROUP_ID]);assert.equal(binding.questionCount.max,24);});

test("P04F28 Pixel current projection is 42/298 and G5A-U04 contains seven visible KPs including q028",()=>{const registry=getCurrentPixelRegistrySnapshot(),source=registry.bySourceId["g5a_u04_5a04"];assert.equal(registry.sourceCount,42);assert.equal(registry.visibleKnowledgePointCount,298);assert.equal(source.visibleKnowledgePoints.length,7);assert.equal(source.visibleKnowledgePoints.some((row)=>row.knowledgePointId===G5A_U04_P04F28_KP_ID),true);});
