import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import {renderInlineMathModel,serializeInlineMathModel} from "../../site/modules/renderer/inline-math.js";
import {buildBatchABrowserPlan,requestsP04F37} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p04f37.js";
import {buildBatchABrowserWorksheetDocument} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-r2e-entry.js";
import {P04F37_DISTINCT_CASE_CAPACITY_PER_SPEC,P04F37_SHARED_RUNTIME_DECISION,generateG6AU02P04F37Questions,validateG6AU02P04F37Question} from "../../site/modules/curriculum/batch-a/g6a-u02-fraction-division-application-runtime-p04f37.js";
import {auditP04F37PublicSelectorComposition,listBatchAKnowledgePointAvailabilityBySource,listVisibleBatchAKnowledgePoints,resolveVisiblePatternSpecIdsForKnowledgePoint} from "../../site/modules/curriculum/registry/batch-a-selector-p04f37-extension.js";
import {G6A_U02_P04F37_SOURCE_ID,G6A_U02_P04F37_KP_ID,G6A_U02_P04F37_GROUP_ID,G6A_U02_P04F37_SPEC_IDS,auditG6AU02P04F37SelectorProjection} from "../../site/modules/curriculum/registry/g6a-u02-fraction-division-application-selector-projection-p04f37.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding,PUBLIC_UI_SURFACES} from "../../site/modules/curriculum/public/public-ui-capability-binding-p04f37.js";

const read=path=>JSON.parse(fs.readFileSync(new URL(`../../${path}`,import.meta.url),"utf8"));
const authority=read("data/curriculum/full-product/p04f/slice037-g6a-u02-fraction-division-application-authority.json"),preflight=read("data/curriculum/full-product/p04f/slice037-g6a-u02-fraction-division-application-preflight-authority.json");
const options={sourceId:G6A_U02_P04F37_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G6A_U02_P04F37_KP_ID],selectedPatternGroupIds:[G6A_U02_P04F37_GROUP_ID],questionMode:"application",requestedQuestionType:"application",questionCount:24,generationSeed:"p04f37-focused",includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showQuestionNumbers:true,showAnswerKeyPage:true}};

test("q037 authority materializes the two locked source-backed application relations",()=>{assert.deepEqual(authority.source.reviewedPages,preflight.sourceAuthority.reviewedPages);assert.equal(authority.knowledgePoint.knowledgePointId,G6A_U02_P04F37_KP_ID);assert.equal(authority.formalMapping.relationFamilyId,"FRACTION_DIVISION_APPLICATION_RELATION");assert.deepEqual(authority.formalMapping.relationVariants.map(row=>row.variantId),["QUOTATIVE_DIVISION_GROUP_COUNT","PARTITIVE_DIVISION_PER_GROUP"]);assert.deepEqual(authority.publicApplicationPatternSpecIds,G6A_U02_P04F37_SPEC_IDS);assert.equal(authority.implementationBoundary.singleKnowledgePointApplicationOnly,true);assert.equal(authority.implementationBoundary.unitNumericAndApplicationSurfacesCoexist,true);assert.equal(authority.implementationBoundary.mixedQuestionModeAdmission,false);assert.equal(authority.implementationBoundary.sharedRuntimeScope,"SHARED_RUNTIME_BOUNDED");assert.equal(authority.implementationBoundary.structuredFractionDisplay,true);assert.equal(authority.implementationBoundary.q036RuntimeTouched,false);assert.equal(authority.implementationBoundary.q038Touched,false);});

test("q037 selector promotes the final G6A-U02 KP and keeps numeric plus application surfaces",()=>{assert.deepEqual(auditG6AU02P04F37SelectorProjection().errors,[]);const audit=auditP04F37PublicSelectorComposition();assert.equal(audit.ok,true,JSON.stringify(audit.errors));assert.deepEqual(audit.counts,{sources:43,knowledgePoints:310,g6aU02Visible:5,g6aU02Hidden:0,g6aU02NotSelectable:0,g6aU02NumericKnowledgePoints:4,g6aU02ApplicationKnowledgePoints:1});assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(G6A_U02_P04F37_KP_ID,"application"),G6A_U02_P04F37_SPEC_IDS);assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(G6A_U02_P04F37_KP_ID,"numeric"),[]);const availability=listBatchAKnowledgePointAvailabilityBySource(G6A_U02_P04F37_SOURCE_ID);assert.ok(availability.visibleKnowledgePointIds.includes(G6A_U02_P04F37_KP_ID));assert.deepEqual(availability.hiddenPendingKnowledgePointIds,[]);assert.deepEqual(availability.notSelectableKnowledgePointIds,[]);const modes=new Set(listVisibleBatchAKnowledgePoints().filter(row=>row.sourceId===G6A_U02_P04F37_SOURCE_ID).map(row=>row.questionMode));assert.deepEqual([...modes].sort(),["application","numeric"]);});

test("q037 public binding is single-KP application-only at max 240",()=>{const audit=auditPublicUiCapabilityBinding();assert.equal(audit.ok,true,JSON.stringify(audit.errors));for(const surfaceId of Object.values(PUBLIC_UI_SURFACES)){const binding=resolvePublicUiCapabilityBinding({...options,surfaceId});assert.equal(binding.blocked,false);assert.equal(binding.selectionMode,"singleKnowledgePoint");assert.equal(binding.questionType,"application");assert.equal(binding.questionCount.max,240);assert.deepEqual(binding.selectedKnowledgePointIds,[G6A_U02_P04F37_KP_ID]);assert.deepEqual(binding.compatiblePatternGroupIds,[G6A_U02_P04F37_GROUP_ID]);assert.deepEqual(binding.patternSpecIds,G6A_U02_P04F37_SPEC_IDS);assert.equal(binding.structuredFractionDisplay,true);assert.equal(binding.unitNumericAndApplicationSurfacesCoexist,true);assert.equal(binding.mixedQuestionModeAdmission,false);assert.equal(binding.sharedRuntimeScope,"SHARED_RUNTIME_BOUNDED");}assert.equal(resolvePublicUiCapabilityBinding({...options,selectionMode:"mixedKnowledgePointsSameUnit"}).selectedKnowledgePointIds.includes(G6A_U02_P04F37_KP_ID),false);});

test("q037 generator and validator implement balanced quotative and partitive semantics",()=>{assert.equal(P04F37_SHARED_RUNTIME_DECISION.scope,"SHARED_RUNTIME_BOUNDED");assert.equal(P04F37_SHARED_RUNTIME_DECISION.q036RuntimeTouched,false);assert.equal(P04F37_SHARED_RUNTIME_DECISION.q038Touched,false);assert.ok(P04F37_DISTINCT_CASE_CAPACITY_PER_SPEC>=240);assert.equal(requestsP04F37(options),true);const plan=buildBatchABrowserPlan(options);assert.equal(plan.selectionMode,"singleKnowledgePoint");assert.equal(plan.questionMode,"application");assert.deepEqual(plan.patternSpecIds,G6A_U02_P04F37_SPEC_IDS);const generated=generateG6AU02P04F37Questions({...options,plan});assert.equal(generated.ok,true,JSON.stringify(generated.errors));assert.equal(generated.questions.length,24);assert.deepEqual(generated.allocation.map(row=>row.questionCount),[12,12]);assert.equal(new Set(generated.questions.map(question=>question.blankedDisplayText)).size,24);for(const question of generated.questions){const result=validateG6AU02P04F37Question(question);assert.equal(result.ok,true,JSON.stringify(result.errors));const metadata=question.metadata;assert.equal(metadata.perGroupNumerator*metadata.groupCount*metadata.totalDenominator,metadata.totalNumerator*metadata.perGroupDenominator);assert.equal(metadata.q036RuntimeTouched,false);assert.equal(metadata.q037Implemented,true);assert.equal(metadata.q038Touched,false);if(question.relationVariantId==="QUOTATIVE_DIVISION_GROUP_COUNT"){assert.deepEqual(question.knownRoleIds,["TOTAL_QUANTITY","PER_GROUP_QUANTITY"]);assert.equal(question.targetRoleId,"GROUP_COUNT");assert.equal(question.finalAnswer.denominator,1);}else{assert.deepEqual(question.knownRoleIds,["TOTAL_QUANTITY","GROUP_COUNT"]);assert.equal(question.targetRoleId,"PER_GROUP_QUANTITY");assert.ok(question.finalAnswer.denominator>1);}}});

test("q037 proves 240 distinct questions per PatternSpec and validator fails closed",()=>{for(const patternSpecId of G6A_U02_P04F37_SPEC_IDS){const generated=generateG6AU02P04F37Questions({sourceId:G6A_U02_P04F37_SOURCE_ID,selectionMode:"singleKnowledgePoint",questionMode:"application",patternSpecIds:[patternSpecId],questionCount:240,generationSeed:`p04f37-capacity-${patternSpecId}`});assert.equal(generated.ok,true,JSON.stringify(generated.errors));assert.equal(generated.questions.length,240);assert.equal(new Set(generated.questions.map(question=>question.blankedDisplayText)).size,240);assert.equal(new Set(generated.questions.map(question=>question.id)).size,240);}const generated=generateG6AU02P04F37Questions({...options,questionCount:2}),question=generated.questions[0];assert.equal(validateG6AU02P04F37Question({...question,answerText:"999 瓶",answer:"999 瓶",finalAnswer:{...question.finalAnswer,canonicalText:"999 瓶",numerator:999}}).ok,false);assert.equal(validateG6AU02P04F37Question({...question,metadata:{...question.metadata,q036RuntimeTouched:true}}).ok,false);const mixedPlan=buildBatchABrowserPlan({...options,selectionMode:"mixedKnowledgePointsSameUnit"}),mixed=generateG6AU02P04F37Questions({plan:mixedPlan});assert.equal(mixed.ok,false);assert.ok(mixed.errors.some(error=>error.code==="p04f37_selection_mode_invalid"));});

test("q037 worksheet produces aligned 24Q/24A with stacked fraction display",()=>{const result=buildBatchABrowserWorksheetDocument(options);assert.equal(result.ok,true,JSON.stringify(result.errors));const document=result.worksheetDocument;assert.equal(document.questionCount,24);assert.equal(document.generatedQuestions.length,24);assert.equal(document.answerKeyItems.length,24);assert.equal(document.questionPages.length,3);assert.equal(document.answerKeyPages.length,3);assert.equal(document.summary.numericQuestionCount,0);assert.equal(document.summary.applicationQuestionCount,24);assert.equal(document.metadata.structuredFractionDisplay,true);assert.equal(document.metadata.unitNumericAndApplicationSurfacesCoexist,true);let questionFractionCount=0,answerPageFractionCount=0;for(let index=0;index<24;index+=1){const question=document.generatedQuestions[index],model=document.questionDisplayModels[index],answer=document.answerKeyItems[index];assert.equal(model.promptText,question.blankedDisplayText);assert.equal(answer.answerText,question.answerText);assert.equal(serializeInlineMathModel(model.promptInlineMath),question.blankedDisplayText);assert.equal(serializeInlineMathModel(answer.promptInlineMath),question.blankedDisplayText);const promptFractions=model.promptInlineMath.runs.filter(run=>run.kind==="fraction").length,answerFractions=answer.answerInlineMath?.runs.filter(run=>run.kind==="fraction").length??0;questionFractionCount+=promptFractions;answerPageFractionCount+=promptFractions+answerFractions;const promptMarkup=renderInlineMathModel(model.promptInlineMath,question.blankedDisplayText);assert.match(promptMarkup,/math-fraction__numerator/);assert.match(promptMarkup,/math-fraction__denominator/);if(answer.answerInlineMath){const answerMarkup=renderInlineMathModel(answer.answerInlineMath,question.answerText);assert.match(answerMarkup,/math-fraction__numerator/);assert.match(answerMarkup,/math-fraction__denominator/);}}assert.equal(questionFractionCount,36);assert.equal(answerPageFractionCount,48);});

test("browser current compatibility pointers expose q037 without changing Node historical snapshots",async()=>{const originalDocument=globalThis.document;globalThis.document={};try{const selector=await import(`../../site/modules/curriculum/registry/batch-a-selector-p04f33-extension.js?browser-q037=${Date.now()}`),binding=await import(`../../site/modules/curriculum/public/public-ui-capability-binding-p04f33.js?browser-q037=${Date.now()}`);assert.equal(selector.getVisibleBatchAKnowledgePoint(G6A_U02_P04F37_KP_ID)?.knowledgePointId,G6A_U02_P04F37_KP_ID);assert.equal(binding.resolvePublicUiCapabilityBinding(options).blocked,false);}finally{if(originalDocument===undefined)delete globalThis.document;else globalThis.document=originalDocument;}});
