import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";

import {auditP04F2PublicSelectorComposition} from "../../site/modules/curriculum/registry/batch-a-selector-p04f2-extension.js";
import {G3B_U02_P04F2_KP_ID,G3B_U02_P04F2_SOURCE_ID,G3B_U02_P04F2_SPEC_ID} from "../../site/modules/curriculum/registry/g3b-u02-capacity-unit-identity-selector-projection-p04f2.js";
import {buildBatchABrowserPlan} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p04f2.js";
import {generateBatchABrowserQuestions} from "../../site/modules/curriculum/batch-a/batch-a-browser-question-router-p04f2.js";
import {validateBatchABrowserPlan,validateBatchABrowserQuestions} from "../../site/modules/curriculum/batch-a/batch-a-browser-validator-p04f2.js";
import {buildBatchABrowserWorksheetDocument} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p04f2-extension.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";

const options={sourceId:G3B_U02_P04F2_SOURCE_ID,selectionMode:"sourceUnit",questionMode:"numeric",questionCount:8,generationSeed:"p04f2-focused",includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showAnswerKeyPage:true}};

test("P04F2 authority is locked to q002 capacity unit identity only",()=>{const authority=JSON.parse(fs.readFileSync("data/curriculum/full-product/p04f/slice002-g3b-u02-capacity-unit-identity-authority.json","utf8"));assert.equal(authority.queue.sliceId,"p04e_q002_r0_g3b_u02_3b02_profile_quantity_measurement_c1");assert.equal(authority.source.sourcePdfTitle,"meow911_3b02_l_ml.pdf");assert.deepEqual(authority.source.primaryWitnessPages,[1]);assert.equal(authority.knowledgePoint.knowledgePointId,G3B_U02_P04F2_KP_ID);assert.equal(authority.patternSpec.patternSpecId,G3B_U02_P04F2_SPEC_ID);assert.deepEqual(authority.formalMapping.canonicalUnitIds,["millilitre","litre"]);assert.equal(authority.knowledgePoint.implementationBoundary.containerScaleReadingAllowed,false);assert.equal(authority.knowledgePoint.implementationBoundary.standaloneConversionQuestionAllowed,false);assert.equal(authority.knowledgePoint.implementationBoundary.mixedUnitComparisonAllowed,false);assert.equal(authority.knowledgePoint.implementationBoundary.mixedUnitArithmeticAllowed,false);assert.deepEqual(authority.knowledgePoint.implementationBoundary.excludedKnowledgePointIds,["kp_capacity_container_scale_reading","kp_capacity_l_ml_conversion","kp_capacity_mixed_unit_compare","kp_capacity_mixed_unit_add_sub"]);});

test("P04F2 selector projects exactly one new public source and KP",()=>{const audit=auditP04F2PublicSelectorComposition();assert.equal(audit.ok,true,JSON.stringify(audit.errors));assert.deepEqual(audit.counts,{sources:36,knowledgePoints:261,g3bU02Visible:1,g3bU02Hidden:0,g3bU02NotSelectable:0});});

test("P04F2 planner generator and validator preserve capacity unit identity only",()=>{const plan=buildBatchABrowserPlan(options);assert.equal(plan.sourceId,G3B_U02_P04F2_SOURCE_ID);assert.deepEqual(plan.patternSpecIds,[G3B_U02_P04F2_SPEC_ID]);assert.equal(plan.questionMode,"numeric");assert.equal(plan.genericFallbackAllowed,false);const pv=validateBatchABrowserPlan(plan);assert.equal(pv.ok,true,JSON.stringify(pv.errors));const generation=generateBatchABrowserQuestions({...options,plan});assert.equal(generation.ok,true,JSON.stringify(generation.errors));assert.equal(generation.questions.length,8);assert.equal(new Set(generation.questions.map(q=>q.blankedDisplayText)).size,8);assert.deepEqual(new Set(generation.questions.map(q=>q.answerText)),new Set(["毫升","公升"]));for(const q of generation.questions){assert.ok(["smaller_capacity","larger_capacity"].includes(q.metadata.capacityScaleClass));assert.ok(["millilitre","litre"].includes(q.metadata.canonicalUnitId));assert.equal(q.metadata.dimensionId,"CAPACITY");assert.equal(q.metadata.unitFamilyId,"METRIC_CAPACITY");assert.equal(q.metadata.containerScaleReading,false);assert.equal(q.metadata.standaloneConversionQuestion,false);assert.equal(q.metadata.mixedUnitComparison,false);assert.equal(q.metadata.mixedUnitArithmetic,false);assert.doesNotMatch(q.blankedDisplayText,/1000|換算|刻度|加減|比較/);}const validation=validateBatchABrowserQuestions(generation.questions);assert.equal(validation.ok,true,JSON.stringify(validation.errors));});

test("P04F2 worksheet carries deterministic unit labels through question and answer pages",()=>{const result=buildBatchABrowserWorksheetDocument(options);assert.equal(result.ok,true,JSON.stringify(result.errors));const doc=result.worksheetDocument;assert.equal(doc.questionCount,8);assert.equal(doc.questionDisplayModels.length,8);assert.equal(doc.answerKeyItems.length,8);assert.equal(doc.questionPages.length,1);assert.equal(doc.answerKeyPages.length,1);assert.ok(doc.answerKeyItems.every(row=>["毫升","公升"].includes(row.answerText)));assert.equal(doc.metadata.containerScaleReading,false);assert.equal(doc.metadata.standaloneConversionQuestion,false);assert.equal(doc.metadata.mixedUnitComparison,false);assert.equal(doc.metadata.mixedUnitArithmetic,false);const html=renderWorksheetDocumentToHtml(doc,{stylesheetHref:""});assert.match(html,/毫升|公升/);assert.doesNotMatch(html,/1\s*公升\s*=\s*1000\s*毫升|混合量比較|混合量加減/);});
