import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";

import {auditP04F1PublicSelectorComposition} from "../../site/modules/curriculum/registry/batch-a-selector-p04f1-extension.js";
import {G3A_U04_P04F1_KP_ID,G3A_U04_P04F1_SOURCE_ID,G3A_U04_P04F1_SPEC_ID} from "../../site/modules/curriculum/registry/g3a-u04-ruler-reading-selector-projection-p04f1.js";
import {buildBatchABrowserPlan} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p04f1.js";
import {generateBatchABrowserQuestions} from "../../site/modules/curriculum/batch-a/batch-a-browser-question-router-p04f1.js";
import {validateBatchABrowserPlan,validateBatchABrowserQuestions} from "../../site/modules/curriculum/batch-a/batch-a-browser-validator-p04f1.js";
import {buildBatchABrowserWorksheetDocument} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p04f1-extension.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";

const options={sourceId:G3A_U04_P04F1_SOURCE_ID,selectionMode:"sourceUnit",questionMode:"numeric",questionCount:8,generationSeed:"p04f1-focused",includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showAnswerKeyPage:true}};

test("P04F1 authority is locked to q001 ruler reading only",()=>{const authority=JSON.parse(fs.readFileSync("data/curriculum/full-product/p04f/slice001-g3a-u04-ruler-reading-authority.json","utf8"));assert.equal(authority.queue.sliceId,"p04e_q001_r0_g3a_u04_3a04_profile_quantity_measurement_c1");assert.equal(authority.source.sourcePdfTitle,"meow911_3a04_mm_number_line.pdf");assert.deepEqual(authority.source.primaryWitnessPages,[1]);assert.equal(authority.knowledgePoint.knowledgePointId,G3A_U04_P04F1_KP_ID);assert.equal(authority.patternSpec.patternSpecId,G3A_U04_P04F1_SPEC_ID);assert.equal(authority.patternSpec.constraints.millimetersPerCentimeter,10);assert.equal(authority.patternSpec.constraints.excludeWholeCentimeterTargets,true);assert.equal(authority.knowledgePoint.implementationBoundary.standaloneConversionQuestionAllowed,false);assert.deepEqual(authority.knowledgePoint.implementationBoundary.excludedKnowledgePointIds,["kp_length_cm_mm_equivalence_conversion","kp_length_mixed_unit_compare","kp_length_mixed_unit_add_sub"]);});

test("P04F1 selector projects exactly one new public source and KP",()=>{const audit=auditP04F1PublicSelectorComposition();assert.equal(audit.ok,true,JSON.stringify(audit.errors));assert.deepEqual(audit.counts,{sources:35,knowledgePoints:260,g3aU04Visible:1,g3aU04Hidden:0,g3aU04NotSelectable:0});});

test("P04F1 planner generator and validator preserve millimeter ruler semantics",()=>{const plan=buildBatchABrowserPlan(options);assert.equal(plan.sourceId,G3A_U04_P04F1_SOURCE_ID);assert.deepEqual(plan.patternSpecIds,[G3A_U04_P04F1_SPEC_ID]);assert.equal(plan.questionMode,"numeric");assert.equal(plan.genericFallbackAllowed,false);const pv=validateBatchABrowserPlan(plan);assert.equal(pv.ok,true,JSON.stringify(pv.errors));const generation=generateBatchABrowserQuestions({...options,plan});assert.equal(generation.ok,true,JSON.stringify(generation.errors));assert.equal(generation.questions.length,8);assert.equal(new Set(generation.questions.map(q=>q.metadata.targetMillimeters)).size,8);for(const q of generation.questions){assert.equal(q.numberLine.kind,"measurement_ruler");assert.equal(q.numberLine.millimetersPerCentimeter,10);assert.equal(q.numberLine.tickCount,51);assert.equal(q.numberLine.endpointTickIndex,q.metadata.targetMillimeters);assert.equal(q.answer,q.metadata.targetMillimeters);assert.equal(q.answerText,`${q.metadata.targetMillimeters} 毫米`);assert.notEqual(q.metadata.targetMillimeters%10,0);assert.equal(q.metadata.standaloneConversionQuestion,false);assert.equal(q.metadata.mixedUnitComparison,false);assert.equal(q.metadata.mixedUnitArithmetic,false);}const validation=validateBatchABrowserQuestions(generation.questions);assert.equal(validation.ok,true,JSON.stringify(validation.errors));});

test("P04F1 worksheet carries ruler representation through question and answer pages",()=>{const result=buildBatchABrowserWorksheetDocument(options);assert.equal(result.ok,true,JSON.stringify(result.errors));const doc=result.worksheetDocument;assert.equal(doc.questionCount,8);assert.equal(doc.questionDisplayModels.length,8);assert.equal(doc.answerKeyItems.length,8);assert.equal(doc.questionPages.length,1);assert.equal(doc.answerKeyPages.length,1);assert.ok(doc.questionDisplayModels.every(row=>row.numberLine?.kind==="measurement_ruler"));assert.ok(doc.answerKeyItems.every(row=>row.numberLine?.kind==="measurement_ruler"));assert.equal(doc.metadata.standaloneConversionQuestion,false);assert.equal(doc.metadata.mixedUnitComparison,false);assert.equal(doc.metadata.mixedUnitArithmetic,false);const html=renderWorksheetDocumentToHtml(doc,{stylesheetHref:""});assert.match(html,/data-representation="measurement-ruler"/);assert.match(html,/worksheet-measurement-ruler/);assert.match(html,/箭頭所指的長度是多少毫米/);assert.doesNotMatch(html,/混合量比較|混合量加減/);});
