import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {materializeP05EW5DirectProductVerticalSliceQueue} from "../../src/curriculum/full-product/p05e-w5-direct-product-vertical-slice-queue.mjs";
import {materializeR04SharedRuntimeCapabilityMatrix} from "../../src/curriculum/global/r04-shared-runtime-capability-matrix.mjs";
import {materializeR05DeliveryWaveRebase} from "../../src/curriculum/global/r05-delivery-wave-rebase.mjs";
const read=p=>JSON.parse(readFileSync(new URL(`../../${p}`,import.meta.url),"utf8"));
const preflight=read("data/curriculum/full-product/p05f/q042-g4b-u02-quadrilateral-inclusion-relation-source-authority-preflight.json");
const r02=read("data/curriculum/global/candidates/r02/chunks/reviewed-source-candidates-02.json");
const KP="kp_g4b_u02_quadrilateral_inclusion_relation",CAPS=["cap_geometry_diagram_representation","cap_geometry_domain_validator","cap_geometry_property_reasoning"];

test("Q042 binds exact frozen row and Q041 E6 predecessor",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),row=q.queueEntries.find(x=>x.queuePosition===42);assert.equal(q.queueFrozen,true);assert.equal(q.queueRegistryParity,true);assert.equal(q.queueRegistry.queueDigest,"a4dae65a1a907ba963a135fce84ba292b8486a12513ae8f1fa54fbf07a6598ae");assert.ok(row);assert.equal(row.sliceId,"p05e_q042_r4_g4b_u02_4b02_profile_geometry_property_c1");assert.equal(row.implementationTaskId,"P05F_W5DirectProductVerticalSlice042Implementation");assert.equal(row.previousSliceId,"p05e_q041_r4_g3b_u05_3b05_profile_geometry_formula_c1");assert.equal(row.previousSliceMustBeD0Complete,true);assert.equal(row.primarySourceNodeId,"g4b_u02_4b02");assert.equal(row.intraWavePrerequisiteRank,4);assert.equal(row.primaryRuntimeProfileId,"profile_geometry_property");assert.equal(row.knowledgePointCount,1);assert.deepEqual(row.knowledgePointIds,[KP]);assert.deepEqual(row.requiredW5CapabilityIds,CAPS);const p=preflight.previousSliceD0Evidence;assert.equal(p.preflightPrNumber,924);assert.equal(p.productPrNumber,925);assert.equal(p.productHeadSha,"7f40cac6b58c3bde2755626ed7792b6341454b99");assert.equal(p.productMergeSha,"95ce7339eaae08d1fd0151db3d290481c343b71d");assert.equal(p.prGateRunId,"34800841737");assert.equal(p.exactPagesRunId,"34800917217");assert.equal(p.evidenceArtifactId,"10331467444");assert.equal(p.evidenceArtifactDigest,"sha256:7453d53f50103c35661a2cbf1eee2188abe02a836334b74036d227b58d0e44e1");assert.equal(p.status,"PASS_E6_D0_COMPLETE");});

test("Q042 reuses established G4B-U02 source identity and binds exact R02 candidate",()=>{const source=r02.sourceRecords.find(x=>x.sourceNodeId==="g4b_u02_4b02"),candidate=source?.candidates.find(x=>x.knowledgePointId===KP);assert.ok(source);assert.ok(candidate);assert.equal(preflight.status,"PASS_SOURCE_AUTHORITY_PREFLIGHT");assert.equal(preflight.sourceAuthority.sourceNodeId,"g4b_u02_4b02");assert.equal(preflight.sourceAuthority.sourcePdfTitle,"meow911_4b02_source.pdf");assert.equal(preflight.sourceAuthority.sourcePdfDriveFileId,"1ysaTTFTY37MC_gNzt1uh6yo2W34OGjIU");assert.equal(preflight.sourceAuthority.sourceUrl,"https://meow911.com/4b02/");assert.deepEqual(preflight.sourceAuthority.reviewedPages,[1,2]);assert.equal(preflight.sourceAuthority.semanticAuthority,"R02_REVIEWED_SOURCE_CANDIDATE");assert.equal(preflight.sourceAuthority.currentPreflightDirectTargetPanelReplayPerformed,false);assert.equal(preflight.sourceAuthority.currentPreflightDirectTargetPanelReplayRequired,false);assert.equal(preflight.sourceAuthority.manualSourceChoiceRequired,false);assert.equal(preflight.sourceAuthority.sourceRefAmbiguity,false);assert.equal(candidate.canonicalNameZh,"四邊形包含關係");assert.equal(candidate.capabilityStatement,"學生能理解特殊四邊形之間的包含關係。");assert.equal(candidate.reasoningInvariant,"滿足較嚴格條件的圖形也屬於其上位類別。");assert.equal(candidate.category,"geometry");assert.deepEqual(candidate.evidencePages,[1,2]);assert.equal(candidate.applicationSuitability,"APPLICATION_COMPATIBLE");assert.deepEqual(preflight.r02ReviewedCandidateAuthority.sameSourceCandidateIds,source.candidates.map(x=>x.knowledgePointId));});

test("Q042 current R04/R05 contract is exact geometry-property with no modifiers",()=>{const r04=materializeR04SharedRuntimeCapabilityMatrix(),m=r04.getMapping(KP);assert.ok(m);assert.equal(m.mappingId,"r04map_g4b_u02_quadrilateral_inclusion_relation");assert.equal(m.primaryRuntimeProfileId,"profile_geometry_property");assert.equal(m.classificationRuleId,"rule_geometry_property");assert.deepEqual(m.appliedModifierIds,[]);const profile=r04.profiles.find(x=>x.profileId==="profile_geometry_property");assert.ok(profile);for(const cap of ["cap_geometry_property_reasoning","cap_geometry_domain_validator","cap_geometry_diagram_representation"])assert.ok(profile.requiredCapabilityIds.includes(cap));const r05=materializeR05DeliveryWaveRebase(),a=r05.getAssignment(KP);assert.ok(a);assert.equal(a.deliveryWaveId,"R05-W5");assert.equal(a.intraWavePrerequisiteRank,4);assert.equal(a.primaryRuntimeProfileId,"profile_geometry_property");assert.deepEqual([...a.contractOnlyRequiredCapabilityIds].sort(),[...CAPS].sort());assert.deepEqual(preflight.runtimeCapabilityAuthority.exactFrozenQueueRequiredW5CapabilityIds,CAPS);});

test("Q042 preserves all four earlier same-source KP owners and is final G4B-U02 owner",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),expected={kp_g4b_u02_parallel_lines_recognition:4,kp_g4b_u02_perpendicular_lines_recognition:25,kp_g4b_u02_parallel_distance_construction:33,kp_g4b_u02_quadrilateral_classification:33};for(const[id,pos]of Object.entries(expected)){const row=q.queueEntries.find(x=>x.knowledgePointIds.includes(id));assert.ok(row,id);assert.equal(row.queuePosition,pos,id);assert.equal(preflight.q042ScopeLock.protectedFrozenOwnership[id],`Q${String(pos).padStart(3,"0")}`);}const sameSource=q.queueEntries.filter(x=>x.primarySourceNodeId==="g4b_u02_4b02");assert.ok(sameSource.some(x=>x.queuePosition===42&&x.knowledgePointIds.includes(KP)));assert.equal(sameSource.filter(x=>x.queuePosition>42).length,0);});

test("Q042 scope is quadrilateral inclusion only and current operator instruction authorizes implementation continuation",()=>{for(const r of ["IDENTIFY_SPECIAL_QUADRILATERAL_INCLUSION_RELATION","INFER_BROADER_CLASS_MEMBERSHIP_FROM_STRICTER_PROPERTY_SET","DISTINGUISH_CLASSIFICATION_LABEL_FROM_INCLUSION_MEMBERSHIP"])assert.ok(preflight.q042ScopeLock.includedRelations.includes(r));for(const r of ["REOWN_PARALLEL_LINE_RECOGNITION","REOWN_PERPENDICULAR_LINE_RECOGNITION","REOWN_PARALLEL_DISTANCE_CONSTRUCTION","REOWN_QUADRILATERAL_CLASSIFICATION_AS_PRIMARY_TARGET","GENERIC_GEOMETRY_CONSTRUCTION","NUMERIC_ANGLE_MEASUREMENT","AREA_OR_PERIMETER_FORMULA","APPLICATION_CONTEXT_IMPLEMENTATION","Q043_OR_LATER_SEMANTICS"])assert.ok(preflight.q042ScopeLock.excludedRelations.includes(r));assert.equal(preflight.q042ScopeLock.inclusionMustBeDerivedFromPropertyContainment,true);assert.equal(preflight.q042ScopeLock.stricterPropertySetImpliesBroaderClassMembership,true);assert.equal(preflight.q042ScopeLock.classificationTargetRemainsOwnedByQ033,true);assert.equal(preflight.q042ScopeLock.implementationAllowedByThisPreflight,false);assert.equal(preflight.q042ScopeLock.publicProductAdmissionAllowedByThisPreflight,false);const b=preflight.preflightValidationBoundary;assert.equal(b.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(b.derivedLane,"SHARED_RUNTIME_BOUNDED");assert.equal(b.fullRepositoryRegressionAllowed,false);assert.equal(b.globalBrowserReplayAllowed,false);const d=preflight.preflightDecision;assert.equal(d.previousSliceD0Satisfied,true);assert.equal(d.existingSameSourceQ004Q025Q033Protected,true);assert.equal(d.manualSourceChoiceRequired,false);assert.equal(d.sourceRefAmbiguity,false);assert.equal(d.separateImplementationApprovalSatisfiedByCurrentOperatorInstruction,true);assert.equal(d.nextTaskRequiresNewOperatorApproval,false);assert.equal(d.nextTask,"P05F_W5DirectProductVerticalSlice042Implementation");});
