import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {G5B_U01_P05F58_FORMAL_MAPPING as MAP,G5B_U01_P05F58_KP_ID as KP,G5B_U01_P05F58_PATTERN_GROUP_ID as GROUP,G5B_U01_P05F58_PATTERN_SPECS as PATTERNS,G5B_U01_P05F58_PRIOR_VISIBLE_KP_IDS as PRIOR,G5B_U01_P05F58_REQUIRED_CAPABILITY_IDS as REQUIRED,G5B_U01_P05F58_SOURCE_ID as SRC,G5B_U01_P05F58_SPEC_IDS as SPECS,auditG5BU01P05F58Projection} from "../../site/modules/curriculum/registry/g5b-u01-volume-unknown-dimension-selector-projection-p05f58.js";
import {auditP05F58PublicSelectorComposition,getVisibleBatchAKnowledgePoint,listBatchAKnowledgePointAvailabilityBySource} from "../../site/modules/curriculum/registry/batch-a-selector-p05f58-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p05f58.js";
import {generateG5BU01P05F58Questions,validateG5BU01P05F58Question} from "../../site/modules/curriculum/batch-a/g5b-u01-volume-unknown-dimension-runtime-p05f58.js";
import {requestsP05F58} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p05f58.js";
import {buildBatchABrowserWorksheetDocument as buildQ058} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f58-extension.js";
import {buildBatchABrowserWorksheetDocument as buildCurrent} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f32-extension.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";
import {validateLayeredCubeVolumeDiagramModel} from "../../site/modules/renderer/cubic-centimeter-unit-diagram.js";
const read=p=>JSON.parse(readFileSync(new URL(`../../${p}`,import.meta.url),"utf8"));
const preflight=read("data/curriculum/full-product/p05f/q058-g5b-u01-volume-unknown-dimension-source-authority-preflight.json");
const implementation=read("data/curriculum/full-product/p05f/q058-g5b-u01-volume-unknown-dimension-implementation.json");
const impact=read("data/project/change-impact/P05F_W5_Q058.impact.json");
const plan=read("data/project/validation-plans/P05F_W5_Q058.validation.json");
const req=(count=24)=>({sourceId:SRC,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[KP],selectedPatternGroupIds:[GROUP],patternSpecIds:[...SPECS],questionMode:"diagram",requestedQuestionType:"diagram",questionCount:count,generationSeed:"p05f58-focused-volume-unknown",includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showQuestionNumbers:true,showAnswerKeyPage:true}});
const occ=(t,x)=>t.split(x).length-1;

test("Q058 exact frozen identity and R02 pages 1-2 authority remain locked",()=>{assert.equal(preflight.status,"PASS_SOURCE_AUTHORITY_PREFLIGHT");assert.equal(preflight.queueAuthority.queuePosition,58);assert.equal(preflight.queueAuthority.sliceId,"p05e_q058_r6_g5b_u01_5b01_profile_geometry_formula_c1");assert.deepEqual(preflight.queueAuthority.knowledgePointIds,[KP]);assert.equal(preflight.previousSliceD0Evidence.status,"PASS_E6_D0_COMPLETE");assert.deepEqual(implementation.sourceAuthority.sourcePages,[1,2]);assert.equal(MAP.r04MappingId,"r04map_g5b_u01_volume_unknown_dimension");assert.deepEqual(MAP.sourcePages,[1,2]);assert.equal(MAP.capabilityStatement,"學生能由體積與兩個尺寸反求未知長、寬或高。");assert.equal(MAP.reasoningInvariant,"未知尺寸乘其餘兩尺寸必須重建原體積。");});

test("Q058 materializes one mapping one group and three inverse-volume PatternSpecs",()=>{const a=auditG5BU01P05F58Projection();assert.equal(a.ok,true,a.errors.join("\n"));assert.equal(PATTERNS.length,3);assert.deepEqual(REQUIRED,["cap_geometry_diagram_representation","cap_geometry_domain_validator","cap_geometry_formula_evaluation","cap_geometry_property_reasoning"]);assert.deepEqual(MAP.prerequisiteFormulaKnowledgePointIds,["kp_g5b_u01_rectangular_prism_volume_formula"]);assert.equal(MAP.appliedRuntimeModifierIds.length,0);assert.equal(MAP.optionalRuntimeCapabilityIds.length,0);assert.deepEqual([...new Set(PATTERNS.map(x=>x.targetDimension))].sort(),["HEIGHT","LENGTH","WIDTH"]);});

test("Q058 promotes only volume unknown-dimension and preserves all prior same-source owners",()=>{const a=auditP05F58PublicSelectorComposition();assert.equal(a.ok,true,a.errors.join("\n"));const s=listBatchAKnowledgePointAvailabilityBySource(SRC);assert.equal(s.visibleCount,5);assert.equal(s.hiddenPendingCount,0);assert.equal(s.notSelectableCount,0);for(const id of [...PRIOR,KP])assert.equal(getVisibleBatchAKnowledgePoint(id)?.sourceId,SRC,id);});

test("Q058 public binding is single-KP diagram-only with no runtime modifier escalation",()=>{assert.equal(auditPublicUiCapabilityBinding().ok,true);const b=resolvePublicUiCapabilityBinding(req());assert.equal(b.blocked,false);assert.equal(b.questionType,"diagram");assert.equal(b.questionCount.max,240);assert.equal(b.sourceBackedVolumeUnknownDimension,true);assert.equal(b.substitutionReconstructionRequired,true);assert.deepEqual(b.prerequisiteFormulaKnowledgePointIds,["kp_g5b_u01_rectangular_prism_volume_formula"]);assert.deepEqual(b.appliedRuntimeModifierIds,[]);assert.equal(b.volumeUnitConversionReowned,false);assert.equal(b.rectangularPrismVolumeFormulaReowned,false);assert.equal(b.cubeVolumeFormulaReowned,false);assert.equal(b.compositeRectangularVolumeReowned,false);assert.equal(requestsP05F58(req()),true);assert.equal(requestsP05F58({...req(),selectionMode:"sourceUnit"}),false);assert.equal(requestsP05F58({...req(),selectedKnowledgePointIds:[KP,PRIOR[0]]}),false);});

test("Q058 every PatternSpec yields 240 deterministic distinct valid variants",()=>{for(const id of SPECS){const o={knowledgePointId:KP,patternSpecIds:[id],questionCount:240,generationSeed:id},a=generateG5BU01P05F58Questions(o),b=generateG5BU01P05F58Questions(o);assert.equal(a.ok,true,`${id}:${a.errors.join("\n")}`);assert.deepEqual(a.questions,b.questions);assert.equal(new Set(a.questions.map(q=>q.questionSignature)).size,240);for(const q of a.questions){assert.equal(validateG5BU01P05F58Question(q).ok,true,id);assert.equal(validateLayeredCubeVolumeDiagramModel(q.geometryDiagram).ok,true,id);}const tampered=JSON.parse(JSON.stringify(a.questions[0]));tampered.answerValue+=1;tampered.answerText=`${tampered.answerValue} 公分`;assert.equal(validateG5BU01P05F58Question(tampered).ok,false);}});

test("Q058 recovered length width or height always reconstructs original volume",()=>{const r=generateG5BU01P05F58Questions({knowledgePointId:KP,questionCount:240,generationSeed:"q058-reconstruction"});assert.equal(r.ok,true,r.errors.join("\n"));const targets=new Set();const counts={LENGTH:0,WIDTH:0,HEIGHT:0};for(const q of r.questions){const d=q.geometryDiagram;targets.add(d.targetDimension);counts[d.targetDimension]+=1;assert.equal(d.reconstructedVolumeCubicCentimeters,d.volumeCubicCentimeters);assert.equal(q.metadata.substitutionReconstructionPassed,true);assert.equal(d.volumeCubicCentimeters,d.length*d.width*d.height);assert.equal(q.answerValue,d.hiddenDimensionValueCm);assert.ok(Number.isInteger(q.answerValue)&&q.answerValue>0);}assert.deepEqual([...targets].sort(),["HEIGHT","LENGTH","WIDTH"]);assert.deepEqual(counts,{LENGTH:80,WIDTH:80,HEIGHT:80});});

test("Q058 worksheet current bridge renderer answer key and browser wrappers stay product-safe",async()=>{const r=buildQ058(req(24));assert.equal(r.ok,true,r.errors.join("\n"));assert.equal(r.worksheetDocument.questionCount,24);assert.equal(r.worksheetDocument.answerKeyItems.length,24);const html=renderWorksheetDocumentToHtml(r.worksheetDocument,{stylesheetHref:"",title:r.worksheetDocument.title,debugDataAttributes:false});assert.equal(occ(html,'data-representation="layered-cube-volume-diagram"'),48);assert.equal(html.includes("kp_g5b_u01_"),false);assert.equal(html.includes("ps_g5b_u01_"),false);const current=buildCurrent(req(12));assert.equal(current.ok,true,current.errors.join("\n"));assert.equal(current.p05f58Implemented,true);assert.equal(current.worksheetDocument.metadata.knowledgePointId,KP);globalThis.document={};try{const selector=await import(`../../site/modules/curriculum/registry/batch-a-selector-p04f33-extension.js?p05f58=${Date.now()}`),binding=await import(`../../site/modules/curriculum/public/public-ui-capability-binding-p04f33.js?p05f58=${Date.now()}`);for(const id of [...PRIOR,KP])assert.equal(selector.getVisibleBatchAKnowledgePoint(id)?.sourceId,SRC,id);assert.equal(binding.resolvePublicUiCapabilityBinding(req()).sourceBackedVolumeUnknownDimension,true);}finally{delete globalThis.document;}});

test("Q058 validation remains bounded and scope guard stays closed",()=>{assert.equal(impact.expectedDerivedGate,"SHARED_RUNTIME_BOUNDED");assert.equal(impact.changeImpact.affectedRoutes,"BOUNDED");assert.equal(impact.changeImpact.legalRouteSemanticsChanged,false);assert.equal(plan.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(plan.lanes.SHARED_RUNTIME_BOUNDED[0].kind,"NODE_TEST");assert.equal(plan.lanes.SHARED_RUNTIME_BOUNDED[1].runtime,"PLAYWRIGHT_CHROMIUM");assert.equal(implementation.validation.fullRepositoryRegression,"FORBIDDEN");assert.equal(implementation.validation.globalBrowserReplay,"FORBIDDEN");for(const v of Object.values(implementation.scopeGuard))assert.equal(v,false);});
