import test from "node:test";
import assert from "node:assert/strict";
import {existsSync,readFileSync} from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";

import {buildBatchABrowserWorksheetDocument} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f10-extension.js";
import {generateG3AU05P05F10Questions,validateG3AU05P05F10Question} from "../../site/modules/curriculum/batch-a/g3a-u05-right-angle-recognition-runtime-p05f10.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";
import {
  G3A_U05_P05F10_FORMAL_MAPPING,
  G3A_U05_P05F10_FUTURE_KP_IDS,
  G3A_U05_P05F10_GROUP_ID,
  G3A_U05_P05F10_KP_ID,
  G3A_U05_P05F10_SPEC_IDS,
  G3A_U05_P05F10_SOURCE_ID,
  auditG3AU05P05F10SelectorProjection,
} from "../../site/modules/curriculum/registry/g3a-u05-right-angle-recognition-selector-projection-p05f10.js";
import {
  BATCH_A_SELECTOR_AVAILABILITY,
  auditP05F10PublicSelectorComposition,
  getVisibleBatchAKnowledgePoint,
  listBatchAKnowledgePointAvailabilityBySource,
  resolveVisiblePatternSpecIdsForKnowledgePoint,
} from "../../site/modules/curriculum/registry/batch-a-selector-p05f10-extension.js";
import {resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p05f10.js";

const preflight=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q010-g3a-u05-right-angle-recognition-source-authority-preflight.json",import.meta.url),"utf8"));
const implementation=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q010-g3a-u05-right-angle-recognition-implementation.json",import.meta.url),"utf8"));
const options={sourceId:G3A_U05_P05F10_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G3A_U05_P05F10_KP_ID],selectedPatternGroupIds:[G3A_U05_P05F10_GROUP_ID],patternSpecIds:[...G3A_U05_P05F10_SPEC_IDS],questionMode:"diagram",requestedQuestionType:"diagram",questionCount:24,generationSeed:"p05f10-focused",includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showQuestionNumbers:true,showAnswerKeyPage:true}};
const occurrences=(text,token)=>text.split(token).length-1;

test("P05F W5 Q010 preserves exact frozen queue/source boundary and Q009 D0 prerequisite",()=>{assert.equal(preflight.status,"PASS_SOURCE_AUTHORITY_PREFLIGHT");assert.equal(preflight.queueAuthority.queuePosition,10);assert.equal(preflight.queueAuthority.sliceId,"p05e_q010_r1_g3a_u05_3a05_profile_geometry_property_c1");assert.equal(preflight.queueAuthority.implementationTaskId,"P05F_W5DirectProductVerticalSlice010Implementation");assert.deepEqual(preflight.queueAuthority.knowledgePointIds,[G3A_U05_P05F10_KP_ID]);assert.equal(preflight.previousSliceD0Evidence.status,"PASS_E6_D0_COMPLETE");assert.equal(preflight.sourceAuthority.page1DirectEvidence.panelTitle,"認識直角");assert.deepEqual(preflight.sourceAuthority.page1DirectEvidence.directlySupportedConcepts,["RIGHT_ANGLE_RECOGNITION_USING_SET_SQUARE_MODEL","RIGHT_ANGLE_SYMBOL_MARKER"]);assert.equal(implementation.status,"IMPLEMENTATION_MATERIALIZED_AWAITING_FOCUSED_CI");assert.equal(implementation.scopeGuard.q011Touched,false);});

test("P05F W5 Q010 materializes one FormalMapping, one group, and three diagram PatternSpecs",()=>{const audit=auditG3AU05P05F10SelectorProjection();assert.equal(audit.ok,true,audit.errors.join("\n"));assert.deepEqual(audit.counts,{knowledgePoints:1,patternGroups:1,patternSpecs:3,diagram:3,application:0});assert.equal(G3A_U05_P05F10_FORMAL_MAPPING.mappingId,"fm_g3a_u05_right_angle_recognition_p05f10");assert.deepEqual(G3A_U05_P05F10_FORMAL_MAPPING.includedRelations,["RECOGNIZE_RIGHT_ANGLE_FROM_DIAGRAM","IDENTIFY_RIGHT_ANGLE_SYMBOL"]);for(const relation of ["IDENTIFY_ANGLE_PARTS","CLASSIFY_ACUTE_RIGHT_OBTUSE","RECTANGLE_SQUARE_PROPERTY_REASONING","ANGLE_MEASURE_NUMERIC","ANGLE_CONSTRUCTION","APPLICATION_CONTEXT"])assert.ok(G3A_U05_P05F10_FORMAL_MAPPING.excludedRelations.includes(relation));});

test("P05F W5 Q010 promotes the second G3A-U05 leaf while two successors remain fail-closed",()=>{const audit=auditP05F10PublicSelectorComposition();assert.equal(audit.ok,true,audit.errors.join("\n"));assert.deepEqual(audit.counts,{sources:51,knowledgePoints:322,g3aU05Visible:2,g3aU05Hidden:2,g3aU05NotSelectable:2});assert.equal(BATCH_A_SELECTOR_AVAILABILITY.publicSourceCount,51);const source=listBatchAKnowledgePointAvailabilityBySource(G3A_U05_P05F10_SOURCE_ID);assert.deepEqual(source.visibleKnowledgePointIds,["kp_angle_parts_identification",G3A_U05_P05F10_KP_ID]);assert.deepEqual(source.hiddenPendingKnowledgePointIds,[...G3A_U05_P05F10_FUTURE_KP_IDS]);assert.deepEqual(source.notSelectableKnowledgePointIds,[...G3A_U05_P05F10_FUTURE_KP_IDS]);assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(G3A_U05_P05F10_KP_ID,"diagram"),[...G3A_U05_P05F10_SPEC_IDS]);for(const id of G3A_U05_P05F10_FUTURE_KP_IDS)assert.equal(getVisibleBatchAKnowledgePoint(id),null);});

test("P05F W5 Q010 generates balanced source-backed right-angle recognition and validates fail-closed",()=>{const generated=generateG3AU05P05F10Questions(options);assert.equal(generated.ok,true,generated.errors.join("\n"));assert.equal(generated.questions.length,24);assert.deepEqual(generated.allocation.map(row=>row.count),[8,8,8]);assert.equal(new Set(generated.questions.map(row=>row.questionSignature)).size,24);assert.deepEqual(new Set(generated.questions.map(row=>row.answerText)),new Set(["是直角","不是直角","直角符號"]));for(const question of generated.questions){assert.equal(validateG3AU05P05F10Question(question).ok,true);assert.equal(question.promptText.includes("銳角"),false);assert.equal(question.promptText.includes("鈍角"),false);assert.equal(question.metadata.numericAngleMeasureUsed,false);assert.equal(question.metadata.applicationContextUsed,false);}const answerTamper=JSON.parse(JSON.stringify(generated.questions[0]));answerTamper.answerText="直角";assert.equal(validateG3AU05P05F10Question(answerTamper).ok,false);const right=generated.questions.find(q=>q.geometryDiagram.targetClass==="RIGHT_ANGLE");const angleTamper=JSON.parse(JSON.stringify(right));angleTamper.geometryDiagram.openingDeg=88;assert.equal(validateG3AU05P05F10Question(angleTamper).ok,false);const symbol=generated.questions.find(q=>q.geometryDiagram.markerMode==="RIGHT_ANGLE_SYMBOL");const markerTamper=JSON.parse(JSON.stringify(symbol));markerTamper.geometryDiagram.rightAngleSymbolVisible=false;assert.equal(validateG3AU05P05F10Question(markerTamper).ok,false);});

test("P05F W5 Q010 proves 240 distinct variants for every PatternSpec",()=>{for(const patternSpecId of G3A_U05_P05F10_SPEC_IDS){const result=generateG3AU05P05F10Questions({questionCount:240,patternSpecIds:[patternSpecId],generationSeed:`capacity-${patternSpecId}`});assert.equal(result.ok,true,`${patternSpecId}: ${result.errors.join("\n")}`);assert.equal(result.questions.length,240);assert.equal(new Set(result.questions.map(row=>row.questionSignature)).size,240);assert.equal(result.questions.every(row=>row.patternSpecId===patternSpecId),true);}});

test("P05F W5 Q010 public binding is diagram-only max-240 with forbidden semantic admissions disabled",()=>{const binding=resolvePublicUiCapabilityBinding(options);assert.equal(binding.blocked,false);assert.equal(binding.questionType,"diagram");assert.deepEqual(binding.availableQuestionTypeOptions.map(row=>row.value),["diagram"]);assert.equal(binding.questionCount.max,240);assert.deepEqual(binding.compatiblePatternGroupIds,[G3A_U05_P05F10_GROUP_ID]);assert.deepEqual(binding.patternSpecIds,[...G3A_U05_P05F10_SPEC_IDS]);assert.equal(binding.geometryDiagramRepresentationRequired,true);assert.equal(binding.geometryDomainValidatorRequired,true);assert.equal(binding.geometryPropertyReasoningRequired,true);assert.equal(binding.numericAngleMeasureAdmission,false);assert.equal(binding.acuteObtuseClassificationAdmission,false);assert.equal(binding.rectangleSquarePropertyAdmission,false);assert.equal(binding.applicationImplementationAllowed,false);assert.equal(binding.genericFallback,false);assert.equal(binding.freeFormAI,false);});

test("P05F W5 Q010 worksheet and HTML renderer preserve 24 questions, 24 answers, and right-angle diagrams",()=>{const result=buildBatchABrowserWorksheetDocument(options);assert.equal(result.ok,true,result.errors.join("\n"));const document=result.worksheetDocument;assert.equal(document.questionCount,24);assert.equal(document.answerKeyItems.length,24);assert.equal(document.questionPages.length,3);assert.equal(document.answerKeyPages.length,3);assert.equal(document.questionDisplayModels.every(row=>row.geometryDiagram?.kind==="right_angle_recognition_diagram"),true);assert.equal(document.answerKeyItems.every(row=>row.geometryDiagram?.kind==="right_angle_recognition_diagram"),true);const html=renderWorksheetDocumentToHtml(document,{stylesheetHref:""});assert.equal(occurrences(html,'class="worksheet-right-angle-recognition-diagram"'),48);assert.equal(occurrences(html,'class="right-angle-recognition-diagram__reference-model"'),32);assert.equal(occurrences(html,'class="right-angle-recognition-diagram__right-angle-symbol"'),16);assert.equal(occurrences(html,'data-target-class="RIGHT_ANGLE"'),32);assert.equal(occurrences(html,'data-target-class="NON_RIGHT_ANGLE"'),16);for(const forbidden of ["銳角","鈍角","90°","90度","量角器","應用題"])assert.equal(html.includes(forbidden),false);});

test("P05F W5 Q010 stable browser selector/binding wrappers continue to expose the Q010 leaf after successor cutovers",async()=>{globalThis.document={};try{const selector=await import(`../../site/modules/curriculum/registry/batch-a-selector-p04f33-extension.js?p05f10=${Date.now()}`),bindingModule=await import(`../../site/modules/curriculum/public/public-ui-capability-binding-p04f33.js?p05f10=${Date.now()}`);assert.equal(selector.getVisibleBatchAKnowledgePoint(G3A_U05_P05F10_KP_ID)?.sourceId,G3A_U05_P05F10_SOURCE_ID);const source=selector.listBatchAKnowledgePointAvailabilityBySource(G3A_U05_P05F10_SOURCE_ID);assert.equal(source.visibleKnowledgePointIds.includes(G3A_U05_P05F10_KP_ID),true);const binding=bindingModule.resolvePublicUiCapabilityBinding(options);assert.equal(binding.questionType,"diagram");assert.equal(binding.questionCount.max,240);}finally{delete globalThis.document;}});

test("P05F W5 Q010 pre-push static relative-import smoke proves every changed JS/MJS import exists",()=>{const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../.."),files=["site/modules/curriculum/registry/g3a-u05-right-angle-recognition-selector-projection-p05f10.js","site/modules/curriculum/registry/batch-a-selector-p05f10-extension.js","site/modules/curriculum/public/public-ui-capability-binding-p05f10.js","site/modules/curriculum/batch-a/g3a-u05-right-angle-recognition-runtime-p05f10.js","site/modules/curriculum/batch-a/batch-a-browser-generator-p05f10.js","site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f10-extension.js","site/modules/curriculum/batch-a/batch-a-browser-worksheet-r2e-entry.js","site/modules/curriculum/registry/batch-a-selector-p04f33-extension.js","site/modules/curriculum/public/public-ui-capability-binding-p04f33.js","site/modules/renderer/right-angle-recognition-diagram.js","site/modules/renderer/html-renderer.js","tools/curriculum/run-p05f-w5-slice010-classic-ui-acceptance.mjs","tools/curriculum/run-p05f-w5-q010-live-pages-e2e.mjs"];const importPattern=/(?:import|export)\s+(?:[^'";]+?\s+from\s+)?["'](\.{1,2}\/[^"']+)["']/g;for(const file of files){const absolute=path.join(root,file),text=readFileSync(absolute,"utf8");for(const match of text.matchAll(importPattern)){const target=path.resolve(path.dirname(absolute),match[1]);assert.equal(existsSync(target),true,`${file} -> ${match[1]}`);}}});
