import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {auditG5AU09P05F46Projection,G5A_U09_P05F46_FORMAL_MAPPINGS,G5A_U09_P05F46_KP_IDS,G5A_U09_P05F46_PATTERN_SPECS,G5A_U09_P05F46_REMAINING_FUTURE_KP_IDS,G5A_U09_P05F46_REQUIRED_W5_CAPABILITY_IDS,G5A_U09_P05F46_RUNTIME_DOMAIN_CAPABILITY_IDS,G5A_U09_P05F46_SOURCE_ID,G5A_U09_P05F46_SPEC_IDS_BY_KP,G5A_U09_P05F46_TRIANGLE_KP_ID,G5A_U09_P05F46_TRAPEZOID_KP_ID} from "../../site/modules/curriculum/registry/g5a-u09-triangle-trapezoid-area-formulas-selector-projection-p05f46.js";
import {BATCH_A_SELECTOR_AVAILABILITY as P05F45_SELECTOR} from "../../site/modules/curriculum/registry/batch-a-selector-p05f45-extension.js";
import {auditP05F46PublicSelectorComposition,getVisibleBatchAKnowledgePoint,listBatchAKnowledgePointAvailabilityBySource,resolveVisiblePatternSpecIdsForKnowledgePoint} from "../../site/modules/curriculum/registry/batch-a-selector-p05f46-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p05f46.js";
import {buildBatchABrowserPlan,generateBatchABrowserQuestions,requestsP05F46} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p05f46.js";
import {buildBatchABrowserWorksheetDocument as buildQ046Worksheet} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f46-extension.js";
import {buildBatchABrowserWorksheetDocument as buildCurrentWorksheet} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f32-extension.js";
import {generateG5AU09P05F46Questions,validateG5AU09P05F46Question} from "../../site/modules/curriculum/batch-a/g5a-u09-triangle-trapezoid-area-formulas-runtime-p05f46.js";
import {renderRectangleSquareAreaFormulaDiagram} from "../../site/modules/renderer/rectangle-square-area-formula-diagram.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";
const preflight=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q046-g5a-u09-triangle-trapezoid-area-formulas-source-authority-preflight.json",import.meta.url),"utf8"));
const implementation=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q046-g5a-u09-triangle-trapezoid-area-formulas-implementation.json",import.meta.url),"utf8"));
const opts=(kp,count=18,extra={})=>({sourceId:G5A_U09_P05F46_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[kp],patternSpecIds:[...G5A_U09_P05F46_SPEC_IDS_BY_KP[kp]],questionMode:"diagram",requestedQuestionType:"diagram",questionCount:count,generationSeed:`q046-${kp}`,includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showQuestionNumbers:true,showAnswerKeyPage:true},...extra});
const occurrences=(text,token)=>text.split(token).length-1;

test("Q046 exact preflight implementation and R04 division modifier identities remain frozen",()=>{assert.equal(preflight.status,"PASS_SOURCE_AUTHORITY_PREFLIGHT");assert.equal(preflight.queueAuthority.queuePosition,46);assert.deepEqual(preflight.queueAuthority.knowledgePointIds,G5A_U09_P05F46_KP_IDS);assert.equal(implementation.taskId,"P05F_W5DirectProductVerticalSlice046Implementation");assert.equal(implementation.preflightMergeSha,"caf5a71127b54355428883b4399828c3a2ded9df");assert.deepEqual(implementation.queueAuthority.requiredW5CapabilityIds,G5A_U09_P05F46_REQUIRED_W5_CAPABILITY_IDS);assert.deepEqual(implementation.runtimeCapabilityBinding.appliedModifierIds,["mod_integer_division"]);assert.deepEqual(implementation.runtimeCapabilityBinding.domainCapabilityIds,G5A_U09_P05F46_RUNTIME_DOMAIN_CAPABILITY_IDS);assert.equal(implementation.runtimeCapabilityBinding.integerDivisionAlreadyProductionAdmitted,true);});

test("Q046 materializes two mappings two groups six exact source-backed PatternSpecs",()=>{const a=auditG5AU09P05F46Projection();assert.equal(a.ok,true,a.errors.join("\n"));assert.deepEqual(a.counts,{knowledgePoints:2,patternGroups:2,patternSpecs:6,diagram:6,application:0});assert.equal(G5A_U09_P05F46_FORMAL_MAPPINGS.length,2);assert.equal(G5A_U09_P05F46_PATTERN_SPECS.length,6);for(const m of G5A_U09_P05F46_FORMAL_MAPPINGS){const p=preflight.r02ReviewedCandidateAuthority.knowledgePoints.find(x=>x.knowledgePointId===m.knowledgePointId);assert.ok(p);assert.deepEqual(m.r02EvidencePages,p.evidencePages);assert.deepEqual(m.appliedRuntimeModifierIds,["mod_integer_division"]);assert.ok(m.runtimeDomainCapabilityIds.includes("cap_integer_division"));assert.equal(m.parallelogramAreaFormulaReowned,false);}});

test("Q046 selector adds only triangle and trapezoid while preserving Q037 and hiding Q057 Q062",()=>{const before=P05F45_SELECTOR.bySourceId[G5A_U09_P05F46_SOURCE_ID];assert.deepEqual(before.visibleKnowledgePointIds,["kp_g5a_u09_parallelogram_area_formula"]);assert.equal(before.hiddenPendingCount,4);const audit=auditP05F46PublicSelectorComposition();assert.equal(audit.ok,true,audit.errors.join("\n"));const s=listBatchAKnowledgePointAvailabilityBySource(G5A_U09_P05F46_SOURCE_ID);assert.equal(s.visibleCount,3);assert.equal(s.hiddenPendingCount,2);assert.equal(s.notSelectableCount,2);for(const id of ["kp_g5a_u09_parallelogram_area_formula",...G5A_U09_P05F46_KP_IDS])assert.ok(getVisibleBatchAKnowledgePoint(id),id);for(const id of G5A_U09_P05F46_REMAINING_FUTURE_KP_IDS)assert.equal(getVisibleBatchAKnowledgePoint(id),null,id);for(const kp of G5A_U09_P05F46_KP_IDS)assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(kp,"diagram"),G5A_U09_P05F46_SPEC_IDS_BY_KP[kp]);});

test("Q046 public bindings and browser plans stay single-KP diagram-only and fail closed on mixed selection",()=>{assert.equal(auditPublicUiCapabilityBinding().ok,true);for(const kp of G5A_U09_P05F46_KP_IDS){const o=opts(kp),b=resolvePublicUiCapabilityBinding(o);assert.equal(b.blocked,false);assert.equal(b.questionType,"diagram");assert.equal(b.questionCount.max,240);assert.equal(b.integerDivisionModifierApplied,true);assert.equal(b.integerDivisionCapabilityId,"cap_integer_division");assert.equal(b.parallelogramAreaFormulaReowned,false);assert.equal(b.unknownDimensionAdmission,false);assert.equal(b.compositePolygonAreaAdmission,false);assert.equal(requestsP05F46(o),true);const p=buildBatchABrowserPlan(o);assert.deepEqual(p.selectedKnowledgePointIds,[kp]);assert.equal(p.genericFallback,false);assert.equal(generateBatchABrowserQuestions(o).ok,true);}assert.equal(requestsP05F46({...opts(G5A_U09_P05F46_TRIANGLE_KP_ID),selectedKnowledgePointIds:[...G5A_U09_P05F46_KP_IDS]}),false);assert.equal(requestsP05F46({...opts(G5A_U09_P05F46_TRIANGLE_KP_ID),selectionMode:"mixedKnowledgePointsSameUnit"}),false);});

test("Q046 deterministically generates and validates 240 questions for each KP and each PatternSpec",()=>{for(const kp of G5A_U09_P05F46_KP_IDS){const a=generateG5AU09P05F46Questions(opts(kp,240)),b=generateG5AU09P05F46Questions(opts(kp,240));assert.equal(a.ok,true,a.errors.join("\n"));assert.equal(a.questions.length,240);assert.equal(new Set(a.questions.map(q=>q.questionSignature)).size,240);assert.deepEqual(a.questions,b.questions);assert.ok(a.questions.every(q=>validateG5AU09P05F46Question(q).ok));for(const id of G5A_U09_P05F46_SPEC_IDS_BY_KP[kp]){const r=generateG5AU09P05F46Questions({knowledgePointId:kp,patternSpecIds:[id],questionCount:240,generationSeed:`capacity-${id}`});assert.equal(r.ok,true,`${id}:${r.errors.join("\n")}`);assert.equal(new Set(r.questions.map(q=>q.questionSignature)).size,240,id);}}});

test("Q046 formulas are exact and validator rejects geometry answer and provenance tampering",()=>{for(const kp of G5A_U09_P05F46_KP_IDS){const q=generateG5AU09P05F46Questions(opts(kp,1)).questions[0],d=q.geometryDiagram;if(kp===G5A_U09_P05F46_TRIANGLE_KP_ID)assert.equal(d.areaCm2,d.baseCm*d.heightCm/2);else assert.equal(d.areaCm2,(d.topBaseCm+d.bottomBaseCm)*d.heightCm/2);assert.equal(Number.isInteger(d.areaCm2),true);assert.equal(d.heightPerpendicular,true);for(const mutate of [x=>x.geometryDiagram.heightPerpendicular=false,x=>x.answerText="錯誤",x=>x.metadata.integerDivisionModifierApplied=false,x=>x.metadata.parallelogramAreaFormulaReowned=true]){const t=JSON.parse(JSON.stringify(q));mutate(t);assert.equal(validateG5AU09P05F46Question(t).ok,false);}}});

test("Q046 worksheet answer key renderer and current top-slot bridge work for both targets",()=>{for(const kp of G5A_U09_P05F46_KP_IDS){for(const build of [buildQ046Worksheet,buildCurrentWorksheet]){const r=build(opts(kp));assert.equal(r.ok,true,r.errors.join("\n"));assert.equal(r.worksheetDocument.questionCount,18);assert.equal(r.worksheetDocument.answerKeyItems.length,18);assert.equal(r.worksheetDocument.metadata.knowledgePointId,kp);const html=renderWorksheetDocumentToHtml(r.worksheetDocument,{stylesheetHref:null,title:r.worksheetDocument.title,debugDataAttributes:false});assert.equal(occurrences(html,'data-representation="triangle-trapezoid-area-formula-diagram"'),36);assert.equal(html.includes("kp_g5a_u09_"),false);assert.equal(html.includes("ps_g5a_u09_"),false);assert.doesNotThrow(()=>renderRectangleSquareAreaFormulaDiagram(r.worksheetDocument.questions[0].geometryDiagram));}}});

test("Q046 current browser wrappers expose targets while prior and future ownership remain correct",async()=>{globalThis.document={};try{const s=await import(`../../site/modules/curriculum/registry/batch-a-selector-p04f33-extension.js?p05f46=${Date.now()}`),b=await import(`../../site/modules/curriculum/public/public-ui-capability-binding-p04f33.js?p05f46=${Date.now()}`);for(const kp of G5A_U09_P05F46_KP_IDS){assert.ok(s.getVisibleBatchAKnowledgePoint(kp));assert.equal(b.resolvePublicUiCapabilityBinding(opts(kp)).blocked,false);}assert.ok(s.getVisibleBatchAKnowledgePoint("kp_g5a_u09_parallelogram_area_formula"));for(const id of G5A_U09_P05F46_REMAINING_FUTURE_KP_IDS)assert.equal(s.getVisibleBatchAKnowledgePoint(id),null);}finally{delete globalThis.document;}});

test("Q046 manifests remain bounded and protect frozen future ownership",()=>{const impact=JSON.parse(readFileSync(new URL("../../data/project/change-impact/P05F_W5_Q046.impact.json",import.meta.url),"utf8")),plan=JSON.parse(readFileSync(new URL("../../data/project/validation-plans/P05F_W5_Q046.validation.json",import.meta.url),"utf8"));assert.equal(implementation.status,"IMPLEMENTATION_MATERIALIZED_AWAITING_FOCUSED_CI");assert.equal(implementation.goalDistance.reduced,"D2_TO_D1");assert.equal(implementation.publicAdmission.expectedGlobalPublicSourceDelta,0);assert.equal(implementation.publicAdmission.expectedGlobalVisibleKnowledgePointDelta,2);for(const v of Object.values(implementation.scopeGuard))assert.equal(v,false);assert.equal(impact.expectedDerivedGate,"SHARED_RUNTIME_BOUNDED");assert.equal(plan.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(plan.lanes.SHARED_RUNTIME_BOUNDED[1].runtime,"PLAYWRIGHT_CHROMIUM");assert.equal(JSON.stringify(plan).includes("full npm test"),false);});
