import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {G4B_U02_P05F25_FORMAL_MAPPING,G4B_U02_P05F25_KP_ID,G4B_U02_P05F25_PATTERN_SPECS,G4B_U02_P05F25_REMAINING_FUTURE_KP_IDS,G4B_U02_P05F25_SOURCE_ID,G4B_U02_P05F25_SPEC_IDS,auditG4BU02P05F25Projection} from "../../site/modules/curriculum/registry/g4b-u02-perpendicular-lines-recognition-selector-projection-p05f25.js";
import {auditP05F25PublicSelectorComposition,getVisibleBatchAKnowledgePoint,listBatchAKnowledgePointAvailabilityBySource,resolveVisiblePatternSpecIdsForKnowledgePoint} from "../../site/modules/curriculum/registry/batch-a-selector-p05f25-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p05f25.js";
import {generateG4BU02P05F25Questions,validateG4BU02P05F25Question} from "../../site/modules/curriculum/batch-a/g4b-u02-perpendicular-lines-recognition-runtime-p05f25.js";
import {buildBatchABrowserPlan,generateBatchABrowserQuestions,requestsP05F25} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p05f25.js";
import {buildBatchABrowserWorksheetDocument} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f25-extension.js";
import {buildBatchABrowserWorksheetDocument as buildStableWorksheet} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-r2e-entry.js";
import {renderPerpendicularLinesRecognitionDiagram,renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";
const implementation=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q025-g4b-u02-perpendicular-lines-recognition-implementation.json",import.meta.url),"utf8"));

test("Q025 exact frozen authority and FormalMapping remain source-bound",()=>{assert.equal(implementation.queueAuthority.queuePosition,25);assert.equal(implementation.queueAuthority.sliceId,"p05e_q025_r2_g4b_u02_4b02_profile_geometry_property_c1");assert.equal(implementation.queueAuthority.sourceId,G4B_U02_P05F25_SOURCE_ID);assert.deepEqual(implementation.queueAuthority.knowledgePointIds,[G4B_U02_P05F25_KP_ID]);assert.equal(implementation.queueAuthority.runtimeProfileId,"profile_geometry_property");assert.equal(implementation.queueAuthority.targetEvidenceLevel,"E6_D0_COMPLETE");assert.equal(implementation.queueAuthority.requiredProductNodes.length,13);assert.equal(G4B_U02_P05F25_FORMAL_MAPPING.knowledgePointId,G4B_U02_P05F25_KP_ID);assert.deepEqual(G4B_U02_P05F25_FORMAL_MAPPING.includedRelations,["RECOGNIZE_INTERSECTING_LINES_FORMING_A_RIGHT_ANGLE_AS_PERPENDICULAR","USE_90_DEGREE_INTERSECTION_AS_PERPENDICULARITY_INVARIANT","PRESERVE_PERPENDICULAR_CLASSIFICATION_INDEPENDENT_OF_SEGMENT_LENGTH"]);assert.equal(auditG4BU02P05F25Projection().ok,true);});

test("Q025 promotes only perpendicular recognition and protects Q004 plus future same-source candidates",()=>{const audit=auditP05F25PublicSelectorComposition();assert.equal(audit.ok,true,JSON.stringify(audit));const source=listBatchAKnowledgePointAvailabilityBySource(G4B_U02_P05F25_SOURCE_ID);assert.equal(source.visibleCount,2);assert.equal(source.hiddenPendingCount,3);assert.equal(source.notSelectableCount,3);for(const id of ["kp_g4b_u02_parallel_lines_recognition",G4B_U02_P05F25_KP_ID]){assert.ok(source.visibleKnowledgePointIds.includes(id));assert.ok(getVisibleBatchAKnowledgePoint(id));}for(const id of G4B_U02_P05F25_REMAINING_FUTURE_KP_IDS){assert.ok(source.hiddenPendingKnowledgePointIds.includes(id));assert.ok(source.notSelectableKnowledgePointIds.includes(id));assert.equal(getVisibleBatchAKnowledgePoint(id),null);}assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(G4B_U02_P05F25_KP_ID,"diagram"),G4B_U02_P05F25_SPEC_IDS);assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(G4B_U02_P05F25_KP_ID,"numeric"),[]);});

test("Q025 public binding admits only single-KP diagram recognition",()=>{const b=resolvePublicUiCapabilityBinding({sourceId:G4B_U02_P05F25_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G4B_U02_P05F25_KP_ID]});assert.equal(b.blocked,false);assert.equal(b.questionType,"diagram");assert.equal(b.questionCount.max,240);assert.equal(b.sourceBackedPerpendicularRecognition,true);assert.equal(b.rightAngleIntersectionDeterminesPerpendicularity,true);assert.equal(b.segmentLengthDoesNotChangePerpendicularity,true);assert.equal(b.parallelLinesRecognitionTargetAdmission,false);assert.equal(b.parallelDistanceMeasurementAdmission,false);assert.equal(b.parallelLineConstructionAdmission,false);assert.equal(b.quadrilateralClassificationAdmission,false);assert.equal(b.quadrilateralInclusionAdmission,false);assert.equal(b.numericAngleMeasurementAdmission,false);assert.equal(b.geometryConstructionAdmission,false);assert.equal(b.applicationImplementationAllowed,false);assert.equal(auditPublicUiCapabilityBinding().ok,true);assert.equal(requestsP05F25({sourceId:G4B_U02_P05F25_SOURCE_ID,selectionMode:"sourceUnit"}),false);assert.equal(requestsP05F25({sourceId:G4B_U02_P05F25_SOURCE_ID,selectionMode:"mixedKnowledgePointsSameUnit",selectedKnowledgePointIds:[G4B_U02_P05F25_KP_ID]}),false);});

for(const spec of G4B_U02_P05F25_PATTERN_SPECS)test(`Q025 ${spec.patternSpecId} proves 240 deterministic validated diagram variants`,()=>{const seed=`q025-${spec.patternSpecId}`,a=generateG4BU02P05F25Questions({patternSpecIds:[spec.patternSpecId],questionCount:240,generationSeed:seed}),b=generateG4BU02P05F25Questions({patternSpecIds:[spec.patternSpecId],questionCount:240,generationSeed:seed});assert.equal(a.ok,true,a.errors.join(","));assert.equal(a.questions.length,240);assert.equal(new Set(a.questions.map(q=>q.questionSignature)).size,240);assert.equal(new Set(a.questions.map(q=>`${q.geometryDiagram.orientationDeg}|${q.geometryDiagram.line1HalfLength}|${q.geometryDiagram.line2HalfLength}`)).size,240);assert.deepEqual(a.questions.map(q=>q.questionSignature),b.questions.map(q=>q.questionSignature));assert.ok(a.questions.every(q=>validateG4BU02P05F25Question(q).ok));assert.deepEqual([...new Set(a.questions.map(q=>q.geometryDiagram.orientationDeg))].sort((x,y)=>x-y),Array.from({length:12},(_,i)=>i*15));assert.ok(a.questions.every(q=>q.geometryDiagram.intersectionAngleDeg===90&&q.geometryDiagram.relationship==="PERPENDICULAR"&&q.geometryDiagram.segmentLengthInvariant===true));});

test("Q025 validator fails closed on angle, relation, answer, sibling-scope, and application tampering",()=>{const q=generateG4BU02P05F25Questions({patternSpecIds:[G4B_U02_P05F25_SPEC_IDS[0]],questionCount:1,generationSeed:"q025-tamper"}).questions[0];assert.equal(validateG4BU02P05F25Question({...q,answerText:"平行"}).ok,false);assert.equal(validateG4BU02P05F25Question({...q,geometryDiagram:{...q.geometryDiagram,intersectionAngleDeg:89}}).ok,false);assert.equal(validateG4BU02P05F25Question({...q,geometryDiagram:{...q.geometryDiagram,relationship:"PARALLEL"}}).ok,false);assert.equal(validateG4BU02P05F25Question({...q,knowledgePointId:"kp_g4b_u02_parallel_lines_recognition"}).ok,false);assert.equal(validateG4BU02P05F25Question({...q,metadata:{...q.metadata,parallelLineConstructionTouched:true}}).ok,false);assert.equal(validateG4BU02P05F25Question({...q,metadata:{...q.metadata,applicationContextUsed:true}}).ok,false);});

test("Q025 renderer rejects malformed perpendicular diagrams and renders full intersecting-line model",()=>{const q=generateG4BU02P05F25Questions({questionCount:1,generationSeed:"q025-renderer"}).questions[0];const html=renderPerpendicularLinesRecognitionDiagram(q.geometryDiagram);assert.match(html,/data-representation="perpendicular-lines-recognition-diagram"/);assert.match(html,/data-relationship="perpendicular"/);assert.throws(()=>renderPerpendicularLinesRecognitionDiagram({...q.geometryDiagram,intersectionAngleDeg:91}),error=>error?.code==="perpendicular_lines_recognition_diagram_invalid");});

test("Q025 browser generator, stable worksheet entry, and perpendicular renderer are bounded end-to-end",()=>{const options={sourceId:G4B_U02_P05F25_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G4B_U02_P05F25_KP_ID],questionCount:24,generationSeed:"q025-e2e",includeAnswerKey:true,printLayout:{columns:2,rowsPerPage:4,showAnswerKeyPage:true}};assert.equal(requestsP05F25(options),true);const plan=buildBatchABrowserPlan(options);assert.equal(plan.genericFallback,false);assert.equal(plan.questionCountMax,240);assert.deepEqual(plan.selectedKnowledgePointIds,[G4B_U02_P05F25_KP_ID]);const generated=generateBatchABrowserQuestions(options);assert.equal(generated.ok,true,generated.errors.join(","));assert.equal(generated.questions.length,24);assert.equal(new Set(generated.questions.map(q=>q.questionSignature)).size,24);const worksheet=buildBatchABrowserWorksheetDocument(options);assert.equal(worksheet.ok,true,worksheet.errors.join(","));assert.equal(worksheet.worksheetDocument.questionCount,24);assert.equal(worksheet.worksheetDocument.answerKeyItems.length,24);assert.equal(worksheet.worksheetDocument.metadata.parallelLinesRecognitionTargetTouched,false);assert.equal(worksheet.worksheetDocument.metadata.q026OrLaterTouched,false);const stable=buildStableWorksheet(options);assert.equal(stable.ok,true,stable.errors.join(","));assert.equal(stable.p05f25Implemented,true);const html=renderWorksheetDocumentToHtml(stable.worksheetDocument,{stylesheetHref:null,title:stable.worksheetDocument.title});assert.match(html,/data-representation="perpendicular-lines-recognition-diagram"/);assert.match(html,/垂直線辨識/);assert.match(html,/worksheet-cell--answer-key/);});
