import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {materializeP05EW5DirectProductVerticalSliceQueue} from "../../src/curriculum/full-product/p05e-w5-direct-product-vertical-slice-queue.mjs";
import {materializeR04SharedRuntimeCapabilityMatrix} from "../../src/curriculum/global/r04-shared-runtime-capability-matrix.mjs";
import {materializeR05DeliveryWaveRebase} from "../../src/curriculum/global/r05-delivery-wave-rebase.mjs";
const read=p=>JSON.parse(readFileSync(new URL(`../../${p}`,import.meta.url),"utf8"));
const preflight=read("data/curriculum/full-product/p05f/q058-g5b-u01-volume-unknown-dimension-source-authority-preflight.json");
const q019=read("data/curriculum/full-product/p05f/q019-g5b-u01-volume-unit-conversion-source-authority-preflight.json");
const q047=read("data/curriculum/full-product/p05f/q047-g5b-u01-rectangular-prism-volume-formula-source-authority-preflight.json");
const q052=read("data/curriculum/full-product/p05f/q052-g5b-u01-composite-cube-volume-source-authority-preflight.json");
const r02=read("data/curriculum/global/candidates/r02/chunks/reviewed-source-candidates-03.json");
const KP="kp_g5b_u01_volume_unknown_dimension";
const CAPS=["cap_geometry_diagram_representation","cap_geometry_domain_validator","cap_geometry_formula_evaluation","cap_geometry_property_reasoning"];
const sorted=v=>[...v].sort();

test("Q058 binds exact frozen row and Q057 D0 predecessor",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),row=q.queueEntries.find(x=>x.queuePosition===58);assert.equal(q.queueFrozen,true);assert.equal(q.queueRegistryParity,true);assert.equal(q.derivedRegistrySnapshot.queueDigest,"a4dae65a1a907ba963a135fce84ba292b8486a12513ae8f1fa54fbf07a6598ae");assert.ok(row);assert.equal(row.sliceId,"p05e_q058_r6_g5b_u01_5b01_profile_geometry_formula_c1");assert.equal(row.implementationTaskId,"P05F_W5DirectProductVerticalSlice058Implementation");assert.equal(row.previousSliceId,"p05e_q057_r6_g5a_u09_5a09_profile_geometry_formula_c1");assert.equal(row.primarySourceNodeId,"g5b_u01_5b01");assert.deepEqual(row.supportingSourceNodeIds,["g5b_u01_5b01"]);assert.equal(row.intraWavePrerequisiteRank,6);assert.equal(row.primaryRuntimeProfileId,"profile_geometry_formula");assert.equal(row.knowledgePointCount,1);assert.deepEqual(row.knowledgePointIds,[KP]);assert.deepEqual(sorted(row.requiredW5CapabilityIds),sorted(CAPS));assert.equal(row.targetEvidenceLevel,"E6_D0_COMPLETE");const p=preflight.previousSliceD0Evidence;assert.equal(p.preflightPrNumber,957);assert.equal(p.productPrNumber,958);assert.equal(p.productHeadSha,"3be036fe5917dbfed47018f4c4c9c59ac44703d0");assert.equal(p.productMergeSha,"7341f4da7a5ddbf2661da43cad17eeaf802bfa42");assert.equal(p.prGateRunId,"35070916243");assert.equal(p.pagesDeploymentRunId,"35071082089");assert.equal(p.exactPagesRunId,"35071082137");assert.equal(p.evidenceArtifactId,"10436247515");assert.equal(p.evidenceArtifactDigest,"sha256:250d26ca8b28308210bdb8797ecc296f344810ded8cb2046a9409cb2d4671bbf");assert.equal(p.status,"PASS_E6_D0_COMPLETE");assert.equal(p.exactPagesEvidenceBoundToProductMergeSha,true);});

test("Q058 reuses verified G5B-U01 source identity from Q019 Q047 and Q052",()=>{const s=preflight.sourceAuthority;assert.equal(s.sourceNodeId,"g5b_u01_5b01");assert.equal(s.sourceTitle,"長方體和正方體的體積");assert.equal(s.sourcePdfTitle,"meow911_5b01_source.pdf");assert.equal(s.sourcePdfDriveFileId,"1IYHtSOWSxqbjcyEi94rmMEyqtOflGQ2f");assert.equal(q019.sourceAuthority.sourcePdfDriveFileId,s.sourcePdfDriveFileId);assert.equal(q047.sourceAuthority.sourcePdfDriveFileId,s.sourcePdfDriveFileId);assert.equal(q052.sourceAuthority.sourcePdfDriveFileId,s.sourcePdfDriveFileId);assert.deepEqual(s.targetEvidencePages,[1,2]);assert.equal(s.targetEvidenceReconciliation.volumeUnknownDimension.sameSourceIdentityAlreadyCorroboratedByQ019Q047Q052,true);assert.equal(s.ocrUsedAsAuthority,false);assert.equal(s.r02AuthorityModified,false);assert.equal(s.sourceRefAmbiguity,false);assert.equal(s.manualSourceChoiceRequired,false);});

test("Q058 locks exact R02 volume-unknown-dimension candidate on pages 1 and 2",()=>{const source=r02.sourceRecords.find(x=>x.sourceNodeId==="g5b_u01_5b01"),c=source?.candidates.find(x=>x.knowledgePointId===KP);assert.ok(c);assert.deepEqual(c,{knowledgePointId:KP,canonicalNameZh:"體積反求尺寸",capabilityStatement:"學生能由體積與兩個尺寸反求未知長、寬或高。",reasoningInvariant:"未知尺寸乘其餘兩尺寸必須重建原體積。",category:"geometry",evidencePages:[1,2],applicationSuitability:"APPLICATION_COMPATIBLE"});assert.deepEqual(preflight.r02ReviewedCandidateAuthority.knowledgePoint,c);assert.deepEqual(preflight.r02ReviewedCandidateAuthority.sameSourceCandidateIds,source.candidates.map(x=>x.knowledgePointId));});

test("Q058 binds current R04 geometry-formula mapping and exact R05 closure",()=>{const r04=materializeR04SharedRuntimeCapabilityMatrix(),m=r04.getMapping(KP),bound=preflight.runtimeCapabilityAuthority.mapping;assert.ok(m);assert.equal(m.mappingId,"r04map_g5b_u01_volume_unknown_dimension");assert.equal(m.primaryRuntimeProfileId,"profile_geometry_formula");assert.equal(m.classificationRuleId,"rule_geometry_formula");assert.deepEqual(m.appliedModifierIds,[]);assert.deepEqual(m.requiredRuntimeCapabilityIds,bound.requiredRuntimeCapabilityIds);assert.deepEqual(m.optionalRuntimeCapabilityIds,[]);assert.deepEqual(m.forbiddenRuntimeCapabilityIds,[]);const a=materializeR05DeliveryWaveRebase().getAssignment(KP);assert.ok(a);assert.equal(a.deliveryWaveId,"R05-W5");assert.equal(a.intraWavePrerequisiteRank,6);assert.equal(a.primaryRuntimeProfileId,"profile_geometry_formula");assert.deepEqual(sorted(a.contractOnlyRequiredCapabilityIds),sorted(CAPS));assert.deepEqual(sorted(preflight.runtimeCapabilityAuthority.exactFrozenQueueRequiredW5CapabilityIds),sorted(CAPS));});

test("Q058 owns volume inverse dimension only and protects all prior G5B-U01 ownership",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),owners={kp_g5b_u01_volume_unit_conversion:19,kp_g5b_u01_rectangular_prism_volume_formula:47,kp_g5b_u01_cube_volume_formula:52,kp_g5b_u01_composite_rectangular_volume:52};for(const[kp,pos]of Object.entries(owners)){const row=q.queueEntries.find(x=>x.knowledgePointIds.includes(kp));assert.equal(row?.queuePosition,pos,kp);}assert.deepEqual(preflight.q058ScopeLock.includedKnowledgePointIds,[KP]);assert.equal(preflight.q058ScopeLock.protectedExistingSameSourceKnowledgePointOwnership.kp_g5b_u01_volume_unit_conversion,"Q019");assert.equal(preflight.q058ScopeLock.protectedExistingSameSourceKnowledgePointOwnership.kp_g5b_u01_rectangular_prism_volume_formula,"Q047");assert.equal(preflight.q058ScopeLock.protectedExistingSameSourceKnowledgePointOwnership.kp_g5b_u01_cube_volume_formula,"Q052");assert.equal(preflight.q058ScopeLock.protectedExistingSameSourceKnowledgePointOwnership.kp_g5b_u01_composite_rectangular_volume,"Q052");assert.equal(preflight.q058ScopeLock.rectangularPrismVolumeFormulaMayBeUsedAsPrerequisiteButNotReowned,true);assert.equal(preflight.q058ScopeLock.unknownDimensionMustReconstructOriginalVolumeWhenSubstitutedBack,true);});

test("Q058 excludes prior ownership surface area application mixed modes and Q059+",()=>{for(const r of ["REOWN_VOLUME_UNIT_CONVERSION","REOWN_RECTANGULAR_PRISM_VOLUME_FORMULA","REOWN_CUBE_VOLUME_FORMULA","REOWN_COMPOSITE_RECTANGULAR_VOLUME","SURFACE_AREA_FORMULA_OR_ARITHMETIC","APPLICATION_CONTEXT_IMPLEMENTATION","SAME_UNIT_MIXED_MODE","CROSS_UNIT_MIXED_MODE","Q059_OR_LATER_SEMANTICS"])assert.ok(preflight.q058ScopeLock.excludedRelations.includes(r),r);for(const k of ["applicationImplementationAllowedByThisPreflight","implementationAllowedByThisPreflight","publicProductAdmissionAllowedByThisPreflight","sameUnitMixedTouched","crossUnitMixedTouched","frozenQueueAuthorityTouched","r02AuthorityTouched","r04AuthorityTouched","r05AuthorityTouched","q059OrLaterTouched"])assert.equal(preflight.q058ScopeLock[k],false,k);});

test("Q058 preflight stays bounded and stops at implementation approval boundary",()=>{const b=preflight.preflightValidationBoundary;assert.equal(b.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(b.derivedLane,"SHARED_RUNTIME_BOUNDED");assert.deepEqual(b.allowedLaneGateIds,["GLOBAL_CONTRACTS","TARGETED_ROUTE_REPLAY"]);assert.equal(b.focusedNodeContractRequired,true);assert.equal(b.nodeOnlyReadbackRequired,true);assert.equal(b.fullRepositoryRegressionAllowed,false);assert.equal(b.globalBrowserReplayAllowed,false);assert.equal(b.productImplementationAllowed,false);assert.equal(b.publicProductAdmissionAllowed,false);const d=preflight.preflightDecision;assert.equal(d.exactFrozenQueueRowResolved,true);assert.equal(d.sourceAuthoritySufficientForQ058ImplementationPlanning,true);assert.equal(d.previousSliceD0Satisfied,true);assert.equal(d.r02AuthorityBoundForTargetKnowledgePoint,true);assert.equal(d.runtimeCapabilityContractLocked,true);assert.equal(d.sameSourcePriorSliceOwnershipProtected,true);assert.equal(d.allSameSourceCandidateOwnershipResolvedThroughQ058,true);assert.equal(d.q019Q047Q052SameSourceIdentityReusedWithoutReclassification,true);assert.equal(d.manualSourceChoiceRequired,false);assert.equal(d.sourceRefAmbiguity,false);assert.equal(d.separateImplementationApprovalSatisfiedByCurrentOperatorInstruction,false);assert.equal(d.nextTaskRequiresNewOperatorApproval,true);assert.equal(d.nextTask,"P05F_W5DirectProductVerticalSlice058Implementation");});
