import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {materializeP05EW5DirectProductVerticalSliceQueue} from "../../src/curriculum/full-product/p05e-w5-direct-product-vertical-slice-queue.mjs";
import {materializeR04SharedRuntimeCapabilityMatrix} from "../../src/curriculum/global/r04-shared-runtime-capability-matrix.mjs";
import {materializeR05DeliveryWaveRebase} from "../../src/curriculum/global/r05-delivery-wave-rebase.mjs";
const read=p=>JSON.parse(readFileSync(new URL(`../../${p}`,import.meta.url),"utf8"));
const preflight=read("data/curriculum/full-product/p05f/q059-g5b-u07-surface-area-unknown-dimension-source-authority-preflight.json");
const q040=read("data/curriculum/full-product/p05f/q040-g5b-u07-surface-area-from-net-source-authority-preflight.json");
const q048=read("data/curriculum/full-product/p05f/q048-g5b-u07-cube-cuboid-surface-area-source-authority-preflight.json");
const q054=read("data/curriculum/full-product/p05f/q054-g5b-u07-composite-surface-area-hidden-faces-source-authority-preflight.json");
const r02=read("data/curriculum/global/candidates/r02/chunks/reviewed-source-candidates-05.json");
const KP="kp_g5b_u07_surface_area_unknown_dimension";
const CAPS=["cap_geometry_diagram_representation","cap_geometry_domain_validator","cap_geometry_formula_evaluation","cap_geometry_property_reasoning"];
const sorted=v=>[...v].sort();

test("Q059 binds exact frozen row and Q058 D0 predecessor",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),row=q.queueEntries.find(x=>x.queuePosition===59);assert.equal(q.queueFrozen,true);assert.equal(q.queueRegistryParity,true);assert.equal(q.derivedRegistrySnapshot.queueDigest,"a4dae65a1a907ba963a135fce84ba292b8486a12513ae8f1fa54fbf07a6598ae");assert.ok(row);assert.equal(row.sliceId,"p05e_q059_r6_g5b_u07_5b07_profile_geometry_formula_c1");assert.equal(row.implementationTaskId,"P05F_W5DirectProductVerticalSlice059Implementation");assert.equal(row.previousSliceId,"p05e_q058_r6_g5b_u01_5b01_profile_geometry_formula_c1");assert.equal(row.previousSliceMustBeD0Complete,true);assert.equal(row.assignedDeliveryWaveId,"R05-W5");assert.equal(row.primarySourceNodeId,"g5b_u07_5b07");assert.deepEqual(row.supportingSourceNodeIds,["g5b_u07_5b07"]);assert.equal(row.intraWavePrerequisiteRank,6);assert.equal(row.primaryRuntimeProfileId,"profile_geometry_formula");assert.equal(row.chunkIndex,1);assert.equal(row.knowledgePointCount,1);assert.deepEqual(row.knowledgePointIds,[KP]);assert.deepEqual(sorted(row.requiredW5CapabilityIds),sorted(CAPS));assert.equal(row.targetEvidenceLevel,"E6_D0_COMPLETE");const p=preflight.previousSliceD0Evidence;assert.equal(p.preflightPrNumber,959);assert.equal(p.productPrNumber,960);assert.equal(p.productHeadSha,"8b3cf9328c87716d40d8b05a235beac31c98ed71");assert.equal(p.productMergeSha,"59d772faa62bbab1d41f5fbc2782c7ba2bc7352e");assert.equal(p.prGateRunId,"35076041227");assert.equal(p.pagesDeploymentRunId,"35076202342");assert.equal(p.exactPagesRunId,"35076202463");assert.equal(p.evidenceArtifactId,"10437778139");assert.equal(p.evidenceArtifactDigest,"sha256:015569d0157c4234f47430b2c5f3cec3d56fedd8b0c6826b2e6101986600dbbd");assert.equal(p.status,"PASS_E6_D0_COMPLETE");assert.equal(p.exactPagesEvidenceBoundToProductMergeSha,true);});

test("Q059 reuses verified G5B-U07 source identity from Q040 Q048 Q054",()=>{const s=preflight.sourceAuthority;assert.equal(s.sourceNodeId,"g5b_u07_5b07");assert.equal(s.sourceTitle,"表面積");assert.equal(s.sourcePdfTitle,"meow911_5b07_source.pdf");assert.equal(s.sourcePdfDriveFileId,"19zLc-rrV6lauqhpxr6undOHHpcg__RKz");assert.equal(s.sourceMetadataDriveFileId,"1UHzU1OMhmO38Z-baRZl8wjWocGv5fOfa");assert.equal(s.verificationNotesDriveFileId,"1oMN8VzmrIhbmfeVUIJqWvc8RjVJYpzbL");assert.equal(s.sourceUrl,"https://meow911.com/5b07/");assert.equal(q040.sourceAuthority.sourcePdfDriveFileId,s.sourcePdfDriveFileId);assert.equal(q048.sourceAuthority.sourcePdfDriveFileId,s.sourcePdfDriveFileId);assert.equal(q054.sourceAuthority.sourcePdfDriveFileId,s.sourcePdfDriveFileId);assert.deepEqual(s.reviewedPages,[1,2]);assert.deepEqual(s.targetEvidencePages,[1,2]);assert.equal(s.targetEvidenceReconciliation.surfaceAreaUnknownDimension.samePdfIdentityAlreadyCorroboratedByQ040Q048Q054,true);assert.equal(s.ocrUsedAsAuthority,false);assert.equal(s.r02AuthorityModified,false);assert.equal(s.sourceRefAmbiguity,false);assert.equal(s.manualSourceChoiceRequired,false);});

test("Q059 locks exact R02 surface-area unknown-dimension candidate",()=>{const source=r02.sourceRecords.find(x=>x.sourceNodeId==="g5b_u07_5b07"),c=source?.candidates.find(x=>x.knowledgePointId===KP);assert.ok(c);assert.deepEqual(c,{knowledgePointId:KP,canonicalNameZh:"表面積反求尺寸",capabilityStatement:"學生能由表面積與部分尺寸反求未知邊長。",reasoningInvariant:"未知尺寸代回各面面積總和必須重建表面積。",category:"geometry",evidencePages:[1,2],applicationSuitability:"APPLICATION_COMPATIBLE"});assert.deepEqual(preflight.r02ReviewedCandidateAuthority.knowledgePoint,c);assert.deepEqual(preflight.r02ReviewedCandidateAuthority.sameSourceCandidateIds,source.candidates.map(x=>x.knowledgePointId));});

test("Q059 binds current R04 geometry-formula mapping and exact R05 closure",()=>{const r04=materializeR04SharedRuntimeCapabilityMatrix(),m=r04.getMapping(KP),bound=preflight.runtimeCapabilityAuthority.mapping;assert.ok(m);assert.equal(m.mappingId,"r04map_g5b_u07_surface_area_unknown_dimension");assert.equal(m.primaryRuntimeProfileId,"profile_geometry_formula");assert.equal(m.classificationRuleId,"rule_geometry_formula");assert.deepEqual(m.appliedModifierIds,[]);assert.deepEqual(m.requiredRuntimeCapabilityIds,bound.requiredRuntimeCapabilityIds);assert.deepEqual(m.optionalRuntimeCapabilityIds,[]);assert.deepEqual(m.forbiddenRuntimeCapabilityIds,[]);const a=materializeR05DeliveryWaveRebase().getAssignment(KP);assert.ok(a);assert.equal(a.deliveryWaveId,"R05-W5");assert.equal(a.intraWavePrerequisiteRank,6);assert.equal(a.primaryRuntimeProfileId,"profile_geometry_formula");assert.deepEqual(sorted(a.contractOnlyRequiredCapabilityIds),sorted(CAPS));assert.deepEqual(sorted(preflight.runtimeCapabilityAuthority.exactFrozenQueueRequiredW5CapabilityIds),sorted(CAPS));assert.equal(preflight.runtimeCapabilityAuthority.mappingPolicyModifierMatchCount,0);});

test("Q059 owns inverse surface-area dimension only and protects Q040 Q048 Q054",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),owners={kp_g5b_u07_surface_area_from_net:40,kp_g5b_u07_cube_surface_area:48,kp_g5b_u07_cuboid_surface_area:48,kp_g5b_u07_composite_surface_area_hidden_faces:54};assert.deepEqual(preflight.q059ScopeLock.includedKnowledgePointIds,[KP]);for(const[kp,pos]of Object.entries(owners)){const row=q.queueEntries.find(x=>x.knowledgePointIds.includes(kp));assert.equal(row?.queuePosition,pos,kp);assert.equal(preflight.q059ScopeLock.protectedExistingSameSourceKnowledgePointOwnership[kp],`Q${String(pos).padStart(3,"0")}`);}assert.equal(preflight.q059ScopeLock.priorSameSourceSurfaceAreaFormulasMayBeUsedAsPrerequisitesNotReowned,true);assert.equal(preflight.q059ScopeLock.unknownDimensionMustReconstructOriginalSurfaceAreaWhenSubstitutedBack,true);});

test("Q059 excludes prior reownership application mixed modes and Q060+",()=>{for(const r of ["REOWN_SURFACE_AREA_FROM_NET","REOWN_CUBE_SURFACE_AREA","REOWN_CUBOID_SURFACE_AREA","REOWN_COMPOSITE_SURFACE_AREA_HIDDEN_FACES","APPLICATION_CONTEXT_IMPLEMENTATION","SAME_UNIT_MIXED_MODE","CROSS_UNIT_MIXED_MODE","Q060_OR_LATER_SEMANTICS"])assert.ok(preflight.q059ScopeLock.excludedRelations.includes(r),r);for(const k of ["applicationImplementationAllowedByThisPreflight","implementationAllowedByThisPreflight","publicProductAdmissionAllowedByThisPreflight","sameSourceSiblingSemanticsTouched","sameUnitMixedTouched","crossUnitMixedTouched","frozenQueueAuthorityTouched","r02AuthorityTouched","r04AuthorityTouched","r05AuthorityTouched","q060OrLaterTouched"])assert.equal(preflight.q059ScopeLock[k],false,k);});

test("Q059 preflight stays bounded and stops at implementation approval boundary",()=>{const b=preflight.preflightValidationBoundary;assert.equal(b.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(b.derivedLane,"SHARED_RUNTIME_BOUNDED");assert.deepEqual(b.allowedLaneGateIds,["GLOBAL_CONTRACTS","TARGETED_ROUTE_REPLAY"]);assert.equal(b.focusedNodeContractRequired,true);assert.equal(b.nodeOnlyReadbackRequired,true);assert.equal(b.fullRepositoryRegressionAllowed,false);assert.equal(b.globalBrowserReplayAllowed,false);assert.equal(b.productImplementationAllowed,false);assert.equal(b.publicProductAdmissionAllowed,false);const d=preflight.preflightDecision;assert.equal(d.exactFrozenQueueRowResolved,true);assert.equal(d.sourceAuthoritySufficientForQ059ImplementationPlanning,true);assert.equal(d.previousSliceD0Satisfied,true);assert.equal(d.r02AuthorityBoundForTargetKnowledgePoint,true);assert.equal(d.runtimeCapabilityContractLocked,true);assert.equal(d.sameSourcePriorSliceOwnershipProtected,true);assert.equal(d.q040Q048Q054SameSourceIdentityReusedWithoutReclassification,true);assert.equal(d.manualSourceChoiceRequired,false);assert.equal(d.sourceRefAmbiguity,false);assert.equal(d.separateImplementationApprovalSatisfiedByCurrentOperatorInstruction,false);assert.equal(d.nextTaskRequiresNewOperatorApproval,true);assert.equal(d.nextTask,"P05F_W5DirectProductVerticalSlice059Implementation");});
