import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {buildBatchABrowserWorksheetDocument as buildQ050Worksheet} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f50-extension.js";
import {buildBatchABrowserWorksheetDocument as buildCurrentWorksheet} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f32-extension.js";
import {requestsP05F50} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p05f50.js";
import {generateG4BU07P05F50Questions,validateG4BU07P05F50Question} from "../../site/modules/curriculum/batch-a/g4b-u07-composite-perimeter-runtime-p05f50.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";
import {auditG4BU07P05F50Projection,G4B_U07_P05F50_FORMAL_MAPPING as MAP,G4B_U07_P05F50_KP_ID as KP,G4B_U07_P05F50_PATTERN_GROUP_ID as GROUP,G4B_U07_P05F50_PRIOR_VISIBLE_KP_IDS as PRIOR,G4B_U07_P05F50_SOURCE_ID as SRC,G4B_U07_P05F50_SPEC_IDS as SPECS} from "../../site/modules/curriculum/registry/g4b-u07-composite-perimeter-selector-projection-p05f50.js";
import {auditP05F50PublicSelectorComposition,getVisibleBatchAKnowledgePoint,listBatchAKnowledgePointAvailabilityBySource,resolveVisiblePatternSpecIdsForKnowledgePoint} from "../../site/modules/curriculum/registry/batch-a-selector-p05f50-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p05f50.js";
const preflight=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q050-g4b-u07-composite-perimeter-source-authority-preflight.json",import.meta.url),"utf8"));
const implementation=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q050-g4b-u07-composite-perimeter-implementation.json",import.meta.url),"utf8"));
const impact=JSON.parse(readFileSync(new URL("../../data/project/change-impact/P05F_W5_Q050.impact.json",import.meta.url),"utf8"));
const plan=JSON.parse(readFileSync(new URL("../../data/project/validation-plans/P05F_W5_Q050.validation.json",import.meta.url),"utf8"));
const opts=(count=24)=>({sourceId:SRC,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[KP],selectedPatternGroupIds:[GROUP],patternSpecIds:[...SPECS],questionMode:"diagram",requestedQuestionType:"diagram",questionCount:count,generationSeed:"p05f50-focused-composite-perimeter",includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showQuestionNumbers:true,showAnswerKeyPage:true}});
const occurrences=(text,token)=>text.split(token).length-1;

test("Q050 exact frozen identity and source authority stay locked",()=>{assert.equal(preflight.status,"PASS_SOURCE_AUTHORITY_PREFLIGHT");assert.equal(preflight.queueAuthority.queuePosition,50);assert.deepEqual(preflight.queueAuthority.knowledgePointIds,[KP]);assert.equal(preflight.previousSliceD0Evidence.status,"PASS_E6_D0_COMPLETE");assert.equal(implementation.taskId,"P05F_W5DirectProductVerticalSlice050Implementation");assert.equal(implementation.queueAuthority.sliceId,"p05e_q050_r5_g4b_u07_4b07_profile_geometry_formula_c1");assert.equal(implementation.queueAuthority.runtimeProfileId,"profile_geometry_formula");for(const value of Object.values(implementation.scopeGuard))assert.equal(value,false);});

test("Q050 materializes one mapping, one group and four exact relation PatternSpecs",()=>{const a=auditG4BU07P05F50Projection();assert.equal(a.ok,true,a.errors.join("\n"));assert.deepEqual(a.counts,{knowledgePoints:1,patternGroups:1,patternSpecs:4,formalMappings:1});assert.deepEqual(MAP.sourcePages,[1]);assert.deepEqual(MAP.includedRelations,preflight.q050ScopeLock.includedRelations);assert.deepEqual(MAP.prerequisiteSemanticsReusedNotReowned,["kp_g4b_u07_perimeter_path_sum","kp_g4b_u07_rectangle_square_perimeter_formula"]);});

test("Q050 promotes the final G4B-U07 knowledge point while preserving four prior owners",()=>{const a=auditP05F50PublicSelectorComposition();assert.equal(a.ok,true,a.errors.join("\n"));const s=listBatchAKnowledgePointAvailabilityBySource(SRC);assert.equal(s.visibleCount,5);assert.equal(s.hiddenPendingCount,0);assert.equal(s.notSelectableCount,0);assert.ok(getVisibleBatchAKnowledgePoint(KP));assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(KP,"diagram"),SPECS);for(const id of PRIOR)assert.ok(getVisibleBatchAKnowledgePoint(id),id);});

test("Q050 public binding is single-KP diagram only and mixed/source-unit requests fail closed",()=>{const a=auditPublicUiCapabilityBinding();assert.equal(a.ok,true,a.errors.join("\n"));const b=resolvePublicUiCapabilityBinding(opts());assert.equal(b.blocked,false);assert.equal(b.questionType,"diagram");assert.equal(b.questionCount.max,240);assert.equal(b.frozenRuntimeProfile,"profile_geometry_formula");assert.equal(b.sourceBackedCompositePerimeter,true);assert.equal(b.perimeterPathSumReowned,false);assert.equal(b.rectangleSquarePerimeterFormulaReowned,false);assert.equal(requestsP05F50(opts()),true);assert.equal(requestsP05F50({...opts(),selectionMode:"sourceUnit"}),false);assert.equal(requestsP05F50({...opts(),selectedKnowledgePointIds:[KP,PRIOR[0]]}),false);});

test("Q050 generates 240 deterministic visible variants per PatternSpec and enforces outer-boundary semantics",()=>{for(const patternSpecId of SPECS){const a=generateG4BU07P05F50Questions({knowledgePointId:KP,patternSpecIds:[patternSpecId],questionCount:240,generationSeed:`capacity-${patternSpecId}`}),b=generateG4BU07P05F50Questions({knowledgePointId:KP,patternSpecIds:[patternSpecId],questionCount:240,generationSeed:`capacity-${patternSpecId}`});assert.equal(a.ok,true,`${patternSpecId}:${a.errors.join("\n")}`);assert.deepEqual(a.questions,b.questions);assert.equal(new Set(a.questions.map(q=>q.questionSignature)).size,240);assert.equal(new Set(a.questions.map(q=>[q.geometryDiagram.outerWidthCm,q.geometryDiagram.outerHeightCm,q.geometryDiagram.notchWidthCm,q.geometryDiagram.notchHeightCm].join("|"))).size,240);for(const q of a.questions){assert.equal(validateG4BU07P05F50Question(q).ok,true);const d=q.geometryDiagram;assert.equal(d.perimeterCm,2*(d.outerWidthCm+d.outerHeightCm));assert.equal(d.outerBoundarySegmentLengthsCm.reduce((x,y)=>x+y,0),d.perimeterCm);assert.equal(d.componentPerimeterSumCm-2*d.sharedInteriorEdgeCm,d.perimeterCm);assert.equal(d.sharedInteriorExcluded,true);}}});

test("Q050 validator fails closed on boundary, shared-edge, missing-length and provenance tampering",()=>{const q=generateG4BU07P05F50Questions({...opts(1),patternSpecIds:[SPECS[2]]}).questions[0];for(const mutate of [x=>x.answerValue+=1,x=>x.geometryDiagram.perimeterCm+=1,x=>x.geometryDiagram.sharedInteriorEdgeCm+=1,x=>x.geometryDiagram.topRunCm+=1,x=>x.metadata.perimeterPathSumPrerequisiteReusedNotReowned=false]){const t=JSON.parse(JSON.stringify(q));mutate(t);assert.equal(validateG4BU07P05F50Question(t).ok,false);}});

test("Q050 worksheet and shared renderer show L-shape questions and answers without internal ids",()=>{const r=buildQ050Worksheet(opts(16));assert.equal(r.ok,true,r.errors.join("\n"));assert.equal(r.worksheetDocument.questionCount,16);assert.equal(r.worksheetDocument.answerKeyItems.length,16);const html=renderWorksheetDocumentToHtml(r.worksheetDocument,{stylesheetHref:"",title:r.worksheetDocument.title,debugDataAttributes:false});assert.equal(occurrences(html,'data-representation="composite-perimeter-diagram"'),32);assert.equal(html.includes("kp_g4b_u07_"),false);assert.equal(html.includes("ps_g4b_u07_"),false);assert.ok(html.includes("共用內部邊")||html.includes("未標示"));});

test("Q050 current top-slot selector, binding and worksheet bridges reach the target without breaking prior G4B-U07 owners",async()=>{const r=buildCurrentWorksheet(opts(8));assert.equal(r.ok,true,r.errors.join("\n"));assert.equal(r.p05f50Implemented,true);assert.equal(r.worksheetDocument.metadata.knowledgePointId,KP);globalThis.document={};try{const selector=await import(`../../site/modules/curriculum/registry/batch-a-selector-p04f33-extension.js?p05f50=${Date.now()}`),binding=await import(`../../site/modules/curriculum/public/public-ui-capability-binding-p04f33.js?p05f50=${Date.now()}`);assert.equal(selector.getVisibleBatchAKnowledgePoint(KP)?.sourceId,SRC);assert.equal(binding.resolvePublicUiCapabilityBinding(opts()).sourceBackedCompositePerimeter,true);for(const id of PRIOR)assert.ok(selector.getVisibleBatchAKnowledgePoint(id),id);}finally{delete globalThis.document;}});

test("Q050 validation policy remains SHARED_RUNTIME_BOUNDED",()=>{assert.equal(impact.expectedDerivedGate,"SHARED_RUNTIME_BOUNDED");assert.equal(impact.changeImpact.affectedRoutes,"BOUNDED");assert.equal(impact.changeImpact.legalRouteSemanticsChanged,false);assert.equal(plan.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(plan.lanes.SHARED_RUNTIME_BOUNDED[0].kind,"NODE_TEST");assert.equal(plan.lanes.SHARED_RUNTIME_BOUNDED[1].runtime,"PLAYWRIGHT_CHROMIUM");assert.equal(implementation.validation.fullRepositoryRegression,"FORBIDDEN");assert.equal(implementation.validation.globalBrowserReplay,"FORBIDDEN");});
