import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {buildBatchABrowserWorksheetDocument as buildQ045Worksheet} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f45-extension.js";
import {buildBatchABrowserWorksheetDocument as buildCurrentTopSlotWorksheet} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f32-extension.js";
import {generateG5AU07P05F45Questions,validateG5AU07P05F45Question} from "../../site/modules/curriculum/batch-a/g5a-u07-complete-symmetric-figure-runtime-p05f45.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";
import {auditG5AU07P05F45Projection,G5A_U07_P05F45_FORMAL_MAPPING,G5A_U07_P05F45_KP_ID,G5A_U07_P05F45_PATTERN_GROUP_ID,G5A_U07_P05F45_REQUIRED_CAPABILITY_IDS,G5A_U07_P05F45_SOURCE_ID,G5A_U07_P05F45_SPEC_IDS} from "../../site/modules/curriculum/registry/g5a-u07-complete-symmetric-figure-selector-projection-p05f45.js";
import {auditP05F45PublicSelectorComposition,getVisibleBatchAKnowledgePoint,listBatchAKnowledgePointAvailabilityBySource,resolveVisiblePatternSpecIdsForKnowledgePoint} from "../../site/modules/curriculum/registry/batch-a-selector-p05f45-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p05f45.js";
const preflight=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q045-g5a-u07-complete-symmetric-figure-source-authority-preflight.json",import.meta.url),"utf8"));
const implementation=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q045-g5a-u07-complete-symmetric-figure-implementation.json",import.meta.url),"utf8"));
const PROTECTED=["kp_g5a_u07_line_symmetry_recognition","kp_g5a_u07_symmetry_axis_count","kp_g5a_u07_symmetric_point_distance"];
const NON_W5=["kp_g5a_u07_coordinate_reflection"];
const opts=(count=24)=>({sourceId:G5A_U07_P05F45_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G5A_U07_P05F45_KP_ID],selectedPatternGroupIds:[G5A_U07_P05F45_PATTERN_GROUP_ID],patternSpecIds:[...G5A_U07_P05F45_SPEC_IDS],questionMode:"diagram",requestedQuestionType:"diagram",questionCount:count,generationSeed:"p05f45-focused-complete-symmetry",includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showQuestionNumbers:true,showAnswerKeyPage:true}});
const occurrences=(text,token)=>text.split(token).length-1;

test("Q045 exact preflight and implementation identities remain frozen",()=>{assert.equal(preflight.status,"PASS_SOURCE_AUTHORITY_PREFLIGHT");assert.equal(preflight.queueAuthority.queuePosition,45);assert.deepEqual(preflight.queueAuthority.knowledgePointIds,[G5A_U07_P05F45_KP_ID]);assert.equal(preflight.previousSliceD0Evidence.status,"PASS_E6_D0_COMPLETE");assert.equal(implementation.taskId,"P05F_W5DirectProductVerticalSlice045Implementation");assert.equal(implementation.queueAuthority.sliceId,"p05e_q045_r4_g5a_u07_5a07_profile_geometry_property_c1");assert.equal(implementation.scopeGuard.q006SemanticsModified,false);assert.equal(implementation.scopeGuard.q016SemanticsModified,false);assert.equal(implementation.scopeGuard.q036SemanticsModified,false);assert.equal(implementation.scopeGuard.q046OrLaterTouched,false);});

test("Q045 materializes one mapping one group and three construction PatternSpecs",()=>{const audit=auditG5AU07P05F45Projection();assert.equal(audit.ok,true,audit.errors.join("\n"));assert.deepEqual(audit.counts,{knowledgePoints:1,patternGroups:1,patternSpecs:3,diagram:3,construction:3,application:0});assert.equal(G5A_U07_P05F45_FORMAL_MAPPING.mappingId,"fm_g5a_u07_complete_symmetric_figure_p05f45");assert.deepEqual(G5A_U07_P05F45_FORMAL_MAPPING.includedRelations,preflight.q045ScopeLock.includedRelations);assert.deepEqual(G5A_U07_P05F45_FORMAL_MAPPING.requiredCapabilityIds,G5A_U07_P05F45_REQUIRED_CAPABILITY_IDS);assert.deepEqual(G5A_U07_P05F45_FORMAL_MAPPING.optionalCapabilityIds,[]);});

test("Q045 selector promotes only completion KP and keeps coordinate reflection non-W5",()=>{const audit=auditP05F45PublicSelectorComposition();assert.equal(audit.ok,true,audit.errors.join("\n"));const source=listBatchAKnowledgePointAvailabilityBySource(G5A_U07_P05F45_SOURCE_ID);assert.equal(source.visibleCount,4);assert.equal(source.hiddenPendingCount,1);assert.equal(source.notSelectableCount,1);for(const id of [...PROTECTED,G5A_U07_P05F45_KP_ID])assert.ok(getVisibleBatchAKnowledgePoint(id),id);for(const id of NON_W5)assert.equal(getVisibleBatchAKnowledgePoint(id),null,id);assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(G5A_U07_P05F45_KP_ID,"diagram"),G5A_U07_P05F45_SPEC_IDS);});

test("Q045 public binding requires geometry construction and only direct single-KP diagram mode",()=>{const audit=auditPublicUiCapabilityBinding();assert.equal(audit.ok,true,audit.errors.join("\n"));const b=resolvePublicUiCapabilityBinding(opts());assert.equal(b.blocked,false);assert.equal(b.questionType,"diagram");assert.equal(b.questionCount.max,240);assert.equal(b.completeSymmetricFigureAdmission,true);assert.equal(b.geometryConstructionRequired,true);assert.equal(b.equalAxisDistanceReflectionRequired,true);assert.deepEqual(b.requiredCapabilityIds,G5A_U07_P05F45_REQUIRED_CAPABILITY_IDS);assert.equal(b.coordinateReflectionAdmission,false);assert.equal(b.sameUnitMixedAdmission,false);assert.equal(b.crossUnitMixedAdmission,false);});

test("Q045 deterministically constructs reflected solution paths without leaking them into question diagrams",()=>{const a=generateG5AU07P05F45Questions(opts(24)),b=generateG5AU07P05F45Questions(opts(24));assert.equal(a.ok,true,a.errors.join("\n"));assert.deepEqual(a.questions,b.questions);assert.equal(a.questions.length,24);assert.equal(new Set(a.questions.map(q=>q.questionSignature)).size,24);for(const q of a.questions){assert.equal(validateG5AU07P05F45Question(q).ok,true);const d=q.geometryDiagram,s=q.answerGeometryDiagram;assert.equal(d.solutionVisible,false);assert.equal(d.reflectedPath.length,0);assert.equal(s.solutionVisible,true);assert.equal(s.reflectedPath.length,s.sourcePath.length);for(let i=0;i<s.sourcePath.length;i++){const p=s.sourcePath[i],r=s.reflectedPath[s.reflectedPath.length-1-i];if(s.axis.orientation==="VERTICAL"){assert.equal(p.y,r.y);assert.equal(120-p.x,r.x-120);}else{assert.equal(p.x,r.x);assert.equal(70-p.y,r.y-70);}}assert.equal(q.metadata.geometryConstructionRequired,true);assert.equal(q.metadata.q006SemanticsReowned,false);assert.equal(q.metadata.q016SemanticsReowned,false);assert.equal(q.metadata.q036SemanticsReowned,false);assert.equal(q.metadata.coordinateReflectionUsed,false);}});

test("Q045 proves 240 distinct variants for every PatternSpec",()=>{for(const patternSpecId of G5A_U07_P05F45_SPEC_IDS){const r=generateG5AU07P05F45Questions({knowledgePointId:G5A_U07_P05F45_KP_ID,questionCount:240,patternSpecIds:[patternSpecId],generationSeed:`capacity-${patternSpecId}`});assert.equal(r.ok,true,`${patternSpecId}:${r.errors.join("\n")}`);assert.equal(r.questions.length,240);assert.equal(new Set(r.questions.map(q=>q.questionSignature)).size,240);}});

test("Q045 validator fails closed on construction geometry answer and provenance tampering",()=>{const q=generateG5AU07P05F45Questions({...opts(1),patternSpecIds:[G5A_U07_P05F45_SPEC_IDS[0]]}).questions[0];for(const mutate of [x=>x.geometryDiagram.sourcePath[1].x+=1,x=>x.answerGeometryDiagram.reflectedPath.pop(),x=>x.answerText="錯誤",x=>x.metadata.coordinateReflectionUsed=true]){const t=JSON.parse(JSON.stringify(q));mutate(t);assert.equal(validateG5AU07P05F45Question(t).ok,false);}});

test("Q045 worksheet renders incomplete question diagrams and completed answer diagrams",()=>{const r=buildQ045Worksheet(opts(18));assert.equal(r.ok,true,r.errors.join("\n"));assert.equal(r.worksheetDocument.questionCount,18);assert.equal(r.worksheetDocument.answerKeyItems.length,18);const html=renderWorksheetDocumentToHtml(r.worksheetDocument,{stylesheetHref:"",title:r.worksheetDocument.title,debugDataAttributes:false});assert.equal(occurrences(html,'data-representation="complete-symmetric-figure-diagram"'),36);assert.equal(occurrences(html,'data-solution-visible="false"'),18);assert.equal(occurrences(html,'data-solution-visible="true"'),18);assert.equal(html.includes("kp_g5a_u07_"),false);assert.equal(html.includes("ps_g5a_u07_"),false);});

test("Q045 current top-slot bridge reaches completion worksheet",()=>{const r=buildCurrentTopSlotWorksheet(opts(9));assert.equal(r.ok,true,r.errors.join("\n"));assert.equal(r.p05f45Implemented,true);assert.equal(r.worksheetDocument.metadata.knowledgePointId,G5A_U07_P05F45_KP_ID);});

test("Q045 browser current selector and binding wrappers expose target while preserving prior owners",async()=>{globalThis.document={};try{const selector=await import(`../../site/modules/curriculum/registry/batch-a-selector-p04f33-extension.js?p05f45=${Date.now()}`),binding=await import(`../../site/modules/curriculum/public/public-ui-capability-binding-p04f33.js?p05f45=${Date.now()}`);assert.equal(selector.getVisibleBatchAKnowledgePoint(G5A_U07_P05F45_KP_ID)?.sourceId,G5A_U07_P05F45_SOURCE_ID);assert.equal(binding.resolvePublicUiCapabilityBinding(opts()).blocked,false);for(const id of PROTECTED)assert.ok(selector.getVisibleBatchAKnowledgePoint(id),id);for(const id of NON_W5)assert.equal(selector.getVisibleBatchAKnowledgePoint(id),null,id);}finally{delete globalThis.document;}});
