import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {buildBatchABrowserWorksheetDocument as buildQ055Worksheet} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f55-extension.js";
import {buildBatchABrowserWorksheetDocument as buildCurrentWorksheet} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f32-extension.js";
import {requestsP05F55} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p05f55.js";
import {generateG6BU03P05F55Questions,validateG6BU03P05F55Question} from "../../site/modules/curriculum/batch-a/g6b-u03-prism-base-area-height-volume-runtime-p05f55.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";
import {validatePrismPyramidElementsDiagramModel} from "../../site/modules/renderer/prism-pyramid-elements-diagram.js";
import {auditG6BU03P05F55Projection,G6B_U03_P05F55_FORMAL_MAPPING,G6B_U03_P05F55_KP_ID as KP,G6B_U03_P05F55_PATTERN_GROUP_ID as GROUP,G6B_U03_P05F55_PRIOR_VISIBLE_KP_ID as PRIOR,G6B_U03_P05F55_PROTECTED_KP_IDS as PROTECTED,G6B_U03_P05F55_SOURCE_ID as SRC,G6B_U03_P05F55_SPEC_IDS as SPECS} from "../../site/modules/curriculum/registry/g6b-u03-prism-base-area-height-volume-selector-projection-p05f55.js";
import {auditP05F55PublicSelectorComposition,getVisibleBatchAKnowledgePoint,listBatchAKnowledgePointAvailabilityBySource,resolveVisiblePatternSpecIdsForKnowledgePoint} from "../../site/modules/curriculum/registry/batch-a-selector-p05f55-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p05f55.js";
const read=p=>JSON.parse(readFileSync(new URL(`../../${p}`,import.meta.url),"utf8"));
const preflight=read("data/curriculum/full-product/p05f/q055-g6b-u03-prism-base-area-height-volume-source-authority-preflight.json");
const implementation=read("data/curriculum/full-product/p05f/q055-g6b-u03-prism-base-area-height-volume-implementation.json");
const impact=read("data/project/change-impact/P05F_W5_Q055.impact.json");
const plan=read("data/project/validation-plans/P05F_W5_Q055.validation.json");
const opts=(count=24)=>({sourceId:SRC,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[KP],selectedPatternGroupIds:[GROUP],patternSpecIds:[...SPECS],questionMode:"diagram",requestedQuestionType:"diagram",questionCount:count,generationSeed:"p05f55-focused-prism-volume",includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showQuestionNumbers:true,showAnswerKeyPage:true}});
const occ=(t,x)=>t.split(x).length-1;

test("Q055 exact frozen identity and implementation manifest remain bounded",()=>{assert.equal(preflight.status,"PASS_SOURCE_AUTHORITY_PREFLIGHT");assert.equal(preflight.queueAuthority.queuePosition,55);assert.equal(preflight.queueAuthority.sliceId,"p05e_q055_r5_g6b_u03_6b03_profile_spatial_solid_c1");assert.deepEqual(preflight.queueAuthority.knowledgePointIds,[KP]);assert.equal(preflight.previousSliceD0Evidence.status,"PASS_E6_D0_COMPLETE");assert.equal(preflight.previousSliceD0Evidence.productPrNumber,952);assert.equal(implementation.taskId,"P05F_W5DirectProductVerticalSlice055Implementation");assert.equal(implementation.runtimeContract.frozenRuntimeProfile,"profile_spatial_solid");assert.equal(implementation.runtimeContract.volumeFormula,"baseArea * prismHeight");assert.equal(implementation.runtimeContract.shapeSpecificBaseAreaDerivation,false);for(const v of Object.values(implementation.scopeGuard))assert.equal(v,false);});

test("Q055 materializes one mapping one group and three source-backed PatternSpecs",()=>{const a=auditG6BU03P05F55Projection();assert.equal(a.ok,true,a.errors.join("\n"));assert.deepEqual(a.counts,{knowledgePoints:1,patternGroups:1,patternSpecs:3,formalMappings:1});assert.equal(G6B_U03_P05F55_FORMAL_MAPPING.r04MappingId,"r04map_g6b_u03_prism_base_area_height_volume");assert.deepEqual(G6B_U03_P05F55_FORMAL_MAPPING.sourcePages,[1,2]);assert.equal(G6B_U03_P05F55_FORMAL_MAPPING.applicationImplementationAllowed,false);});

test("Q055 selector promotes prism volume while preserving Q049 and hiding Q060 plus cylinder sibling",()=>{const a=auditP05F55PublicSelectorComposition();assert.equal(a.ok,true,a.errors.join("\n"));const s=listBatchAKnowledgePointAvailabilityBySource(SRC);assert.equal(s.visibleCount,2);assert.equal(s.hiddenPendingCount,3);assert.equal(s.notSelectableCount,3);for(const id of [PRIOR,KP])assert.ok(getVisibleBatchAKnowledgePoint(id),id);for(const id of PROTECTED){assert.equal(getVisibleBatchAKnowledgePoint(id),null,id);assert.ok(s.hiddenPendingKnowledgePointIds.includes(id),id);assert.ok(s.notSelectableKnowledgePointIds.includes(id),id);}assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(KP,"diagram"),[...SPECS]);});

test("Q055 public binding is single-KP diagram only and fails closed for mixed/source-unit selection",()=>{const a=auditPublicUiCapabilityBinding();assert.equal(a.ok,true,a.errors.join("\n"));const b=resolvePublicUiCapabilityBinding(opts());assert.equal(b.blocked,false);assert.equal(b.questionType,"diagram");assert.equal(b.questionCount.max,240);assert.equal(b.frozenRuntimeProfile,"profile_spatial_solid");assert.equal(b.prismVolumeAdmission,true);assert.equal(b.prismSurfaceAreaReowned,false);assert.equal(b.triangularPrismVolumeAdmission,false);assert.equal(b.cylinderAdmission,false);assert.equal(b.compositePrismAdmission,false);assert.equal(b.shapeSpecificBaseAreaDerivationAdmission,false);assert.deepEqual(b.optionalCapabilityIds,["cap_geometry_construction"]);assert.equal(requestsP05F55(opts()),true);assert.equal(requestsP05F55({...opts(),selectionMode:"sourceUnit"}),false);assert.equal(requestsP05F55({...opts(),selectedKnowledgePointIds:[KP,PROTECTED[0]]}),false);});

test("Q055 generates 240 deterministic unique variants per PatternSpec and enforces base-area-times-height",()=>{for(const id of SPECS){const o={knowledgePointId:KP,patternSpecIds:[id],questionCount:240,generationSeed:`q055-${id}`},a=generateG6BU03P05F55Questions(o),b=generateG6BU03P05F55Questions(o);assert.equal(a.ok,true,`${id}:${a.errors.join("\n")}`);assert.deepEqual(a.questions,b.questions);assert.equal(new Set(a.questions.map(q=>q.questionSignature)).size,240,id);assert.equal(new Set(a.questions.map(q=>q.promptText)).size,240,id);for(const q of a.questions){assert.equal(validateG6BU03P05F55Question(q).ok,true,id);assert.equal(validatePrismPyramidElementsDiagramModel(q.geometryDiagram).ok,true,`${id}:${q.geometryDiagram.variant}`);const d=q.geometryDiagram;assert.equal(d.solidKind,"PRISM");assert.equal(d.volume,d.baseArea*d.prismHeight);assert.equal(d.equalCrossSectionArea,d.baseArea);assert.equal(d.layerCount,d.prismHeight);assert.equal(d.shapeSpecificBaseAreaDerivation,false);}}});

test("Q055 validator fails closed on formula geometry provenance and future-scope tampering",()=>{const q=generateG6BU03P05F55Questions({...opts(1),patternSpecIds:[SPECS[0]]}).questions[0];for(const mutate of [x=>x.answerValue++,x=>x.geometryDiagram.volume++,x=>x.geometryDiagram.prismHeight++,x=>x.geometryDiagram.taskMode="IDENTIFY_EDGE",x=>x.metadata.shapeSpecificBaseAreaReasoningReowned=true,x=>x.metadata.triangularPrismVolumeTouched=true]){const t=JSON.parse(JSON.stringify(q));mutate(t);assert.equal(validateG6BU03P05F55Question(t).ok,false);}});

test("Q055 worksheet current bridge and HTML render questions answers and prism diagrams without internal IDs",async()=>{const r=buildQ055Worksheet(opts(18));assert.equal(r.ok,true,r.errors.join("\n"));assert.equal(r.worksheetDocument.questionCount,18);assert.equal(r.worksheetDocument.answerKeyItems.length,18);const html=renderWorksheetDocumentToHtml(r.worksheetDocument,{stylesheetHref:"",title:r.worksheetDocument.title,debugDataAttributes:false});assert.equal(occ(html,'data-representation="prism-pyramid-elements-diagram"'),36);assert.equal(html.includes("kp_g6b_u03_"),false);assert.equal(html.includes("ps_g6b_u03_"),false);const current=buildCurrentWorksheet(opts(9));assert.equal(current.ok,true,current.errors.join("\n"));assert.equal(current.p05f55Implemented,true);globalThis.document={};try{const s=await import(`../../site/modules/curriculum/registry/batch-a-selector-p04f33-extension.js?p05f55=${Date.now()}`),b=await import(`../../site/modules/curriculum/public/public-ui-capability-binding-p04f33.js?p05f55=${Date.now()}`);assert.equal(s.getVisibleBatchAKnowledgePoint(PRIOR)?.sourceId,SRC);assert.equal(s.getVisibleBatchAKnowledgePoint(KP)?.sourceId,SRC);for(const id of PROTECTED)assert.equal(s.getVisibleBatchAKnowledgePoint(id),null,id);assert.equal(b.resolvePublicUiCapabilityBinding(opts()).prismVolumeAdmission,true);}finally{delete globalThis.document;}});

test("Q055 validation remains SHARED_RUNTIME_BOUNDED",()=>{assert.equal(impact.expectedDerivedGate,"SHARED_RUNTIME_BOUNDED");assert.equal(impact.changeImpact.affectedRoutes,"BOUNDED");assert.equal(impact.changeImpact.legalRouteSemanticsChanged,false);assert.equal(plan.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(plan.lanes.SHARED_RUNTIME_BOUNDED[0].kind,"NODE_TEST");assert.equal(plan.lanes.SHARED_RUNTIME_BOUNDED[1].runtime,"PLAYWRIGHT_CHROMIUM");assert.equal(implementation.validation.fullRepositoryRegression,"FORBIDDEN");assert.equal(implementation.validation.globalBrowserReplay,"FORBIDDEN");});
