import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {materializeP05EW5DirectProductVerticalSliceQueue} from "../../src/curriculum/full-product/p05e-w5-direct-product-vertical-slice-queue.mjs";
import {materializeR04SharedRuntimeCapabilityMatrix} from "../../src/curriculum/global/r04-shared-runtime-capability-matrix.mjs";
import {materializeR05DeliveryWaveRebase} from "../../src/curriculum/global/r05-delivery-wave-rebase.mjs";
const read=p=>JSON.parse(readFileSync(new URL(`../../${p}`,import.meta.url),"utf8"));
const preflight=read("data/curriculum/full-product/p05f/q052-g5b-u01-composite-cube-volume-source-authority-preflight.json");
const r02=read("data/curriculum/global/candidates/r02/chunks/reviewed-source-candidates-03.json");
const KPS=["kp_g5b_u01_composite_rectangular_volume","kp_g5b_u01_cube_volume_formula"];
const CAPS=["cap_geometry_domain_validator","cap_geometry_property_reasoning","cap_solid_geometry_representation","cap_spatial_solid_reasoning"];
const sorted=v=>[...v].sort();

test("Q052 binds exact frozen row and Q051 E6 predecessor",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),row=q.queueEntries.find(x=>x.queuePosition===52);assert.equal(q.queueFrozen,true);assert.equal(q.queueRegistryParity,true);assert.equal(q.queueRegistry.queueDigest,"a4dae65a1a907ba963a135fce84ba292b8486a12513ae8f1fa54fbf07a6598ae");assert.ok(row);assert.equal(row.sliceId,"p05e_q052_r5_g5b_u01_5b01_profile_spatial_solid_c1");assert.equal(row.implementationTaskId,"P05F_W5DirectProductVerticalSlice052Implementation");assert.equal(row.previousSliceId,"p05e_q051_r5_g5a_u05_5a05a_profile_geometry_property_c1");assert.equal(row.previousSliceMustBeD0Complete,true);assert.equal(row.assignedDeliveryWaveId,"R05-W5");assert.equal(row.primarySourceNodeId,"g5b_u01_5b01");assert.deepEqual(row.supportingSourceNodeIds,["g5b_u01_5b01"]);assert.equal(row.intraWavePrerequisiteRank,5);assert.equal(row.primaryRuntimeProfileId,"profile_spatial_solid");assert.equal(row.chunkIndex,1);assert.equal(row.knowledgePointCount,2);assert.deepEqual(row.knowledgePointIds,KPS);assert.deepEqual(sorted(row.requiredW5CapabilityIds),sorted(CAPS));assert.equal(row.targetEvidenceLevel,"E6_D0_COMPLETE");assert.equal(preflight.queueAuthority.queueDigest,q.derivedRegistrySnapshot.queueDigest);const p=preflight.previousSliceD0Evidence;assert.equal(p.preflightPrNumber,945);assert.equal(p.productPrNumber,946);assert.equal(p.productHeadSha,"2ae8cf550935575cab44db695846e9148c4c9ab1");assert.equal(p.productMergeSha,"8aba5d639bf5d27d24403306e7c9e9836e825686");assert.equal(p.prGateRunId,"34938329146");assert.equal(p.pagesDeploymentRunId,"34938535741");assert.equal(p.exactPagesRunId,"34938535730");assert.equal(p.evidenceArtifactId,"10384067438");assert.equal(p.evidenceArtifactDigest,"sha256:cea1c96b04d3a92ec533ccb4d7c293e07886d995689ab617d222672952c18bf8");assert.equal(p.status,"PASS_E6_D0_COMPLETE");assert.equal(p.prGateConclusion,"success");assert.equal(p.pagesDeploymentConclusion,"success");assert.equal(p.exactPagesWorkflowConclusion,"success");});

test("Q052 binds exact R02 composite-volume and cube-volume candidates from the verified G5B-U01 source",()=>{const source=r02.sourceRecords.find(x=>x.sourceNodeId==="g5b_u01_5b01");assert.ok(source);assert.equal(source.sourceTitle,"長方體和正方體的體積");assert.equal(source.sourcePdfTitle,"meow911_5b01_source.pdf");assert.equal(source.pageCount,2);assert.deepEqual(source.reviewedPages,[1,2]);const composite=source.candidates.find(x=>x.knowledgePointId===KPS[0]),cube=source.candidates.find(x=>x.knowledgePointId===KPS[1]);assert.deepEqual(composite,{knowledgePointId:KPS[0],canonicalNameZh:"複合長方體體積",capabilityStatement:"學生能以分割或補形求複合立體體積。",reasoningInvariant:"不重疊部分體積和或大體積扣除空缺等於原立體體積。",category:"geometry",evidencePages:[1,2],applicationSuitability:"APPLICATION_COMPATIBLE"});assert.deepEqual(cube,{knowledgePointId:KPS[1],canonicalNameZh:"正方體體積公式",capabilityStatement:"學生能以邊長三次乘積求正方體體積。",reasoningInvariant:"正方體長寬高相等，體積為邊長乘邊長乘邊長。",category:"geometry",evidencePages:[1,2],applicationSuitability:"APPLICATION_COMPATIBLE"});assert.deepEqual(preflight.r02ReviewedCandidateAuthority.knowledgePoints,[composite,cube]);assert.deepEqual(preflight.r02ReviewedCandidateAuthority.sameSourceCandidateIds,source.candidates.map(x=>x.knowledgePointId));assert.equal(preflight.sourceAuthority.sourcePdfDriveFileId,"1IYHtSOWSxqbjcyEi94rmMEyqtOflGQ2f");assert.equal(preflight.sourceAuthority.sourceUrl,"https://meow911.com/5b01/");assert.equal(preflight.sourceAuthority.ocrUsedAsAuthority,false);assert.equal(preflight.sourceAuthority.sourceRefAmbiguity,false);assert.equal(preflight.sourceAuthority.manualSourceChoiceRequired,false);});

test("Q052 current R04/R05 contracts are exact spatial-solid with construction optional",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),row=q.queueEntries.find(x=>x.queuePosition===52),r04=materializeR04SharedRuntimeCapabilityMatrix(),r05=materializeR05DeliveryWaveRebase(),profile=r04.profiles.find(x=>x.profileId==="profile_spatial_solid");assert.ok(row);assert.ok(profile);assert.deepEqual(profile.requiredCapabilityIds,["cap_spatial_solid_reasoning","cap_geometry_domain_validator","cap_solid_geometry_representation"]);assert.deepEqual(profile.optionalCapabilityIds,["cap_geometry_construction"]);for(const kp of KPS){const m=r04.getMapping(kp),a=r05.getAssignment(kp),bound=preflight.runtimeCapabilityAuthority.perKnowledgePointMappings.find(x=>x.knowledgePointId===kp);assert.ok(m,kp);assert.ok(a,kp);assert.ok(bound,kp);assert.equal(m.mappingId,`r04map_${kp.replace(/^kp_/,"")}`);assert.equal(m.primaryRuntimeProfileId,"profile_spatial_solid");assert.equal(m.classificationRuleId,"rule_spatial_solid");assert.deepEqual(m.appliedModifierIds,[]);assert.deepEqual(m.optionalRuntimeCapabilityIds,["cap_geometry_construction"]);assert.deepEqual(m.forbiddenRuntimeCapabilityIds,[]);assert.deepEqual(bound.requiredRuntimeCapabilityIds,m.requiredRuntimeCapabilityIds);assert.deepEqual(bound.optionalRuntimeCapabilityIds,m.optionalRuntimeCapabilityIds);assert.equal(a.deliveryWaveId,"R05-W5");assert.equal(a.intraWavePrerequisiteRank,5);assert.equal(a.primaryRuntimeProfileId,"profile_spatial_solid");assert.deepEqual(sorted(a.contractOnlyRequiredCapabilityIds),sorted(CAPS));}assert.deepEqual(sorted(row.requiredW5CapabilityIds),sorted(CAPS));assert.deepEqual(preflight.runtimeCapabilityAuthority.r05DependencyClosureCapabilityIds,["cap_geometry_property_reasoning"]);});

test("Q052 owns exactly composite rectangular volume plus cube volume and protects Q019/Q047/Q058",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),q19=q.queueEntries.find(x=>x.knowledgePointIds.includes("kp_g5b_u01_volume_unit_conversion")),q47=q.queueEntries.find(x=>x.knowledgePointIds.includes("kp_g5b_u01_rectangular_prism_volume_formula")),q58=q.queueEntries.find(x=>x.knowledgePointIds.includes("kp_g5b_u01_volume_unknown_dimension"));assert.equal(q19?.queuePosition,19);assert.equal(q47?.queuePosition,47);assert.equal(q58?.queuePosition,58);assert.deepEqual(preflight.q052ScopeLock.includedKnowledgePointIds,KPS);assert.equal(preflight.q052ScopeLock.protectedExistingSameSourceKnowledgePointOwnership.kp_g5b_u01_volume_unit_conversion,"Q019");assert.equal(preflight.q052ScopeLock.protectedExistingSameSourceKnowledgePointOwnership.kp_g5b_u01_rectangular_prism_volume_formula,"Q047");assert.deepEqual(preflight.q052ScopeLock.deferredFrozenOwnership.Q058,["kp_g5b_u01_volume_unknown_dimension"]);assert.equal(preflight.q052ScopeLock.rectangularPrismFormulaMayBeReusedAsPrerequisiteNotReowned,true);assert.equal(preflight.q052ScopeLock.compositePartsMustBeNonOverlappingForSumModel,true);assert.equal(preflight.q052ScopeLock.completionModelMustSubtractExactlyTheMissingRectangularPrism,true);assert.equal(preflight.q052ScopeLock.cubeFormulaMustUseThreeEqualEdgeDimensions,true);for(const r of ["REOWN_VOLUME_UNIT_CONVERSION","REOWN_RECTANGULAR_PRISM_VOLUME_FORMULA","SOLVE_UNKNOWN_LENGTH_WIDTH_OR_HEIGHT_FROM_VOLUME","SURFACE_AREA_FORMULA_OR_ARITHMETIC","APPLICATION_CONTEXT_IMPLEMENTATION","SAME_UNIT_MIXED_MODE","CROSS_UNIT_MIXED_MODE","Q053_OR_LATER_SEMANTICS"])assert.ok(preflight.q052ScopeLock.excludedRelations.includes(r),r);});

test("Q052 preflight stays bounded and stops at implementation approval boundary",()=>{const b=preflight.preflightValidationBoundary;assert.equal(b.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(b.derivedLane,"SHARED_RUNTIME_BOUNDED");assert.deepEqual(b.allowedLaneGateIds,["GLOBAL_CONTRACTS","TARGETED_ROUTE_REPLAY"]);assert.equal(b.focusedNodeContractRequired,true);assert.equal(b.nodeOnlyReadbackRequired,true);assert.equal(b.fullRepositoryRegressionAllowed,false);assert.equal(b.globalBrowserReplayAllowed,false);assert.equal(b.productImplementationAllowed,false);assert.equal(b.publicProductAdmissionAllowed,false);for(const k of ["applicationImplementationAllowedByThisPreflight","implementationAllowedByThisPreflight","publicProductAdmissionAllowedByThisPreflight","frozenQueueAuthorityTouched","r02AuthorityTouched","r04AuthorityTouched","r05AuthorityTouched","q053OrLaterTouched"])assert.equal(preflight.q052ScopeLock[k],false,k);const d=preflight.preflightDecision;assert.equal(d.exactFrozenQueueRowResolved,true);assert.equal(d.sourceAuthoritySufficientForQ052ImplementationPlanning,true);assert.equal(d.previousSliceD0Satisfied,true);assert.equal(d.r02AuthorityBoundForBothTargetKnowledgePoints,true);assert.equal(d.runtimeCapabilityContractLockedForBothTargetKnowledgePoints,true);assert.equal(d.twoKnowledgePointScopeLocked,true);assert.equal(d.priorSameSourceFrozenOwnershipProtected,true);assert.equal(d.q058DeferredOwnershipProtected,true);assert.equal(d.manualSourceChoiceRequired,false);assert.equal(d.sourceRefAmbiguity,false);assert.equal(d.separateImplementationApprovalSatisfiedByCurrentOperatorInstruction,false);assert.equal(d.nextTaskRequiresNewOperatorApproval,true);assert.equal(d.nextTask,"P05F_W5DirectProductVerticalSlice052Implementation");});
