import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {G4B_U07_P05F26_FORMAL_MAPPING,G4B_U07_P05F26_KP_ID,G4B_U07_P05F26_PATTERN_SPECS,G4B_U07_P05F26_REMAINING_FUTURE_KP_IDS,G4B_U07_P05F26_SOURCE_ID,G4B_U07_P05F26_SPEC_IDS,auditG4BU07P05F26Projection} from "../../site/modules/curriculum/registry/g4b-u07-rectangle-square-area-formula-selector-projection-p05f26.js";
import {auditP05F26PublicSelectorComposition,getVisibleBatchAKnowledgePoint,listBatchAKnowledgePointAvailabilityBySource,resolveVisiblePatternSpecIdsForKnowledgePoint} from "../../site/modules/curriculum/registry/batch-a-selector-p05f26-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p05f26.js";
import {buildBatchABrowserPlan,generateBatchABrowserQuestions,requestsP05F26} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p05f26.js";
import {G4B_U07_P05F26_MAX_QUESTION_COUNT,generateG4BU07P05F26Questions,validateG4BU07P05F26Question} from "../../site/modules/curriculum/batch-a/g4b-u07-rectangle-square-area-formula-runtime-p05f26.js";
import {buildBatchABrowserWorksheetDocument as buildP05F26Worksheet} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f26-extension.js";
import {renderRectangleSquareAreaFormulaDiagram} from "../../site/modules/renderer/rectangle-square-area-formula-diagram.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";

const request=(extra={})=>({sourceId:G4B_U07_P05F26_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G4B_U07_P05F26_KP_ID],questionType:"diagram",questionMode:"diagram",questionCount:20,generationSeed:"q026-test",includeAnswerKey:true,printLayout:{columns:2,rowsPerPage:4,showAnswerKeyPage:true},...extra});

test("Q026 projection and public selector admit only the exact frozen KP",()=>{assert.equal(auditG4BU07P05F26Projection().ok,true);const audit=auditP05F26PublicSelectorComposition();assert.equal(audit.ok,true,audit.errors.join("\n"));const target=getVisibleBatchAKnowledgePoint(G4B_U07_P05F26_KP_ID);assert.ok(target);assert.equal(target.sourceId,G4B_U07_P05F26_SOURCE_ID);assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(G4B_U07_P05F26_KP_ID,"diagram"),G4B_U07_P05F26_SPEC_IDS);assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(G4B_U07_P05F26_KP_ID,"numeric"),[]);const source=listBatchAKnowledgePointAvailabilityBySource(G4B_U07_P05F26_SOURCE_ID);assert.ok(source.visibleKnowledgePointIds.includes(G4B_U07_P05F26_KP_ID));for(const id of G4B_U07_P05F26_REMAINING_FUTURE_KP_IDS){assert.ok(source.hiddenPendingKnowledgePointIds.includes(id),id);assert.ok(source.notSelectableKnowledgePointIds.includes(id),id);assert.equal(getVisibleBatchAKnowledgePoint(id),null,id);}});

test("Q026 FormalMapping and PatternSpecs preserve only the three page-1 area-formula relations",()=>{assert.equal(G4B_U07_P05F26_FORMAL_MAPPING.sourceId,G4B_U07_P05F26_SOURCE_ID);assert.deepEqual(G4B_U07_P05F26_FORMAL_MAPPING.sourcePages,[1]);assert.equal(G4B_U07_P05F26_FORMAL_MAPPING.evidencePointerMismatchReconciled,true);assert.equal(G4B_U07_P05F26_PATTERN_SPECS.length,3);assert.equal(new Set(G4B_U07_P05F26_SPEC_IDS).size,3);assert.deepEqual(G4B_U07_P05F26_PATTERN_SPECS.map(row=>row.relation),G4B_U07_P05F26_FORMAL_MAPPING.includedRelations);assert.ok(G4B_U07_P05F26_PATTERN_SPECS.every(row=>row.questionMode==="diagram"&&row.applicationAllowed===false&&row.perimeterAllowed===false&&row.compositeAreaAllowed===false&&row.areaUnitConversionAllowed===false&&row.areaPerimeterComparisonAllowed===false));});

test("Q026 runtime produces deterministic validated 240-question mixed allocation",()=>{assert.equal(G4B_U07_P05F26_MAX_QUESTION_COUNT,240);const a=generateG4BU07P05F26Questions({knowledgePointId:G4B_U07_P05F26_KP_ID,questionCount:240,generationSeed:"q026-capacity"}),b=generateG4BU07P05F26Questions({knowledgePointId:G4B_U07_P05F26_KP_ID,questionCount:240,generationSeed:"q026-capacity"});assert.equal(a.ok,true,a.errors.join("\n"));assert.equal(a.questions.length,240);assert.equal(new Set(a.questions.map(q=>q.questionSignature)).size,240);assert.deepEqual(a.questions.map(q=>q.questionSignature),b.questions.map(q=>q.questionSignature));assert.ok(a.questions.every(q=>validateG4BU07P05F26Question(q).ok));assert.deepEqual([...new Set(a.questions.map(q=>q.relation))].sort(),[...G4B_U07_P05F26_FORMAL_MAPPING.includedRelations].sort());assert.ok(a.questions.every(q=>q.metadata.applicationContextUsed===false&&q.metadata.perimeterPathSumTouched===false&&q.metadata.perimeterFormulaTouched===false&&q.metadata.compositePerimeterTouched===false&&q.metadata.compositeRectilinearAreaTouched===false&&q.metadata.areaUnitConversionUsed===false&&q.metadata.q027OrLaterTouched===false));});

test("Q026 each PatternSpec has 240 deterministic distinct diagram variants and tampering fails closed",()=>{for(const patternSpecId of G4B_U07_P05F26_SPEC_IDS){const out=generateG4BU07P05F26Questions({knowledgePointId:G4B_U07_P05F26_KP_ID,patternSpecIds:[patternSpecId],questionCount:240,generationSeed:`q026-${patternSpecId}`});assert.equal(out.ok,true,`${patternSpecId}:${out.errors.join(",")}`);assert.equal(new Set(out.questions.map(q=>q.questionSignature)).size,240,patternSpecId);const first=out.questions[0],tampered={...first,geometryDiagram:{...first.geometryDiagram,areaCm2:first.geometryDiagram.areaCm2+1}};assert.equal(validateG4BU07P05F26Question(tampered).ok,false,patternSpecId);}});

test("Q026 public binding and browser generator stay bounded to single-KP diagram mode",()=>{const binding=resolvePublicUiCapabilityBinding(request());assert.equal(auditPublicUiCapabilityBinding().ok,true);assert.equal(binding.blocked,false);assert.equal(binding.questionType,"diagram");assert.equal(binding.questionCount.max,240);assert.equal(binding.sourceBackedRectangleSquareAreaFormula,true);assert.equal(binding.applicationImplementationAllowed,false);assert.equal(binding.perimeterTargetAdmission,false);assert.equal(binding.compositeRectilinearAreaAdmission,false);assert.equal(binding.areaUnitConversionAdmission,false);assert.equal(requestsP05F26(request()),true);assert.equal(requestsP05F26(request({selectionMode:"sourceUnit"})),false);const plan=buildBatchABrowserPlan(request());assert.equal(plan.sourceId,G4B_U07_P05F26_SOURCE_ID);assert.equal(plan.selectionMode,"singleKnowledgePoint");assert.equal(plan.genericFallback,false);const generated=generateBatchABrowserQuestions(request());assert.equal(generated.ok,true,generated.errors.join("\n"));assert.equal(generated.questions.length,20);});

test("Q026 worksheet renderer materializes questions, answers, formula diagrams, and print pages",()=>{const result=buildP05F26Worksheet(request());assert.equal(result.ok,true,result.errors.join("\n"));const doc=result.worksheetDocument;assert.equal(doc.questionCount,20);assert.equal(doc.answerKeyItems.length,20);assert.equal(doc.summary.diagramQuestionCount,20);assert.ok(doc.questionPages.length>=3);assert.ok(doc.answerKeyPages.length>=3);const html=renderWorksheetDocumentToHtml(doc,{stylesheetHref:null,title:doc.title});assert.match(html,/長方形正方形面積公式/);assert.match(html,/rectangle-square-area-formula-diagram/);assert.match(html,/平方公分/);assert.doesNotThrow(()=>renderRectangleSquareAreaFormulaDiagram(doc.questions[0].geometryDiagram));});

test("Q026 implementation manifests preserve incremental-validation and frozen scope guards",()=>{const implementation=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q026-g4b-u07-rectangle-square-area-formula-implementation.json",import.meta.url),"utf8")),impact=JSON.parse(readFileSync(new URL("../../data/project/change-impact/P05F_W5_Q026.impact.json",import.meta.url),"utf8")),plan=JSON.parse(readFileSync(new URL("../../data/project/validation-plans/P05F_W5_Q026.validation.json",import.meta.url),"utf8"));assert.equal(implementation.status,"IMPLEMENTATION_MATERIALIZED_AWAITING_FOCUSED_CI");assert.equal(implementation.goalDistance,"D1");assert.equal(implementation.sourceAuthority.r02EvidencePointerMismatchReconciled,true);assert.equal(implementation.sourceAuthority.embeddedHeaderUrlMismatchObserved,true);for(const value of Object.values(implementation.scopeGuard))assert.equal(value,false);assert.equal(impact.expectedDerivedGate,"SHARED_RUNTIME_BOUNDED");assert.equal(plan.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.ok(!JSON.stringify(plan).includes("full npm test"));});
