import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {G5A_U09_P05F37_FORMAL_MAPPING,G5A_U09_P05F37_KP_ID,G5A_U09_P05F37_PATTERN_SPECS,G5A_U09_P05F37_REMAINING_FUTURE_KP_IDS,G5A_U09_P05F37_SOURCE_ID,G5A_U09_P05F37_SPEC_IDS,auditG5AU09P05F37Projection} from "../../site/modules/curriculum/registry/g5a-u09-parallelogram-area-formula-selector-projection-p05f37.js";
import {BATCH_A_SELECTOR_AVAILABILITY as P05F36_SELECTOR_AVAILABILITY} from "../../site/modules/curriculum/registry/batch-a-selector-p05f36-extension.js";
import {BATCH_A_SELECTOR_AVAILABILITY as P05F37_SELECTOR_AVAILABILITY,auditP05F37PublicSelectorComposition,getVisibleBatchAKnowledgePoint,listBatchAKnowledgePointAvailabilityBySource,resolveVisiblePatternSpecIdsForKnowledgePoint} from "../../site/modules/curriculum/registry/batch-a-selector-p05f37-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p05f37.js";
import {buildBatchABrowserPlan,generateBatchABrowserQuestions,requestsP05F37} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p05f37.js";
import {G5A_U09_P05F37_MAX_QUESTION_COUNT,generateG5AU09P05F37Questions,validateG5AU09P05F37Question} from "../../site/modules/curriculum/batch-a/g5a-u09-parallelogram-area-formula-runtime-p05f37.js";
import {buildBatchABrowserWorksheetDocument as buildP05F37Worksheet} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f37-extension.js";
import {getBatchASourceUnit,listBatchASourceUnits} from "../../site/modules/curriculum/batch-a/source-units.js";
import {renderRectangleSquareAreaFormulaDiagram} from "../../site/modules/renderer/rectangle-square-area-formula-diagram.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";
const request=(extra={})=>({sourceId:G5A_U09_P05F37_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G5A_U09_P05F37_KP_ID],questionType:"diagram",questionMode:"diagram",questionCount:20,generationSeed:"q037-test",includeAnswerKey:true,printLayout:{columns:2,rowsPerPage:4,showAnswerKeyPage:true},...extra});

test("Q037 first-new-source selector admission preserves P05F36 baseline",()=>{assert.equal(P05F36_SELECTOR_AVAILABILITY.bySourceId?.[G5A_U09_P05F37_SOURCE_ID],undefined);const s=listBatchAKnowledgePointAvailabilityBySource(G5A_U09_P05F37_SOURCE_ID);assert.deepEqual(s.visibleKnowledgePointIds,[G5A_U09_P05F37_KP_ID]);assert.deepEqual(s.hiddenPendingKnowledgePointIds,G5A_U09_P05F37_REMAINING_FUTURE_KP_IDS);assert.deepEqual(s.notSelectableKnowledgePointIds,G5A_U09_P05F37_REMAINING_FUTURE_KP_IDS);assert.equal(s.visibleCount,1);assert.equal(s.hiddenPendingCount,4);assert.equal(s.notSelectableCount,4);assert.equal(P05F37_SELECTOR_AVAILABILITY.sourceCount,Number(P05F36_SELECTOR_AVAILABILITY.sourceCount)+1);assert.equal(P05F37_SELECTOR_AVAILABILITY.publicSourceCount,Number(P05F36_SELECTOR_AVAILABILITY.publicSourceCount)+1);assert.equal(P05F37_SELECTOR_AVAILABILITY.visibleCount,Number(P05F36_SELECTOR_AVAILABILITY.visibleCount)+1);assert.equal(P05F37_SELECTOR_AVAILABILITY.hiddenPendingCount,Number(P05F36_SELECTOR_AVAILABILITY.hiddenPendingCount)+4);assert.equal(P05F37_SELECTOR_AVAILABILITY.notSelectableCount,Number(P05F36_SELECTOR_AVAILABILITY.notSelectableCount)+4);for(const id of Object.keys(P05F36_SELECTOR_AVAILABILITY.bySourceId))assert.strictEqual(P05F37_SELECTOR_AVAILABILITY.bySourceId[id],P05F36_SELECTOR_AVAILABILITY.bySourceId[id],id);});

test("Q037 source catalog and selector expose only target KP",()=>{const sourceUnit=getBatchASourceUnit(G5A_U09_P05F37_SOURCE_ID);assert.equal(sourceUnit?.unitCode,"5A-U09");assert.equal(sourceUnit?.domain,"geometry_formula");assert.ok(listBatchASourceUnits({includeW5Slice037:true}).some(x=>x.sourceId===G5A_U09_P05F37_SOURCE_ID));assert.equal(auditG5AU09P05F37Projection().ok,true);const audit=auditP05F37PublicSelectorComposition();assert.equal(audit.ok,true,audit.errors.join("\n"));assert.ok(getVisibleBatchAKnowledgePoint(G5A_U09_P05F37_KP_ID));assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(G5A_U09_P05F37_KP_ID,"diagram"),G5A_U09_P05F37_SPEC_IDS);assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(G5A_U09_P05F37_KP_ID,"numeric"),[]);for(const id of G5A_U09_P05F37_REMAINING_FUTURE_KP_IDS)assert.equal(getVisibleBatchAKnowledgePoint(id),null,id);});

test("Q037 FormalMapping and PatternSpecs preserve exact three preflight relations",()=>{assert.equal(G5A_U09_P05F37_FORMAL_MAPPING.sourceId,G5A_U09_P05F37_SOURCE_ID);assert.deepEqual(G5A_U09_P05F37_FORMAL_MAPPING.r02EvidencePages,[1]);assert.deepEqual(G5A_U09_P05F37_FORMAL_MAPPING.directVisualCorroborationPages,[1,2]);assert.equal(G5A_U09_P05F37_PATTERN_SPECS.length,3);assert.deepEqual(G5A_U09_P05F37_PATTERN_SPECS.map(x=>x.relation),G5A_U09_P05F37_FORMAL_MAPPING.includedRelations);assert.ok(G5A_U09_P05F37_PATTERN_SPECS.every(x=>x.questionMode==="diagram"&&x.requiresPerpendicularHeight&&x.applicationAllowed===false&&x.triangleFormulaAllowed===false&&x.trapezoidFormulaAllowed===false&&x.unknownDimensionAllowed===false&&x.compositePolygonAreaAllowed===false));});

test("Q037 runtime produces deterministic validated 240-question allocation",()=>{assert.equal(G5A_U09_P05F37_MAX_QUESTION_COUNT,240);const a=generateG5AU09P05F37Questions({knowledgePointId:G5A_U09_P05F37_KP_ID,questionCount:240,generationSeed:"q037-capacity"}),b=generateG5AU09P05F37Questions({knowledgePointId:G5A_U09_P05F37_KP_ID,questionCount:240,generationSeed:"q037-capacity"});assert.equal(a.ok,true,a.errors.join("\n"));assert.equal(a.questions.length,240);assert.equal(new Set(a.questions.map(q=>q.questionSignature)).size,240);assert.deepEqual(a.questions.map(q=>q.questionSignature),b.questions.map(q=>q.questionSignature));assert.ok(a.questions.every(q=>validateG5AU09P05F37Question(q).ok));assert.deepEqual([...new Set(a.questions.map(q=>q.relation))].sort(),[...G5A_U09_P05F37_FORMAL_MAPPING.includedRelations].sort());});

test("Q037 each PatternSpec has 240 distinct variants and tampering fails closed",()=>{for(const patternSpecId of G5A_U09_P05F37_SPEC_IDS){const out=generateG5AU09P05F37Questions({knowledgePointId:G5A_U09_P05F37_KP_ID,patternSpecIds:[patternSpecId],questionCount:240,generationSeed:`q037-${patternSpecId}`});assert.equal(out.ok,true,`${patternSpecId}:${out.errors.join(",")}`);assert.equal(new Set(out.questions.map(q=>q.questionSignature)).size,240,patternSpecId);const first=out.questions[0];assert.equal(validateG5AU09P05F37Question({...first,geometryDiagram:{...first.geometryDiagram,heightPerpendicular:false}}).ok,false,patternSpecId);}});

test("Q037 public binding and browser generator remain bounded to single-KP diagram mode",()=>{const binding=resolvePublicUiCapabilityBinding(request());assert.equal(auditPublicUiCapabilityBinding().ok,true);assert.equal(binding.blocked,false);assert.equal(binding.questionType,"diagram");assert.equal(binding.questionCount.max,240);assert.equal(binding.sourceBackedParallelogramAreaFormula,true);assert.equal(binding.applicationImplementationAllowed,false);assert.equal(binding.triangleFormulaAdmission,false);assert.equal(binding.trapezoidFormulaAdmission,false);assert.equal(requestsP05F37(request()),true);assert.equal(requestsP05F37(request({selectionMode:"sourceUnit"})),false);const plan=buildBatchABrowserPlan(request());assert.equal(plan.sourceId,G5A_U09_P05F37_SOURCE_ID);assert.equal(plan.genericFallback,false);const generated=generateBatchABrowserQuestions(request());assert.equal(generated.ok,true,generated.errors.join("\n"));assert.equal(generated.questions.length,20);});

test("Q037 worksheet and shared renderer materialize questions answers and parallelogram diagrams",()=>{const result=buildP05F37Worksheet(request());assert.equal(result.ok,true,result.errors.join("\n"));const doc=result.worksheetDocument;assert.equal(doc.questionCount,20);assert.equal(doc.answerKeyItems.length,20);assert.equal(doc.summary.diagramQuestionCount,20);const html=renderWorksheetDocumentToHtml(doc,{stylesheetHref:null,title:doc.title,debugDataAttributes:false});assert.match(html,/平行四邊形面積/);assert.match(html,/parallelogram-area-formula-diagram/);assert.match(html,/平方公分/);assert.doesNotThrow(()=>renderRectangleSquareAreaFormulaDiagram(doc.questions[0].geometryDiagram));});

test("Q037 implementation manifests preserve bounded validation and future sibling guards",()=>{const implementation=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q037-g5a-u09-parallelogram-area-formula-implementation.json",import.meta.url),"utf8")),impact=JSON.parse(readFileSync(new URL("../../data/project/change-impact/P05F_W5_Q037.impact.json",import.meta.url),"utf8")),plan=JSON.parse(readFileSync(new URL("../../data/project/validation-plans/P05F_W5_Q037.validation.json",import.meta.url),"utf8"));assert.equal(implementation.status,"IMPLEMENTATION_MATERIALIZED_AWAITING_FOCUSED_CI");assert.equal(implementation.goalDistance.reduced,"D2_TO_D1");assert.equal(implementation.publicAdmission.sourceAlreadyAdmittedBeforeQ037,false);assert.equal(implementation.publicAdmission.expectedGlobalPublicSourceDelta,1);assert.equal(implementation.publicAdmission.expectedGlobalHiddenPendingKnowledgePointDelta,4);for(const value of Object.values(implementation.scopeGuard))assert.equal(value,false);assert.equal(impact.expectedDerivedGate,"SHARED_RUNTIME_BOUNDED");assert.equal(plan.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(plan.lanes.SHARED_RUNTIME_BOUNDED[1].runtime,"PLAYWRIGHT_CHROMIUM");assert.ok(!JSON.stringify(plan).includes("full npm test"));});
