import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {materializeP05EW5DirectProductVerticalSliceQueue} from "../../src/curriculum/full-product/p05e-w5-direct-product-vertical-slice-queue.mjs";
import {materializeR04SharedRuntimeCapabilityMatrix} from "../../src/curriculum/global/r04-shared-runtime-capability-matrix.mjs";
import {materializeR05DeliveryWaveRebase} from "../../src/curriculum/global/r05-delivery-wave-rebase.mjs";
const read=p=>JSON.parse(readFileSync(new URL(`../../${p}`,import.meta.url),"utf8"));
const preflight=read("data/curriculum/full-product/p05f/q057-g5a-u09-area-unknown-dimension-source-authority-preflight.json");
const q037=read("data/curriculum/full-product/p05f/q037-g5a-u09-parallelogram-area-formula-source-authority-preflight.json");
const q046=read("data/curriculum/full-product/p05f/q046-g5a-u09-triangle-trapezoid-area-formulas-source-authority-preflight.json");
const r02=read("data/curriculum/global/candidates/r02/chunks/reviewed-source-candidates-03.json");
const KP="kp_g5a_u09_area_unknown_dimension";
const CAPS=["cap_geometry_diagram_representation","cap_geometry_domain_validator","cap_geometry_formula_evaluation","cap_geometry_property_reasoning"];
const sorted=v=>[...v].sort();

test("Q057 binds exact frozen row and Q056 D0 predecessor",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),row=q.queueEntries.find(x=>x.queuePosition===57);assert.equal(q.queueFrozen,true);assert.equal(q.queueRegistryParity,true);assert.equal(q.derivedRegistrySnapshot.queueDigest,"a4dae65a1a907ba963a135fce84ba292b8486a12513ae8f1fa54fbf07a6598ae");assert.ok(row);assert.equal(row.sliceId,"p05e_q057_r6_g5a_u09_5a09_profile_geometry_formula_c1");assert.equal(row.implementationTaskId,"P05F_W5DirectProductVerticalSlice057Implementation");assert.equal(row.previousSliceId,"p05e_q056_r6_g5a_u05_5a05a_profile_geometry_property_c1");assert.equal(row.primarySourceNodeId,"g5a_u09_5a09");assert.deepEqual(row.supportingSourceNodeIds,["g5a_u09_5a09"]);assert.equal(row.intraWavePrerequisiteRank,6);assert.equal(row.primaryRuntimeProfileId,"profile_geometry_formula");assert.equal(row.knowledgePointCount,1);assert.deepEqual(row.knowledgePointIds,[KP]);assert.deepEqual(sorted(row.requiredW5CapabilityIds),sorted(CAPS));assert.equal(row.targetEvidenceLevel,"E6_D0_COMPLETE");const p=preflight.previousSliceD0Evidence;assert.equal(p.preflightPrNumber,955);assert.equal(p.productPrNumber,956);assert.equal(p.productHeadSha,"6103b46f4528b972c3d3aea969032604fb03038c");assert.equal(p.productMergeSha,"0cffcfdc7659dae1bc2b648baa6beb2901070cc9");assert.equal(p.prGateRunId,"35054571664");assert.equal(p.pagesDeploymentRunId,"35054704273");assert.equal(p.exactPagesRunId,"35054704300");assert.equal(p.evidenceArtifactId,"10430078055");assert.equal(p.evidenceArtifactDigest,"sha256:4fd7a0c286d9c371f310a0290180135172bd9189b2b82351eea74722fd46c089");assert.equal(p.status,"PASS_E6_D0_COMPLETE");});

test("Q057 reuses verified G5A-U09 source identity from Q037 and Q046",()=>{const s=preflight.sourceAuthority;assert.equal(s.sourceNodeId,"g5a_u09_5a09");assert.equal(s.sourceTitle,"平行四邊形三角形梯形面積");assert.equal(s.sourcePdfTitle,"meow911_5a09_source.pdf");assert.equal(s.sourcePdfDriveFileId,"1fvDY9emawKVJgMNyt5oN-TbHvaRtpUy9");assert.equal(s.sourceMetadataDriveFileId,"1wWfnemvRk-X5As2l4UvEc2zKHGanlH0y");assert.equal(s.verificationNotesDriveFileId,"1NMsQLNSSWLbPbiQcWDXFhdn-Rzg9-iOo");assert.equal(q037.sourceAuthority.sourcePdfDriveFileId,s.sourcePdfDriveFileId);assert.equal(q046.sourceAuthority.sourcePdfDriveFileId,s.sourcePdfDriveFileId);assert.deepEqual(s.targetEvidencePages,[4]);assert.equal(s.targetEvidenceReconciliation.areaUnknownDimension.sameSourceIdentityAlreadyCorroboratedByQ037AndQ046,true);assert.equal(s.ocrUsedAsAuthority,false);assert.equal(s.r02AuthorityModified,false);assert.equal(s.sourceRefAmbiguity,false);assert.equal(s.manualSourceChoiceRequired,false);});

test("Q057 locks exact R02 area-unknown-dimension candidate on page 4",()=>{const source=r02.sourceRecords.find(x=>x.sourceNodeId==="g5a_u09_5a09"),c=source?.candidates.find(x=>x.knowledgePointId===KP);assert.ok(c);assert.deepEqual(c,{knowledgePointId:KP,canonicalNameZh:"面積反求底或高",capabilityStatement:"學生能由面積與另一尺寸反求未知底或高。",reasoningInvariant:"反求結果代回面積公式必須重建原面積。",category:"geometry",evidencePages:[4],applicationSuitability:"APPLICATION_COMPATIBLE"});assert.deepEqual(preflight.r02ReviewedCandidateAuthority.knowledgePoint,c);assert.deepEqual(preflight.r02ReviewedCandidateAuthority.sameSourceCandidateIds,source.candidates.map(x=>x.knowledgePointId));});

test("Q057 binds current R04 geometry-formula mapping and exact R05 closure",()=>{const r04=materializeR04SharedRuntimeCapabilityMatrix(),m=r04.getMapping(KP),bound=preflight.runtimeCapabilityAuthority.mapping;assert.ok(m);assert.equal(m.mappingId,"r04map_g5a_u09_area_unknown_dimension");assert.equal(m.primaryRuntimeProfileId,"profile_geometry_formula");assert.equal(m.classificationRuleId,"rule_geometry_formula");assert.deepEqual(m.appliedModifierIds,[]);assert.deepEqual(m.requiredRuntimeCapabilityIds,bound.requiredRuntimeCapabilityIds);assert.deepEqual(m.optionalRuntimeCapabilityIds,[]);assert.deepEqual(m.forbiddenRuntimeCapabilityIds,[]);const a=materializeR05DeliveryWaveRebase().getAssignment(KP);assert.ok(a);assert.equal(a.deliveryWaveId,"R05-W5");assert.equal(a.intraWavePrerequisiteRank,6);assert.equal(a.primaryRuntimeProfileId,"profile_geometry_formula");assert.deepEqual(sorted(a.contractOnlyRequiredCapabilityIds),sorted(CAPS));assert.deepEqual(sorted(preflight.runtimeCapabilityAuthority.exactFrozenQueueRequiredW5CapabilityIds),sorted(CAPS));});

test("Q057 owns inverse dimension only and protects prior area formulas plus Q062 composite area",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),owners={kp_g5a_u09_parallelogram_area_formula:37,kp_g5a_u09_triangle_area_formula:46,kp_g5a_u09_trapezoid_area_formula:46,kp_g5a_u09_composite_polygon_area:62};for(const[kp,pos]of Object.entries(owners)){const row=q.queueEntries.find(x=>x.knowledgePointIds.includes(kp));assert.equal(row?.queuePosition,pos,kp);}assert.deepEqual(preflight.q057ScopeLock.includedKnowledgePointIds,[KP]);assert.equal(preflight.q057ScopeLock.protectedExistingSameSourceKnowledgePointOwnership.kp_g5a_u09_parallelogram_area_formula,"Q037");assert.equal(preflight.q057ScopeLock.protectedExistingSameSourceKnowledgePointOwnership.kp_g5a_u09_triangle_area_formula,"Q046");assert.equal(preflight.q057ScopeLock.protectedExistingSameSourceKnowledgePointOwnership.kp_g5a_u09_trapezoid_area_formula,"Q046");assert.equal(preflight.q057ScopeLock.deferredFrozenQueueOwnership.kp_g5a_u09_composite_polygon_area,"Q062");assert.equal(preflight.q057ScopeLock.priorAreaFormulaSemanticsMayBeUsedAsPrerequisitesButNotReowned,true);assert.equal(preflight.q057ScopeLock.unknownDimensionMustReconstructOriginalAreaWhenSubstitutedBack,true);});

test("Q057 excludes formula reownership composite area application mixed modes and Q058+",()=>{for(const r of ["REOWN_PARALLELOGRAM_AREA_FORMULA","REOWN_TRIANGLE_AREA_FORMULA","REOWN_TRAPEZOID_AREA_FORMULA","COMPOSITE_POLYGON_AREA","APPLICATION_CONTEXT_IMPLEMENTATION","SAME_UNIT_MIXED_MODE","CROSS_UNIT_MIXED_MODE","Q058_OR_LATER_SEMANTICS"])assert.ok(preflight.q057ScopeLock.excludedRelations.includes(r),r);for(const k of ["applicationImplementationAllowedByThisPreflight","implementationAllowedByThisPreflight","publicProductAdmissionAllowedByThisPreflight","sameUnitMixedTouched","crossUnitMixedTouched","frozenQueueAuthorityTouched","r02AuthorityTouched","r04AuthorityTouched","r05AuthorityTouched","q058OrLaterTouched"])assert.equal(preflight.q057ScopeLock[k],false,k);});

test("Q057 preflight stays bounded and stops at implementation approval boundary",()=>{const b=preflight.preflightValidationBoundary;assert.equal(b.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(b.derivedLane,"SHARED_RUNTIME_BOUNDED");assert.deepEqual(b.allowedLaneGateIds,["GLOBAL_CONTRACTS","TARGETED_ROUTE_REPLAY"]);assert.equal(b.focusedNodeContractRequired,true);assert.equal(b.nodeOnlyReadbackRequired,true);assert.equal(b.fullRepositoryRegressionAllowed,false);assert.equal(b.globalBrowserReplayAllowed,false);assert.equal(b.productImplementationAllowed,false);assert.equal(b.publicProductAdmissionAllowed,false);const d=preflight.preflightDecision;assert.equal(d.exactFrozenQueueRowResolved,true);assert.equal(d.sourceAuthoritySufficientForQ057ImplementationPlanning,true);assert.equal(d.previousSliceD0Satisfied,true);assert.equal(d.r02AuthorityBoundForTargetKnowledgePoint,true);assert.equal(d.runtimeCapabilityContractLocked,true);assert.equal(d.sameSourcePriorSliceOwnershipProtected,true);assert.equal(d.q062FutureSameSourceOwnershipProtected,true);assert.equal(d.q037Q046SameSourceIdentityReusedWithoutReclassification,true);assert.equal(d.manualSourceChoiceRequired,false);assert.equal(d.sourceRefAmbiguity,false);assert.equal(d.separateImplementationApprovalSatisfiedByCurrentOperatorInstruction,false);assert.equal(d.nextTaskRequiresNewOperatorApproval,true);assert.equal(d.nextTask,"P05F_W5DirectProductVerticalSlice057Implementation");});
