import test from "node:test";
import assert from "node:assert/strict";
import {buildBatchABrowserWorksheetDocument as buildStableWorksheet} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-r2e-entry.js";
import {requestsP05F15} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p05f15.js";
import {G5A_U05A1_P05F15_FUTURE_KP_IDS,G5A_U05A1_P05F15_KP_ID,G5A_U05A1_P05F15_SOURCE_ID} from "../../site/modules/curriculum/registry/g5a-u05a1-sector-elements-selector-projection-p05f15.js";
import {listBatchAKnowledgePointAvailabilityBySource} from "../../site/modules/curriculum/registry/batch-a-selector-p05f15-extension.js";
test("P05F W5 Q015 owns first same-source sourceUnit route",()=>{const options={sourceId:G5A_U05A1_P05F15_SOURCE_ID,selectionMode:"sourceUnit",questionCount:8,generationSeed:"q015-sourceunit",includeAnswerKey:true,printLayout:{columns:2,rowsPerPage:4,showAnswerKeyPage:true}};assert.equal(requestsP05F15(options),true);const result=buildStableWorksheet(options);assert.equal(result.ok,true,result.errors?.join(","));assert.equal(result.p05f15Implemented,true);assert.equal(result.worksheetDocument.metadata.taskId,"P05F_W5DirectProductVerticalSlice015Implementation");assert.equal(result.worksheetDocument.metadata.knowledgePointId,G5A_U05A1_P05F15_KP_ID);assert.equal(result.worksheetDocument.metadata.q016OrLaterTouched,false);});
test("P05F W5 Q015 does not steal Q014 explicit route",()=>{const result=buildStableWorksheet({sourceId:"g4b_u10_4b10",selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:["kp_g4b_u10_unit_cube_counting"],questionCount:8,generationSeed:"q015-q014-protection",includeAnswerKey:true,printLayout:{columns:2,rowsPerPage:4,showAnswerKeyPage:true}});assert.equal(result.ok,true,result.errors?.join(","));assert.equal(result.p05f14Implemented,true);assert.equal(result.worksheetDocument.metadata.taskId,"P05F_W5DirectProductVerticalSlice014Implementation");});
test("P05F W5 Q015 selector keeps future siblings hidden and rejects mixed activation",()=>{const source=listBatchAKnowledgePointAvailabilityBySource(G5A_U05A1_P05F15_SOURCE_ID);assert.deepEqual(source.visibleKnowledgePointIds,[G5A_U05A1_P05F15_KP_ID]);for(const id of G5A_U05A1_P05F15_FUTURE_KP_IDS){assert.ok(source.hiddenPendingKnowledgePointIds.includes(id));assert.ok(source.notSelectableKnowledgePointIds.includes(id));}assert.equal(requestsP05F15({sourceId:G5A_U05A1_P05F15_SOURCE_ID,selectionMode:"mixedKnowledgePointsSameUnit",selectedKnowledgePointIds:[G5A_U05A1_P05F15_KP_ID,...G5A_U05A1_P05F15_FUTURE_KP_IDS.slice(0,1)]}),false);assert.equal(requestsP05F15({sourceId:G5A_U05A1_P05F15_SOURCE_ID,selectionMode:"mixedKnowledgePointsCrossUnit",selectedKnowledgePointIds:[G5A_U05A1_P05F15_KP_ID]}),false);});
