import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {G5A_U05A_P05F56_FORMAL_MAPPING as MAP,G5A_U05A_P05F56_INCLUDED_RELATIONS as RELATIONS,G5A_U05A_P05F56_KP_ID as KP,G5A_U05A_P05F56_PATTERN_GROUP_ID as GROUP,G5A_U05A_P05F56_PATTERN_SPECS as PATTERNS,G5A_U05A_P05F56_PRIOR_VISIBLE_KP_IDS as PRIOR,G5A_U05A_P05F56_PROTECTED_KP_IDS as PROTECTED,G5A_U05A_P05F56_REQUIRED_CAPABILITY_IDS as REQUIRED,G5A_U05A_P05F56_OPTIONAL_CAPABILITY_IDS as OPTIONAL,G5A_U05A_P05F56_SOURCE_ID as SRC,G5A_U05A_P05F56_SPEC_IDS as SPECS,auditG5AU05AP05F56Projection} from "../../site/modules/curriculum/registry/g5a-u05-polygon-triangulation-selector-projection-p05f56.js";
import {auditP05F56PublicSelectorComposition,getVisibleBatchAKnowledgePoint,listBatchAKnowledgePointAvailabilityBySource} from "../../site/modules/curriculum/registry/batch-a-selector-p05f56-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p05f56.js";
import {generateG5AU05AP05F56Questions,validateG5AU05AP05F56Question} from "../../site/modules/curriculum/batch-a/g5a-u05-polygon-triangulation-runtime-p05f56.js";
import {requestsP05F56} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p05f56.js";
import {buildBatchABrowserWorksheetDocument as buildQ056} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f56-extension.js";
import {buildBatchABrowserWorksheetDocument as buildCurrent} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f32-extension.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";
const preflight=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q056-g5a-u05-polygon-triangulation-source-authority-preflight.json",import.meta.url),"utf8"));
const implementation=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q056-g5a-u05-polygon-triangulation-implementation.json",import.meta.url),"utf8"));
const impact=JSON.parse(readFileSync(new URL("../../data/project/change-impact/P05F_W5_Q056.impact.json",import.meta.url),"utf8"));
const plan=JSON.parse(readFileSync(new URL("../../data/project/validation-plans/P05F_W5_Q056.validation.json",import.meta.url),"utf8"));
const req=(count=24)=>({sourceId:SRC,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[KP],selectedPatternGroupIds:[GROUP],patternSpecIds:[...SPECS],questionMode:"diagram",requestedQuestionType:"diagram",questionCount:count,generationSeed:"p05f56-focused-polygon-triangulation",includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showQuestionNumbers:true,showAnswerKeyPage:true}});
const occ=(t,x)=>t.split(x).length-1;

test("Q056 exact frozen identity and page-1 R02 authority remain locked",()=>{assert.equal(preflight.status,"PASS_SOURCE_AUTHORITY_PREFLIGHT");assert.equal(preflight.queueAuthority.queuePosition,56);assert.equal(preflight.queueAuthority.sliceId,"p05e_q056_r6_g5a_u05_5a05a_profile_geometry_property_c1");assert.deepEqual(preflight.queueAuthority.knowledgePointIds,[KP]);assert.equal(preflight.previousSliceD0Evidence.status,"PASS_E6_D0_COMPLETE");assert.equal(implementation.queueAuthority.runtimeProfileId,"profile_geometry_property");assert.deepEqual(implementation.sourceAuthority.sourcePages,[1]);assert.equal(MAP.r04MappingId,"r04map_g5a_u05a_polygon_triangulation");assert.deepEqual(MAP.sourcePages,[1]);assert.equal(MAP.capabilityStatement,"學生能由同一頂點畫對角線將多邊形分割成三角形。");assert.equal(MAP.reasoningInvariant,"n邊形可由同一頂點分成n減2個不重疊三角形。");});

test("Q056 materializes one mapping one group and three exact relation PatternSpecs",()=>{const a=auditG5AU05AP05F56Projection();assert.equal(a.ok,true,a.errors.join("\n"));assert.equal(PATTERNS.length,3);assert.deepEqual(PATTERNS.map(x=>x.relation),RELATIONS);assert.deepEqual(REQUIRED,["cap_geometry_diagram_representation","cap_geometry_domain_validator","cap_geometry_property_reasoning"]);assert.deepEqual(OPTIONAL,["cap_geometry_construction"]);assert.equal(MAP.geometryConstructionRequired,false);assert.equal(MAP.interactiveConstructionAllowed,false);assert.equal(MAP.applicationImplementationAllowed,false);});

test("Q056 promotes triangulation only while preserving three prior owners and hiding angle sum",()=>{const a=auditP05F56PublicSelectorComposition();assert.equal(a.ok,true,a.errors.join("\n"));const s=listBatchAKnowledgePointAvailabilityBySource(SRC);assert.equal(s.visibleCount,4);assert.equal(s.hiddenPendingCount,1);assert.equal(s.notSelectableCount,1);for(const id of [...PRIOR,KP])assert.equal(getVisibleBatchAKnowledgePoint(id)?.sourceId,SRC,id);for(const id of PROTECTED)assert.equal(getVisibleBatchAKnowledgePoint(id),null,id);});

test("Q056 public binding is single-KP diagram-only and keeps construction optional",()=>{assert.equal(auditPublicUiCapabilityBinding().ok,true);const b=resolvePublicUiCapabilityBinding(req());assert.equal(b.blocked,false);assert.equal(b.questionType,"diagram");assert.equal(b.questionCount.max,240);assert.equal(b.sourceBackedPolygonTriangulation,true);assert.equal(b.commonOriginVertexInvariant,true);assert.equal(b.triangleCountInvariant,true);assert.equal(b.nonOverlappingInteriorCoverage,true);assert.equal(b.geometryConstructionRequired,false);assert.equal(b.interactiveConstructionAllowed,false);assert.deepEqual(b.optionalCapabilityIds,["cap_geometry_construction"]);assert.equal(requestsP05F56(req()),true);assert.equal(requestsP05F56({...req(),selectionMode:"sourceUnit"}),false);assert.equal(requestsP05F56({...req(),selectedKnowledgePointIds:[KP,PRIOR[0]]}),false);});

test("Q056 every PatternSpec yields 240 deterministic distinct valid variants",()=>{for(const id of SPECS){const a=generateG5AU05AP05F56Questions({knowledgePointId:KP,patternSpecIds:[id],questionCount:240,generationSeed:id}),b=generateG5AU05AP05F56Questions({knowledgePointId:KP,patternSpecIds:[id],questionCount:240,generationSeed:id});assert.equal(a.ok,true,`${id}:${a.errors.join("\n")}`);assert.deepEqual(a.questions,b.questions);assert.equal(new Set(a.questions.map(q=>q.questionSignature)).size,240);assert.ok(a.questions.every(q=>validateG5AU05AP05F56Question(q).ok));const t=JSON.parse(JSON.stringify(a.questions[0]));t.answerText="錯誤";assert.equal(validateG5AU05AP05F56Question(t).ok,false);}});

test("Q056 triangulation semantics enforce one origin n-3 diagonals n-2 non-overlapping covering triangles",()=>{const r=generateG5AU05AP05F56Questions({knowledgePointId:KP,questionCount:240,generationSeed:"q056-semantics"});assert.equal(r.ok,true,r.errors.join("\n"));for(const q of r.questions){const d=q.geometryDiagram;assert.equal(d.diagonalCount,d.sideCount-3);assert.equal(d.triangleCount,d.sideCount-2);assert.equal(d.diagonals.length,d.sideCount-3);assert.equal(d.triangles.length,d.sideCount-2);assert.equal(d.commonOriginVertex,true);assert.equal(d.nonOverlapping,true);assert.equal(d.coversPolygonInterior,true);for(const x of d.diagonals){assert.equal(x.startIndex,d.originIndex);const adjacent=((d.originIndex+1)%d.sideCount===x.endIndex)||((x.endIndex+1)%d.sideCount===d.originIndex);assert.equal(adjacent,false);}for(const tri of d.triangles){assert.equal(tri[0],d.originIndex);assert.equal(new Set(tri).size,3);}}});

test("Q056 worksheet and current bridge render questions answers and triangulation diagrams without internal IDs",async()=>{const r=buildQ056(req(18));assert.equal(r.ok,true,r.errors.join("\n"));assert.equal(r.worksheetDocument.questionCount,18);assert.equal(r.worksheetDocument.answerKeyItems.length,18);const html=renderWorksheetDocumentToHtml(r.worksheetDocument,{stylesheetHref:"",title:r.worksheetDocument.title,debugDataAttributes:false});assert.equal(occ(html,'data-representation="polygon-triangulation-diagram"'),36);assert.equal(html.includes("kp_g5a_u05a_"),false);assert.equal(html.includes("ps_g5a_u05a_"),false);const current=buildCurrent(req(9));assert.equal(current.ok,true,current.errors.join("\n"));assert.equal(current.p05f56Implemented,true);assert.equal(current.worksheetDocument.metadata.knowledgePointId,KP);globalThis.document={};try{const selector=await import(`../../site/modules/curriculum/registry/batch-a-selector-p04f33-extension.js?p05f56=${Date.now()}`),binding=await import(`../../site/modules/curriculum/public/public-ui-capability-binding-p04f33.js?p05f56=${Date.now()}`);for(const id of [...PRIOR,KP])assert.equal(selector.getVisibleBatchAKnowledgePoint(id)?.sourceId,SRC,id);for(const id of PROTECTED)assert.equal(selector.getVisibleBatchAKnowledgePoint(id),null,id);assert.equal(binding.resolvePublicUiCapabilityBinding(req()).sourceBackedPolygonTriangulation,true);}finally{delete globalThis.document;}});

test("Q056 validation remains SHARED_RUNTIME_BOUNDED and scope guard stays closed",()=>{assert.equal(impact.expectedDerivedGate,"SHARED_RUNTIME_BOUNDED");assert.equal(impact.changeImpact.affectedRoutes,"BOUNDED");assert.equal(impact.changeImpact.legalRouteSemanticsChanged,false);assert.equal(plan.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(plan.lanes.SHARED_RUNTIME_BOUNDED[0].kind,"NODE_TEST");assert.equal(plan.lanes.SHARED_RUNTIME_BOUNDED[1].runtime,"PLAYWRIGHT_CHROMIUM");assert.equal(implementation.validation.fullRepositoryRegression,"FORBIDDEN");assert.equal(implementation.validation.globalBrowserReplay,"FORBIDDEN");for(const v of Object.values(implementation.scopeGuard))assert.equal(v,false);});
