import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {buildBatchABrowserWorksheetDocument as buildQ060Worksheet} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f60-extension.js";
import {buildBatchABrowserWorksheetDocument as buildCurrentWorksheet} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f32-extension.js";
import {requestsP05F60} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p05f60.js";
import {generateG6BU03P05F60Questions,validateG6BU03P05F60Question} from "../../site/modules/curriculum/batch-a/g6b-u03-triangular-composite-prism-runtime-p05f60.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";
import {validatePrismPyramidElementsDiagramModel} from "../../site/modules/renderer/prism-pyramid-elements-diagram.js";
import {validateLayeredCubeVolumeDiagramModel} from "../../site/modules/renderer/cubic-centimeter-unit-diagram.js";
import {auditG6BU03P05F60Projection,G6B_U03_P05F60_COMPOSITE_KP_ID as COMPOSITE_KP,G6B_U03_P05F60_FORMAL_MAPPINGS as MAPPINGS,G6B_U03_P05F60_PATTERN_GROUPS as GROUPS,G6B_U03_P05F60_PATTERN_SPECS as PATTERNS,G6B_U03_P05F60_PROTECTED_KP_IDS as PROTECTED,G6B_U03_P05F60_SOURCE_ID as SRC,G6B_U03_P05F60_TARGET_KP_IDS as TARGETS,G6B_U03_P05F60_TRIANGULAR_KP_ID as TRIANGULAR_KP} from "../../site/modules/curriculum/registry/g6b-u03-triangular-composite-prism-selector-projection-p05f60.js";
import {auditP05F60PublicSelectorComposition,getVisibleBatchAKnowledgePoint,listBatchAKnowledgePointAvailabilityBySource,resolveVisiblePatternSpecIdsForKnowledgePoint} from "../../site/modules/curriculum/registry/batch-a-selector-p05f60-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p05f60.js";
import {G6B_U03_P05F49_FORMAL_MAPPING as Q049_MAPPING} from "../../site/modules/curriculum/registry/g6b-u03-prism-surface-area-selector-projection-p05f49.js";
import {G6B_U03_P05F55_FORMAL_MAPPING as Q055_MAPPING} from "../../site/modules/curriculum/registry/g6b-u03-prism-base-area-height-volume-selector-projection-p05f55.js";
const read=p=>JSON.parse(readFileSync(new URL(`../../${p}`,import.meta.url),"utf8"));
const preflight=read("data/curriculum/full-product/p05f/q060-g6b-u03-triangular-composite-prism-source-authority-preflight.json");
const implementation=read("data/curriculum/full-product/p05f/q060-g6b-u03-triangular-composite-prism-implementation.json");
const impact=read("data/project/change-impact/P05F_W5_Q060.impact.json");
const plan=read("data/project/validation-plans/P05F_W5_Q060.validation.json");
const groupFor=kp=>GROUPS.find(x=>x.primaryKnowledgePointId===kp);
const specsFor=kp=>PATTERNS.filter(x=>x.knowledgePointId===kp).map(x=>x.patternSpecId);
const opts=(kp,count=16)=>({sourceId:SRC,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[kp],selectedPatternGroupIds:[groupFor(kp).patternGroupId],patternSpecIds:specsFor(kp),questionMode:"diagram",requestedQuestionType:"diagram",questionCount:count,generationSeed:`p05f60-${kp}`,includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showQuestionNumbers:true,showAnswerKeyPage:true}});
const occ=(t,x)=>t.split(x).length-1;

test("Q060 exact frozen two-KP identity consumes Q059 D0 and preserves scope",()=>{assert.equal(preflight.status,"PASS_SOURCE_AUTHORITY_PREFLIGHT");assert.equal(preflight.queueAuthority.queuePosition,60);assert.equal(preflight.queueAuthority.sliceId,"p05e_q060_r6_g6b_u03_6b03_profile_spatial_solid_c1");assert.deepEqual(preflight.queueAuthority.knowledgePointIds,[COMPOSITE_KP,TRIANGULAR_KP]);assert.equal(preflight.previousSliceD0Evidence.status,"PASS_E6_D0_COMPLETE");assert.equal(preflight.previousSliceD0Evidence.productPrNumber,962);assert.equal(implementation.taskId,"P05F_W5DirectProductVerticalSlice060Implementation");assert.deepEqual(implementation.queueAuthority.knowledgePointIds,[COMPOSITE_KP,TRIANGULAR_KP]);assert.equal(implementation.runtimeContract.frozenRuntimeProfile,"profile_spatial_solid");for(const v of Object.values(implementation.scopeGuard))assert.equal(v,false);});

test("Q060 materializes two mappings two groups and four exact bounded PatternSpecs",()=>{const a=auditG6BU03P05F60Projection();assert.equal(a.ok,true,a.errors.join("\n"));assert.deepEqual(a.counts,{knowledgePoints:2,patternGroups:2,patternSpecs:4,formalMappings:2});assert.deepEqual(MAPPINGS.map(x=>x.knowledgePointId),[COMPOSITE_KP,TRIANGULAR_KP]);assert.ok(MAPPINGS.every(x=>x.sourcePages.join(",")==="1,2"&&!x.applicationImplementationAllowed));assert.equal(Q049_MAPPING.knowledgePointId,"kp_g6b_u03_prism_surface_area");assert.equal(Q055_MAPPING.knowledgePointId,"kp_g6b_u03_prism_base_area_height_volume");});

test("Q060 selector promotes both targets while cylinder remains hidden",()=>{const a=auditP05F60PublicSelectorComposition();assert.equal(a.ok,true,a.errors.join("\n"));const s=listBatchAKnowledgePointAvailabilityBySource(SRC);assert.equal(s.visibleCount,4);assert.equal(s.hiddenPendingCount,1);assert.equal(s.notSelectableCount,1);for(const id of TARGETS){assert.ok(getVisibleBatchAKnowledgePoint(id),id);assert.equal(resolveVisiblePatternSpecIdsForKnowledgePoint(id,"diagram").length,2,id);}for(const id of PROTECTED){assert.equal(getVisibleBatchAKnowledgePoint(id),null,id);assert.ok(s.hiddenPendingKnowledgePointIds.includes(id),id);}});

test("Q060 public bindings allow each target singly and reject mixed/source-unit activation",()=>{const a=auditPublicUiCapabilityBinding();assert.equal(a.ok,true,a.errors.join("\n"));for(const kp of TARGETS){const b=resolvePublicUiCapabilityBinding(opts(kp));assert.equal(b.blocked,false);assert.equal(b.questionType,"diagram");assert.equal(b.patternSpecIds.length,2);assert.equal(b.questionCount.max,240);assert.equal(b.frozenRuntimeProfile,"profile_spatial_solid");assert.equal(b.q049PrismSurfaceAreaReowned,false);assert.equal(b.q055PrismBaseAreaHeightVolumeReowned,false);assert.equal(b.cylinderAdmission,false);assert.equal(requestsP05F60(opts(kp)),true);assert.equal(requestsP05F60({...opts(kp),selectionMode:"sourceUnit"}),false);}assert.equal(requestsP05F60({...opts(COMPOSITE_KP),selectedKnowledgePointIds:[COMPOSITE_KP,TRIANGULAR_KP]}),false);});

test("Q060 proves 240 deterministic unique variants per PatternSpec with correct geometry invariants",()=>{for(const spec of PATTERNS){const o={knowledgePointId:spec.knowledgePointId,patternSpecIds:[spec.patternSpecId],questionCount:240,generationSeed:`q060-${spec.patternSpecId}`},a=generateG6BU03P05F60Questions(o),b=generateG6BU03P05F60Questions(o);assert.equal(a.ok,true,`${spec.patternSpecId}:${a.errors.join("\n")}`);assert.deepEqual(a.questions,b.questions);assert.equal(new Set(a.questions.map(q=>q.questionSignature)).size,240,spec.patternSpecId);assert.equal(new Set(a.questions.map(q=>q.promptText)).size,240,spec.patternSpecId);for(const q of a.questions){assert.equal(validateG6BU03P05F60Question(q).ok,true,spec.patternSpecId);if(q.knowledgePointId===TRIANGULAR_KP){assert.equal(validatePrismPyramidElementsDiagramModel(q.geometryDiagram).ok,true);const d=q.geometryDiagram;assert.equal(d.baseArea,d.triangleBase*d.trianglePerpendicularHeight/2);assert.equal(d.volume,d.baseArea*d.prismHeight);assert.equal(d.perpendicularHeightUsed,true);}else{assert.equal(validateLayeredCubeVolumeDiagramModel(q.geometryDiagram).ok,true);const d=q.geometryDiagram;assert.equal(d.volume,d.totalCubeCount);assert.equal(d.surfaceArea,d.componentSurfaceSum-2*d.contactArea);}}}});

test("Q060 validator fails closed on formulas geometry scope and cross-KP PatternSpec tampering",()=>{const triangular=generateG6BU03P05F60Questions({...opts(TRIANGULAR_KP,1),patternSpecIds:[specsFor(TRIANGULAR_KP)[0]]}).questions[0],composite=generateG6BU03P05F60Questions({...opts(COMPOSITE_KP,1),patternSpecIds:[specsFor(COMPOSITE_KP)[0]]}).questions[0];for(const [q,mutate] of [[triangular,x=>x.answerValue++],[triangular,x=>x.geometryDiagram.volume++],[triangular,x=>x.metadata.q055PrismBaseAreaHeightVolumeReowned=true],[composite,x=>x.geometryDiagram.surfaceArea++],[composite,x=>x.metadata.cylinderTouched=true]]){const t=JSON.parse(JSON.stringify(q));mutate(t);assert.equal(validateG6BU03P05F60Question(t).ok,false);}const mixed=JSON.parse(JSON.stringify(triangular));mixed.patternSpecId=specsFor(COMPOSITE_KP)[0];assert.equal(validateG6BU03P05F60Question(mixed).ok,false);});

test("Q060 worksheet and current bridge render both target routes with answers and no internal ids",async()=>{for(const kp of TARGETS){const r=buildQ060Worksheet(opts(kp,8));assert.equal(r.ok,true,r.errors.join("\n"));assert.equal(r.worksheetDocument.questionCount,8);assert.equal(r.worksheetDocument.answerKeyItems.length,8);const html=renderWorksheetDocumentToHtml(r.worksheetDocument,{stylesheetHref:"",title:r.worksheetDocument.title,debugDataAttributes:false}),rep=kp===COMPOSITE_KP?"layered-cube-volume-diagram":"prism-pyramid-elements-diagram";assert.equal(occ(html,`data-representation="${rep}"`),16);assert.equal(html.includes("kp_g6b_u03_"),false);assert.equal(html.includes("ps_g6b_u03_"),false);const current=buildCurrentWorksheet(opts(kp,6));assert.equal(current.ok,true,current.errors.join("\n"));assert.equal(current.p05f60Implemented,true);}globalThis.document={};try{const s=await import(`../../site/modules/curriculum/registry/batch-a-selector-p04f33-extension.js?p05f60=${Date.now()}`),b=await import(`../../site/modules/curriculum/public/public-ui-capability-binding-p04f33.js?p05f60=${Date.now()}`);for(const kp of TARGETS){assert.equal(s.getVisibleBatchAKnowledgePoint(kp)?.sourceId,SRC);assert.equal(b.resolvePublicUiCapabilityBinding(opts(kp)).blocked,false);}for(const id of PROTECTED)assert.equal(s.getVisibleBatchAKnowledgePoint(id),null);}finally{delete globalThis.document;}});

test("Q060 validation remains SHARED_RUNTIME_BOUNDED without full regression or global replay",()=>{assert.equal(impact.expectedDerivedGate,"SHARED_RUNTIME_BOUNDED");assert.equal(impact.changeImpact.affectedRoutes,"BOUNDED");assert.equal(impact.changeImpact.legalRouteSemanticsChanged,false);assert.equal(plan.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(plan.lanes.SHARED_RUNTIME_BOUNDED[0].kind,"NODE_TEST");assert.equal(plan.lanes.SHARED_RUNTIME_BOUNDED[1].runtime,"PLAYWRIGHT_CHROMIUM");assert.equal(implementation.validation.fullRepositoryRegression,"FORBIDDEN");assert.equal(implementation.validation.globalBrowserReplay,"FORBIDDEN");});
