import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";
import {materializeP05EW5DirectProductVerticalSliceQueue} from "../../src/curriculum/full-product/p05e-w5-direct-product-vertical-slice-queue.mjs";
import {materializeR04SharedRuntimeCapabilityMatrix} from "../../src/curriculum/global/r04-shared-runtime-capability-matrix.mjs";
import {materializeR05DeliveryWaveRebase} from "../../src/curriculum/global/r05-delivery-wave-rebase.mjs";

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");
const read=p=>JSON.parse(fs.readFileSync(path.join(ROOT,p),"utf8"));
const preflight=read("data/curriculum/full-product/p05f/q035-g4b-u10-rectangular-prism-volume-structure-source-authority-preflight.json");
const q027=read("data/curriculum/full-product/p05f/q027-g4b-u10-layered-cube-volume-conservation-source-authority-preflight.json");
const r02=read("data/curriculum/global/candidates/r02/chunks/reviewed-source-candidates-02.json");
const KP="kp_g4b_u10_rectangular_prism_volume_structure";
const REQUIRED_W5=["cap_geometry_domain_validator","cap_geometry_property_reasoning","cap_solid_geometry_representation","cap_spatial_solid_reasoning"];
const PROFILE_REQUIRED=["cap_spatial_solid_reasoning","cap_geometry_domain_validator","cap_solid_geometry_representation"];
const PROFILE_OPTIONAL=["cap_geometry_construction"];
const PROTECTED=["kp_g4b_u10_cubic_centimeter_unit","kp_g4b_u10_unit_cube_counting","kp_g4b_u10_layered_cube_counting","kp_g4b_u10_volume_conservation_rearrangement"];
const sorted=values=>[...values].sort();

test("Q035 binds exact frozen queue row and Q034 D0 predecessor",()=>{
  const queue=materializeP05EW5DirectProductVerticalSliceQueue();
  assert.equal(queue.status,"W5_DIRECT_PRODUCT_VERTICAL_SLICE_QUEUE_FROZEN");
  assert.equal(queue.queueFrozen,true);
  assert.equal(queue.queueRegistryParity,true);
  const row=queue.queueEntries.find(x=>x.queuePosition===35); assert.ok(row);
  assert.equal(row.sliceId,"p05e_q035_r3_g4b_u10_4b10_profile_spatial_solid_c1");
  assert.equal(row.implementationTaskId,"P05F_W5DirectProductVerticalSlice035Implementation");
  assert.equal(row.previousSliceId,"p05e_q034_r3_g4b_u07_4b07_profile_geometry_formula_c1");
  assert.equal(row.previousSliceMustBeD0Complete,true);
  assert.equal(row.assignedDeliveryWaveId,"R05-W5");
  assert.equal(row.primarySourceNodeId,"g4b_u10_4b10");
  assert.deepEqual(row.supportingSourceNodeIds,["g4b_u10_4b10"]);
  assert.equal(row.intraWavePrerequisiteRank,3);
  assert.equal(row.primaryRuntimeProfileId,"profile_spatial_solid");
  assert.equal(row.chunkIndex,1);
  assert.equal(row.knowledgePointCount,1);
  assert.deepEqual(row.knowledgePointIds,[KP]);
  assert.deepEqual(sorted(row.requiredW5CapabilityIds),sorted(REQUIRED_W5));
  assert.equal(row.targetEvidenceLevel,"E6_D0_COMPLETE");
  assert.equal(preflight.queueAuthority.queueDigest,queue.derivedRegistrySnapshot.queueDigest);
  assert.deepEqual(preflight.queueAuthority.knowledgePointIds,row.knowledgePointIds);
  assert.equal(preflight.previousSliceD0Evidence.preflightPrNumber,909);
  assert.equal(preflight.previousSliceD0Evidence.productPrNumber,911);
  assert.equal(preflight.previousSliceD0Evidence.productMergeSha,"d0e587622f47684047f9a7736cf902bd01a5e39b");
  assert.equal(preflight.previousSliceD0Evidence.prGateRunId,"34750338546");
  assert.equal(preflight.previousSliceD0Evidence.pagesDeploymentRunId,"34750391911");
  assert.equal(preflight.previousSliceD0Evidence.exactPagesRunId,"34750391879");
  assert.equal(preflight.previousSliceD0Evidence.evidenceArtifactId,"10314939914");
  assert.equal(preflight.previousSliceD0Evidence.evidenceArtifactDigest,"sha256:2501e0fdedf2dea1d8b5336156f0f981c7d03eb4428544c3f3e20bca94a12144");
  assert.equal(preflight.previousSliceD0Evidence.status,"PASS_E6_D0_COMPLETE");
});

test("Q035 binds exact R02 rectangular-prism volume-structure candidate",()=>{
  const source=r02.sourceRecords.find(x=>x.sourceNodeId==="g4b_u10_4b10"); assert.ok(source);
  assert.equal(source.sourceTitle,"立方公分與體積");
  assert.equal(source.sourcePdfTitle,"meow911_4b10_source.pdf");
  assert.equal(source.pageCount,2);
  assert.deepEqual(source.reviewedPages,[1,2]);
  const candidate=source.candidates.find(x=>x.knowledgePointId===KP); assert.ok(candidate);
  assert.equal(candidate.canonicalNameZh,"長方體體積乘法結構");
  assert.equal(candidate.capabilityStatement,"學生能由長、寬、高的單位方塊排列理解體積。");
  assert.equal(candidate.reasoningInvariant,"每層為長乘寬，總體積再乘高度。");
  assert.equal(candidate.category,"geometry");
  assert.deepEqual(candidate.evidencePages,[1,2]);
  assert.equal(candidate.applicationSuitability,"APPLICATION_COMPATIBLE");
  const bound=preflight.r02ReviewedCandidateAuthority.knowledgePoint;
  assert.equal(bound.knowledgePointId,candidate.knowledgePointId);
  assert.equal(bound.canonicalNameZh,candidate.canonicalNameZh);
  assert.equal(bound.capabilityStatement,candidate.capabilityStatement);
  assert.equal(bound.reasoningInvariant,candidate.reasoningInvariant);
  assert.deepEqual(bound.evidencePages,candidate.evidencePages);
  assert.deepEqual(preflight.r02ReviewedCandidateAuthority.sameSourceCandidateIds,source.candidates.map(x=>x.knowledgePointId));
});

test("Q035 reuses Q027 exact page-2 visual evidence and verified source identity",()=>{
  assert.equal(q027.sourceAuthority.sourceNodeId,preflight.sourceAuthority.sourceNodeId);
  assert.equal(q027.sourceAuthority.sourcePdfTitle,preflight.sourceAuthority.sourcePdfTitle);
  assert.equal(q027.sourceAuthority.sourcePdfDriveFileId,preflight.sourceAuthority.sourcePdfDriveFileId);
  assert.equal(q027.sourceAuthority.sourceMetadataDriveFileId,preflight.sourceAuthority.sourceMetadataDriveFileId);
  assert.equal(q027.sourceAuthority.verificationNotesDriveFileId,preflight.sourceAuthority.verificationNotesDriveFileId);
  assert.equal(q027.sourceAuthority.sourceUrlFromMetadata,preflight.sourceAuthority.sourceUrlFromMetadata);
  assert.equal(q027.sourceAuthority.embeddedHeaderUrlFromPdf,preflight.sourceAuthority.embeddedHeaderUrlFromPdf);
  assert.ok(q027.sourceAuthority.directVisualEvidence.page2.observedPanels.includes("長方體的體積公式"));
  assert.ok(q027.sourceAuthority.directVisualEvidence.page2.observedPanels.includes("用1立方公分積木堆成的形體求體積"));
  assert.ok(q027.sourceAuthority.directVisualEvidence.page2.useRestriction.includes("not admitted into Q027"));
  assert.deepEqual(preflight.sourceAuthority.targetEvidenceReconciliation.rectangularPrismVolumeStructure.q027DirectVisualCorroborationPages,[2]);
  assert.equal(preflight.sourceAuthority.targetEvidenceReconciliation.rectangularPrismVolumeStructure.q027RestrictionReleasedOnlyForExactQ035Target,true);
  assert.equal(preflight.sourceAuthority.targetEvidenceReconciliation.r02AuthorityModified,false);
  assert.equal(preflight.sourceAuthority.sourceIdentityReuse.sameSourceNodeConfirmed,true);
  assert.equal(preflight.sourceAuthority.sourceIdentityReuse.samePdfIdentityConfirmed,true);
  assert.equal(preflight.sourceAuthority.sourceIdentityReuse.sourceRefAmbiguity,false);
  assert.equal(preflight.sourceAuthority.manualSourceChoiceRequired,false);
});

test("Q035 binds current R04 spatial-solid mapping and exact R05 dependency-closed W5 capabilities",()=>{
  const r04=materializeR04SharedRuntimeCapabilityMatrix();
  const r05=materializeR05DeliveryWaveRebase();
  const mapping=r04.getMapping(KP); assert.ok(mapping);
  const profile=r04.profiles.find(x=>x.profileId==="profile_spatial_solid"); assert.ok(profile);
  assert.equal(mapping.mappingId,"r04map_g4b_u10_rectangular_prism_volume_structure");
  assert.equal(mapping.primaryRuntimeProfileId,"profile_spatial_solid");
  assert.equal(mapping.classificationRuleId,"rule_spatial_solid");
  assert.deepEqual(mapping.appliedModifierIds,[]);
  for(const capabilityId of PROFILE_REQUIRED) assert.ok(mapping.requiredRuntimeCapabilityIds.includes(capabilityId),capabilityId);
  assert.deepEqual(profile.optionalCapabilityIds,PROFILE_OPTIONAL);
  assert.deepEqual(mapping.optionalRuntimeCapabilityIds,PROFILE_OPTIONAL);
  assert.deepEqual(mapping.forbiddenRuntimeCapabilityIds,[]);
  assert.deepEqual(preflight.runtimeCapabilityAuthority.mapping.requiredRuntimeCapabilityIds,mapping.requiredRuntimeCapabilityIds);
  assert.deepEqual(preflight.runtimeCapabilityAuthority.mapping.optionalRuntimeCapabilityIds,mapping.optionalRuntimeCapabilityIds);
  assert.deepEqual(preflight.runtimeCapabilityAuthority.mapping.forbiddenRuntimeCapabilityIds,mapping.forbiddenRuntimeCapabilityIds);
  assert.deepEqual(preflight.runtimeCapabilityAuthority.profileOptionalCapabilityIds,PROFILE_OPTIONAL);
  const assignment=r05.getAssignment(KP); assert.ok(assignment);
  assert.equal(assignment.deliveryWaveId,"R05-W5");
  assert.equal(assignment.intraWavePrerequisiteRank,3);
  assert.equal(assignment.primaryRuntimeProfileId,"profile_spatial_solid");
  assert.deepEqual(sorted(assignment.contractOnlyRequiredCapabilityIds),sorted(REQUIRED_W5));
  assert.equal(preflight.runtimeCapabilityAuthority.mapping.mappingId,mapping.mappingId);
  assert.deepEqual(preflight.runtimeCapabilityAuthority.profileRequiredCapabilityIds,PROFILE_REQUIRED);
  assert.deepEqual(preflight.runtimeCapabilityAuthority.r05DependencyClosureCapabilityIds,["cap_geometry_property_reasoning"]);
  assert.deepEqual(sorted(preflight.runtimeCapabilityAuthority.exactFrozenQueueRequiredW5CapabilityIds),sorted(REQUIRED_W5));
  assert.deepEqual(sorted(preflight.queueAuthority.requiredW5CapabilityIds),sorted(REQUIRED_W5));
});

test("Q035 scope owns only the rectangular-prism multiplicative structure and protects Q005 Q014 Q027",()=>{
  assert.deepEqual(preflight.q035ScopeLock.includedKnowledgePointIds,[KP]);
  assert.deepEqual(preflight.q035ScopeLock.protectedExistingSameSourceKnowledgePointIds,PROTECTED);
  assert.equal(preflight.q035ScopeLock.protectedFrozenQueueOwnership.kp_g4b_u10_cubic_centimeter_unit,"Q005");
  assert.equal(preflight.q035ScopeLock.protectedFrozenQueueOwnership.kp_g4b_u10_unit_cube_counting,"Q014");
  assert.equal(preflight.q035ScopeLock.protectedFrozenQueueOwnership.kp_g4b_u10_layered_cube_counting,"Q027");
  assert.equal(preflight.q035ScopeLock.protectedFrozenQueueOwnership.kp_g4b_u10_volume_conservation_rearrangement,"Q027");
  assert.ok(preflight.q035ScopeLock.includedRelations.includes("COUNT_ONE_LAYER_AS_LENGTH_TIMES_WIDTH"));
  assert.ok(preflight.q035ScopeLock.includedRelations.includes("COUNT_ALL_LAYERS_AS_LENGTH_TIMES_WIDTH_TIMES_HEIGHT"));
  assert.equal(preflight.q035ScopeLock.lengthWidthHeightMustRemainUnitCubeArrayDimensions,true);
  assert.equal(preflight.q035ScopeLock.layerMultiplicationStructureMustRemainExplicit,true);
  assert.equal(preflight.q035ScopeLock.applicationImplementationAllowedByThisPreflight,false);
  assert.equal(preflight.q035ScopeLock.implementationAllowedByThisPreflight,false);
  assert.equal(preflight.q035ScopeLock.publicProductAdmissionAllowedByThisPreflight,false);
  assert.equal(preflight.q035ScopeLock.frozenQueueAuthorityTouched,false);
  assert.equal(preflight.q035ScopeLock.r02AuthorityTouched,false);
  assert.equal(preflight.q035ScopeLock.r04AuthorityTouched,false);
  assert.equal(preflight.q035ScopeLock.r05AuthorityTouched,false);
  assert.equal(preflight.q035ScopeLock.q036OrLaterTouched,false);
});

test("Q035 preflight uses bounded validation and stops before separately approved implementation",()=>{
  assert.equal(preflight.preflightValidationBoundary.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");
  assert.equal(preflight.preflightValidationBoundary.derivedLane,"SHARED_RUNTIME_BOUNDED");
  assert.equal(preflight.preflightValidationBoundary.fullRepositoryRegressionAllowed,false);
  assert.equal(preflight.preflightValidationBoundary.globalBrowserReplayAllowed,false);
  assert.equal(preflight.preflightDecision.exactFrozenQueueRowResolved,true);
  assert.equal(preflight.preflightDecision.sourceAuthoritySufficientForQ035ImplementationPlanning,true);
  assert.equal(preflight.preflightDecision.previousSliceD0Satisfied,true);
  assert.equal(preflight.preflightDecision.manualSourceChoiceRequired,false);
  assert.equal(preflight.preflightDecision.sourceRefAmbiguity,false);
  assert.equal(preflight.preflightDecision.separateImplementationApprovalSatisfiedByCurrentOperatorInstruction,false);
  assert.equal(preflight.preflightDecision.nextTaskRequiresNewOperatorApproval,true);
  assert.equal(preflight.preflightDecision.nextTask,"P05F_W5DirectProductVerticalSlice035Implementation");
});
