import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {auditG5AU10AP05F28Projection,G5A_U10A_P05F28_KP_ID,G5A_U10A_P05F28_REMAINING_FUTURE_KP_IDS,G5A_U10A_P05F28_SPEC_IDS} from "../../site/modules/curriculum/registry/g5a-u10a-solid-net-correspondence-selector-projection-p05f28.js";
import {BATCH_A_SELECTOR_AVAILABILITY as BEFORE} from "../../site/modules/curriculum/registry/batch-a-selector-p05f27-extension.js";
import {BATCH_A_SELECTOR_AVAILABILITY as AFTER,auditP05F28PublicSelectorComposition,getVisibleBatchAKnowledgePoint} from "../../site/modules/curriculum/registry/batch-a-selector-p05f28-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p05f28.js";
import {generateG5AU10AP05F28Questions,validateG5AU10P05F28SolidNetQuestion} from "../../site/modules/curriculum/batch-a/g5a-u10a-solid-net-correspondence-runtime-p05f28.js";
import {buildBatchABrowserWorksheetDocument} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f28-extension.js";
import {renderSolidNetCorrespondenceDiagram} from "../../site/modules/renderer/solid-net-correspondence-diagram.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";
const SOURCE="g5a_u10_5a10a";

test("Q028 projection and selector promote only solid-net correspondence while preserving future viewpoint hidden",()=>{assert.equal(auditG5AU10AP05F28Projection().ok,true);assert.equal(auditP05F28PublicSelectorComposition().ok,true);const before=BEFORE.bySourceId[SOURCE],after=AFTER.bySourceId[SOURCE];for(const id of before.visibleKnowledgePointIds)assert.ok(after.visibleKnowledgePointIds.includes(id));assert.ok(after.visibleKnowledgePointIds.includes(G5A_U10A_P05F28_KP_ID));assert.ok(getVisibleBatchAKnowledgePoint(G5A_U10A_P05F28_KP_ID));assert.ok(!after.hiddenPendingKnowledgePointIds.includes(G5A_U10A_P05F28_KP_ID));for(const id of G5A_U10A_P05F28_REMAINING_FUTURE_KP_IDS){assert.ok(after.hiddenPendingKnowledgePointIds.includes(id));assert.ok(after.notSelectableKnowledgePointIds.includes(id));assert.equal(getVisibleBatchAKnowledgePoint(id),null);}assert.equal(AFTER.sourceCount,BEFORE.sourceCount);});

test("Q028 public capability binding is exact, diagram-only and bounded",()=>{assert.equal(auditPublicUiCapabilityBinding().ok,true);const binding=resolvePublicUiCapabilityBinding({sourceId:SOURCE,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G5A_U10A_P05F28_KP_ID]});assert.equal(binding.blocked,false);assert.equal(binding.questionType,"diagram");assert.equal(binding.questionCount.max,240);assert.deepEqual(binding.patternSpecIds,G5A_U10A_P05F28_SPEC_IDS);assert.equal(binding.applicationImplementationAllowed,false);assert.equal(binding.cubeCuboidNetAdmission,false);assert.equal(binding.sharedRuntimeScope,"SHARED_RUNTIME_BOUNDED");});

for(const specId of G5A_U10A_P05F28_SPEC_IDS)test(`Q028 deterministic generator/validator/renderer supports 240 distinct ${specId}`,()=>{const result=generateG5AU10AP05F28Questions({knowledgePointId:G5A_U10A_P05F28_KP_ID,patternSpecIds:[specId],questionCount:240,generationSeed:`q028-${specId}`});assert.equal(result.ok,true,JSON.stringify(result.errors));assert.equal(result.questions.length,240);assert.equal(new Set(result.questions.map(q=>q.questionSignature)).size,240);assert.ok(result.questions.every(q=>validateG5AU10P05F28SolidNetQuestion(q).ok));for(const q of result.questions.slice(0,9)){const html=renderSolidNetCorrespondenceDiagram(q.geometryDiagram);assert.match(html,/data-representation="solid-net-correspondence"/);}const original=result.questions[0],tampered={...original,geometryDiagram:{...original.geometryDiagram,solidFamily:"CUBE"}};assert.equal(validateG5AU10P05F28SolidNetQuestion(tampered).ok,false);});

test("Q028 worksheet and shared HTML renderer materialize questions, answer key and solid-net diagrams",()=>{const result=buildBatchABrowserWorksheetDocument({sourceId:SOURCE,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G5A_U10A_P05F28_KP_ID],questionCount:20,generationSeed:"q028-worksheet",includeAnswerKey:true,printLayout:{columns:2,rowsPerPage:4,showAnswerKeyPage:true}});assert.equal(result.ok,true,JSON.stringify(result.errors));assert.equal(result.worksheetDocument.questionCount,20);assert.equal(result.worksheetDocument.answerKeyItems.length,20);assert.equal(result.worksheetDocument.metadata.q029CubeCuboidNetTouched,false);const html=renderWorksheetDocumentToHtml(result.worksheetDocument,{stylesheetHref:null});assert.equal((html.match(/data-representation="solid-net-correspondence"/g)??[]).length,40);assert.match(html,/立體與展開圖對應|觀察下圖/);});

test("Q028 remains the immediate predecessor after current integration pointers advance to P05F29",()=>{const selector=readFileSync(new URL("../../site/modules/curriculum/registry/batch-a-selector-p04f33-extension.js",import.meta.url),"utf8"),binding=readFileSync(new URL("../../site/modules/curriculum/public/public-ui-capability-binding-p04f33.js",import.meta.url),"utf8"),entry=readFileSync(new URL("../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-r2e-entry.js",import.meta.url),"utf8");assert.match(selector,/batch-a-selector-p05f29-extension/);assert.match(binding,/public-ui-capability-binding-p05f29/);assert.match(entry,/requestsP05F29/);assert.match(entry,/requestsP05F28/);assert.match(entry,/requestsP05F27/);assert.ok(entry.indexOf("requestsP05F29")<entry.indexOf("requestsP05F28"));assert.ok(entry.indexOf("requestsP05F28")<entry.indexOf("requestsP05F27"));});
