import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {buildBatchABrowserWorksheetDocument as buildQ035Worksheet} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f35-extension.js";
import {buildBatchABrowserWorksheetDocument as buildCurrentTopSlotWorksheet} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f32-extension.js";
import {generateG4BU10P05F35Questions,validateG4BU10P05F35Question} from "../../site/modules/curriculum/batch-a/g4b-u10-rectangular-prism-volume-runtime-p05f35.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";
import {auditG4BU10P05F35Projection,G4B_U10_P05F35_FORMAL_MAPPINGS,G4B_U10_P05F35_KP_ID,G4B_U10_P05F35_PATTERN_GROUP_ID,G4B_U10_P05F35_SOURCE_ID,G4B_U10_P05F35_SPEC_IDS} from "../../site/modules/curriculum/registry/g4b-u10-rectangular-prism-volume-selector-projection-p05f35.js";
import {auditP05F35PublicSelectorComposition,getVisibleBatchAKnowledgePoint,listBatchAKnowledgePointAvailabilityBySource,resolveVisiblePatternSpecIdsForKnowledgePoint} from "../../site/modules/curriculum/registry/batch-a-selector-p05f35-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p05f35.js";
const preflight=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q035-g4b-u10-rectangular-prism-volume-structure-source-authority-preflight.json",import.meta.url),"utf8"));
const implementation=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q035-g4b-u10-rectangular-prism-volume-structure-implementation.json",import.meta.url),"utf8"));
const PROTECTED=["kp_g4b_u10_cubic_centimeter_unit","kp_g4b_u10_unit_cube_counting","kp_g4b_u10_layered_cube_counting","kp_g4b_u10_volume_conservation_rearrangement"];
const opts=(count=24)=>({sourceId:G4B_U10_P05F35_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G4B_U10_P05F35_KP_ID],selectedPatternGroupIds:[G4B_U10_P05F35_PATTERN_GROUP_ID],patternSpecIds:[...G4B_U10_P05F35_SPEC_IDS],questionMode:"diagram",requestedQuestionType:"diagram",questionCount:count,generationSeed:"p05f35-focused-prism-volume",includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showQuestionNumbers:true,showAnswerKeyPage:true}});
const occurrences=(text,token)=>text.split(token).length-1;

test("Q035 exact preflight and implementation identities remain frozen",()=>{assert.equal(preflight.status,"PASS_SOURCE_AUTHORITY_PREFLIGHT");assert.equal(preflight.queueAuthority.queuePosition,35);assert.deepEqual(preflight.queueAuthority.knowledgePointIds,[G4B_U10_P05F35_KP_ID]);assert.equal(preflight.previousSliceD0Evidence.status,"PASS_E6_D0_COMPLETE");assert.equal(implementation.taskId,"P05F_W5DirectProductVerticalSlice035Implementation");assert.equal(implementation.queueAuthority.sliceId,"p05e_q035_r3_g4b_u10_4b10_profile_spatial_solid_c1");assert.equal(implementation.scopeGuard.q027SemanticsModified,false);assert.equal(implementation.scopeGuard.q036OrLaterTouched,false);});

test("Q035 materializes one mapping one group and four bounded PatternSpecs",()=>{const audit=auditG4BU10P05F35Projection();assert.equal(audit.ok,true,audit.errors.join("\n"));assert.deepEqual(audit.counts,{knowledgePoints:1,patternGroups:1,patternSpecs:4,diagram:4,application:0});assert.equal(G4B_U10_P05F35_FORMAL_MAPPINGS.length,1);assert.deepEqual(G4B_U10_P05F35_FORMAL_MAPPINGS[0].includedRelations,preflight.q035ScopeLock.includedRelations);assert.deepEqual(G4B_U10_P05F35_FORMAL_MAPPINGS[0].optionalCapabilityIds,["cap_geometry_construction"]);});

test("Q035 selector promotes final G4B-U10 KP while preserving all four prior products",()=>{const audit=auditP05F35PublicSelectorComposition();assert.equal(audit.ok,true,audit.errors.join("\n"));const source=listBatchAKnowledgePointAvailabilityBySource(G4B_U10_P05F35_SOURCE_ID);assert.equal(source.visibleCount,5);assert.equal(source.hiddenPendingCount,0);assert.equal(source.notSelectableCount,0);for(const id of [...PROTECTED,G4B_U10_P05F35_KP_ID])assert.ok(getVisibleBatchAKnowledgePoint(id),id);assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(G4B_U10_P05F35_KP_ID,"diagram"),G4B_U10_P05F35_SPEC_IDS);});

test("Q035 public binding exposes direct single-KP diagram path only",()=>{const audit=auditPublicUiCapabilityBinding();assert.equal(audit.ok,true,audit.errors.join("\n"));const b=resolvePublicUiCapabilityBinding(opts());assert.equal(b.blocked,false);assert.equal(b.questionType,"diagram");assert.equal(b.questionCount.max,240);assert.equal(b.rectangularPrismVolumeStructureTarget,true);assert.equal(b.lengthWidthHeightAreUnitCubeArrayDimensions,true);assert.equal(b.layerMultiplicationStructureExplicit,true);assert.deepEqual(b.optionalCapabilityIds,["cap_geometry_construction"]);assert.equal(b.applicationImplementationAllowed,false);assert.equal(b.unknownDimensionInverseAdmission,false);assert.equal(b.volumeUnitConversionAdmission,false);assert.equal(b.sameUnitMixedAdmission,false);assert.equal(b.crossUnitMixedAdmission,false);});

test("Q035 generates deterministic source-backed prism-volume questions",()=>{const a=generateG4BU10P05F35Questions(opts(24)),b=generateG4BU10P05F35Questions(opts(24));assert.equal(a.ok,true,a.errors.join("\n"));assert.deepEqual(a.questions,b.questions);assert.equal(a.questions.length,24);assert.equal(new Set(a.questions.map(q=>q.questionSignature)).size,24);for(const q of a.questions){assert.equal(validateG4BU10P05F35Question(q).ok,true);assert.equal(q.answerValue,q.geometryDiagram.length*q.geometryDiagram.width*q.geometryDiagram.height);assert.equal(q.geometryDiagram.layerCubeCount,q.geometryDiagram.length*q.geometryDiagram.width);assert.equal(q.geometryDiagram.totalCubeCount,q.geometryDiagram.layerCubeCount*q.geometryDiagram.height);assert.equal(q.metadata.q005SemanticsModified,false);assert.equal(q.metadata.q014SemanticsModified,false);assert.equal(q.metadata.q027SemanticsModified,false);assert.equal(q.metadata.unknownDimensionInverseUsed,false);assert.equal(q.metadata.volumeUnitConversionUsed,false);assert.equal(q.metadata.applicationContextUsed,false);assert.equal(q.metadata.q036OrLaterTouched,false);}});

test("Q035 proves 240 distinct variants for every PatternSpec",()=>{for(const patternSpecId of G4B_U10_P05F35_SPEC_IDS){const r=generateG4BU10P05F35Questions({knowledgePointId:G4B_U10_P05F35_KP_ID,questionCount:240,patternSpecIds:[patternSpecId],generationSeed:`capacity-${patternSpecId}`});assert.equal(r.ok,true,`${patternSpecId}:${r.errors.join("\n")}`);assert.equal(r.questions.length,240);assert.equal(new Set(r.questions.map(q=>q.questionSignature)).size,240);}});

test("Q035 validator fails closed on dimensions answer diagram and provenance tampering",()=>{const q=generateG4BU10P05F35Questions({...opts(1),patternSpecIds:[G4B_U10_P05F35_SPEC_IDS[2]]}).questions[0];for(const mutate of [x=>x.geometryDiagram.length+=1,x=>x.answerValue+=1,x=>x.geometryDiagram.arrangements[0].cubes.pop(),x=>x.metadata.q027SemanticsModified=true]){const t=JSON.parse(JSON.stringify(q));mutate(t);assert.equal(validateG4BU10P05F35Question(t).ok,false);}});

test("Q035 worksheet reuses shared unit-cube solid renderer for questions and answers",()=>{const r=buildQ035Worksheet(opts(16));assert.equal(r.ok,true,r.errors.join("\n"));assert.equal(r.worksheetDocument.questionCount,16);assert.equal(r.worksheetDocument.answerKeyItems.length,16);const html=renderWorksheetDocumentToHtml(r.worksheetDocument,{stylesheetHref:"",title:r.worksheetDocument.title,debugDataAttributes:false});assert.equal(occurrences(html,'data-representation="layered-cube-volume-diagram"'),32);assert.equal(html.includes("kp_g4b_u10_"),false);assert.equal(html.includes("ps_g4b_u10_"),false);});

test("Q035 current top-slot bridge reaches prism worksheet",()=>{const r=buildCurrentTopSlotWorksheet(opts(8));assert.equal(r.ok,true,r.errors.join("\n"));assert.equal(r.p05f35Implemented,true);assert.equal(r.worksheetDocument.metadata.knowledgePointId,G4B_U10_P05F35_KP_ID);});

test("Q035 browser current selector and binding wrappers expose final G4B-U10 KP",async()=>{globalThis.document={};try{const selector=await import(`../../site/modules/curriculum/registry/batch-a-selector-p04f33-extension.js?p05f35=${Date.now()}`),binding=await import(`../../site/modules/curriculum/public/public-ui-capability-binding-p04f33.js?p05f35=${Date.now()}`);assert.equal(selector.getVisibleBatchAKnowledgePoint(G4B_U10_P05F35_KP_ID)?.sourceId,G4B_U10_P05F35_SOURCE_ID);assert.equal(binding.resolvePublicUiCapabilityBinding(opts()).blocked,false);for(const id of PROTECTED)assert.ok(selector.getVisibleBatchAKnowledgePoint(id),id);}finally{delete globalThis.document;}});
