import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {materializeP05EW5DirectProductVerticalSliceQueue} from "../../src/curriculum/full-product/p05e-w5-direct-product-vertical-slice-queue.mjs";
import {materializeR04SharedRuntimeCapabilityMatrix} from "../../src/curriculum/global/r04-shared-runtime-capability-matrix.mjs";
import {materializeR05DeliveryWaveRebase} from "../../src/curriculum/global/r05-delivery-wave-rebase.mjs";
const read=p=>JSON.parse(readFileSync(new URL(`../../${p}`,import.meta.url),"utf8"));
const preflight=read("data/curriculum/full-product/p05f/q055-g6b-u03-prism-base-area-height-volume-source-authority-preflight.json");
const q049=read("data/curriculum/full-product/p05f/q049-g6b-u03-prism-surface-area-source-authority-preflight.json");
const r02=read("data/curriculum/global/candidates/r02/chunks/reviewed-source-candidates-08.json");
const KP="kp_g6b_u03_prism_base_area_height_volume";
const CAPS=["cap_geometry_domain_validator","cap_geometry_property_reasoning","cap_solid_geometry_representation","cap_spatial_solid_reasoning"];
const sorted=v=>[...v].sort();

test("Q055 binds exact frozen row and Q054 D0 predecessor",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),row=q.queueEntries.find(x=>x.queuePosition===55);assert.equal(q.queueFrozen,true);assert.equal(q.queueRegistryParity,true);assert.equal(q.derivedRegistrySnapshot.queueDigest,"a4dae65a1a907ba963a135fce84ba292b8486a12513ae8f1fa54fbf07a6598ae");assert.ok(row);assert.equal(row.sliceId,"p05e_q055_r5_g6b_u03_6b03_profile_spatial_solid_c1");assert.equal(row.implementationTaskId,"P05F_W5DirectProductVerticalSlice055Implementation");assert.equal(row.previousSliceId,"p05e_q054_r5_g5b_u07_5b07_profile_spatial_solid_c1");assert.equal(row.previousSliceMustBeD0Complete,true);assert.equal(row.assignedDeliveryWaveId,"R05-W5");assert.equal(row.primarySourceNodeId,"g6b_u03_6b03");assert.deepEqual(row.supportingSourceNodeIds,["g6b_u03_6b03"]);assert.equal(row.intraWavePrerequisiteRank,5);assert.equal(row.primaryRuntimeProfileId,"profile_spatial_solid");assert.equal(row.chunkIndex,1);assert.equal(row.knowledgePointCount,1);assert.deepEqual(row.knowledgePointIds,[KP]);assert.deepEqual(sorted(row.requiredW5CapabilityIds),sorted(CAPS));assert.equal(row.targetEvidenceLevel,"E6_D0_COMPLETE");const p=preflight.previousSliceD0Evidence;assert.equal(p.preflightPrNumber,951);assert.equal(p.productPrNumber,952);assert.equal(p.productHeadSha,"50a6bb25c1a10ba2c705909877fa070ab1567f35");assert.equal(p.productMergeSha,"2d1d0809f3a19b13c13b7b878bcd7b4e3e16a810");assert.equal(p.prGateRunId,"34988757179");assert.equal(p.pagesDeploymentRunId,"34988940266");assert.equal(p.exactPagesRunId,"34988940516");assert.equal(p.evidenceArtifactId,"10404089754");assert.equal(p.evidenceArtifactDigest,"sha256:4ff476a8b6cbd93c7c2fd8a62f39ec273ed25cb7f325b8cb37bf40050e05104a");assert.equal(p.status,"PASS_E6_D0_COMPLETE");});

test("Q055 reuses verified G6B-U03 source identity from Q049",()=>{const s=preflight.sourceAuthority;assert.equal(s.sourceNodeId,"g6b_u03_6b03");assert.equal(s.sourceTitle,"柱體體積與表面積");assert.equal(s.sourcePdfTitle,"meow911_6b03_source.pdf");assert.equal(s.sourcePdfDriveFileId,"10LlUyzn4WOkxHAY3S9SsZeGT0i_ixV9u");assert.equal(s.sourceMetadataDriveFileId,"166jSxr7CwhLSrHc--uSlPwCUzCk0vyr7");assert.equal(s.verificationNotesDriveFileId,"1MWLwKWehiRhekfnmf2zX1-kck2t0Azlg");assert.equal(s.sourceUrl,"https://meow911.com/6b03/");assert.equal(q049.sourceAuthority.sourceNodeId,s.sourceNodeId);assert.equal(q049.sourceAuthority.sourcePdfDriveFileId,s.sourcePdfDriveFileId);assert.deepEqual(s.reviewedPages,[1,2]);assert.deepEqual(s.targetEvidencePages,[1,2]);assert.equal(s.targetEvidenceReconciliation.samePdfIdentityAlreadyCorroboratedByQ049,true);assert.equal(s.ocrUsedAsAuthority,false);assert.equal(s.r02AuthorityModified,false);assert.equal(s.sourceRefAmbiguity,false);assert.equal(s.manualSourceChoiceRequired,false);});

test("Q055 locks exact R02 prism base-area-times-height candidate",()=>{const source=r02.sourceRecords.find(x=>x.sourceNodeId==="g6b_u03_6b03"),c=source?.candidates.find(x=>x.knowledgePointId===KP);assert.ok(c);assert.deepEqual(c,{knowledgePointId:KP,canonicalNameZh:"柱體體積通式",capabilityStatement:"學生能以底面積乘高求直柱體體積。",reasoningInvariant:"每個平行截面面積相同，體積等於底面積累積高度。",category:"geometry",evidencePages:[1,2],applicationSuitability:"APPLICATION_COMPATIBLE"});assert.deepEqual(preflight.r02ReviewedCandidateAuthority.knowledgePoint,c);assert.deepEqual(preflight.r02ReviewedCandidateAuthority.sameSourceCandidateIds,source.candidates.map(x=>x.knowledgePointId));});

test("Q055 binds current R04 spatial-solid mapping and exact R05 closure",()=>{const r04=materializeR04SharedRuntimeCapabilityMatrix(),m=r04.getMapping(KP),bound=preflight.runtimeCapabilityAuthority.mapping;assert.ok(m);assert.equal(m.mappingId,"r04map_g6b_u03_prism_base_area_height_volume");assert.equal(m.primaryRuntimeProfileId,"profile_spatial_solid");assert.equal(m.classificationRuleId,"rule_spatial_solid");assert.deepEqual(m.appliedModifierIds,[]);assert.deepEqual(m.requiredRuntimeCapabilityIds,bound.requiredRuntimeCapabilityIds);assert.deepEqual(m.optionalRuntimeCapabilityIds,["cap_geometry_construction"]);assert.deepEqual(m.optionalRuntimeCapabilityIds,bound.optionalRuntimeCapabilityIds);assert.deepEqual(m.forbiddenRuntimeCapabilityIds,[]);const a=materializeR05DeliveryWaveRebase().getAssignment(KP);assert.ok(a);assert.equal(a.deliveryWaveId,"R05-W5");assert.equal(a.intraWavePrerequisiteRank,5);assert.equal(a.primaryRuntimeProfileId,"profile_spatial_solid");assert.deepEqual(sorted(a.contractOnlyRequiredCapabilityIds),sorted(CAPS));assert.deepEqual(sorted(preflight.runtimeCapabilityAuthority.exactFrozenQueueRequiredW5CapabilityIds),sorted(CAPS));assert.equal(preflight.runtimeCapabilityAuthority.volumeTermAlsoMatchesGeometryFormulaButSpatialRulePrecedencePreserved,true);assert.equal(preflight.runtimeCapabilityAuthority.mappingPolicyModifierMatchCount,0);});

test("Q055 owns generic right-prism volume only and protects Q049 Q060 and cylinder sibling",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),owners={kp_g6b_u03_prism_surface_area:49,kp_g6b_u03_triangular_prism_volume:60,kp_g6b_u03_composite_prism_volume_surface:60};assert.deepEqual(preflight.q055ScopeLock.includedKnowledgePointIds,[KP]);for(const[kp,pos]of Object.entries(owners)){const row=q.queueEntries.find(x=>x.knowledgePointIds.includes(kp));assert.equal(row?.queuePosition,pos,kp);assert.equal(preflight.q055ScopeLock.protectedExistingSameSourceKnowledgePointOwnership[kp],`Q${String(pos).padStart(3,"0")}`);}assert.equal(q.queueEntries.some(x=>x.knowledgePointIds.includes("kp_g6b_u03_cylinder_volume")),false);assert.deepEqual(preflight.q055ScopeLock.protectedNonW5SiblingCandidateIds,["kp_g6b_u03_cylinder_volume"]);assert.equal(preflight.q055ScopeLock.baseAreaMayBeGivenOrObtainedFromPriorKnowledgeButShapeSpecificAreaReasoningIsNotReowned,true);assert.equal(preflight.q055ScopeLock.prismHeightMustRepresentPerpendicularSeparationOfCongruentParallelBases,true);assert.equal(preflight.q055ScopeLock.volumeMustEqualBaseAreaTimesPrismHeight,true);});

test("Q055 excludes sibling reownership application mixed mode and Q056+",()=>{for(const r of ["REOWN_PRISM_SURFACE_AREA","TRIANGULAR_PRISM_BASE_AREA_DERIVATION_AS_TARGET_KP","CYLINDER_VOLUME_OR_SURFACE_AREA_AS_TARGET_KP","COMPOSITE_PRISM_VOLUME_OR_SURFACE_AREA_AS_TARGET_KP","GENERAL_APPLICATION_CONTEXT_IMPLEMENTATION","SAME_UNIT_MIXED_MODE","CROSS_UNIT_MIXED_MODE","Q056_OR_LATER_SEMANTICS"])assert.ok(preflight.q055ScopeLock.excludedRelations.includes(r),r);for(const k of ["applicationImplementationAllowedByThisPreflight","implementationAllowedByThisPreflight","publicProductAdmissionAllowedByThisPreflight","sameSourceSiblingSemanticsTouched","sameUnitMixedTouched","crossUnitMixedTouched","frozenQueueAuthorityTouched","r02AuthorityTouched","r04AuthorityTouched","r05AuthorityTouched","q056OrLaterTouched"])assert.equal(preflight.q055ScopeLock[k],false,k);assert.equal(preflight.q055ScopeLock.geometryConstructionRemainsOptionalNotW5Required,true);});

test("Q055 preflight stays bounded and stops at implementation approval boundary",()=>{const b=preflight.preflightValidationBoundary;assert.equal(b.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(b.derivedLane,"SHARED_RUNTIME_BOUNDED");assert.deepEqual(b.allowedLaneGateIds,["GLOBAL_CONTRACTS","TARGETED_ROUTE_REPLAY"]);assert.equal(b.focusedNodeContractRequired,true);assert.equal(b.nodeOnlyReadbackRequired,true);assert.equal(b.fullRepositoryRegressionAllowed,false);assert.equal(b.globalBrowserReplayAllowed,false);assert.equal(b.productImplementationAllowed,false);assert.equal(b.publicProductAdmissionAllowed,false);const d=preflight.preflightDecision;assert.equal(d.exactFrozenQueueRowResolved,true);assert.equal(d.sourceAuthoritySufficientForQ055ImplementationPlanning,true);assert.equal(d.previousSliceD0Satisfied,true);assert.equal(d.r02AuthorityBoundForTargetKnowledgePoint,true);assert.equal(d.runtimeCapabilityContractLocked,true);assert.equal(d.sameSourcePriorSliceOwnershipProtected,true);assert.equal(d.futureSameSourceOwnershipProtected,true);assert.equal(d.q049SameSourceIdentityReusedWithoutReclassification,true);assert.equal(d.manualSourceChoiceRequired,false);assert.equal(d.sourceRefAmbiguity,false);assert.equal(d.separateImplementationApprovalSatisfiedByCurrentOperatorInstruction,false);assert.equal(d.nextTaskRequiresNewOperatorApproval,true);assert.equal(d.nextTask,"P05F_W5DirectProductVerticalSlice055Implementation");});
