import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {materializeP05EW5DirectProductVerticalSliceQueue} from "../../src/curriculum/full-product/p05e-w5-direct-product-vertical-slice-queue.mjs";
import {materializeR04SharedRuntimeCapabilityMatrix} from "../../src/curriculum/global/r04-shared-runtime-capability-matrix.mjs";
import {materializeR05DeliveryWaveRebase} from "../../src/curriculum/global/r05-delivery-wave-rebase.mjs";
const read=p=>JSON.parse(readFileSync(new URL(`../../${p}`,import.meta.url),"utf8"));
const preflight=read("data/curriculum/full-product/p05f/q041-g3b-u05-area-compare-same-perimeter-source-authority-preflight.json");
const r02=read("data/curriculum/global/candidates/r02/chunks/reviewed-source-candidates-01.json");
const KP="kp_area_compare_same_perimeter",CAPS=["cap_geometry_diagram_representation","cap_geometry_domain_validator","cap_geometry_formula_evaluation","cap_geometry_property_reasoning"];

test("Q041 binds exact frozen row and Q040 E6 predecessor",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),row=q.queueEntries.find(x=>x.queuePosition===41);assert.equal(q.queueFrozen,true);assert.equal(q.queueRegistryParity,true);assert.equal(q.queueRegistry.queueDigest,"a4dae65a1a907ba963a135fce84ba292b8486a12513ae8f1fa54fbf07a6598ae");assert.ok(row);assert.equal(row.sliceId,"p05e_q041_r4_g3b_u05_3b05_profile_geometry_formula_c1");assert.equal(row.implementationTaskId,"P05F_W5DirectProductVerticalSlice041Implementation");assert.equal(row.previousSliceId,"p05e_q040_r3_g5b_u07_5b07_profile_geometry_formula_c1");assert.equal(row.previousSliceMustBeD0Complete,true);assert.equal(row.primarySourceNodeId,"g3b_u05_3b05");assert.equal(row.intraWavePrerequisiteRank,4);assert.equal(row.primaryRuntimeProfileId,"profile_geometry_formula");assert.equal(row.knowledgePointCount,1);assert.deepEqual(row.knowledgePointIds,[KP]);assert.deepEqual(row.requiredW5CapabilityIds,CAPS);const p=preflight.previousSliceD0Evidence;assert.equal(p.productPrNumber,923);assert.equal(p.productHeadSha,"cdc1a620c600aa97c0f1a47a2c7089ceaf01aca6");assert.equal(p.productMergeSha,"65b7ecba049e89059abce78f949a44023c3bbc14");assert.equal(p.prGateRunId,"34798769761");assert.equal(p.pagesDeploymentRunId,"34798844486");assert.equal(p.exactPagesRunId,"34798844537");assert.equal(p.evidenceArtifactId,"10330593875");assert.equal(p.evidenceArtifactDigest,"sha256:8e6055275190406c210f248650ded0ce253312200debeed5de0ba5521cd75fc2");assert.equal(p.status,"PASS_E6_D0_COMPLETE");});

test("Q041 reuses established G3B-U05 source identity and binds exact R02 candidate",()=>{const source=r02.sourceRecords.find(x=>x.sourceNodeId==="g3b_u05_3b05"),candidate=source?.candidates.find(x=>x.knowledgePointId===KP);assert.ok(source);assert.ok(candidate);assert.equal(preflight.status,"PASS_SOURCE_AUTHORITY_PREFLIGHT");assert.equal(preflight.sourceAuthority.sourceNodeId,"g3b_u05_3b05");assert.equal(preflight.sourceAuthority.sourcePdfTitle,"meow911_3b05_cm2_area.pdf");assert.equal(preflight.sourceAuthority.sourcePdfDriveFileId,"1JqksZyiKwD_cnZUN_zfmGlXwRpa_0w-8");assert.equal(preflight.sourceAuthority.sourceUrlFromMetadata,"https://meow911.com/3b05/");assert.deepEqual(preflight.sourceAuthority.reviewedPages,[1]);assert.equal(preflight.sourceAuthority.semanticAuthority,"R02_REVIEWED_SOURCE_CANDIDATE");assert.equal(preflight.sourceAuthority.currentPreflightDirectTargetPanelReplayPerformed,false);assert.equal(preflight.sourceAuthority.currentPreflightDirectTargetPanelReplayRequired,false);assert.equal(preflight.sourceAuthority.manualSourceChoiceRequired,false);assert.equal(preflight.sourceAuthority.sourceIdentityCrossCheck.sourceRefAmbiguity,false);assert.equal(candidate.canonicalNameZh,"相同周長下的面積比較");assert.equal(candidate.capabilityStatement,"學生能比較周長相同但形狀不同圖形的面積。");assert.equal(candidate.reasoningInvariant,"周長相同不保證面積相同，面積必須依實際覆蓋單位判定。");assert.equal(candidate.category,"geometry");assert.deepEqual(candidate.evidencePages,[1]);assert.equal(candidate.applicationSuitability,"APPLICATION_COMPATIBLE");assert.deepEqual(preflight.r02ReviewedCandidateAuthority.sameSourceCandidateIds,source.candidates.map(x=>x.knowledgePointId));});

test("Q041 current R04/R05 contract is exact geometry-formula with no modifiers",()=>{const r04=materializeR04SharedRuntimeCapabilityMatrix(),m=r04.getMapping(KP);assert.ok(m);assert.equal(m.mappingId,"r04map_area_compare_same_perimeter");assert.equal(m.primaryRuntimeProfileId,"profile_geometry_formula");assert.equal(m.classificationRuleId,"rule_geometry_formula");assert.deepEqual(m.appliedModifierIds,[]);const profile=r04.profiles.find(x=>x.profileId==="profile_geometry_formula");assert.ok(profile);for(const cap of ["cap_geometry_formula_evaluation","cap_geometry_domain_validator","cap_geometry_diagram_representation"])assert.ok(profile.requiredCapabilityIds.includes(cap));const r05=materializeR05DeliveryWaveRebase(),a=r05.getAssignment(KP);assert.ok(a);assert.equal(a.deliveryWaveId,"R05-W5");assert.equal(a.intraWavePrerequisiteRank,4);assert.equal(a.primaryRuntimeProfileId,"profile_geometry_formula");assert.deepEqual([...a.contractOnlyRequiredCapabilityIds].sort(),[...CAPS].sort());assert.deepEqual(preflight.runtimeCapabilityAuthority.exactFrozenQueueRequiredW5CapabilityIds,CAPS);});

test("Q041 preserves all four earlier same-source KP owners",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),expected={kp_area_square_centimeter_unit:3,kp_area_grid_counting:12,kp_area_conservation_cut_rearrange:23,kp_irregular_grid_area:23};for(const[id,pos]of Object.entries(expected)){const row=q.queueEntries.find(x=>x.knowledgePointIds.includes(id));assert.ok(row,id);assert.equal(row.queuePosition,pos,id);assert.equal(preflight.q041ScopeLock.protectedFrozenOwnership[id],`Q${String(pos).padStart(3,"0")}`);}const sameSource=q.queueEntries.filter(x=>x.primarySourceNodeId==="g3b_u05_3b05");assert.ok(sameSource.some(x=>x.queuePosition===41&&x.knowledgePointIds.includes(KP)));assert.equal(sameSource.filter(x=>x.queuePosition>41).length,0);});

test("Q041 scope is equal-perimeter area comparison only and stops before implementation",()=>{for(const r of ["COMPARE_AREA_OF_DISTINCT_SHAPES_WITH_EQUAL_PERIMETER","REJECT_EQUAL_PERIMETER_IMPLIES_EQUAL_AREA","DETERMINE_AREA_FROM_ACTUAL_COVERED_UNIT_SQUARES","COMPARE_GREATER_EQUAL_OR_LESS_AREA_UNDER_EQUAL_PERIMETER"])assert.ok(preflight.q041ScopeLock.includedRelations.includes(r));for(const r of ["SQUARE_CENTIMETER_UNIT_IDENTITY_AS_TARGET_KP","BASIC_GRID_AREA_COUNTING_AS_TARGET_KP","CUT_REARRANGE_AREA_CONSERVATION_AS_TARGET_KP","IRREGULAR_GRID_DECOMPOSITION_OR_COMPLETION_AS_TARGET_KP","RECTANGLE_OR_SQUARE_AREA_FORMULA_AS_TARGET_KP","GENERAL_PERIMETER_FORMULA_AS_TARGET_KP","GLOBAL_MAXIMUM_AREA_OPTIMIZATION_FOR_FIXED_PERIMETER","APPLICATION_CONTEXT_IMPLEMENTATION","Q042_OR_LATER_SEMANTICS"])assert.ok(preflight.q041ScopeLock.excludedRelations.includes(r));assert.equal(preflight.q041ScopeLock.equalPerimeterMayBeGivenOrVerifiedAsBoundedPrerequisite,true);assert.equal(preflight.q041ScopeLock.areaMustBeDeterminedFromActualCoverage,true);assert.equal(preflight.q041ScopeLock.equalPerimeterDoesNotImplyEqualArea,true);assert.equal(preflight.q041ScopeLock.implementationAllowedByThisPreflight,false);assert.equal(preflight.q041ScopeLock.publicProductAdmissionAllowedByThisPreflight,false);const b=preflight.preflightValidationBoundary;assert.equal(b.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(b.derivedLane,"SHARED_RUNTIME_BOUNDED");assert.equal(b.fullRepositoryRegressionAllowed,false);assert.equal(b.globalBrowserReplayAllowed,false);const d=preflight.preflightDecision;assert.equal(d.previousSliceD0Satisfied,true);assert.equal(d.existingSameSourceQ003Q012Q023Protected,true);assert.equal(d.manualSourceChoiceRequired,false);assert.equal(d.sourceRefAmbiguity,false);assert.equal(d.nextTaskRequiresNewOperatorApproval,true);assert.equal(d.nextTask,"P05F_W5DirectProductVerticalSlice041Implementation");});
