import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {materializeP05EW5DirectProductVerticalSliceQueue} from "../../src/curriculum/full-product/p05e-w5-direct-product-vertical-slice-queue.mjs";
import {materializeR04SharedRuntimeCapabilityMatrix} from "../../src/curriculum/global/r04-shared-runtime-capability-matrix.mjs";
import {materializeR05DeliveryWaveRebase} from "../../src/curriculum/global/r05-delivery-wave-rebase.mjs";
const read=p=>JSON.parse(readFileSync(new URL(`../../${p}`,import.meta.url),"utf8"));
const preflight=read("data/curriculum/full-product/p05f/q053-g5b-u03-container-fill-displacement-source-authority-preflight.json");
const q020=read("data/curriculum/full-product/p05f/q020-g5b-u03-container-volume-capacity-distinction-source-authority-preflight.json");
const q030=read("data/curriculum/full-product/p05f/q030-g5b-u03-capacity-volume-equivalence-source-authority-preflight.json");
const q039=read("data/curriculum/full-product/p05f/q039-g5b-u03-capacity-volume-conversion-source-authority-preflight.json");
const r02=read("data/curriculum/global/candidates/r02/chunks/reviewed-source-candidates-04.json");
const policy=read("data/curriculum/global/runtime/r04/runtime-capability-mapping-policy.json");
const KP="kp_g5b_u03_container_fill_displacement",CAPS=["cap_geometry_diagram_representation","cap_geometry_domain_validator","cap_geometry_formula_evaluation","cap_geometry_property_reasoning"],sorted=v=>[...v].sort();

test("Q053 binds exact frozen row and Q052 E6 predecessor",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),row=q.queueEntries.find(x=>x.queuePosition===53);assert.equal(q.queueFrozen,true);assert.equal(q.queueRegistryParity,true);assert.equal(q.derivedRegistrySnapshot.queueDigest,"a4dae65a1a907ba963a135fce84ba292b8486a12513ae8f1fa54fbf07a6598ae");assert.ok(row);assert.equal(row.sliceId,"p05e_q053_r5_g5b_u03_5b03_profile_geometry_formula_c1");assert.equal(row.implementationTaskId,"P05F_W5DirectProductVerticalSlice053Implementation");assert.equal(row.previousSliceId,"p05e_q052_r5_g5b_u01_5b01_profile_spatial_solid_c1");assert.equal(row.previousSliceMustBeD0Complete,true);assert.equal(row.assignedDeliveryWaveId,"R05-W5");assert.equal(row.primarySourceNodeId,"g5b_u03_5b03");assert.deepEqual(row.supportingSourceNodeIds,["g5b_u03_5b03"]);assert.equal(row.intraWavePrerequisiteRank,5);assert.equal(row.primaryRuntimeProfileId,"profile_geometry_formula");assert.equal(row.chunkIndex,1);assert.equal(row.knowledgePointCount,1);assert.deepEqual(row.knowledgePointIds,[KP]);assert.deepEqual(sorted(row.requiredW5CapabilityIds),sorted(CAPS));assert.equal(row.targetEvidenceLevel,"E6_D0_COMPLETE");const p=preflight.previousSliceD0Evidence;assert.equal(p.preflightPrNumber,947);assert.equal(p.productPrNumber,948);assert.equal(p.productHeadSha,"ec153bd94399f54bcaac07557f84ddebeb2e839c");assert.equal(p.productMergeSha,"b2af6f8149dc0df34436bb9e00b8d49f1c1fbe21");assert.equal(p.prGateRunId,"34959202403");assert.equal(p.pagesDeploymentRunId,"34959361121");assert.equal(p.exactPagesRunId,"34959361044");assert.equal(p.evidenceArtifactId,"10411319619");assert.equal(p.evidenceArtifactDigest,"sha256:13728a51133790d033c1732239ba6488ad17886f867adad8aa6d22858cb829d2");assert.equal(p.status,"PASS_E6_D0_COMPLETE");});

test("Q053 reuses exact verified G5B-U03 source identity from Q020 Q030 Q039",()=>{const s=preflight.sourceAuthority;for(const prior of [q020.sourceAuthority,q030.sourceAuthority,q039.sourceAuthority]){assert.equal(s.sourceNodeId,prior.sourceNodeId);assert.equal(s.sourceTitle,prior.sourceTitle);assert.equal(s.sourcePdfTitle,prior.sourcePdfTitle);assert.equal(s.sourcePdfDriveFileId,prior.sourcePdfDriveFileId);assert.equal(s.sourceUrl,prior.sourceUrl);}assert.equal(s.sourceNodeId,"g5b_u03_5b03");assert.equal(s.sourceTitle,"容積和容量");assert.equal(s.sourcePdfDriveFileId,"1k87iKFmra0RQ17__kXRPwuPbezKvtiPG");assert.deepEqual(s.reviewedPages,[1,2]);assert.equal(s.ocrUsedAsAuthority,false);assert.equal(s.sourceRefAmbiguity,false);assert.equal(s.manualSourceChoiceRequired,false);});

test("Q053 locks exact R02 container-fill displacement candidate",()=>{const source=r02.sourceRecords.find(x=>x.sourceNodeId==="g5b_u03_5b03"),c=source?.candidates.find(x=>x.knowledgePointId===KP);assert.ok(c);assert.deepEqual(c,{knowledgePointId:KP,canonicalNameZh:"容器裝填與排水量",capabilityStatement:"學生能由容器尺寸或水位變化求容量、體積或排水量。",reasoningInvariant:"液體體積、容器可用空間與排開體積必須守恆。",category:"measurement",evidencePages:[1,2],applicationSuitability:"APPLICATION_COMPATIBLE"});assert.deepEqual(preflight.r02ReviewedCandidateAuthority.knowledgePoint,c);assert.deepEqual(preflight.r02ReviewedCandidateAuthority.sameSourceCandidateIds,source.candidates.map(x=>x.knowledgePointId));});

test("Q053 current R04 mapping is geometry-formula plus explicit application semantics",()=>{const r04=materializeR04SharedRuntimeCapabilityMatrix(),m=r04.getMapping(KP),bound=preflight.runtimeCapabilityAuthority.mapping;assert.ok(m);assert.equal(m.mappingId,"r04map_g5b_u03_container_fill_displacement");assert.equal(m.primaryRuntimeProfileId,"profile_geometry_formula");assert.equal(m.classificationRuleId,"rule_geometry_formula");assert.deepEqual(m.appliedModifierIds,["mod_application_semantics"]);assert.deepEqual(m.requiredRuntimeCapabilityIds,bound.requiredRuntimeCapabilityIds);assert.deepEqual(m.optionalRuntimeCapabilityIds,["cap_global_context_binding","cap_pbl_task_set_projection"]);assert.deepEqual(m.optionalRuntimeCapabilityIds,bound.optionalRuntimeCapabilityIds);assert.deepEqual(m.forbiddenRuntimeCapabilityIds,[]);const modifier=policy.modifiers.find(x=>x.modifierId==="mod_application_semantics");assert.ok(modifier);assert.ok(modifier.profileIds.includes("profile_geometry_formula"));assert.ok(modifier.anyTerms.includes("fill"));assert.ok(modifier.anyTerms.includes("displacement"));assert.deepEqual(modifier.addRequiredCapabilityIds,["cap_relation_model_binding","cap_word_problem_semantic_validation","cap_text_application_representation"]);assert.equal(preflight.runtimeCapabilityAuthority.applicationModifierRequiredByCurrentR04Mapping,true);});

test("Q053 R05 dependency closure exactly matches frozen W5 capability contract",()=>{const r05=materializeR05DeliveryWaveRebase(),a=r05.getAssignment(KP);assert.ok(a);assert.equal(a.deliveryWaveId,"R05-W5");assert.equal(a.intraWavePrerequisiteRank,5);assert.equal(a.primaryRuntimeProfileId,"profile_geometry_formula");assert.deepEqual(sorted(a.contractOnlyRequiredCapabilityIds),sorted(CAPS));assert.deepEqual(sorted(preflight.runtimeCapabilityAuthority.exactFrozenQueueRequiredW5CapabilityIds),sorted(CAPS));assert.ok(a.contractOnlyRequiredCapabilityIds.includes("cap_geometry_property_reasoning"));for(const id of ["cap_relation_model_binding","cap_word_problem_semantic_validation","cap_text_application_representation"])assert.equal(a.contractOnlyRequiredCapabilityIds.includes(id),false,id);});

test("Q053 preserves exact same-source ownership for Q020 Q030 Q039",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),owners={kp_g5b_u03_container_volume_capacity_distinction:20,kp_g5b_u03_l_dm3_equivalence:30,kp_g5b_u03_ml_cm3_equivalence:30,kp_g5b_u03_capacity_volume_conversion:39};for(const[kp,pos]of Object.entries(owners)){const row=q.queueEntries.find(x=>x.knowledgePointIds.includes(kp));assert.equal(row?.queuePosition,pos,kp);assert.equal(preflight.q053ScopeLock.protectedExistingSameSourceKnowledgePointOwnership[kp],`Q${String(pos).padStart(3,"0")}`);}assert.deepEqual(preflight.q053ScopeLock.includedKnowledgePointIds,[KP]);assert.equal(preflight.q053ScopeLock.priorSameSourceFactsMayBeUsedAsPrerequisitesNotReowned,true);assert.equal(preflight.q053ScopeLock.containerDimensionsOrWaterLevelChangeMustDetermineTheTargetQuantity,true);assert.equal(preflight.q053ScopeLock.liquidContainerSpaceAndDisplacementConservationMustHold,true);});

test("Q053 excludes reownership broad application/mixed/global redesign and Q054+",()=>{for(const r of ["REOWN_CONTAINER_VOLUME_CAPACITY_DISTINCTION","REOWN_SIMPLE_LITER_CUBIC_DECIMETER_EQUIVALENCE","REOWN_SIMPLE_MILLILITER_CUBIC_CENTIMETER_EQUIVALENCE","REOWN_COMPOUND_CAPACITY_VOLUME_CONVERSION","GENERAL_UNIT_CONVERSION_FRAMEWORK_REDESIGN","GENERAL_APPLICATION_CONTEXT_LIBRARY_BEYOND_SOURCE_BACKED_CONTAINER_FILL_DISPLACEMENT","SAME_UNIT_MIXED_MODE","CROSS_UNIT_MIXED_MODE","Q054_OR_LATER_SEMANTICS"])assert.ok(preflight.q053ScopeLock.excludedRelations.includes(r),r);for(const k of ["implementationAllowedByThisPreflight","publicProductAdmissionAllowedByThisPreflight","sameSourceSiblingSemanticsTouched","sameUnitMixedTouched","crossUnitMixedTouched","frozenQueueAuthorityTouched","r02AuthorityTouched","r04AuthorityTouched","r05AuthorityTouched","q054OrLaterTouched"])assert.equal(preflight.q053ScopeLock[k],false,k);assert.equal(preflight.q053ScopeLock.sourceBackedApplicationSemanticsRequiredByCurrentR04Mapping,true);});

test("Q053 preflight stays bounded and stops at implementation approval boundary",()=>{const b=preflight.preflightValidationBoundary;assert.equal(b.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(b.derivedLane,"SHARED_RUNTIME_BOUNDED");assert.deepEqual(b.allowedLaneGateIds,["GLOBAL_CONTRACTS","TARGETED_ROUTE_REPLAY"]);assert.equal(b.focusedNodeContractRequired,true);assert.equal(b.nodeOnlyReadbackRequired,true);assert.equal(b.fullRepositoryRegressionAllowed,false);assert.equal(b.globalBrowserReplayAllowed,false);assert.equal(b.productImplementationAllowed,false);assert.equal(b.publicProductAdmissionAllowed,false);const d=preflight.preflightDecision;assert.equal(d.exactFrozenQueueRowResolved,true);assert.equal(d.sourceAuthoritySufficientForQ053ImplementationPlanning,true);assert.equal(d.previousSliceD0Satisfied,true);assert.equal(d.r02AuthorityBoundForTargetKnowledgePoint,true);assert.equal(d.runtimeCapabilityContractLocked,true);assert.equal(d.applicationModifierExplicitlyBound,true);assert.equal(d.singleKnowledgePointScopeLocked,true);assert.equal(d.priorSameSourceFrozenOwnershipProtected,true);assert.equal(d.manualSourceChoiceRequired,false);assert.equal(d.sourceRefAmbiguity,false);assert.equal(d.separateImplementationApprovalSatisfiedByCurrentOperatorInstruction,false);assert.equal(d.nextTaskRequiresNewOperatorApproval,true);assert.equal(d.nextTask,"P05F_W5DirectProductVerticalSlice053Implementation");});
