import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {materializeP05EW5DirectProductVerticalSliceQueue} from "../../src/curriculum/full-product/p05e-w5-direct-product-vertical-slice-queue.mjs";
import {materializeR04SharedRuntimeCapabilityMatrix} from "../../src/curriculum/global/r04-shared-runtime-capability-matrix.mjs";
import {materializeR05DeliveryWaveRebase} from "../../src/curriculum/global/r05-delivery-wave-rebase.mjs";
const read=p=>JSON.parse(readFileSync(new URL(`../../${p}`,import.meta.url),"utf8"));
const preflight=read("data/curriculum/full-product/p05f/q044-g5a-u05-polygon-definition-classification-source-authority-preflight.json");
const r02=read("data/curriculum/global/candidates/r02/chunks/reviewed-source-candidates-02.json");
const KP="kp_g5a_u05a_polygon_definition_classification";
const CAPS=["cap_geometry_diagram_representation","cap_geometry_domain_validator","cap_geometry_property_reasoning"];

test("Q044 binds exact frozen row and Q043 E6 predecessor",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),row=q.queueEntries.find(x=>x.queuePosition===44);assert.equal(q.queueFrozen,true);assert.equal(q.queueRegistryParity,true);assert.equal(q.queueRegistry.queueDigest,"a4dae65a1a907ba963a135fce84ba292b8486a12513ae8f1fa54fbf07a6598ae");assert.ok(row);assert.equal(row.sliceId,"p05e_q044_r4_g5a_u05_5a05a_profile_geometry_property_c1");assert.equal(row.implementationTaskId,"P05F_W5DirectProductVerticalSlice044Implementation");assert.equal(row.previousSliceId,"p05e_q043_r4_g4b_u07_4b07_profile_geometry_formula_c1");assert.equal(row.previousSliceMustBeD0Complete,true);assert.equal(row.primarySourceNodeId,"g5a_u05_5a05a");assert.equal(row.intraWavePrerequisiteRank,4);assert.equal(row.primaryRuntimeProfileId,"profile_geometry_property");assert.equal(row.knowledgePointCount,1);assert.deepEqual(row.knowledgePointIds,[KP]);assert.deepEqual(row.requiredW5CapabilityIds,CAPS);const p=preflight.previousSliceD0Evidence;assert.equal(p.preflightPrNumber,928);assert.equal(p.productPrNumber,929);assert.equal(p.productHeadSha,"fd6768056243669c1c0e25dddefbcf3a86600c37");assert.equal(p.productMergeSha,"8d3b0137131aff0a2983b2928bd14f0e2e5ae313");assert.equal(p.prGateRunId,"34806265038");assert.equal(p.pagesDeploymentRunId,"34806386536");assert.equal(p.exactPagesRunId,"34806386548");assert.equal(p.evidenceArtifactId,"10332074390");assert.equal(p.evidenceArtifactDigest,"sha256:47db01ba4767aabf2cdfe7794a101d4d5f7aafb3a085eaa0bbdf09ca3ab713c2");assert.equal(p.status,"PASS_E6_D0_COMPLETE");});

test("Q044 binds exact 5A05a source identity and R02 reviewed polygon-definition candidate",()=>{const source=r02.sourceRecords.find(x=>x.sourceNodeId==="g5a_u05_5a05a"),candidate=source?.candidates.find(x=>x.knowledgePointId===KP);assert.ok(source);assert.ok(candidate);assert.equal(preflight.status,"PASS_SOURCE_AUTHORITY_PREFLIGHT");assert.equal(preflight.sourceAuthority.sourceNodeId,"g5a_u05_5a05a");assert.equal(preflight.sourceAuthority.sourcePdfTitle,"meow911_5a05a_source.pdf");assert.equal(preflight.sourceAuthority.sourcePdfDriveFileId,"1FQuOHAf5-DTUS31bwBxFcWzAvCOZclbT");assert.equal(preflight.sourceAuthority.sourceMetadataDriveFileId,"1H2UqXYe-2Cfntxmp9OJDeKG4E9p2OFiO");assert.equal(preflight.sourceAuthority.verificationNotesDriveFileId,"18rwR0QbZJ-40ynpkXjexLc8Q1ZMsGVkd");assert.equal(preflight.sourceAuthority.originalFileNameFromMetadata,"題型總覽-5a05a-多邊形與平面圖形.pdf");assert.equal(preflight.sourceAuthority.sourceUrlFromMetadata,"https://meow911.com/5a05a/");assert.deepEqual(preflight.sourceAuthority.reviewedPages,[1,2,3]);assert.equal(preflight.sourceAuthority.semanticAuthority,"R02_REVIEWED_SOURCE_CANDIDATE");assert.equal(preflight.sourceAuthority.currentPreflightDirectTargetPanelReplayPerformed,false);assert.equal(preflight.sourceAuthority.currentPreflightDirectTargetPanelReplayRequired,false);assert.equal(preflight.sourceAuthority.driveVerificationNotesUsedAsCurrentSemanticAuthority,false);assert.equal(preflight.sourceAuthority.r02FullPageVisualReadbackIsCurrentSemanticAuthority,true);assert.equal(preflight.sourceAuthority.manualSourceChoiceRequired,false);assert.equal(preflight.sourceAuthority.sourceRefAmbiguity,false);assert.equal(preflight.sourceAuthority.adjacentSourceNodeConfusionRejected,"g5a_u05_5a05a1");assert.equal(candidate.canonicalNameZh,"多邊形定義與分類");assert.equal(candidate.capabilityStatement,"學生能依邊數與封閉性辨認三角形、四邊形及多邊形。");assert.equal(candidate.reasoningInvariant,"多邊形由有限線段首尾相接形成封閉平面圖形。");assert.equal(candidate.category,"geometry");assert.deepEqual(candidate.evidencePages,[1]);assert.equal(candidate.applicationSuitability,"APPLICATION_COMPATIBLE");assert.deepEqual(preflight.r02ReviewedCandidateAuthority.sameSourceCandidateIds,source.candidates.map(x=>x.knowledgePointId));});

test("Q044 current R04/R05 contract is exact geometry-property with no modifiers",()=>{const r04=materializeR04SharedRuntimeCapabilityMatrix(),m=r04.getMapping(KP);assert.ok(m);assert.equal(m.mappingId,"r04map_g5a_u05a_polygon_definition_classification");assert.equal(m.primaryRuntimeProfileId,"profile_geometry_property");assert.equal(m.classificationRuleId,"rule_geometry_property");assert.deepEqual(m.appliedModifierIds,[]);const profile=r04.profiles.find(x=>x.profileId==="profile_geometry_property");assert.ok(profile);for(const cap of CAPS)assert.ok(profile.requiredCapabilityIds.includes(cap));const r05=materializeR05DeliveryWaveRebase(),a=r05.getAssignment(KP);assert.ok(a);assert.equal(a.deliveryWaveId,"R05-W5");assert.equal(a.intraWavePrerequisiteRank,4);assert.equal(a.primaryRuntimeProfileId,"profile_geometry_property");assert.deepEqual([...a.contractOnlyRequiredCapabilityIds].sort(),[...CAPS].sort());assert.deepEqual(preflight.runtimeCapabilityAuthority.exactFrozenQueueRequiredW5CapabilityIds,CAPS);assert.deepEqual(preflight.runtimeCapabilityAuthority.r05DependencyClosureCapabilityIds,[]);});

test("Q044 protects later 5A05a frozen owners and non-W5 angle-sum candidate",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),q51=q.queueEntries.find(x=>x.queuePosition===51),q56=q.queueEntries.find(x=>x.queuePosition===56);assert.ok(q51);assert.ok(q56);assert.equal(q51.primarySourceNodeId,"g5a_u05_5a05a");assert.equal(q51.primaryRuntimeProfileId,"profile_geometry_property");assert.deepEqual(q51.knowledgePointIds,["kp_g5a_u05a_polygon_diagonal","kp_g5a_u05a_regular_polygon_properties"]);assert.equal(q56.primarySourceNodeId,"g5a_u05_5a05a");assert.equal(q56.primaryRuntimeProfileId,"profile_geometry_property");assert.deepEqual(q56.knowledgePointIds,["kp_g5a_u05a_polygon_triangulation"]);assert.deepEqual(preflight.q044ScopeLock.deferredFrozenOwnership.Q051,q51.knowledgePointIds);assert.deepEqual(preflight.q044ScopeLock.deferredFrozenOwnership.Q056,q56.knowledgePointIds);assert.deepEqual(preflight.q044ScopeLock.sameSourceNonW5CandidateIds,["kp_g5a_u05a_polygon_angle_sum_reasoning"]);assert.equal(q.queueEntries.some(x=>x.knowledgePointIds.includes("kp_g5a_u05a_polygon_angle_sum_reasoning")),false);});

test("Q044 scope is polygon definition/classification only and implementation remains approval-gated",()=>{for(const r of ["IDENTIFY_POLYGON_BY_CLOSED_STRAIGHT_SEGMENT_BOUNDARY","CLASSIFY_POLYGON_BY_SIDE_COUNT","REJECT_OPEN_CURVED_OR_NON_SEGMENT_FIGURE_AS_POLYGON"])assert.ok(preflight.q044ScopeLock.includedRelations.includes(r));for(const r of ["REGULAR_POLYGON_EQUAL_SIDE_EQUAL_ANGLE_PROPERTIES","POLYGON_DIAGONAL_IDENTIFICATION_OR_CONSTRUCTION","POLYGON_TRIANGULATION","POLYGON_INTERIOR_ANGLE_SUM_REASONING","APPLICATION_CONTEXT_IMPLEMENTATION","GEOMETRY_CONSTRUCTION_AS_PRIMARY_TARGET","SAME_UNIT_MIXED_MODE","CROSS_UNIT_MIXED_MODE","Q045_OR_LATER_SEMANTICS"])assert.ok(preflight.q044ScopeLock.excludedRelations.includes(r));assert.equal(preflight.q044ScopeLock.polygonBoundaryMustUseFiniteStraightSegments,true);assert.equal(preflight.q044ScopeLock.polygonBoundaryMustBeClosed,true);assert.equal(preflight.q044ScopeLock.polygonClassMustBeDeterminedBySideCountForThisSlice,true);assert.equal(preflight.q044ScopeLock.regularPolygonPropertiesRemainDeferred,true);assert.equal(preflight.q044ScopeLock.implementationAllowedByThisPreflight,false);assert.equal(preflight.q044ScopeLock.publicProductAdmissionAllowedByThisPreflight,false);const b=preflight.preflightValidationBoundary;assert.equal(b.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(b.derivedLane,"SHARED_RUNTIME_BOUNDED");assert.equal(b.fullRepositoryRegressionAllowed,false);assert.equal(b.globalBrowserReplayAllowed,false);const d=preflight.preflightDecision;assert.equal(d.previousSliceD0Satisfied,true);assert.equal(d.futureSameSourceQ051Q056Protected,true);assert.equal(d.nonW5SameSourceAngleSumProtected,true);assert.equal(d.adjacent5a05a1SourceKeptSeparate,true);assert.equal(d.manualSourceChoiceRequired,false);assert.equal(d.sourceRefAmbiguity,false);assert.equal(d.separateImplementationApprovalSatisfiedByCurrentOperatorInstruction,false);assert.equal(d.nextTaskRequiresNewOperatorApproval,true);assert.equal(d.nextTask,"P05F_W5DirectProductVerticalSlice044Implementation");});
