import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {G5A_U10A1_P05F38_FORMAL_MAPPING,G5A_U10A1_P05F38_INCLUDED_RELATIONS,G5A_U10A1_P05F38_KP_ID,G5A_U10A1_P05F38_PATTERN_SPECS,G5A_U10A1_P05F38_REQUIRED_CAPABILITY_IDS,G5A_U10A1_P05F38_SOURCE_ID,G5A_U10A1_P05F38_SPEC_IDS,auditG5AU10A1P05F38Projection} from "../../site/modules/curriculum/registry/g5a-u10a1-cube-cuboid-spatial-reasoning-selector-projection-p05f38.js";
import {BATCH_A_SELECTOR_AVAILABILITY as P05F37_SELECTOR_AVAILABILITY} from "../../site/modules/curriculum/registry/batch-a-selector-p05f37-extension.js";
import {BATCH_A_SELECTOR_AVAILABILITY as P05F38_SELECTOR_AVAILABILITY,auditP05F38PublicSelectorComposition,getVisibleBatchAKnowledgePoint,listBatchAKnowledgePointAvailabilityBySource,resolveVisiblePatternSpecIdsForKnowledgePoint} from "../../site/modules/curriculum/registry/batch-a-selector-p05f38-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p05f38.js";
import {buildBatchABrowserPlan,generateBatchABrowserQuestions,requestsP05F38} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p05f38.js";
import {G5A_U10A1_P05F38_MAX_QUESTION_COUNT,generateG5AU10A1P05F38Questions,validateG5AU10A1P05F38Question} from "../../site/modules/curriculum/batch-a/g5a-u10a1-cube-cuboid-spatial-reasoning-runtime-p05f38.js";
import {buildBatchABrowserWorksheetDocument as buildP05F38Worksheet} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f38-extension.js";
import {getBatchASourceUnit} from "../../site/modules/curriculum/batch-a/source-units.js";
import {renderCubeCuboidElementsDiagram,renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";
const request=(extra={})=>({sourceId:G5A_U10A1_P05F38_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G5A_U10A1_P05F38_KP_ID],questionType:"diagram",questionMode:"diagram",questionCount:18,generationSeed:"q038-test",includeAnswerKey:true,printLayout:{columns:2,rowsPerPage:4,showAnswerKeyPage:true},...extra});

test("Q038 selector promotes only the final pending G5A-U10A1 spatial-reasoning KP",()=>{const before=P05F37_SELECTOR_AVAILABILITY.bySourceId[G5A_U10A1_P05F38_SOURCE_ID],after=listBatchAKnowledgePointAvailabilityBySource(G5A_U10A1_P05F38_SOURCE_ID);assert.ok(before);assert.ok(before.hiddenPendingKnowledgePointIds.includes(G5A_U10A1_P05F38_KP_ID));assert.ok(before.notSelectableKnowledgePointIds.includes(G5A_U10A1_P05F38_KP_ID));assert.equal(after.visibleCount,before.visibleCount+1);assert.equal(after.hiddenPendingCount,before.hiddenPendingCount-1);assert.equal(after.notSelectableCount,before.notSelectableCount-1);assert.ok(after.visibleKnowledgePointIds.includes(G5A_U10A1_P05F38_KP_ID));assert.ok(!after.hiddenPendingKnowledgePointIds.includes(G5A_U10A1_P05F38_KP_ID));assert.ok(!after.notSelectableKnowledgePointIds.includes(G5A_U10A1_P05F38_KP_ID));assert.equal(P05F38_SELECTOR_AVAILABILITY.sourceCount,P05F37_SELECTOR_AVAILABILITY.sourceCount);assert.equal(P05F38_SELECTOR_AVAILABILITY.visibleCount,P05F37_SELECTOR_AVAILABILITY.visibleCount+1);assert.equal(P05F38_SELECTOR_AVAILABILITY.hiddenPendingCount,P05F37_SELECTOR_AVAILABILITY.hiddenPendingCount-1);assert.equal(P05F38_SELECTOR_AVAILABILITY.notSelectableCount,P05F37_SELECTOR_AVAILABILITY.notSelectableCount-1);});

test("Q038 source selector and projection expose exact frozen KP and three bounded PatternSpecs",()=>{const source=getBatchASourceUnit(G5A_U10A1_P05F38_SOURCE_ID);assert.equal(source?.unitCode,"5A-U10A1");assert.equal(auditG5AU10A1P05F38Projection().ok,true);const audit=auditP05F38PublicSelectorComposition();assert.equal(audit.ok,true,audit.errors.join("\n"));assert.ok(getVisibleBatchAKnowledgePoint(G5A_U10A1_P05F38_KP_ID));assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(G5A_U10A1_P05F38_KP_ID,"diagram"),G5A_U10A1_P05F38_SPEC_IDS);assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(G5A_U10A1_P05F38_KP_ID,"numeric"),[]);assert.deepEqual(G5A_U10A1_P05F38_REQUIRED_CAPABILITY_IDS,["cap_geometry_domain_validator","cap_geometry_property_reasoning","cap_solid_geometry_representation","cap_spatial_solid_reasoning"]);assert.ok(!G5A_U10A1_P05F38_REQUIRED_CAPABILITY_IDS.includes("cap_geometry_construction"));});

test("Q038 FormalMapping exactly preserves preflight relations and protected semantic boundaries",()=>{assert.equal(G5A_U10A1_P05F38_FORMAL_MAPPING.sourceId,G5A_U10A1_P05F38_SOURCE_ID);assert.deepEqual(G5A_U10A1_P05F38_FORMAL_MAPPING.sourcePages,[1,2]);assert.deepEqual(G5A_U10A1_P05F38_FORMAL_MAPPING.q029ExactPdfVisualCorroborationPages,[1,2]);assert.equal(G5A_U10A1_P05F38_PATTERN_SPECS.length,3);assert.deepEqual(G5A_U10A1_P05F38_PATTERN_SPECS.map(row=>row.relation),G5A_U10A1_P05F38_INCLUDED_RELATIONS.slice(0,3));assert.equal(G5A_U10A1_P05F38_FORMAL_MAPPING.fixedAdjacencyMustBePreserved,true);assert.equal(G5A_U10A1_P05F38_FORMAL_MAPPING.genericViewpointMayOnlyBeConditionNotTarget,true);assert.equal(G5A_U10A1_P05F38_FORMAL_MAPPING.cuttingMayNotComputeSurfaceArea,true);assert.ok(G5A_U10A1_P05F38_PATTERN_SPECS.every(row=>row.questionMode==="diagram"&&row.preservesFixedAdjacency&&row.geometryConstructionRequired===false&&row.applicationAllowed===false&&row.netFoldabilityAllowed===false&&row.surfaceAreaArithmeticAllowed===false&&row.volumeArithmeticAllowed===false&&row.genericViewpointTargetAllowed===false));});

test("Q038 runtime produces deterministic validated 240-question allocation",()=>{assert.equal(G5A_U10A1_P05F38_MAX_QUESTION_COUNT,240);const a=generateG5AU10A1P05F38Questions({knowledgePointId:G5A_U10A1_P05F38_KP_ID,questionCount:240,generationSeed:"q038-capacity"}),b=generateG5AU10A1P05F38Questions({knowledgePointId:G5A_U10A1_P05F38_KP_ID,questionCount:240,generationSeed:"q038-capacity"});assert.equal(a.ok,true,a.errors.join("\n"));assert.equal(a.questions.length,240);assert.equal(new Set(a.questions.map(q=>q.questionSignature)).size,240);assert.deepEqual(a.questions.map(q=>q.questionSignature),b.questions.map(q=>q.questionSignature));assert.ok(a.questions.every(q=>validateG5AU10A1P05F38Question(q).ok));assert.deepEqual([...new Set(a.questions.map(q=>q.relation))].sort(),G5A_U10A1_P05F38_INCLUDED_RELATIONS.slice(0,3).sort());});

test("Q038 each PatternSpec has 240 distinct variants and validator fails closed on spatial-condition tampering",()=>{for(const patternSpecId of G5A_U10A1_P05F38_SPEC_IDS){const out=generateG5AU10A1P05F38Questions({knowledgePointId:G5A_U10A1_P05F38_KP_ID,patternSpecIds:[patternSpecId],questionCount:240,generationSeed:`q038-${patternSpecId}`});assert.equal(out.ok,true,`${patternSpecId}:${out.errors.join(",")}`);assert.equal(new Set(out.questions.map(q=>q.questionSignature)).size,240,patternSpecId);const first=out.questions[0];assert.equal(validateG5AU10A1P05F38Question({...first,geometryDiagram:{...first.geometryDiagram,fixedAdjacencyPreserved:false}}).ok,false,patternSpecId);assert.equal(validateG5AU10A1P05F38Question({...first,answerText:"錯誤答案"}).ok,false,patternSpecId);}});

test("Q038 public binding and browser generator are bounded to single-KP diagram mode",()=>{const binding=resolvePublicUiCapabilityBinding(request());assert.equal(auditPublicUiCapabilityBinding().ok,true);assert.equal(binding.blocked,false);assert.equal(binding.questionType,"diagram");assert.equal(binding.questionCount.max,240);assert.equal(binding.sourceBackedCubeCuboidSpatialReasoning,true);assert.equal(binding.fixedAdjacencyPreserved,true);assert.equal(binding.geometryConstructionRequired,false);assert.equal(binding.surfaceAreaArithmeticAdmission,false);assert.equal(binding.volumeArithmeticAdmission,false);assert.equal(binding.netFoldabilityAdmission,false);assert.equal(binding.genericViewpointTargetAdmission,false);assert.equal(binding.applicationImplementationAllowed,false);assert.equal(requestsP05F38(request()),true);assert.equal(requestsP05F38(request({selectionMode:"sourceUnit"})),false);const plan=buildBatchABrowserPlan(request());assert.equal(plan.sourceId,G5A_U10A1_P05F38_SOURCE_ID);assert.equal(plan.genericFallback,false);const generated=generateBatchABrowserQuestions(request());assert.equal(generated.ok,true,generated.errors.join("\n"));assert.equal(generated.questions.length,18);});

test("Q038 worksheet and existing shared cube/cuboid renderer materialize questions answers and diagrams",()=>{const result=buildP05F38Worksheet(request());assert.equal(result.ok,true,result.errors.join("\n"));const doc=result.worksheetDocument;assert.equal(doc.questionCount,18);assert.equal(doc.answerKeyItems.length,18);assert.equal(doc.summary.diagramQuestionCount,18);assert.equal(doc.summary.missingFaceQuestionCount,6);assert.equal(doc.summary.multiviewColorQuestionCount,6);assert.equal(doc.summary.cutPositionQuestionCount,6);const html=renderWorksheetDocumentToHtml(doc,{stylesheetHref:null,title:doc.title,debugDataAttributes:false});assert.match(html,/正方體長方體空間推理/);assert.match(html,/cube-cuboid-elements-diagram/);assert.match(html,/相對兩面點數和為 7/);assert.match(html,/兩個方向觀察/);assert.match(html,/沿長、寬、高三個方向/);assert.doesNotThrow(()=>renderCubeCuboidElementsDiagram(doc.questions[0].geometryDiagram));});

test("Q038 implementation manifests preserve bounded validation and same-source ownership guards",()=>{const implementation=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q038-g5a-u10a1-cube-cuboid-spatial-reasoning-implementation.json",import.meta.url),"utf8")),impact=JSON.parse(readFileSync(new URL("../../data/project/change-impact/P05F_W5_Q038.impact.json",import.meta.url),"utf8")),plan=JSON.parse(readFileSync(new URL("../../data/project/validation-plans/P05F_W5_Q038.validation.json",import.meta.url),"utf8"));assert.equal(implementation.status,"IMPLEMENTATION_MATERIALIZED_AWAITING_FOCUSED_CI");assert.equal(implementation.goalDistance.reduced,"D2_TO_D1");assert.equal(implementation.publicAdmission.sourceAlreadyAdmittedBeforeQ038,true);assert.equal(implementation.publicAdmission.expectedGlobalPublicSourceDelta,0);assert.equal(implementation.publicAdmission.expectedGlobalVisibleKnowledgePointDelta,1);assert.equal(implementation.publicAdmission.expectedGlobalHiddenPendingKnowledgePointDelta,-1);assert.equal(implementation.publicAdmission.expectedGlobalNotSelectableKnowledgePointDelta,-1);assert.equal(implementation.runtimeContract.sharedRendererModified,false);for(const value of Object.values(implementation.scopeGuard))assert.equal(value,false);assert.equal(impact.expectedDerivedGate,"SHARED_RUNTIME_BOUNDED");assert.equal(impact.changeImpact.affectedRoutes,"BOUNDED");assert.equal(plan.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(plan.lanes.SHARED_RUNTIME_BOUNDED[1].runtime,"PLAYWRIGHT_CHROMIUM");assert.ok(!JSON.stringify(plan).includes("full npm test"));});
