import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {G4A_U05_P05F32_FORMAL_MAPPING,G4A_U05_P05F32_KP_ID,G4A_U05_P05F32_PATTERN_SPECS,G4A_U05_P05F32_PROTECTED_FUTURE_KP_IDS,G4A_U05_P05F32_SOURCE_ID,G4A_U05_P05F32_SPEC_IDS,auditG4AU05P05F32Projection} from "../../site/modules/curriculum/registry/g4a-u05-triangle-inequality-selector-projection-p05f32.js";
import {auditP05F32PublicSelectorComposition,getVisibleBatchAKnowledgePoint,listBatchAKnowledgePointAvailabilityBySource,resolveVisiblePatternSpecIdsForKnowledgePoint} from "../../site/modules/curriculum/registry/batch-a-selector-p05f32-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p05f32.js";
import {generateG4AU05P05F32Questions,validateG4AU05P05F32Question} from "../../site/modules/curriculum/batch-a/g4a-u05-triangle-inequality-runtime-p05f32.js";
import {buildBatchABrowserPlan,generateBatchABrowserQuestions,requestsP05F32} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p05f32.js";
import {buildBatchABrowserWorksheetDocument} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f32-extension.js";
import {buildBatchABrowserWorksheetDocument as buildStableWorksheet} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-r2e-entry.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";
const implementation=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q032-g4a-u05-triangle-inequality-implementation.json",import.meta.url),"utf8"));
const canForm=(a,b,c)=>a+b>c&&a+c>b&&b+c>a;

test("Q032 exact frozen authority and FormalMapping remain source-bound",()=>{assert.equal(implementation.queueAuthority.queuePosition,32);assert.equal(implementation.queueAuthority.sliceId,"p05e_q032_r3_g4a_u05_4a05_profile_geometry_property_c1");assert.equal(implementation.queueAuthority.sourceId,G4A_U05_P05F32_SOURCE_ID);assert.equal(implementation.queueAuthority.knowledgePointId,G4A_U05_P05F32_KP_ID);assert.equal(implementation.queueAuthority.runtimeProfileId,"profile_geometry_property");assert.equal(implementation.queueAuthority.targetEvidenceLevel,"E6_D0_COMPLETE");assert.equal(G4A_U05_P05F32_FORMAL_MAPPING.knowledgePointId,G4A_U05_P05F32_KP_ID);assert.deepEqual(G4A_U05_P05F32_FORMAL_MAPPING.includedRelations,["TEST_TRIANGLE_EXISTENCE_BY_SUM_OF_TWO_SIDES","REJECT_EQUALITY_OR_SHORTFALL_DEGENERATE_CASES"]);assert.equal(auditG4AU05P05F32Projection().ok,true);});

test("Q032 promotes only triangle inequality and protects existing/future same-source KPs",()=>{const audit=auditP05F32PublicSelectorComposition();assert.equal(audit.ok,true,JSON.stringify(audit));const source=listBatchAKnowledgePointAvailabilityBySource(G4A_U05_P05F32_SOURCE_ID);assert.equal(source.visibleCount,3);assert.equal(source.hiddenPendingCount,2);assert.equal(source.notSelectableCount,2);for(const id of ["kp_g4a_u05_triangle_elements_naming","kp_g4a_u05_triangle_side_classification",G4A_U05_P05F32_KP_ID]){assert.ok(source.visibleKnowledgePointIds.includes(id));assert.ok(getVisibleBatchAKnowledgePoint(id));}for(const id of G4A_U05_P05F32_PROTECTED_FUTURE_KP_IDS){assert.ok(source.hiddenPendingKnowledgePointIds.includes(id));assert.ok(source.notSelectableKnowledgePointIds.includes(id));assert.equal(getVisibleBatchAKnowledgePoint(id),null);}assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(G4A_U05_P05F32_KP_ID,"diagram"),G4A_U05_P05F32_SPEC_IDS);assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(G4A_U05_P05F32_KP_ID,"numeric"),[]);});

test("Q032 public binding admits only single-KP bounded diagram reasoning",()=>{const b=resolvePublicUiCapabilityBinding({sourceId:G4A_U05_P05F32_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G4A_U05_P05F32_KP_ID]});assert.equal(b.blocked,false);assert.equal(b.questionType,"diagram");assert.equal(b.questionCount.max,240);assert.equal(b.sourceBackedTriangleInequality,true);assert.equal(b.strictTriangleInequality,true);assert.equal(b.equalityRejected,true);assert.equal(b.allThreePairwiseChecks,true);assert.equal(b.applicationImplementationAllowed,false);assert.equal(auditPublicUiCapabilityBinding().ok,true);assert.equal(requestsP05F32({sourceId:G4A_U05_P05F32_SOURCE_ID,selectionMode:"sourceUnit"}),false);assert.equal(requestsP05F32({sourceId:G4A_U05_P05F32_SOURCE_ID,selectionMode:"mixedKnowledgePointsSameUnit",selectedKnowledgePointIds:[G4A_U05_P05F32_KP_ID]}),false);});

for(const spec of G4A_U05_P05F32_PATTERN_SPECS)test(`Q032 ${spec.patternSpecId} proves 240 deterministic validated variants`,()=>{const seed=`q032-${spec.patternSpecId}`,a=generateG4AU05P05F32Questions({patternSpecIds:[spec.patternSpecId],questionCount:240,generationSeed:seed}),b=generateG4AU05P05F32Questions({patternSpecIds:[spec.patternSpecId],questionCount:240,generationSeed:seed});assert.equal(a.ok,true,a.errors.join(","));assert.equal(a.questions.length,240);assert.equal(new Set(a.questions.map(q=>q.questionSignature)).size,240);assert.equal(new Set(a.questions.map(q=>q.promptText)).size,240);assert.deepEqual(a.questions.map(q=>q.questionSignature),b.questions.map(q=>q.questionSignature));assert.ok(a.questions.every(q=>validateG4AU05P05F32Question(q).ok));assert.deepEqual([...new Set(a.questions.map(q=>q.answerText))].sort(),["不能","能"].sort());});

test("Q032 enforces strict inequality including equality rejection and three-pair validity",()=>{const generated=generateG4AU05P05F32Questions({questionCount:240,generationSeed:"q032-semantics"});assert.equal(generated.ok,true,generated.errors.join(","));let equality=0,shortfall=0,valid=0;for(const q of generated.questions){const m=q.triangleInequalityModel,expected=canForm(m.a,m.b,m.c);assert.equal(m.valid,expected);assert.equal(q.answerText,expected?"能":"不能");assert.equal(m.shortestPairSum,m.a+m.b);assert.equal(m.longest,m.c);if(m.boundaryDelta===0)equality+=1;else if(m.boundaryDelta<0)shortfall+=1;else valid+=1;if(expected){assert.ok(q.geometryDiagram);assert.equal(q.geometryDiagram.triangleInequalitySatisfied,true);}else assert.equal(q.geometryDiagram,null);}assert.ok(equality>0);assert.ok(shortfall>0);assert.ok(valid>0);});

test("Q032 validator fails closed on answer, inequality model, false invalid diagram, scope and application tampering",()=>{const generated=generateG4AU05P05F32Questions({questionCount:20,generationSeed:"q032-tamper"});const valid=generated.questions.find(q=>q.triangleInequalityModel.valid),invalid=generated.questions.find(q=>!q.triangleInequalityModel.valid);assert.ok(valid);assert.ok(invalid);assert.equal(validateG4AU05P05F32Question({...valid,answerText:"不能"}).ok,false);assert.equal(validateG4AU05P05F32Question({...valid,triangleInequalityModel:{...valid.triangleInequalityModel,c:valid.triangleInequalityModel.a+valid.triangleInequalityModel.b}}).ok,false);assert.equal(validateG4AU05P05F32Question({...invalid,geometryDiagram:valid.geometryDiagram}).ok,false);assert.equal(validateG4AU05P05F32Question({...valid,knowledgePointId:"kp_g4a_u05_triangle_angle_classification"}).ok,false);assert.equal(validateG4AU05P05F32Question({...valid,metadata:{...valid.metadata,triangleSideClassificationTargetTouched:true}}).ok,false);assert.equal(validateG4AU05P05F32Question({...valid,metadata:{...valid.metadata,applicationContextUsed:true}}).ok,false);});

test("Q032 browser generator, stable worksheet entry and existing triangle renderer are bounded end-to-end",()=>{const options={sourceId:G4A_U05_P05F32_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G4A_U05_P05F32_KP_ID],questionCount:24,generationSeed:"q032-e2e",includeAnswerKey:true,printLayout:{columns:2,rowsPerPage:4,showAnswerKeyPage:true}};assert.equal(requestsP05F32(options),true);const plan=buildBatchABrowserPlan(options);assert.equal(plan.genericFallback,false);assert.equal(plan.questionCountMax,240);assert.deepEqual(plan.selectedKnowledgePointIds,[G4A_U05_P05F32_KP_ID]);const generated=generateBatchABrowserQuestions(options);assert.equal(generated.ok,true,generated.errors.join(","));assert.equal(generated.questions.length,24);assert.equal(new Set(generated.questions.map(q=>q.questionSignature)).size,24);const worksheet=buildBatchABrowserWorksheetDocument(options);assert.equal(worksheet.ok,true,worksheet.errors.join(","));assert.equal(worksheet.worksheetDocument.questionCount,24);assert.equal(worksheet.worksheetDocument.answerKeyItems.length,24);assert.equal(worksheet.worksheetDocument.metadata.strictTriangleInequality,true);assert.equal(worksheet.worksheetDocument.metadata.q033OrLaterTouched,false);const stable=buildStableWorksheet(options);assert.equal(stable.ok,true,stable.errors.join(","));assert.equal(stable.p05f32Implemented,true);const html=renderWorksheetDocumentToHtml(stable.worksheetDocument,{stylesheetHref:null});assert.match(html,/data-representation="triangle-elements-naming-diagram"/);assert.match(html,/能組成/);assert.match(html,/worksheet-cell--answer-key/);});
