import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {materializeP05EW5DirectProductVerticalSliceQueue} from "../../src/curriculum/full-product/p05e-w5-direct-product-vertical-slice-queue.mjs";
import {materializeR04SharedRuntimeCapabilityMatrix} from "../../src/curriculum/global/r04-shared-runtime-capability-matrix.mjs";
import {materializeR05DeliveryWaveRebase} from "../../src/curriculum/global/r05-delivery-wave-rebase.mjs";
const read=p=>JSON.parse(readFileSync(new URL(`../../${p}`,import.meta.url),"utf8"));
const preflight=read("data/curriculum/full-product/p05f/q056-g5a-u05-polygon-triangulation-source-authority-preflight.json");
const q051=read("data/curriculum/full-product/p05f/q051-g5a-u05-polygon-diagonal-regular-properties-source-authority-preflight.json");
const r02=read("data/curriculum/global/candidates/r02/chunks/reviewed-source-candidates-02.json");
const KP="kp_g5a_u05a_polygon_triangulation";
const CAPS=["cap_geometry_diagram_representation","cap_geometry_domain_validator","cap_geometry_property_reasoning"];
const sorted=v=>[...v].sort();

test("Q056 binds exact frozen row and Q055 D0 predecessor",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),row=q.queueEntries.find(x=>x.queuePosition===56);assert.equal(q.queueFrozen,true);assert.equal(q.queueRegistryParity,true);assert.equal(q.derivedRegistrySnapshot.queueDigest,"a4dae65a1a907ba963a135fce84ba292b8486a12513ae8f1fa54fbf07a6598ae");assert.ok(row);assert.equal(row.sliceId,"p05e_q056_r6_g5a_u05_5a05a_profile_geometry_property_c1");assert.equal(row.implementationTaskId,"P05F_W5DirectProductVerticalSlice056Implementation");assert.equal(row.previousSliceId,"p05e_q055_r5_g6b_u03_6b03_profile_spatial_solid_c1");assert.equal(row.previousSliceMustBeD0Complete,true);assert.equal(row.assignedDeliveryWaveId,"R05-W5");assert.equal(row.primarySourceNodeId,"g5a_u05_5a05a");assert.deepEqual(row.supportingSourceNodeIds,["g5a_u05_5a05a"]);assert.equal(row.intraWavePrerequisiteRank,6);assert.equal(row.primaryRuntimeProfileId,"profile_geometry_property");assert.equal(row.chunkIndex,1);assert.equal(row.knowledgePointCount,1);assert.deepEqual(row.knowledgePointIds,[KP]);assert.deepEqual(sorted(row.requiredW5CapabilityIds),sorted(CAPS));assert.equal(row.targetEvidenceLevel,"E6_D0_COMPLETE");const p=preflight.previousSliceD0Evidence;assert.equal(p.preflightPrNumber,953);assert.equal(p.productPrNumber,954);assert.equal(p.productHeadSha,"14be3eebe9a1df5d3e9e8bf0be083751ce7cceb2");assert.equal(p.productMergeSha,"7792db48324c631c9f27bab6a87d62e0b397b57e");assert.equal(p.prGateRunId,"34991773436");assert.equal(p.pagesDeploymentRunId,"34991930310");assert.equal(p.exactPagesRunId,"34991930279");assert.equal(p.evidenceArtifactId,"10404954688");assert.equal(p.evidenceArtifactDigest,"sha256:f851f052268e0f2e3b75d0b1b383f522370db8510e9618714b838cdd7b033474");assert.equal(p.status,"PASS_E6_D0_COMPLETE");});

test("Q056 reuses verified G5A-U05 source identity from Q044 and Q051",()=>{const s=preflight.sourceAuthority;assert.equal(s.sourceNodeId,"g5a_u05_5a05a");assert.equal(s.sourceTitle,"多邊形與平面圖形");assert.equal(s.sourcePdfTitle,"meow911_5a05a_source.pdf");assert.equal(s.sourcePdfDriveFileId,"1FQuOHAf5-DTUS31bwBxFcWzAvCOZclbT");assert.equal(s.sourceMetadataDriveFileId,"1H2UqXYe-2Cfntxmp9OJDeKG4E9p2OFiO");assert.equal(s.verificationNotesDriveFileId,"18rwR0QbZJ-40ynpkXjexLc8Q1ZMsGVkd");assert.equal(s.sourceUrlFromMetadata,"https://meow911.com/5a05a/");assert.equal(q051.sourceAuthority.sourceNodeId,s.sourceNodeId);assert.equal(q051.sourceAuthority.sourcePdfDriveFileId,s.sourcePdfDriveFileId);assert.deepEqual(s.reviewedPages,[1,2,3]);assert.deepEqual(s.targetEvidencePages,[1]);assert.equal(s.targetEvidenceReconciliation.polygonTriangulation.sameSourceIdentityAlreadyCorroboratedByQ044AndQ051,true);assert.equal(s.ocrUsedAsAuthority,false);assert.equal(s.r02AuthorityModified,false);assert.equal(s.sourceRefAmbiguity,false);assert.equal(s.manualSourceChoiceRequired,false);});

test("Q056 locks exact R02 polygon triangulation candidate",()=>{const source=r02.sourceRecords.find(x=>x.sourceNodeId==="g5a_u05_5a05a"),c=source?.candidates.find(x=>x.knowledgePointId===KP);assert.ok(c);assert.deepEqual(c,{knowledgePointId:KP,canonicalNameZh:"多邊形分割成三角形",capabilityStatement:"學生能由同一頂點畫對角線將多邊形分割成三角形。",reasoningInvariant:"n邊形可由同一頂點分成n減2個不重疊三角形。",category:"geometry",evidencePages:[1],applicationSuitability:"APPLICATION_COMPATIBLE"});assert.deepEqual(preflight.r02ReviewedCandidateAuthority.knowledgePoint,c);assert.deepEqual(preflight.r02ReviewedCandidateAuthority.sameSourceCandidateIds,source.candidates.map(x=>x.knowledgePointId));});

test("Q056 binds current R04 geometry-property mapping and exact R05 closure",()=>{const r04=materializeR04SharedRuntimeCapabilityMatrix(),m=r04.getMapping(KP),bound=preflight.runtimeCapabilityAuthority.mapping;assert.ok(m);assert.equal(m.mappingId,"r04map_g5a_u05a_polygon_triangulation");assert.equal(m.primaryRuntimeProfileId,"profile_geometry_property");assert.equal(m.classificationRuleId,"rule_geometry_property");assert.deepEqual(m.appliedModifierIds,[]);assert.deepEqual(m.requiredRuntimeCapabilityIds,bound.requiredRuntimeCapabilityIds);assert.deepEqual(m.optionalRuntimeCapabilityIds,["cap_geometry_construction"]);assert.deepEqual(m.optionalRuntimeCapabilityIds,bound.optionalRuntimeCapabilityIds);assert.deepEqual(m.forbiddenRuntimeCapabilityIds,[]);const a=materializeR05DeliveryWaveRebase().getAssignment(KP);assert.ok(a);assert.equal(a.deliveryWaveId,"R05-W5");assert.equal(a.intraWavePrerequisiteRank,6);assert.equal(a.primaryRuntimeProfileId,"profile_geometry_property");assert.deepEqual(sorted(a.contractOnlyRequiredCapabilityIds),sorted(CAPS));assert.deepEqual(sorted(preflight.runtimeCapabilityAuthority.exactFrozenQueueRequiredW5CapabilityIds),sorted(CAPS));assert.equal(preflight.runtimeCapabilityAuthority.geometryConstructionBoundary.profileOptionalCapabilityPreserved,true);assert.equal(preflight.runtimeCapabilityAuthority.geometryConstructionBoundary.r04ConstructionModifierApplied,false);});

test("Q056 owns triangulation only and protects Q044 Q051 angle-sum and adjacent source",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),owners={kp_g5a_u05a_polygon_definition_classification:44,kp_g5a_u05a_polygon_diagonal:51,kp_g5a_u05a_regular_polygon_properties:51};assert.deepEqual(preflight.q056ScopeLock.includedKnowledgePointIds,[KP]);for(const[kp,pos]of Object.entries(owners)){const row=q.queueEntries.find(x=>x.knowledgePointIds.includes(kp));assert.equal(row?.queuePosition,pos,kp);assert.equal(preflight.q056ScopeLock.protectedExistingSameSourceKnowledgePointOwnership[kp],`Q${String(pos).padStart(3,"0")}`);}assert.equal(q.queueEntries.some(x=>x.knowledgePointIds.includes("kp_g5a_u05a_polygon_angle_sum_reasoning")),false);assert.deepEqual(preflight.q056ScopeLock.protectedNonW5SiblingCandidateIds,["kp_g5a_u05a_polygon_angle_sum_reasoning"]);assert.equal(preflight.q056ScopeLock.adjacentSourceNodeKeptSeparate,"g5a_u05_5a05a1");assert.equal(preflight.q056ScopeLock.triangulationMustUseOneCommonOriginVertex,true);assert.equal(preflight.q056ScopeLock.triangleCountMustEqualSideCountMinusTwo,true);assert.equal(preflight.q056ScopeLock.trianglesMustBeNonOverlappingAndCoverPolygonInterior,true);});

test("Q056 excludes sibling reownership angle-sum application free-form construction mixed mode and Q057+",()=>{for(const r of ["REOWN_POLYGON_DEFINITION_CLASSIFICATION","REOWN_POLYGON_DIAGONAL_AS_STANDALONE_TARGET","REOWN_REGULAR_POLYGON_PROPERTIES","POLYGON_INTERIOR_ANGLE_SUM_REASONING","SECTOR_OR_CENTRAL_ANGLE_SEMANTICS","APPLICATION_CONTEXT_IMPLEMENTATION","INTERACTIVE_FREE_FORM_GEOMETRY_CONSTRUCTION_REQUIREMENT","SAME_UNIT_MIXED_MODE","CROSS_UNIT_MIXED_MODE","Q057_OR_LATER_SEMANTICS"])assert.ok(preflight.q056ScopeLock.excludedRelations.includes(r),r);for(const k of ["applicationImplementationAllowedByThisPreflight","implementationAllowedByThisPreflight","publicProductAdmissionAllowedByThisPreflight","sameUnitMixedTouched","crossUnitMixedTouched","frozenQueueAuthorityTouched","r02AuthorityTouched","r04AuthorityTouched","r05AuthorityTouched","q057OrLaterTouched"])assert.equal(preflight.q056ScopeLock[k],false,k);assert.equal(preflight.q056ScopeLock.geometryConstructionRemainsOptionalNotW5Required,true);});

test("Q056 preflight stays bounded and stops at implementation approval boundary",()=>{const b=preflight.preflightValidationBoundary;assert.equal(b.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(b.derivedLane,"SHARED_RUNTIME_BOUNDED");assert.deepEqual(b.allowedLaneGateIds,["GLOBAL_CONTRACTS","TARGETED_ROUTE_REPLAY"]);assert.equal(b.focusedNodeContractRequired,true);assert.equal(b.nodeOnlyReadbackRequired,true);assert.equal(b.fullRepositoryRegressionAllowed,false);assert.equal(b.globalBrowserReplayAllowed,false);assert.equal(b.productImplementationAllowed,false);assert.equal(b.publicProductAdmissionAllowed,false);const d=preflight.preflightDecision;assert.equal(d.exactFrozenQueueRowResolved,true);assert.equal(d.sourceAuthoritySufficientForQ056ImplementationPlanning,true);assert.equal(d.previousSliceD0Satisfied,true);assert.equal(d.r02AuthorityBoundForTargetKnowledgePoint,true);assert.equal(d.runtimeCapabilityContractLocked,true);assert.equal(d.sameSourcePriorSliceOwnershipProtected,true);assert.equal(d.nonW5AngleSumOwnershipProtected,true);assert.equal(d.q044Q051SameSourceIdentityReusedWithoutReclassification,true);assert.equal(d.manualSourceChoiceRequired,false);assert.equal(d.sourceRefAmbiguity,false);assert.equal(d.separateImplementationApprovalSatisfiedByCurrentOperatorInstruction,false);assert.equal(d.nextTaskRequiresNewOperatorApproval,true);assert.equal(d.nextTask,"P05F_W5DirectProductVerticalSlice056Implementation");});
