import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {auditG5AU03A1P05F61Projection,G5A_U03A1_P05F61_KP_ID as KP,G5A_U03A1_P05F61_PROTECTED_SIBLING_KP_IDS as PROTECTED,G5A_U03A1_P05F61_REQUIRED_CAPABILITY_IDS as CAPS,G5A_U03A1_P05F61_SOURCE_ID as SRC,G5A_U03A1_P05F61_SPEC_IDS as SPECS} from "../../site/modules/curriculum/registry/g5a-u03a1-rectangle-square-tiling-selector-projection-p05f61.js";
import {auditP05F61PublicSelectorComposition,getVisibleBatchAKnowledgePoint,getVisiblePatternGroupsForKnowledgePoint,listBatchAKnowledgePointAvailabilityBySource,resolveVisiblePatternSpecIdsForKnowledgePoint} from "../../site/modules/curriculum/registry/batch-a-selector-p05f61-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p05f61.js";
import {buildG5AU03A1P05F61Question,generateG5AU03A1P05F61Questions,validateG5AU03A1P05F61Question} from "../../site/modules/curriculum/batch-a/g5a-u03a1-rectangle-square-tiling-runtime-p05f61.js";
import {buildBatchABrowserPlan,generateBatchABrowserQuestions} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p05f61.js";
import {buildBatchABrowserWorksheetDocument} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f61-extension.js";
import {renderG5AU03A1Q061Diagram} from "../../site/modules/renderer/g5a-u03a1-rectangle-square-tiling-diagram-p05f61.js";
const read=p=>JSON.parse(readFileSync(new URL(`../../${p}`,import.meta.url),"utf8")),implementation=read("data/curriculum/full-product/p05f/q061-g5a-u03a1-rectangle-square-tiling-implementation.json"),impact=read("data/project/change-impact/P05F_W5_Q061.impact.json"),validation=read("data/project/validation-plans/P05F_W5_Q061.validation.json");
const request=(extra={})=>({sourceId:SRC,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[KP],questionMode:"diagram",questionCount:20,generationSeed:"q061-test",...extra});
const gcd=(a,b)=>{while(b)[a,b]=[b,a%b];return a;};

test("Q061 materializes the exact frozen product contract without expanding scope",()=>{assert.equal(implementation.status,"IMPLEMENTATION_MATERIALIZED_AWAITING_FOCUSED_CI");assert.equal(implementation.queueAuthority.queuePosition,61);assert.deepEqual(implementation.queueAuthority.knowledgePointIds,[KP]);assert.deepEqual(implementation.queueAuthority.requiredW5CapabilityIds,CAPS);assert.equal(implementation.sourceAuthority.applicationClassification,"APPLICATION_REQUIRED");assert.equal(implementation.productContract.applicationContextMode,"SOURCE_REQUIRED_FIXED_TILING_CONTEXT_ONLY");assert.equal(implementation.productContract.maxQuestionCount,240);for(const v of Object.values(implementation.scopeGuard))assert.equal(v,false);assert.deepEqual(auditG5AU03A1P05F61Projection(),{ok:true,errors:[],counts:{knowledgePoints:1,patternGroups:1,patternSpecs:2,formalMappings:1}});});

test("Q061 selector promotes only rectangle-square tiling and protects all same-source siblings",()=>{const a=auditP05F61PublicSelectorComposition();assert.equal(a.ok,true,a.errors.join("\n"));const s=listBatchAKnowledgePointAvailabilityBySource(SRC);assert.ok(s.visibleKnowledgePointIds.includes(KP));assert.ok(getVisibleBatchAKnowledgePoint(KP));assert.equal(getVisiblePatternGroupsForKnowledgePoint(KP).length,1);assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(KP,"diagram"),SPECS);for(const id of PROTECTED){assert.equal(getVisibleBatchAKnowledgePoint(id),null);assert.ok(s.hiddenPendingKnowledgePointIds.includes(id));assert.ok(s.notSelectableKnowledgePointIds.includes(id));}});

test("Q061 public binding keeps source-required application context while forbidding mixed modes",()=>{const a=auditPublicUiCapabilityBinding();assert.equal(a.ok,true,a.errors.join("\n"));const b=resolvePublicUiCapabilityBinding(request());assert.equal(b.blocked,false);assert.equal(b.questionType,"diagram");assert.equal(b.applicationSuitability,"APPLICATION_REQUIRED");assert.equal(b.applicationImplementationAllowed,true);assert.equal(b.applicationBoundary,"SOURCE_REQUIRED_FIXED_TILING_CONTEXT_ONLY");assert.deepEqual(b.requiredCapabilityIds,CAPS);assert.equal(b.sameSourceSiblingAdmission,false);assert.equal(b.sameUnitMixedAdmission,false);assert.equal(b.crossUnitMixedAdmission,false);});

for(const patternSpecId of SPECS)test(`Q061 ${patternSpecId} has 240 deterministic unique source-backed variants`,()=>{const a=generateG5AU03A1P05F61Questions({questionCount:240,patternSpecIds:[patternSpecId],generationSeed:"stable"}),b=generateG5AU03A1P05F61Questions({questionCount:240,patternSpecIds:[patternSpecId],generationSeed:"stable"});assert.equal(a.ok,true,a.errors.join("\n"));assert.deepEqual(a.questions,b.questions);assert.equal(new Set(a.questions.map(q=>q.questionSignature)).size,240);for(const q of a.questions){const m=q.geometryDiagram;assert.equal(m.minimumSquareSideCm,(m.tileLengthCm*m.tileWidthCm)/gcd(m.tileLengthCm,m.tileWidthCm));assert.equal(m.tileColumns*m.tileLengthCm,m.minimumSquareSideCm);assert.equal(m.tileRows*m.tileWidthCm,m.minimumSquareSideCm);assert.match(q.displayText,/長方形片/);assert.match(q.displayText,/最小/);assert.equal(q.metadata.applicationContextUsed,true);assert.equal(q.metadata.geometryTilingConstraintPreserved,true);assert.equal(q.metadata.minimumCommonMultipleUsedUnderTilingConstraint,true);}});

test("Q061 validator fails closed on answer diagram and scope mutation",()=>{const q=buildG5AU03A1P05F61Question({variant:17,patternSpecId:SPECS[0],generationSeed:"mut"});assert.equal(validateG5AU03A1P05F61Question(q).ok,true);assert.equal(validateG5AU03A1P05F61Question({...q,answerText:"999 公分"}).ok,false);assert.equal(validateG5AU03A1P05F61Question({...q,geometryDiagram:{...q.geometryDiagram,noGap:false}}).ok,false);assert.equal(validateG5AU03A1P05F61Question({...q,metadata:{...q.metadata,genericCommonMultipleReowned:true}}).ok,false);});

test("Q061 browser plan generator worksheet and renderer are usable at D1",()=>{const p=buildBatchABrowserPlan(request({questionCount:8}));assert.equal(p.sourceId,SRC);assert.equal(p.questionCountMax,240);assert.deepEqual(p.selectedKnowledgePointIds,[KP]);const g=generateBatchABrowserQuestions(request({questionCount:8}));assert.equal(g.ok,true,g.errors.join("\n"));assert.equal(g.questions.length,8);const w=buildBatchABrowserWorksheetDocument(request({questionCount:8,includeAnswerKey:true,printLayout:{columns:2,rowsPerPage:4,showAnswerKeyPage:true}}));assert.equal(w.ok,true,w.errors.join("\n"));assert.equal(w.worksheetDocument.questionCount,8);assert.equal(w.worksheetDocument.answerKeyItems.length,8);assert.equal(w.worksheetDocument.summary.applicationQuestionCount,8);const html=renderG5AU03A1Q061Diagram(g.questions[0].geometryDiagram);assert.match(html,/data-representation="rectangle-square-tiling-diagram"/);assert.match(html,/正方形邊長：？公分/);assert.ok(!html.includes(String(g.questions[0].geometryDiagram.minimumSquareSideCm)+" 公分</text>"));});

test("Q061 validation contract stays SHARED_RUNTIME_BOUNDED",()=>{assert.equal(impact.expectedDerivedGate,"SHARED_RUNTIME_BOUNDED");assert.equal(validation.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");const lane=validation.lanes.SHARED_RUNTIME_BOUNDED;assert.deepEqual(lane.map(x=>x.gateId),["GLOBAL_CONTRACTS","TARGETED_ROUTE_REPLAY"]);assert.equal(JSON.stringify(validation).includes("FULL_REPOSITORY"),false);});
