import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {auditG5AU09P05F62Projection,G5A_U09_P05F62_INCLUDED_RELATIONS as RELATIONS,G5A_U09_P05F62_KP_ID as KP,G5A_U09_P05F62_PRIOR_VISIBLE_KP_IDS as PRIOR,G5A_U09_P05F62_REQUIRED_CAPABILITY_IDS as CAPS,G5A_U09_P05F62_SOURCE_ID as SRC,G5A_U09_P05F62_SPEC_IDS as SPECS} from "../../site/modules/curriculum/registry/g5a-u09-composite-polygon-area-selector-projection-p05f62.js";
import * as preQ062Selector from "../../site/modules/curriculum/registry/batch-a-selector-p05f61-extension.js";
import {auditP05F62PublicSelectorComposition,getVisibleBatchAKnowledgePoint,getVisiblePatternGroupsForKnowledgePoint,listBatchAKnowledgePointAvailabilityBySource,listVisibleBatchAKnowledgePoints,resolveVisiblePatternSpecIdsForKnowledgePoint} from "../../site/modules/curriculum/registry/batch-a-selector-p05f62-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p05f62.js";
import {buildG5AU09P05F62Question,generateG5AU09P05F62Questions,validateG5AU09P05F62Question} from "../../site/modules/curriculum/batch-a/g5a-u09-composite-polygon-area-runtime-p05f62.js";
import {buildBatchABrowserPlan,generateBatchABrowserQuestions} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p05f62.js";
import {buildBatchABrowserWorksheetDocument} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f62-extension.js";
import {renderG5AU09Q062Diagram} from "../../site/modules/renderer/g5a-u09-composite-polygon-area-diagram-p05f62.js";
import {renderRectangleSquareAreaFormulaDiagram} from "../../site/modules/renderer/rectangle-square-area-formula-diagram.js";
const read=p=>JSON.parse(readFileSync(new URL(`../../${p}`,import.meta.url),"utf8"));
const implementation=read("data/curriculum/full-product/p05f/q062-g5a-u09-composite-polygon-area-implementation.json"),impact=read("data/project/change-impact/P05F_W5_Q062.impact.json"),validation=read("data/project/validation-plans/P05F_W5_Q062.validation.json");
const request=(extra={})=>({sourceId:SRC,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[KP],questionMode:"diagram",questionCount:20,generationSeed:"q062-test",...extra});
const area=c=>c.shapeType==="PARALLELOGRAM"?c.baseCm*c.heightCm:c.shapeType==="TRIANGLE"?c.baseCm*c.heightCm/2:(c.topBaseCm+c.bottomBaseCm)*c.heightCm/2;

test("Q062 materializes the exact frozen composite-area contract without expanding scope",()=>{assert.equal(implementation.status,"IMPLEMENTATION_MATERIALIZED_AWAITING_FOCUSED_CI");assert.equal(implementation.queueAuthority.queuePosition,62);assert.deepEqual(implementation.queueAuthority.knowledgePointIds,[KP]);assert.deepEqual(implementation.queueAuthority.requiredW5CapabilityIds,CAPS);assert.deepEqual(implementation.productContract.includedRelations,RELATIONS);assert.equal(implementation.productContract.maxQuestionCount,240);for(const v of Object.values(implementation.scopeGuard))assert.equal(v,false);assert.deepEqual(auditG5AU09P05F62Projection(),{ok:true,errors:[],counts:{knowledgePoints:1,patternGroups:1,patternSpecs:3,formalMappings:1}});});

test("Q062 adds only composite polygon area while preserving four prior G5A-U09 public rows",()=>{const legacyRows=preQ062Selector.listVisibleBatchAKnowledgePoints().filter(x=>x.sourceId===SRC),legacyIds=legacyRows.map(x=>x.knowledgePointId).sort();assert.deepEqual(legacyIds,[...PRIOR].sort());assert.equal(preQ062Selector.getVisibleBatchAKnowledgePoint(KP),null);const a=auditP05F62PublicSelectorComposition();assert.equal(a.ok,true,a.errors.join("\n"));const s=listBatchAKnowledgePointAvailabilityBySource(SRC),afterIds=listVisibleBatchAKnowledgePoints().filter(x=>x.sourceId===SRC).map(x=>x.knowledgePointId).sort();assert.deepEqual(afterIds,[...PRIOR,KP].sort());assert.deepEqual([...s.visibleKnowledgePointIds].sort(),afterIds);assert.equal(s.visibleCount,5);assert.equal(s.hiddenPendingCount,0);assert.equal(s.notSelectableCount,0);assert.deepEqual([...s.q062AddedKnowledgePointIds],[KP]);assert.ok(getVisibleBatchAKnowledgePoint(KP));assert.equal(getVisiblePatternGroupsForKnowledgePoint(KP).length,1);assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(KP,"diagram"),SPECS);for(const id of PRIOR){assert.deepEqual(getVisibleBatchAKnowledgePoint(id),preQ062Selector.getVisibleBatchAKnowledgePoint(id));assert.deepEqual(getVisiblePatternGroupsForKnowledgePoint(id),preQ062Selector.getVisiblePatternGroupsForKnowledgePoint(id));assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(id),preQ062Selector.resolveVisiblePatternSpecIdsForKnowledgePoint(id));}});

test("Q062 public binding admits diagram-only composite area and keeps application/mixed modes closed",()=>{const a=auditPublicUiCapabilityBinding();assert.equal(a.ok,true,a.errors.join("\n"));const b=resolvePublicUiCapabilityBinding(request());assert.equal(b.blocked,false);assert.equal(b.questionType,"diagram");assert.equal(b.applicationSuitability,"APPLICATION_COMPATIBLE");assert.equal(b.applicationImplementationAllowed,false);assert.deepEqual(b.requiredCapabilityIds,CAPS);assert.equal(b.sameUnitMixedAdmission,false);assert.equal(b.crossUnitMixedAdmission,false);assert.equal(b.priorFormulaKnowledgePointsPrerequisiteOnly,true);});

for(const patternSpecId of SPECS)test(`Q062 ${patternSpecId} has 240 deterministic unique non-overlapping variants`,()=>{const a=generateG5AU09P05F62Questions({questionCount:240,patternSpecIds:[patternSpecId],generationSeed:"stable"}),b=generateG5AU09P05F62Questions({questionCount:240,patternSpecIds:[patternSpecId],generationSeed:"stable"});assert.equal(a.ok,true,a.errors.join("\n"));assert.deepEqual(a.questions,b.questions);assert.equal(new Set(a.questions.map(q=>q.questionSignature)).size,240);for(const q of a.questions){const d=q.geometryDiagram;assert.equal(d.nonOverlapping,true);assert.equal(d.decompositionComplete,true);assert.equal(d.wholeAreaEqualsSumOfParts,true);assert.equal(area(d.componentA)+area(d.componentB),d.totalAreaCm2);assert.equal(q.answerValue,d.totalAreaCm2);assert.equal(q.metadata.priorAreaFormulasUsedAsPrerequisites,true);assert.equal(q.metadata.applicationContextUsed,false);}});

test("Q062 validator fails closed on answer diagram and ownership mutation",()=>{const q=buildG5AU09P05F62Question({variant:17,patternSpecId:SPECS[0],generationSeed:"mut"});assert.equal(validateG5AU09P05F62Question(q).ok,true);assert.equal(validateG5AU09P05F62Question({...q,answerText:"999 平方公分"}).ok,false);assert.equal(validateG5AU09P05F62Question({...q,geometryDiagram:{...q.geometryDiagram,nonOverlapping:false}}).ok,false);assert.equal(validateG5AU09P05F62Question({...q,metadata:{...q.metadata,triangleAreaReowned:true}}).ok,false);});

test("Q062 browser plan generator worksheet and shared renderer are usable at D1",()=>{const p=buildBatchABrowserPlan(request({questionCount:8}));assert.equal(p.sourceId,SRC);assert.equal(p.questionCountMax,240);assert.deepEqual(p.selectedKnowledgePointIds,[KP]);const g=generateBatchABrowserQuestions(request({questionCount:8}));assert.equal(g.ok,true,g.errors.join("\n"));assert.equal(g.questions.length,8);const w=buildBatchABrowserWorksheetDocument(request({questionCount:8,includeAnswerKey:true,printLayout:{columns:2,rowsPerPage:4,showAnswerKeyPage:true}}));assert.equal(w.ok,true,w.errors.join("\n"));assert.equal(w.worksheetDocument.questionCount,8);assert.equal(w.worksheetDocument.answerKeyItems.length,8);assert.equal(w.worksheetDocument.summary.applicationQuestionCount,0);const direct=renderG5AU09Q062Diagram(g.questions[0].geometryDiagram),shared=renderRectangleSquareAreaFormulaDiagram(g.questions[0].geometryDiagram);assert.match(direct,/data-representation="composite-polygon-area-diagram"/);assert.equal(shared,direct);assert.match(direct,/各部分不重疊/);assert.ok(!direct.includes(`${g.questions[0].answerValue} 平方公分`));});

test("Q062 validation contract stays SHARED_RUNTIME_BOUNDED",()=>{assert.equal(impact.expectedDerivedGate,"SHARED_RUNTIME_BOUNDED");assert.equal(validation.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");const lane=validation.lanes.SHARED_RUNTIME_BOUNDED;assert.deepEqual(lane.map(x=>x.gateId),["GLOBAL_CONTRACTS","TARGETED_ROUTE_REPLAY"]);assert.equal(JSON.stringify(validation).includes("FULL_REPOSITORY"),false);});
