import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {materializeP05EW5DirectProductVerticalSliceQueue} from "../../src/curriculum/full-product/p05e-w5-direct-product-vertical-slice-queue.mjs";
import {materializeR04SharedRuntimeCapabilityMatrix} from "../../src/curriculum/global/r04-shared-runtime-capability-matrix.mjs";
import {materializeR05DeliveryWaveRebase} from "../../src/curriculum/global/r05-delivery-wave-rebase.mjs";
const read=p=>JSON.parse(readFileSync(new URL(`../../${p}`,import.meta.url),"utf8"));
const preflight=read("data/curriculum/full-product/p05f/q054-g5b-u07-composite-surface-area-hidden-faces-source-authority-preflight.json");
const q040=read("data/curriculum/full-product/p05f/q040-g5b-u07-surface-area-from-net-source-authority-preflight.json");
const q048=read("data/curriculum/full-product/p05f/q048-g5b-u07-cube-cuboid-surface-area-source-authority-preflight.json");
const r02=read("data/curriculum/global/candidates/r02/chunks/reviewed-source-candidates-05.json");
const KP="kp_g5b_u07_composite_surface_area_hidden_faces";
const CAPS=["cap_geometry_domain_validator","cap_geometry_property_reasoning","cap_solid_geometry_representation","cap_spatial_solid_reasoning"];
const sorted=v=>[...v].sort();

test("Q054 binds exact frozen row and Q053 D0 predecessor",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),row=q.queueEntries.find(x=>x.queuePosition===54);assert.equal(q.queueFrozen,true);assert.equal(q.queueRegistryParity,true);assert.equal(q.derivedRegistrySnapshot.queueDigest,"a4dae65a1a907ba963a135fce84ba292b8486a12513ae8f1fa54fbf07a6598ae");assert.ok(row);assert.equal(row.sliceId,"p05e_q054_r5_g5b_u07_5b07_profile_spatial_solid_c1");assert.equal(row.implementationTaskId,"P05F_W5DirectProductVerticalSlice054Implementation");assert.equal(row.previousSliceId,"p05e_q053_r5_g5b_u03_5b03_profile_geometry_formula_c1");assert.equal(row.previousSliceMustBeD0Complete,true);assert.equal(row.assignedDeliveryWaveId,"R05-W5");assert.equal(row.primarySourceNodeId,"g5b_u07_5b07");assert.deepEqual(row.supportingSourceNodeIds,["g5b_u07_5b07"]);assert.equal(row.intraWavePrerequisiteRank,5);assert.equal(row.primaryRuntimeProfileId,"profile_spatial_solid");assert.equal(row.chunkIndex,1);assert.equal(row.knowledgePointCount,1);assert.deepEqual(row.knowledgePointIds,[KP]);assert.deepEqual(sorted(row.requiredW5CapabilityIds),sorted(CAPS));assert.equal(row.targetEvidenceLevel,"E6_D0_COMPLETE");const p=preflight.previousSliceD0Evidence;assert.equal(p.productPrNumber,950);assert.equal(p.productHeadSha,"13546e39b2dec2fe5b6018c0cf16e0dbed3a08b1");assert.equal(p.productMergeSha,"037acf13c6a3b19ec101ade3abc62b5c742a238a");assert.equal(p.prGateRunId,"34962053715");assert.equal(p.pagesDeploymentRunId,"34962198225");assert.equal(p.exactPagesRunId,"34962198355");assert.equal(p.evidenceArtifactId,"10420840761");assert.equal(p.evidenceArtifactDigest,"sha256:d32f47fb81cd422cc6b0f3eabe815367216214998bbe2169bd1af1ca80b55db1");assert.equal(p.status,"PASS_E6_D0_COMPLETE");});

test("Q054 reuses verified G5B-U07 source identity from Q040 and Q048",()=>{const s=preflight.sourceAuthority;assert.equal(s.sourceNodeId,"g5b_u07_5b07");assert.equal(s.sourceTitle,"表面積");assert.equal(s.sourcePdfTitle,"meow911_5b07_source.pdf");assert.equal(s.sourcePdfDriveFileId,"19zLc-rrV6lauqhpxr6undOHHpcg__RKz");assert.equal(s.sourceMetadataDriveFileId,"1UHzU1OMhmO38Z-baRZl8wjWocGv5fOfa");assert.equal(s.verificationNotesDriveFileId,"1oMN8VzmrIhbmfeVUIJqWvc8RjVJYpzbL");assert.equal(s.sourceUrl,"https://meow911.com/5b07/");assert.equal(q048.sourceAuthority.sourceNodeId,s.sourceNodeId);assert.equal(q048.sourceAuthority.sourcePdfDriveFileId,s.sourcePdfDriveFileId);assert.equal(q040.sourceAuthority.sourceNodeId,s.sourceNodeId);assert.equal(q040.sourceAuthority.sourcePdfDriveFileId,s.sourcePdfDriveFileId);assert.deepEqual(s.reviewedPages,[1,2]);assert.equal(s.ocrUsedAsAuthority,false);assert.equal(s.sourceRefAmbiguity,false);assert.equal(s.manualSourceChoiceRequired,false);});

test("Q054 locks exact R02 composite exposed-surface candidate",()=>{const source=r02.sourceRecords.find(x=>x.sourceNodeId==="g5b_u07_5b07"),c=source?.candidates.find(x=>x.knowledgePointId===KP);assert.ok(c);assert.deepEqual(c,{knowledgePointId:KP,canonicalNameZh:"複合立體外露面積",capabilityStatement:"學生能扣除黏合或被遮蔽面求外露表面積。",reasoningInvariant:"內部接觸面不屬於外表面，接合處兩面均須扣除。",category:"geometry",evidencePages:[1,2],applicationSuitability:"APPLICATION_COMPATIBLE"});assert.deepEqual(preflight.r02ReviewedCandidateAuthority.knowledgePoint,c);assert.deepEqual(preflight.r02ReviewedCandidateAuthority.sameSourceCandidateIds,source.candidates.map(x=>x.knowledgePointId));});

test("Q054 binds current R04 spatial-solid mapping and exact R05 closure",()=>{const r04=materializeR04SharedRuntimeCapabilityMatrix(),m=r04.getMapping(KP),bound=preflight.runtimeCapabilityAuthority.mapping;assert.ok(m);assert.equal(m.mappingId,"r04map_g5b_u07_composite_surface_area_hidden_faces");assert.equal(m.primaryRuntimeProfileId,"profile_spatial_solid");assert.equal(m.classificationRuleId,"rule_spatial_solid");assert.deepEqual(m.appliedModifierIds,[]);assert.deepEqual(m.requiredRuntimeCapabilityIds,bound.requiredRuntimeCapabilityIds);assert.deepEqual(m.optionalRuntimeCapabilityIds,["cap_geometry_construction"]);assert.deepEqual(m.optionalRuntimeCapabilityIds,bound.optionalRuntimeCapabilityIds);assert.deepEqual(m.forbiddenRuntimeCapabilityIds,[]);const a=materializeR05DeliveryWaveRebase().getAssignment(KP);assert.ok(a);assert.equal(a.deliveryWaveId,"R05-W5");assert.equal(a.intraWavePrerequisiteRank,5);assert.equal(a.primaryRuntimeProfileId,"profile_spatial_solid");assert.deepEqual(sorted(a.contractOnlyRequiredCapabilityIds),sorted(CAPS));assert.deepEqual(sorted(preflight.runtimeCapabilityAuthority.exactFrozenQueueRequiredW5CapabilityIds),sorted(CAPS));assert.equal(preflight.runtimeCapabilityAuthority.surfaceAreaTermAlsoMatchesGeometryFormulaButSpatialRulePrecedencePreserved,true);assert.equal(preflight.runtimeCapabilityAuthority.mappingPolicyModifierMatchCount,0);});

test("Q054 owns hidden-face composite surface area only and protects Q040 Q048 Q059",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),owners={kp_g5b_u07_surface_area_from_net:40,kp_g5b_u07_cube_surface_area:48,kp_g5b_u07_cuboid_surface_area:48,kp_g5b_u07_surface_area_unknown_dimension:59};assert.deepEqual(preflight.q054ScopeLock.includedKnowledgePointIds,[KP]);for(const[kp,pos]of Object.entries(owners)){const row=q.queueEntries.find(x=>x.knowledgePointIds.includes(kp));assert.equal(row?.queuePosition,pos,kp);assert.equal(preflight.q054ScopeLock.protectedExistingSameSourceKnowledgePointOwnership[kp],`Q${String(pos).padStart(3,"0")}`);}assert.equal(preflight.q054ScopeLock.priorSameSourceSurfaceAreaFactsMayBeUsedAsPrerequisitesNotReowned,true);assert.equal(preflight.q054ScopeLock.internalContactFacesMustNotCountAsExteriorSurface,true);assert.equal(preflight.q054ScopeLock.eachJoinedInterfaceMustRemoveBothTouchingFaces,true);assert.equal(preflight.q054ScopeLock.componentSumModelMustSubtractTwiceEachContactArea,true);assert.equal(preflight.q054ScopeLock.directFaceEnumerationMustCountEachExposedFaceExactlyOnce,true);});

test("Q054 excludes sibling reownership application mixed mode and Q055+",()=>{for(const r of ["REOWN_SURFACE_AREA_FROM_NET","REOWN_CUBE_SURFACE_AREA","REOWN_CUBOID_SURFACE_AREA","SOLVE_UNKNOWN_DIMENSION_FROM_SURFACE_AREA_AS_TARGET_KP","GENERAL_NET_CONSTRUCTION_OR_FOLDABILITY_AS_TARGET_KP","GENERAL_APPLICATION_CONTEXT_IMPLEMENTATION","SAME_UNIT_MIXED_MODE","CROSS_UNIT_MIXED_MODE","Q055_OR_LATER_SEMANTICS"])assert.ok(preflight.q054ScopeLock.excludedRelations.includes(r),r);for(const k of ["applicationImplementationAllowedByThisPreflight","implementationAllowedByThisPreflight","publicProductAdmissionAllowedByThisPreflight","sameSourceSiblingSemanticsTouched","sameUnitMixedTouched","crossUnitMixedTouched","frozenQueueAuthorityTouched","r02AuthorityTouched","r04AuthorityTouched","r05AuthorityTouched","q055OrLaterTouched"])assert.equal(preflight.q054ScopeLock[k],false,k);assert.equal(preflight.q054ScopeLock.geometryConstructionRemainsOptionalNotW5Required,true);});

test("Q054 preflight stays bounded and stops at implementation approval boundary",()=>{const b=preflight.preflightValidationBoundary;assert.equal(b.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(b.derivedLane,"SHARED_RUNTIME_BOUNDED");assert.deepEqual(b.allowedLaneGateIds,["GLOBAL_CONTRACTS","TARGETED_ROUTE_REPLAY"]);assert.equal(b.focusedNodeContractRequired,true);assert.equal(b.nodeOnlyReadbackRequired,true);assert.equal(b.fullRepositoryRegressionAllowed,false);assert.equal(b.globalBrowserReplayAllowed,false);assert.equal(b.productImplementationAllowed,false);assert.equal(b.publicProductAdmissionAllowed,false);const d=preflight.preflightDecision;assert.equal(d.exactFrozenQueueRowResolved,true);assert.equal(d.sourceAuthoritySufficientForQ054ImplementationPlanning,true);assert.equal(d.previousSliceD0Satisfied,true);assert.equal(d.r02AuthorityBoundForTargetKnowledgePoint,true);assert.equal(d.runtimeCapabilityContractLocked,true);assert.equal(d.sameSourcePriorSliceOwnershipProtected,true);assert.equal(d.futureSameSourceOwnershipProtected,true);assert.equal(d.q040Q048SameSourceIdentityReusedWithoutReclassification,true);assert.equal(d.manualSourceChoiceRequired,false);assert.equal(d.sourceRefAmbiguity,false);assert.equal(d.separateImplementationApprovalSatisfiedByCurrentOperatorInstruction,false);assert.equal(d.nextTaskRequiresNewOperatorApproval,true);assert.equal(d.nextTask,"P05F_W5DirectProductVerticalSlice054Implementation");});
