import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {materializeP05EW5DirectProductVerticalSliceQueue} from "../../src/curriculum/full-product/p05e-w5-direct-product-vertical-slice-queue.mjs";
import {materializeR04SharedRuntimeCapabilityMatrix} from "../../src/curriculum/global/r04-shared-runtime-capability-matrix.mjs";
import {materializeR05DeliveryWaveRebase} from "../../src/curriculum/global/r05-delivery-wave-rebase.mjs";
const read=p=>JSON.parse(readFileSync(new URL(`../../${p}`,import.meta.url),"utf8"));
const preflight=read("data/curriculum/full-product/p05f/q061-g5a-u03a1-rectangle-square-tiling-source-authority-preflight.json");
const source=read("data/curriculum/knowledge/units/g5a_u03_5a03a1.knowledge-operation.json");
const impact=read("data/project/change-impact/P05F_W5_Q061_PREFLIGHT.impact.json");
const plan=read("data/project/validation-plans/P05F_W5_Q061_PREFLIGHT.validation.json");
const KP="kp_g5a_u03a1_rectangle_square_tiling";
const CAPS=["cap_geometry_diagram_representation","cap_geometry_domain_validator","cap_geometry_property_reasoning"];
const SIBLINGS=["kp_g5a_u03a1_common_multiple_lcm","kp_g5a_u03a1_grouping_constraints","kp_g5a_u03a1_bounded_common_multiples","kp_g5a_u03a1_factor_multiple_language","kp_g5a_u03a1_number_constraint_construction"];
const sorted=v=>[...v].sort();

test("Q061 binds the exact frozen row after Q060 E6 D0",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),row=q.queueEntries.find(x=>x.queuePosition===61);assert.equal(q.queueFrozen,true);assert.equal(q.queueRegistryParity,true);assert.equal(q.derivedRegistrySnapshot.queueDigest,"a4dae65a1a907ba963a135fce84ba292b8486a12513ae8f1fa54fbf07a6598ae");assert.ok(row);assert.equal(row.sliceId,"p05e_q061_r7_g5a_u03_5a03a1_profile_geometry_property_c1");assert.equal(row.implementationTaskId,"P05F_W5DirectProductVerticalSlice061Implementation");assert.equal(row.previousSliceId,"p05e_q060_r6_g6b_u03_6b03_profile_spatial_solid_c1");assert.equal(row.previousSliceMustBeD0Complete,true);assert.equal(row.assignedDeliveryWaveId,"R05-W5");assert.equal(row.primarySourceNodeId,"g5a_u03_5a03a1");assert.deepEqual(row.supportingSourceNodeIds,["g5a_u03_5a03a1"]);assert.equal(row.intraWavePrerequisiteRank,7);assert.equal(row.primaryRuntimeProfileId,"profile_geometry_property");assert.equal(row.chunkIndex,1);assert.equal(row.knowledgePointCount,1);assert.deepEqual(row.knowledgePointIds,[KP]);assert.deepEqual(sorted(row.requiredW5CapabilityIds),sorted(CAPS));assert.equal(row.targetEvidenceLevel,"E6_D0_COMPLETE");const p=preflight.previousSliceD0Evidence;assert.equal(p.preflightPrNumber,963);assert.equal(p.productPrNumber,964);assert.equal(p.productHeadSha,"c5105de7b76ed62af2a9830d9dc95208a2b64be4");assert.equal(p.productMergeSha,"fba0a83ae9b827f65c720a9beece610aac8a43eb");assert.equal(p.prGateRunId,"35105995901");assert.equal(p.exactPagesRunId,"35106267887");assert.equal(p.evidenceArtifactId,"10450915100");assert.equal(p.evidenceArtifactDigest,"sha256:13b1bcd1fe63807fb74cea412c4ff11adc818738dd1d5d56ccbd679271c85f6e");assert.equal(p.status,"PASS_E6_D0_COMPLETE");assert.equal(p.exactPagesEvidenceBoundToProductMergeSha,true);assert.equal(p.exactAssetDigestParity,true);});

test("Q061 locks exact W02 page-evidenced source and target candidate",()=>{assert.equal(source.sourceNodeId,"g5a_u03_5a03a1");assert.equal(source.sourceTitle,"公倍數");assert.equal(source.domainFamily,"common_multiple_and_cycle_alignment");assert.equal(source.candidateState,"PAGE_EVIDENCED_KP_CANDIDATES_CLASSIFIED_CANONICAL_MODEL_PENDING");assert.equal(source.sourceEvidence.sha256,"b329b79c2e4518ac42725b026ddd61ec6740020e33e74269824da967e477b393");assert.equal(source.sourceEvidence.contentIdentityGroup,"pdf_b329b79c2e45");assert.deepEqual(source.sourceEvidence.reviewedPages,[1,2]);assert.equal(source.sourceEvidence.reviewMethod,"FULL_PAGE_VISUAL_READBACK");const c=source.knowledgePoints.find(x=>x.candidateId===KP);assert.ok(c);assert.equal(c.name,"長方形拼成最小正方形");assert.equal(c.scope,"以長寬公倍數求無縫拼成正方形的最小邊長。");assert.deepEqual(c.evidencePages,[1]);assert.equal(c.applicationClassification,"APPLICATION_REQUIRED");assert.equal(c.classificationRationale,"來源的鋪排幾何限制直接決定最小公倍數模型。");const a=preflight.r02ReviewedCandidateAuthority.knowledgePoint;assert.equal(a.knowledgePointId,KP);assert.equal(a.canonicalNameZh,c.name);assert.equal(a.capabilityStatement,`學生能${c.scope}`);assert.equal(a.reasoningInvariant,"以長寬公倍數求無縫拼成正方形的最小邊長；改變數值或題面時必須保留相同核心判定或運算關係。");assert.deepEqual(a.evidencePages,c.evidencePages);assert.equal(a.applicationClassification,c.applicationClassification);assert.equal(a.classificationRationale,c.classificationRationale);assert.deepEqual(preflight.r02ReviewedCandidateAuthority.sameSourceCandidateIds,source.knowledgePoints.map(x=>x.candidateId));});

test("Q061 current R04 and R05 contracts exactly match the frozen queue",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),row=q.queueEntries.find(x=>x.queuePosition===61),r04=materializeR04SharedRuntimeCapabilityMatrix(),r05=materializeR05DeliveryWaveRebase(),m=r04.getMapping(KP),a=r05.getAssignment(KP);assert.ok(row);assert.ok(m);assert.ok(a);assert.equal(m.mappingId,"r04map_g5a_u03a1_rectangle_square_tiling");assert.equal(m.primaryRuntimeProfileId,row.primaryRuntimeProfileId);assert.equal(m.primaryRuntimeProfileId,"profile_geometry_property");assert.deepEqual(m.optionalRuntimeCapabilityIds,["cap_geometry_construction"]);for(const cap of ["cap_pattern_spec_resolution","cap_deterministic_answer_model","cap_worksheet_document_assembly","cap_answer_key_projection","cap_html_print_renderer","cap_geometry_property_reasoning","cap_geometry_domain_validator","cap_geometry_diagram_representation"])assert.ok(m.requiredRuntimeCapabilityIds.includes(cap),cap);assert.equal(a.deliveryWaveId,"R05-W5");assert.equal(a.intraWavePrerequisiteRank,7);assert.equal(a.primaryRuntimeProfileId,row.primaryRuntimeProfileId);assert.deepEqual(sorted(a.contractOnlyRequiredCapabilityIds),sorted(CAPS));assert.deepEqual(sorted(preflight.runtimeCapabilityAuthority.exactFrozenQueueRequiredW5CapabilityIds),sorted(CAPS));});

test("Q061 keeps all same-source siblings and Q062+ outside the preflight",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),scope=preflight.q061ScopeLock;assert.deepEqual(scope.includedKnowledgePointIds,[KP]);assert.deepEqual(scope.protectedSameSourceSiblingCandidateIds,SIBLINGS);for(const sibling of SIBLINGS)assert.equal(q.queueEntries.some(x=>x.knowledgePointIds.includes(sibling)),false,sibling);assert.equal(scope.sourceRequiredApplicationClassification,"APPLICATION_REQUIRED");assert.equal(scope.sourceGeometryConstraintMustRemainAuthoritative,true);assert.equal(scope.minimumCommonMultipleSemanticsMustRemainAuthoritative,true);for(const key of ["implementationAllowedByThisPreflight","publicProductAdmissionAllowedByThisPreflight","sameSourceSiblingSemanticsTouched","sameUnitMixedTouched","crossUnitMixedTouched","frozenQueueAuthorityTouched","r02AuthorityTouched","r03AuthorityTouched","r04AuthorityTouched","r05AuthorityTouched","q062OrLaterTouched"])assert.equal(scope[key],false,key);assert.ok(scope.excludedRelations.includes("Q062_OR_LATER_SEMANTICS"));});

test("Q061 preflight validation stays bounded and implementation requires a new approval",()=>{assert.equal(impact.expectedDerivedGate,"SHARED_RUNTIME_BOUNDED");assert.equal(impact.changeImpact.publicAuthorityCutover,false);assert.equal(impact.changeImpact.legalRouteSemanticsChanged,false);assert.equal(plan.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(plan.lanes.SHARED_RUNTIME_BOUNDED.length,2);assert.equal(plan.lanes.SHARED_RUNTIME_BOUNDED[0].kind,"NODE_TEST");assert.equal(plan.lanes.SHARED_RUNTIME_BOUNDED[1].runtime,"NODE_ONLY");const b=preflight.preflightValidationBoundary;assert.equal(b.derivedLane,"SHARED_RUNTIME_BOUNDED");assert.equal(b.fullRepositoryRegressionAllowed,false);assert.equal(b.globalBrowserReplayAllowed,false);const d=preflight.preflightDecision;assert.equal(d.previousSliceD0Satisfied,true);assert.equal(d.sourceAuthorityBound,true);assert.equal(d.r02AuthorityBoundForTargetKnowledgePoint,true);assert.equal(d.runtimeCapabilityContractLockedForTargetKnowledgePoint,true);assert.equal(d.applicationRequiredBoundaryLocked,true);assert.equal(d.manualSourceChoiceRequired,false);assert.equal(d.sourceRefAmbiguity,false);assert.equal(d.separateImplementationApprovalSatisfiedByCurrentOperatorInstruction,false);assert.equal(d.nextTaskRequiresNewOperatorApproval,true);assert.equal(d.nextTask,"P05F_W5DirectProductVerticalSlice061Implementation");});
