import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {materializeP05EW5DirectProductVerticalSliceQueue} from "../../src/curriculum/full-product/p05e-w5-direct-product-vertical-slice-queue.mjs";
import {materializeR04SharedRuntimeCapabilityMatrix} from "../../src/curriculum/global/r04-shared-runtime-capability-matrix.mjs";
import {materializeR05DeliveryWaveRebase} from "../../src/curriculum/global/r05-delivery-wave-rebase.mjs";
const read=p=>JSON.parse(readFileSync(new URL(`../../${p}`,import.meta.url),"utf8"));
const preflight=read("data/curriculum/full-product/p05f/q043-g4b-u07-rectangle-square-perimeter-formula-source-authority-preflight.json");
const r02=read("data/curriculum/global/candidates/r02/chunks/reviewed-source-candidates-02.json");
const KP="kp_g4b_u07_rectangle_square_perimeter_formula",CAPS=["cap_geometry_diagram_representation","cap_geometry_domain_validator","cap_geometry_formula_evaluation","cap_geometry_property_reasoning"];

test("Q043 binds exact frozen row and Q042 E6 predecessor",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),row=q.queueEntries.find(x=>x.queuePosition===43);assert.equal(q.queueFrozen,true);assert.equal(q.queueRegistryParity,true);assert.equal(q.queueRegistry.queueDigest,"a4dae65a1a907ba963a135fce84ba292b8486a12513ae8f1fa54fbf07a6598ae");assert.ok(row);assert.equal(row.sliceId,"p05e_q043_r4_g4b_u07_4b07_profile_geometry_formula_c1");assert.equal(row.implementationTaskId,"P05F_W5DirectProductVerticalSlice043Implementation");assert.equal(row.previousSliceId,"p05e_q042_r4_g4b_u02_4b02_profile_geometry_property_c1");assert.equal(row.previousSliceMustBeD0Complete,true);assert.equal(row.primarySourceNodeId,"g4b_u07_4b07");assert.equal(row.intraWavePrerequisiteRank,4);assert.equal(row.primaryRuntimeProfileId,"profile_geometry_formula");assert.equal(row.knowledgePointCount,1);assert.deepEqual(row.knowledgePointIds,[KP]);assert.deepEqual(row.requiredW5CapabilityIds,CAPS);const p=preflight.previousSliceD0Evidence;assert.equal(p.preflightPrNumber,926);assert.equal(p.productPrNumber,927);assert.equal(p.productHeadSha,"1c656e71e88b7bb799bcf61e1d1887cd0d67e00a");assert.equal(p.productMergeSha,"3a1a4bc5009eda316eec522e8d6d000ee5a17367");assert.equal(p.prGateRunId,"34803478317");assert.equal(p.exactPagesRunId,"34803900060");assert.equal(p.evidenceArtifactId,"10332871241");assert.equal(p.evidenceArtifactDigest,"sha256:5a46e0853726502d1d48f9e04334537304f00cd7a907856179b7a0d851a5b87c");assert.equal(p.status,"PASS_E6_D0_COMPLETE");});

test("Q043 reuses established G4B-U07 source identity and exact R02 perimeter-formula candidate",()=>{const source=r02.sourceRecords.find(x=>x.sourceNodeId==="g4b_u07_4b07"),candidate=source?.candidates.find(x=>x.knowledgePointId===KP);assert.ok(source);assert.ok(candidate);assert.equal(preflight.status,"PASS_SOURCE_AUTHORITY_PREFLIGHT");assert.equal(preflight.sourceAuthority.sourceNodeId,"g4b_u07_4b07");assert.equal(preflight.sourceAuthority.sourcePdfTitle,"meow911_4b07_source.pdf");assert.equal(preflight.sourceAuthority.sourcePdfDriveFileId,"19yZxx2bt_rQgqAA7Rx4HALoL3l3nfpw-");assert.equal(preflight.sourceAuthority.sourceUrlFromMetadata,"https://meow911.com/4b07/");assert.equal(preflight.sourceAuthority.embeddedHeaderUrlFromPdf,"https://meow911.com/4b06/");assert.deepEqual(preflight.sourceAuthority.reviewedPages,[1,2,3]);assert.equal(preflight.sourceAuthority.semanticAuthority,"R02_REVIEWED_SOURCE_CANDIDATE");assert.equal(preflight.sourceAuthority.currentPreflightDirectTargetPanelReplayPerformed,false);assert.equal(preflight.sourceAuthority.currentPreflightDirectTargetPanelReplayRequired,false);assert.equal(preflight.sourceAuthority.manualSourceChoiceRequired,false);assert.equal(preflight.sourceAuthority.sourceRefAmbiguity,false);assert.equal(candidate.canonicalNameZh,"長方形正方形周長公式");assert.equal(candidate.capabilityStatement,"學生能運用邊長關係求長方形與正方形周長。");assert.equal(candidate.reasoningInvariant,"長方形周長為兩組長寬和，正方形周長為邊長四倍。");assert.equal(candidate.category,"geometry");assert.deepEqual(candidate.evidencePages,[2]);assert.equal(candidate.applicationSuitability,"APPLICATION_COMPATIBLE");assert.deepEqual(preflight.r02ReviewedCandidateAuthority.sameSourceCandidateIds,source.candidates.map(x=>x.knowledgePointId));});

test("Q043 current R04/R05 contract is exact geometry-formula with no modifiers",()=>{const r04=materializeR04SharedRuntimeCapabilityMatrix(),m=r04.getMapping(KP);assert.ok(m);assert.equal(m.mappingId,"r04map_g4b_u07_rectangle_square_perimeter_formula");assert.equal(m.primaryRuntimeProfileId,"profile_geometry_formula");assert.equal(m.classificationRuleId,"rule_geometry_formula");assert.deepEqual(m.appliedModifierIds,[]);const profile=r04.profiles.find(x=>x.profileId==="profile_geometry_formula");assert.ok(profile);for(const cap of ["cap_geometry_formula_evaluation","cap_geometry_domain_validator","cap_geometry_diagram_representation"])assert.ok(profile.requiredCapabilityIds.includes(cap));const r05=materializeR05DeliveryWaveRebase(),a=r05.getAssignment(KP);assert.ok(a);assert.equal(a.deliveryWaveId,"R05-W5");assert.equal(a.intraWavePrerequisiteRank,4);assert.equal(a.primaryRuntimeProfileId,"profile_geometry_formula");assert.deepEqual([...a.contractOnlyRequiredCapabilityIds].sort(),[...CAPS].sort());assert.deepEqual(preflight.runtimeCapabilityAuthority.exactFrozenQueueRequiredW5CapabilityIds,CAPS);});

test("Q043 preserves prior G4B-U07 owners and future Q050 composite-perimeter ownership",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),expected={kp_g4b_u07_rectangle_square_area_formula:26,kp_g4b_u07_composite_rectilinear_area:34,kp_g4b_u07_perimeter_path_sum:34,kp_g4b_u07_rectangle_square_perimeter_formula:43,kp_g4b_u07_composite_perimeter:50};for(const[id,pos]of Object.entries(expected)){const row=q.queueEntries.find(x=>x.knowledgePointIds.includes(id));assert.ok(row,id);assert.equal(row.queuePosition,pos,id);}for(const[id,owner]of Object.entries(preflight.q043ScopeLock.protectedFrozenOwnership))assert.equal(owner,`Q${String(expected[id]).padStart(3,"0")}`);assert.equal(preflight.q043ScopeLock.deferredFrozenOwnership.kp_g4b_u07_composite_perimeter,"Q050");const later=q.queueEntries.filter(x=>x.primarySourceNodeId==="g4b_u07_4b07"&&x.queuePosition>43);assert.ok(later.some(x=>x.queuePosition===50&&x.knowledgePointIds.includes("kp_g4b_u07_composite_perimeter")));});

test("Q043 scope is rectangle/square perimeter formula only and implementation remains approval-gated",()=>{for(const r of ["COMPUTE_RECTANGLE_PERIMETER_AS_TWO_TIMES_LENGTH_WIDTH_SUM","COMPUTE_SQUARE_PERIMETER_AS_FOUR_TIMES_SIDE","REWRITE_RECTANGLE_PERIMETER_FROM_OUTER_SIDE_SUM_USING_OPPOSITE_SIDE_EQUALITY"])assert.ok(preflight.q043ScopeLock.includedRelations.includes(r));for(const r of ["REOWN_PERIMETER_PATH_SUM_AS_PRIMARY_TARGET","REOWN_RECTANGLE_SQUARE_AREA_FORMULA","REOWN_COMPOSITE_RECTILINEAR_AREA","COMPOSITE_PERIMETER_AS_TARGET_KP","AREA_PERIMETER_COMPARISON_CONTEXT","APPLICATION_CONTEXT_IMPLEMENTATION","SAME_UNIT_MIXED_MODE","CROSS_UNIT_MIXED_MODE","Q044_OR_LATER_SEMANTICS"])assert.ok(preflight.q043ScopeLock.excludedRelations.includes(r));assert.equal(preflight.q043ScopeLock.rectanglePerimeterMustEqualTwiceLengthPlusWidthSum,true);assert.equal(preflight.q043ScopeLock.squarePerimeterMustEqualFourTimesSide,true);assert.equal(preflight.q043ScopeLock.genericClosedBoundaryPathSumRemainsOwnedByQ034,true);assert.equal(preflight.q043ScopeLock.implementationAllowedByThisPreflight,false);assert.equal(preflight.q043ScopeLock.publicProductAdmissionAllowedByThisPreflight,false);const b=preflight.preflightValidationBoundary;assert.equal(b.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(b.derivedLane,"SHARED_RUNTIME_BOUNDED");assert.equal(b.fullRepositoryRegressionAllowed,false);assert.equal(b.globalBrowserReplayAllowed,false);const d=preflight.preflightDecision;assert.equal(d.previousSliceD0Satisfied,true);assert.equal(d.existingSameSourceQ026Q034Protected,true);assert.equal(d.futureSameSourceQ050Protected,true);assert.equal(d.manualSourceChoiceRequired,false);assert.equal(d.sourceRefAmbiguity,false);assert.equal(d.separateImplementationApprovalSatisfiedByCurrentOperatorInstruction,false);assert.equal(d.nextTaskRequiresNewOperatorApproval,true);assert.equal(d.nextTask,"P05F_W5DirectProductVerticalSlice043Implementation");});
