import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {materializeP05EW5DirectProductVerticalSliceQueue} from "../../src/curriculum/full-product/p05e-w5-direct-product-vertical-slice-queue.mjs";
import {materializeR04SharedRuntimeCapabilityMatrix} from "../../src/curriculum/global/r04-shared-runtime-capability-matrix.mjs";
import {materializeR05DeliveryWaveRebase} from "../../src/curriculum/global/r05-delivery-wave-rebase.mjs";
const read=p=>JSON.parse(readFileSync(new URL(`../../${p}`,import.meta.url),"utf8"));
const preflight=read("data/curriculum/full-product/p05f/q040-g5b-u07-surface-area-from-net-source-authority-preflight.json");
const r02=read("data/curriculum/global/candidates/r02/chunks/reviewed-source-candidates-05.json");
const mappingPolicy=read("data/curriculum/global/runtime/r04/runtime-capability-mapping-policy.json");
const KP="kp_g5b_u07_surface_area_from_net",CAPS=["cap_geometry_diagram_representation","cap_geometry_domain_validator","cap_geometry_formula_evaluation","cap_geometry_property_reasoning"];

test("Q040 binds exact frozen row and Q039 E6 predecessor",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),row=q.queueEntries.find(x=>x.queuePosition===40);assert.equal(q.queueFrozen,true);assert.equal(q.queueRegistryParity,true);assert.equal(q.queueRegistry.queueDigest,"a4dae65a1a907ba963a135fce84ba292b8486a12513ae8f1fa54fbf07a6598ae");assert.ok(row);assert.equal(row.sliceId,"p05e_q040_r3_g5b_u07_5b07_profile_geometry_formula_c1");assert.equal(row.implementationTaskId,"P05F_W5DirectProductVerticalSlice040Implementation");assert.equal(row.previousSliceId,"p05e_q039_r3_g5b_u03_5b03_profile_geometry_formula_c1");assert.equal(row.previousSliceMustBeD0Complete,true);assert.equal(row.primarySourceNodeId,"g5b_u07_5b07");assert.equal(row.intraWavePrerequisiteRank,3);assert.equal(row.primaryRuntimeProfileId,"profile_geometry_formula");assert.equal(row.knowledgePointCount,1);assert.deepEqual(row.knowledgePointIds,[KP]);assert.deepEqual(row.requiredW5CapabilityIds,CAPS);const p=preflight.previousSliceD0Evidence;assert.equal(p.productPrNumber,921);assert.equal(p.productMergeSha,"17244674ded4878eaa82f4820191ae3cb87f9195");assert.equal(p.prGateRunId,"34795063746");assert.equal(p.pagesDeploymentRunId,"34795166808");assert.equal(p.exactPagesRunId,"34795166852");assert.equal(p.evidenceArtifactId,"10329497534");assert.equal(p.evidenceArtifactDigest,"sha256:fd2abc576f019a04c1d8e8bb576209aa5ad21315f6045ea6fe7ca2353ba4497c");assert.equal(p.status,"PASS_E6_D0_COMPLETE");});

test("Q040 binds current Drive source identity and R02 reviewed target without OCR authority",()=>{const s=preflight.sourceAuthority;assert.equal(preflight.status,"PASS_SOURCE_AUTHORITY_PREFLIGHT");assert.equal(s.sourceNodeId,"g5b_u07_5b07");assert.equal(s.sourceTitle,"表面積");assert.equal(s.sourcePdfTitle,"meow911_5b07_source.pdf");assert.equal(s.sourcePdfDriveFileId,"19zLc-rrV6lauqhpxr6undOHHpcg__RKz");assert.equal(s.sourceMetadataDriveFileId,"1UHzU1OMhmO38Z-baRZl8wjWocGv5fOfa");assert.equal(s.verificationNotesDriveFileId,"1oMN8VzmrIhbmfeVUIJqWvc8RjVJYpzbL");assert.equal(s.sourceUrlFromMetadata,"https://meow911.com/5b07/");assert.equal(s.pageCount,2);assert.deepEqual(s.reviewedPages,[1,2]);assert.equal(s.verificationStateReconciliation.legacyDriveVerificationNoteSaysDoNotTreatOCRAsAuthority,true);assert.equal(s.verificationStateReconciliation.r02FullPageReviewIsCurrentSemanticAuthority,true);assert.equal(s.verificationStateReconciliation.currentDirectPdfVisualVerificationCompleted,true);assert.deepEqual(s.targetEvidenceReconciliation.surfaceAreaFromNet.directVisualCorroborationPages,[1]);assert.equal(s.sourceRefAmbiguity,false);assert.equal(s.manualSourceChoiceRequired,false);});

test("Q040 R02 candidate is exactly surface-area-from-net and siblings stay separate",()=>{const source=r02.sourceRecords.find(x=>x.sourceNodeId==="g5b_u07_5b07");assert.ok(source);assert.equal(source.sourceTitle,"表面積");assert.equal(source.sourcePdfTitle,"meow911_5b07_source.pdf");assert.deepEqual(source.reviewedPages,[1,2]);const c=source.candidates.find(x=>x.knowledgePointId===KP);assert.ok(c);assert.equal(c.canonicalNameZh,"由展開圖求表面積");assert.equal(c.capabilityStatement,"學生能辨認展開圖各面並加總面積。");assert.equal(c.reasoningInvariant,"每個外露面恰計一次，摺疊相鄰關係不改變面積。");assert.equal(c.category,"geometry");assert.deepEqual(c.evidencePages,[1,2]);assert.equal(c.applicationSuitability,"APPLICATION_COMPATIBLE");assert.deepEqual(preflight.r02ReviewedCandidateAuthority.sameSourceCandidateIds,source.candidates.map(x=>x.knowledgePointId));assert.deepEqual(preflight.q040ScopeLock.excludedSameSourceKnowledgePointIds,["kp_g5b_u07_cube_surface_area","kp_g5b_u07_cuboid_surface_area","kp_g5b_u07_composite_surface_area_hidden_faces","kp_g5b_u07_surface_area_unknown_dimension"]);});

test("Q040 current R04/R05 contract stays geometry-formula with no silent net-construction modifier",()=>{const r04=materializeR04SharedRuntimeCapabilityMatrix(),m=r04.getMapping(KP);assert.ok(m);assert.equal(m.mappingId,"r04map_g5b_u07_surface_area_from_net");assert.equal(m.primaryRuntimeProfileId,"profile_geometry_formula");assert.equal(m.classificationRuleId,"rule_geometry_formula");assert.deepEqual(m.appliedModifierIds,[]);const profile=r04.profiles.find(x=>x.profileId==="profile_geometry_formula");assert.ok(profile);for(const cap of ["cap_geometry_formula_evaluation","cap_geometry_domain_validator","cap_geometry_diagram_representation"])assert.ok(profile.requiredCapabilityIds.includes(cap));const mod=mappingPolicy.modifiers.find(x=>x.modifierId==="mod_geometry_construction");assert.ok(mod);assert.equal(mod.profileIds.includes("profile_geometry_formula"),false);assert.equal(preflight.runtimeCapabilityAuthority.geometryConstructionModifierObservation.q040ProfileEligible,false);const r05=materializeR05DeliveryWaveRebase(),a=r05.getAssignment(KP);assert.ok(a);assert.equal(a.deliveryWaveId,"R05-W5");assert.equal(a.intraWavePrerequisiteRank,3);assert.equal(a.primaryRuntimeProfileId,"profile_geometry_formula");assert.deepEqual([...a.contractOnlyRequiredCapabilityIds].sort(),[...CAPS].sort());});

test("Q040 deferred same-source ownership remains Q048/Q054/Q059",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),expected={kp_g5b_u07_cube_surface_area:48,kp_g5b_u07_cuboid_surface_area:48,kp_g5b_u07_composite_surface_area_hidden_faces:54,kp_g5b_u07_surface_area_unknown_dimension:59};for(const[id,pos]of Object.entries(expected)){const row=q.queueEntries.find(x=>x.knowledgePointIds.includes(id));assert.ok(row,id);assert.equal(row.queuePosition,pos,id);assert.equal(preflight.q040ScopeLock.deferredFrozenQueueOwnership[id],`Q${String(pos).padStart(3,"0")}`);}});

test("Q040 scope admits only net-to-surface-area semantics and stops before implementation",()=>{for(const r of ["MAP_NET_FACES_TO_OUTER_SOLID_FACES","SUM_EACH_OUTER_NET_FACE_AREA_EXACTLY_ONCE","PRESERVE_FACE_AREA_AND_ADJACENCY_UNDER_FOLDING"])assert.ok(preflight.q040ScopeLock.includedRelations.includes(r));for(const r of ["DIRECT_CUBE_SURFACE_AREA_FORMULA_AS_TARGET_KP","DIRECT_CUBOID_SURFACE_AREA_FORMULA_AS_TARGET_KP","COMPOSITE_HIDDEN_FACE_SURFACE_AREA_AS_TARGET_KP","SURFACE_AREA_UNKNOWN_DIMENSION_AS_TARGET_KP","GENERAL_NET_CONSTRUCTION_OR_FOLDABILITY_AS_TARGET_KP","APPLICATION_CONTEXT_IMPLEMENTATION","Q041_OR_LATER_SEMANTICS"])assert.ok(preflight.q040ScopeLock.excludedRelations.includes(r));assert.equal(preflight.q040ScopeLock.eachOuterFaceMustBeCountedExactlyOnce,true);assert.equal(preflight.q040ScopeLock.foldingAdjacencyMustPreserveFaceArea,true);assert.equal(preflight.q040ScopeLock.implementationAllowedByThisPreflight,false);assert.equal(preflight.q040ScopeLock.publicProductAdmissionAllowedByThisPreflight,false);const b=preflight.preflightValidationBoundary;assert.equal(b.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(b.derivedLane,"SHARED_RUNTIME_BOUNDED");assert.equal(b.fullRepositoryRegressionAllowed,false);assert.equal(b.globalBrowserReplayAllowed,false);const d=preflight.preflightDecision;assert.equal(d.previousSliceD0Satisfied,true);assert.equal(d.currentDirectPdfVisualVerificationCompleted,true);assert.equal(d.manualSourceChoiceRequired,false);assert.equal(d.sourceRefAmbiguity,false);assert.equal(d.nextTaskRequiresNewOperatorApproval,true);assert.equal(d.nextTask,"P05F_W5DirectProductVerticalSlice040Implementation");});
