import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {buildBatchABrowserWorksheetDocument as buildQ034Worksheet} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f34-extension.js";
import {buildBatchABrowserWorksheetDocument as buildCurrentTopSlotWorksheet} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f32-extension.js";
import {generateG4BU07P05F34Questions,validateG4BU07P05F34Question} from "../../site/modules/curriculum/batch-a/g4b-u07-composite-area-perimeter-path-runtime-p05f34.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";
import {auditG4BU07P05F34Projection,G4B_U07_P05F34_AREA_GROUP_ID,G4B_U07_P05F34_AREA_KP_ID,G4B_U07_P05F34_AREA_SPEC_IDS,G4B_U07_P05F34_KP_IDS,G4B_U07_P05F34_PERIMETER_GROUP_ID,G4B_U07_P05F34_PERIMETER_KP_ID,G4B_U07_P05F34_PERIMETER_SPEC_IDS,G4B_U07_P05F34_SOURCE_ID} from "../../site/modules/curriculum/registry/g4b-u07-composite-area-perimeter-path-selector-projection-p05f34.js";
import {auditP05F34PublicSelectorComposition,getVisibleBatchAKnowledgePoint,listBatchAKnowledgePointAvailabilityBySource,resolveVisiblePatternSpecIdsForKnowledgePoint} from "../../site/modules/curriculum/registry/batch-a-selector-p05f34-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p05f34.js";
const preflight=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q034-g4b-u07-composite-area-perimeter-path-source-authority-preflight.json",import.meta.url),"utf8"));
const implementation=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q034-g4b-u07-composite-area-perimeter-path-implementation.json",import.meta.url),"utf8"));
const opts=(kpId,count=24)=>({sourceId:G4B_U07_P05F34_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[kpId],selectedPatternGroupIds:[kpId===G4B_U07_P05F34_AREA_KP_ID?G4B_U07_P05F34_AREA_GROUP_ID:G4B_U07_P05F34_PERIMETER_GROUP_ID],patternSpecIds:[...(kpId===G4B_U07_P05F34_AREA_KP_ID?G4B_U07_P05F34_AREA_SPEC_IDS:G4B_U07_P05F34_PERIMETER_SPEC_IDS)],questionMode:"diagram",requestedQuestionType:"diagram",questionCount:count,generationSeed:`p05f34-focused-${kpId}`,includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showQuestionNumbers:true,showAnswerKeyPage:true}});
const occurrences=(text,token)=>text.split(token).length-1;

test("Q034 exact preflight and implementation identities remain frozen",()=>{assert.equal(preflight.status,"PASS_SOURCE_AUTHORITY_PREFLIGHT");assert.equal(preflight.queueAuthority.queuePosition,34);assert.deepEqual(preflight.queueAuthority.knowledgePointIds,G4B_U07_P05F34_KP_IDS);assert.equal(preflight.previousSliceD0Evidence.status,"PASS_E6_D0_COMPLETE");assert.equal(implementation.taskId,"P05F_W5DirectProductVerticalSlice034Implementation");assert.equal(implementation.queueAuthority.sliceId,"p05e_q034_r3_g4b_u07_4b07_profile_geometry_formula_c1");assert.equal(implementation.scopeGuard.rectangleSquarePerimeterFormulaTouched,false);assert.equal(implementation.scopeGuard.compositePerimeterTouched,false);});

test("Q034 materializes 2 mappings 2 groups and 6 bounded PatternSpecs",()=>{const audit=auditG4BU07P05F34Projection();assert.equal(audit.ok,true,audit.errors.join("\n"));assert.deepEqual(audit.counts,{knowledgePoints:2,patternGroups:2,patternSpecs:6,areaSpecs:3,perimeterSpecs:3});});

test("Q034 public selector promotes exactly two KPs and preserves Q026 plus Q043/Q050 deferrals",()=>{const audit=auditP05F34PublicSelectorComposition();assert.equal(audit.ok,true,audit.errors.join("\n"));const source=listBatchAKnowledgePointAvailabilityBySource(G4B_U07_P05F34_SOURCE_ID);assert.equal(source.visibleCount,3);assert.equal(source.hiddenPendingCount,2);assert.equal(source.notSelectableCount,2);for(const id of ["kp_g4b_u07_rectangle_square_area_formula",...G4B_U07_P05F34_KP_IDS])assert.ok(getVisibleBatchAKnowledgePoint(id));for(const id of ["kp_g4b_u07_rectangle_square_perimeter_formula","kp_g4b_u07_composite_perimeter"])assert.equal(getVisibleBatchAKnowledgePoint(id),null);assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(G4B_U07_P05F34_AREA_KP_ID,"diagram"),G4B_U07_P05F34_AREA_SPEC_IDS);assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(G4B_U07_P05F34_PERIMETER_KP_ID,"diagram"),G4B_U07_P05F34_PERIMETER_SPEC_IDS);});

test("Q034 public binding exposes only single-KP diagram paths",()=>{const audit=auditPublicUiCapabilityBinding();assert.equal(audit.ok,true,audit.errors.join("\n"));const a=resolvePublicUiCapabilityBinding(opts(G4B_U07_P05F34_AREA_KP_ID)),p=resolvePublicUiCapabilityBinding(opts(G4B_U07_P05F34_PERIMETER_KP_ID));assert.equal(a.compositeRectilinearAreaTarget,true);assert.equal(a.areaPartitionComplementEquivalenceRequired,true);assert.equal(p.perimeterPathSumTarget,true);assert.equal(p.outerBoundaryOnlyRequired,true);assert.equal(p.interiorSegmentsExcludedRequired,true);for(const b of [a,p]){assert.equal(b.questionType,"diagram");assert.equal(b.questionCount.max,240);assert.equal(b.rectangleSquareAreaFormulaReowned,false);assert.equal(b.rectangleSquarePerimeterFormulaAdmission,false);assert.equal(b.compositePerimeterAdmission,false);assert.equal(b.sameUnitMixedAdmission,false);assert.equal(b.crossUnitMixedAdmission,false);}});

test("Q034 both KPs generate deterministic validated worksheet questions",()=>{for(const kpId of G4B_U07_P05F34_KP_IDS){const a=generateG4BU07P05F34Questions({...opts(kpId),questionCount:24}),b=generateG4BU07P05F34Questions({...opts(kpId),questionCount:24});assert.equal(a.ok,true,a.errors.join("\n"));assert.deepEqual(a.questions,b.questions);assert.equal(a.questions.length,24);assert.equal(new Set(a.questions.map(q=>q.questionSignature)).size,24);assert.equal(a.questions.every(q=>validateG4BU07P05F34Question(q).ok),true);assert.equal(a.questions.every(q=>q.metadata.rectangleSquarePerimeterFormulaTouched===false&&q.metadata.compositePerimeterTouched===false&&q.metadata.applicationContextUsed===false&&q.metadata.q035OrLaterTouched===false),true);}});

test("Q034 proves 240 distinct variants for every PatternSpec",()=>{for(const kpId of G4B_U07_P05F34_KP_IDS){const ids=kpId===G4B_U07_P05F34_AREA_KP_ID?G4B_U07_P05F34_AREA_SPEC_IDS:G4B_U07_P05F34_PERIMETER_SPEC_IDS;for(const patternSpecId of ids){const r=generateG4BU07P05F34Questions({knowledgePointId:kpId,questionCount:240,patternSpecIds:[patternSpecId],generationSeed:`capacity-${patternSpecId}`});assert.equal(r.ok,true,`${patternSpecId}:${r.errors.join("\n")}`);assert.equal(r.questions.length,240);assert.equal(new Set(r.questions.map(q=>q.questionSignature)).size,240);}}});

test("Q034 validators fail closed on area/perimeter tampering",()=>{const a=generateG4BU07P05F34Questions({...opts(G4B_U07_P05F34_AREA_KP_ID),questionCount:1}).questions[0],p=generateG4BU07P05F34Questions({...opts(G4B_U07_P05F34_PERIMETER_KP_ID),questionCount:1}).questions[0];const ta=JSON.parse(JSON.stringify(a));ta.geometryDiagram.areaCm2+=1;assert.equal(validateG4BU07P05F34Question(ta).ok,false);const tp=JSON.parse(JSON.stringify(p));tp.geometryDiagram.perimeterCm+=tp.geometryDiagram.interiorCm;assert.equal(validateG4BU07P05F34Question(tp).ok,false);const ti=generateG4BU07P05F34Questions({knowledgePointId:G4B_U07_P05F34_PERIMETER_KP_ID,questionCount:1,patternSpecIds:["ps_g4b_u07_perimeter_exclude_interior"],generationSeed:"tamper-interior"}).questions[0],tii=JSON.parse(JSON.stringify(ti));tii.geometryDiagram.showInterior=false;assert.equal(validateG4BU07P05F34Question(tii).ok,false);});

test("Q034 worksheet and shared renderer project both diagram subtypes into questions and answers",()=>{for(const kpId of G4B_U07_P05F34_KP_IDS){const r=buildQ034Worksheet(opts(kpId,16));assert.equal(r.ok,true,r.errors.join("\n"));assert.equal(r.worksheetDocument.questionCount,16);assert.equal(r.worksheetDocument.answerKeyItems.length,16);const html=renderWorksheetDocumentToHtml(r.worksheetDocument,{stylesheetHref:"",title:r.worksheetDocument.title});const rep=kpId===G4B_U07_P05F34_AREA_KP_ID?"composite-rectilinear-area-diagram":"perimeter-path-sum-diagram";assert.equal(occurrences(html,`data-representation="${rep}"`),32);assert.equal(html.includes("kp_g4b_u07_"),false);assert.equal(html.includes("ps_g4b_u07_"),false);}});

test("Q034 current top-slot bridge reaches both new worksheets while preserving explicit implementation",()=>{for(const kpId of G4B_U07_P05F34_KP_IDS){const r=buildCurrentTopSlotWorksheet(opts(kpId,8));assert.equal(r.ok,true,r.errors.join("\n"));assert.equal(r.p05f34Implemented,true);assert.equal(r.worksheetDocument.metadata.knowledgePointId,kpId);}});

test("Q034 browser current selector and binding wrappers expose Q034 while retaining Q026 and Q033",async()=>{globalThis.document={};try{const selector=await import(`../../site/modules/curriculum/registry/batch-a-selector-p04f33-extension.js?p05f34=${Date.now()}`),binding=await import(`../../site/modules/curriculum/public/public-ui-capability-binding-p04f33.js?p05f34=${Date.now()}`);for(const id of G4B_U07_P05F34_KP_IDS){assert.equal(selector.getVisibleBatchAKnowledgePoint(id)?.sourceId,G4B_U07_P05F34_SOURCE_ID);assert.equal(binding.resolvePublicUiCapabilityBinding(opts(id)).blocked,false);}assert.ok(selector.getVisibleBatchAKnowledgePoint("kp_g4b_u07_rectangle_square_area_formula"));assert.ok(selector.getVisibleBatchAKnowledgePoint("kp_g4b_u02_parallel_distance_construction"));assert.ok(selector.getVisibleBatchAKnowledgePoint("kp_g4b_u02_quadrilateral_classification"));for(const id of ["kp_g4b_u07_rectangle_square_perimeter_formula","kp_g4b_u07_composite_perimeter"])assert.equal(selector.getVisibleBatchAKnowledgePoint(id),null);}finally{delete globalThis.document;}});
