import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {G5A_U09_P05F57_FORMAL_MAPPING as MAP,G5A_U09_P05F57_KP_ID as KP,G5A_U09_P05F57_PATTERN_GROUP_ID as GROUP,G5A_U09_P05F57_PATTERN_SPECS as PATTERNS,G5A_U09_P05F57_PRIOR_VISIBLE_KP_IDS as PRIOR,G5A_U09_P05F57_PROTECTED_KP_IDS as PROTECTED,G5A_U09_P05F57_REQUIRED_CAPABILITY_IDS as REQUIRED,G5A_U09_P05F57_SOURCE_ID as SRC,G5A_U09_P05F57_SPEC_IDS as SPECS,auditG5AU09P05F57Projection} from "../../site/modules/curriculum/registry/g5a-u09-area-unknown-dimension-selector-projection-p05f57.js";
import {auditP05F57PublicSelectorComposition,getVisibleBatchAKnowledgePoint,listBatchAKnowledgePointAvailabilityBySource} from "../../site/modules/curriculum/registry/batch-a-selector-p05f57-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p05f57.js";
import {generateG5AU09P05F57Questions,validateG5AU09P05F57Question} from "../../site/modules/curriculum/batch-a/g5a-u09-area-unknown-dimension-runtime-p05f57.js";
import {requestsP05F57} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p05f57.js";
import {buildBatchABrowserWorksheetDocument as buildQ057} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f57-extension.js";
import {buildBatchABrowserWorksheetDocument as buildCurrent} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f32-extension.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";
const preflight=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q057-g5a-u09-area-unknown-dimension-source-authority-preflight.json",import.meta.url),"utf8"));
const implementation=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q057-g5a-u09-area-unknown-dimension-implementation.json",import.meta.url),"utf8"));
const impact=JSON.parse(readFileSync(new URL("../../data/project/change-impact/P05F_W5_Q057.impact.json",import.meta.url),"utf8"));
const plan=JSON.parse(readFileSync(new URL("../../data/project/validation-plans/P05F_W5_Q057.validation.json",import.meta.url),"utf8"));
const req=(count=24)=>({sourceId:SRC,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[KP],selectedPatternGroupIds:[GROUP],patternSpecIds:[...SPECS],questionMode:"diagram",requestedQuestionType:"diagram",questionCount:count,generationSeed:"p05f57-focused-area-unknown",includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showQuestionNumbers:true,showAnswerKeyPage:true}});
const occ=(t,x)=>t.split(x).length-1;

test("Q057 exact frozen identity and R02 page-4 authority remain locked",()=>{assert.equal(preflight.status,"PASS_SOURCE_AUTHORITY_PREFLIGHT");assert.equal(preflight.queueAuthority.queuePosition,57);assert.equal(preflight.queueAuthority.sliceId,"p05e_q057_r6_g5a_u09_5a09_profile_geometry_formula_c1");assert.deepEqual(preflight.queueAuthority.knowledgePointIds,[KP]);assert.equal(preflight.previousSliceD0Evidence.status,"PASS_E6_D0_COMPLETE");assert.deepEqual(implementation.sourceAuthority.sourcePages,[4]);assert.equal(MAP.r04MappingId,"r04map_g5a_u09_area_unknown_dimension");assert.deepEqual(MAP.sourcePages,[4]);assert.equal(MAP.capabilityStatement,"學生能由面積與另一尺寸反求未知底或高。");assert.equal(MAP.reasoningInvariant,"反求結果代回面積公式必須重建原面積。");});

test("Q057 materializes one mapping one group and six area inverse PatternSpecs",()=>{const a=auditG5AU09P05F57Projection();assert.equal(a.ok,true,a.errors.join("\n"));assert.equal(PATTERNS.length,6);assert.deepEqual(REQUIRED,["cap_geometry_diagram_representation","cap_geometry_domain_validator","cap_geometry_formula_evaluation","cap_geometry_property_reasoning"]);assert.equal(MAP.prerequisiteFormulaKnowledgePointIds.length,3);assert.equal(MAP.appliedRuntimeModifierIds.length,0);assert.equal(MAP.optionalRuntimeCapabilityIds.length,0);assert.equal(new Set(PATTERNS.map(x=>`${x.shapeType}:${x.targetDimension}`)).size,6);});

test("Q057 promotes only unknown-dimension and preserves Q037 Q046 owners plus Q062 future ownership",()=>{const a=auditP05F57PublicSelectorComposition();assert.equal(a.ok,true,a.errors.join("\n"));const s=listBatchAKnowledgePointAvailabilityBySource(SRC);assert.equal(s.visibleCount,4);assert.equal(s.hiddenPendingCount,1);assert.equal(s.notSelectableCount,1);for(const id of [...PRIOR,KP])assert.equal(getVisibleBatchAKnowledgePoint(id)?.sourceId,SRC,id);for(const id of PROTECTED)assert.equal(getVisibleBatchAKnowledgePoint(id),null,id);});

test("Q057 public binding is single-KP diagram-only with no runtime modifier escalation",()=>{assert.equal(auditPublicUiCapabilityBinding().ok,true);const b=resolvePublicUiCapabilityBinding(req());assert.equal(b.blocked,false);assert.equal(b.questionType,"diagram");assert.equal(b.questionCount.max,240);assert.equal(b.sourceBackedAreaUnknownDimension,true);assert.equal(b.substitutionReconstructionRequired,true);assert.equal(b.prerequisiteFormulaKnowledgePointIds.length,3);assert.deepEqual(b.appliedRuntimeModifierIds,[]);assert.equal(b.parallelogramAreaReowned,false);assert.equal(b.triangleAreaReowned,false);assert.equal(b.trapezoidAreaReowned,false);assert.equal(b.compositePolygonTouched,false);assert.equal(requestsP05F57(req()),true);assert.equal(requestsP05F57({...req(),selectionMode:"sourceUnit"}),false);assert.equal(requestsP05F57({...req(),selectedKnowledgePointIds:[KP,PRIOR[0]]}),false);});

test("Q057 every PatternSpec yields 240 deterministic distinct valid variants",()=>{for(const id of SPECS){const a=generateG5AU09P05F57Questions({knowledgePointId:KP,patternSpecIds:[id],questionCount:240,generationSeed:id}),b=generateG5AU09P05F57Questions({knowledgePointId:KP,patternSpecIds:[id],questionCount:240,generationSeed:id});assert.equal(a.ok,true,`${id}:${a.errors.join("\n")}`);assert.deepEqual(a.questions,b.questions);assert.equal(new Set(a.questions.map(q=>q.questionSignature)).size,240);assert.ok(a.questions.every(q=>validateG5AU09P05F57Question(q).ok));const tampered=JSON.parse(JSON.stringify(a.questions[0]));tampered.answerValue+=1;tampered.answerText=`${tampered.answerValue} 公分`;assert.equal(validateG5AU09P05F57Question(tampered).ok,false);}});

test("Q057 recovered dimension always reconstructs the original area for all three prerequisite shapes",()=>{const r=generateG5AU09P05F57Questions({knowledgePointId:KP,questionCount:240,generationSeed:"q057-reconstruction"});assert.equal(r.ok,true,r.errors.join("\n"));const shapes=new Set();for(const q of r.questions){const d=q.geometryDiagram;shapes.add(d.shapeType);assert.equal(d.reconstructedAreaCm2,d.areaCm2);assert.equal(q.metadata.substitutionReconstructionPassed,true);assert.ok(Number.isInteger(q.answerValue)&&q.answerValue>0);if(d.shapeType==="PARALLELOGRAM")assert.equal(d.areaCm2,d.baseCm*d.heightCm);if(d.shapeType==="TRIANGLE")assert.equal(d.areaCm2,d.baseCm*d.heightCm/2);if(d.shapeType==="TRAPEZOID")assert.equal(d.areaCm2,(d.topBaseCm+d.bottomBaseCm)*d.heightCm/2);}assert.deepEqual([...shapes].sort(),["PARALLELOGRAM","TRAPEZOID","TRIANGLE"]);});

test("Q057 worksheet current bridge renderer answer key and print HTML stay product-safe",async()=>{const r=buildQ057(req(24));assert.equal(r.ok,true,r.errors.join("\n"));assert.equal(r.worksheetDocument.questionCount,24);assert.equal(r.worksheetDocument.answerKeyItems.length,24);const html=renderWorksheetDocumentToHtml(r.worksheetDocument,{stylesheetHref:"",title:r.worksheetDocument.title,debugDataAttributes:false});assert.equal(occ(html,'data-representation="area-unknown-dimension-diagram"'),48);assert.equal(html.includes("kp_g5a_u09_"),false);assert.equal(html.includes("ps_g5a_u09_"),false);const current=buildCurrent(req(12));assert.equal(current.ok,true,current.errors.join("\n"));assert.equal(current.p05f57Implemented,true);assert.equal(current.worksheetDocument.metadata.knowledgePointId,KP);globalThis.document={};try{const selector=await import(`../../site/modules/curriculum/registry/batch-a-selector-p04f33-extension.js?p05f57=${Date.now()}`),binding=await import(`../../site/modules/curriculum/public/public-ui-capability-binding-p04f33.js?p05f57=${Date.now()}`);for(const id of [...PRIOR,KP])assert.equal(selector.getVisibleBatchAKnowledgePoint(id)?.sourceId,SRC,id);for(const id of PROTECTED)assert.equal(selector.getVisibleBatchAKnowledgePoint(id),null,id);assert.equal(binding.resolvePublicUiCapabilityBinding(req()).sourceBackedAreaUnknownDimension,true);}finally{delete globalThis.document;}});

test("Q057 validation remains bounded and scope guard stays closed",()=>{assert.equal(impact.expectedDerivedGate,"SHARED_RUNTIME_BOUNDED");assert.equal(impact.changeImpact.affectedRoutes,"BOUNDED");assert.equal(impact.changeImpact.legalRouteSemanticsChanged,false);assert.equal(plan.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(plan.lanes.SHARED_RUNTIME_BOUNDED[0].kind,"NODE_TEST");assert.equal(plan.lanes.SHARED_RUNTIME_BOUNDED[1].runtime,"PLAYWRIGHT_CHROMIUM");assert.equal(implementation.validation.fullRepositoryRegression,"FORBIDDEN");assert.equal(implementation.validation.globalBrowserReplay,"FORBIDDEN");for(const v of Object.values(implementation.scopeGuard))assert.equal(v,false);});
