import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {buildBatchABrowserWorksheetDocument as buildQ033Worksheet} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f33-extension.js";
import {buildBatchABrowserWorksheetDocument as buildCurrentTopSlotWorksheet} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f32-extension.js";
import {generateG4BU02P05F33Questions,validateG4BU02P05F33Question} from "../../site/modules/curriculum/batch-a/g4b-u02-parallel-distance-quadrilateral-classification-runtime-p05f33.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";
import {auditG4BU02P05F33Projection,G4B_U02_P05F33_CLASSIFICATION_GROUP_ID,G4B_U02_P05F33_CLASSIFICATION_KP_ID,G4B_U02_P05F33_CLASSIFICATION_SPEC_IDS,G4B_U02_P05F33_DISTANCE_GROUP_ID,G4B_U02_P05F33_DISTANCE_KP_ID,G4B_U02_P05F33_DISTANCE_SPEC_IDS,G4B_U02_P05F33_KP_IDS,G4B_U02_P05F33_SOURCE_ID} from "../../site/modules/curriculum/registry/g4b-u02-parallel-distance-quadrilateral-classification-selector-projection-p05f33.js";
import {auditP05F33PublicSelectorComposition,getVisibleBatchAKnowledgePoint,listBatchAKnowledgePointAvailabilityBySource,resolveVisiblePatternSpecIdsForKnowledgePoint} from "../../site/modules/curriculum/registry/batch-a-selector-p05f33-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p05f33.js";
const preflight=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q033-g4b-u02-parallel-distance-quadrilateral-classification-source-authority-preflight.json",import.meta.url),"utf8"));
const implementation=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q033-g4b-u02-parallel-distance-quadrilateral-classification-implementation.json",import.meta.url),"utf8"));
const opts=(kpId,count=24)=>({sourceId:G4B_U02_P05F33_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[kpId],selectedPatternGroupIds:[kpId===G4B_U02_P05F33_DISTANCE_KP_ID?G4B_U02_P05F33_DISTANCE_GROUP_ID:G4B_U02_P05F33_CLASSIFICATION_GROUP_ID],patternSpecIds:[...(kpId===G4B_U02_P05F33_DISTANCE_KP_ID?G4B_U02_P05F33_DISTANCE_SPEC_IDS:G4B_U02_P05F33_CLASSIFICATION_SPEC_IDS)],questionMode:"diagram",requestedQuestionType:"diagram",questionCount:count,generationSeed:`p05f33-focused-${kpId}`,includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showQuestionNumbers:true,showAnswerKeyPage:true}});
const occurrences=(text,token)=>text.split(token).length-1;

test("Q033 exact preflight and implementation identities remain frozen",()=>{assert.equal(preflight.status,"PASS_SOURCE_AUTHORITY_PREFLIGHT");assert.equal(preflight.queueAuthority.queuePosition,33);assert.deepEqual(preflight.queueAuthority.knowledgePointIds,G4B_U02_P05F33_KP_IDS);assert.equal(preflight.previousSliceD0Evidence.status,"PASS_E6_D0_COMPLETE");assert.equal(implementation.taskId,"P05F_W5DirectProductVerticalSlice033Implementation");assert.equal(implementation.queueAuthority.sliceId,"p05e_q033_r3_g4b_u02_4b02_profile_geometry_property_c1");assert.equal(implementation.scopeGuard.quadrilateralInclusionTouched,false);});

test("Q033 materializes 2 mappings 2 groups and 8 bounded PatternSpecs",()=>{const audit=auditG4BU02P05F33Projection();assert.equal(audit.ok,true,audit.errors.join("\n"));assert.deepEqual(audit.counts,{knowledgePoints:2,patternGroups:2,patternSpecs:8,distanceSpecs:3,classificationSpecs:5});});

test("Q033 public selector promotes exactly two KPs and leaves inclusion fail-closed",()=>{const audit=auditP05F33PublicSelectorComposition();assert.equal(audit.ok,true,audit.errors.join("\n"));const source=listBatchAKnowledgePointAvailabilityBySource(G4B_U02_P05F33_SOURCE_ID);assert.equal(source.visibleCount,4);assert.equal(source.hiddenPendingCount,1);assert.equal(source.notSelectableCount,1);for(const id of ["kp_g4b_u02_parallel_lines_recognition","kp_g4b_u02_perpendicular_lines_recognition",...G4B_U02_P05F33_KP_IDS])assert.ok(getVisibleBatchAKnowledgePoint(id));assert.equal(getVisibleBatchAKnowledgePoint("kp_g4b_u02_quadrilateral_inclusion_relation"),null);assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(G4B_U02_P05F33_DISTANCE_KP_ID,"diagram"),G4B_U02_P05F33_DISTANCE_SPEC_IDS);assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(G4B_U02_P05F33_CLASSIFICATION_KP_ID,"diagram"),G4B_U02_P05F33_CLASSIFICATION_SPEC_IDS);});

test("Q033 public binding exposes only single-KP diagram paths",()=>{const audit=auditPublicUiCapabilityBinding();assert.equal(audit.ok,true,audit.errors.join("\n"));const d=resolvePublicUiCapabilityBinding(opts(G4B_U02_P05F33_DISTANCE_KP_ID)),c=resolvePublicUiCapabilityBinding(opts(G4B_U02_P05F33_CLASSIFICATION_KP_ID));assert.equal(d.parallelDistanceConstructionTarget,true);assert.equal(d.geometryConstructionRequired,true);assert.equal(c.quadrilateralClassificationTarget,true);assert.equal(c.geometryConstructionRequired,false);for(const b of [d,c]){assert.equal(b.questionType,"diagram");assert.equal(b.questionCount.max,240);assert.equal(b.quadrilateralInclusionAdmission,false);assert.equal(b.sameUnitMixedAdmission,false);assert.equal(b.crossUnitMixedAdmission,false);}});

test("Q033 both KPs generate deterministic validated worksheet questions",()=>{for(const kpId of G4B_U02_P05F33_KP_IDS){const a=generateG4BU02P05F33Questions({...opts(kpId),questionCount:24}),b=generateG4BU02P05F33Questions({...opts(kpId),questionCount:24});assert.equal(a.ok,true,a.errors.join("\n"));assert.deepEqual(a.questions,b.questions);assert.equal(a.questions.length,24);assert.equal(new Set(a.questions.map(q=>q.questionSignature)).size,24);assert.equal(a.questions.every(q=>validateG4BU02P05F33Question(q).ok),true);assert.equal(a.questions.every(q=>q.metadata.quadrilateralInclusionUsed===false&&q.metadata.q034OrLaterTouched===false),true);}});

test("Q033 proves 240 distinct variants for every PatternSpec",()=>{for(const kpId of G4B_U02_P05F33_KP_IDS){const ids=kpId===G4B_U02_P05F33_DISTANCE_KP_ID?G4B_U02_P05F33_DISTANCE_SPEC_IDS:G4B_U02_P05F33_CLASSIFICATION_SPEC_IDS;for(const patternSpecId of ids){const r=generateG4BU02P05F33Questions({knowledgePointId:kpId,questionCount:240,patternSpecIds:[patternSpecId],generationSeed:`capacity-${patternSpecId}`});assert.equal(r.ok,true,`${patternSpecId}:${r.errors.join("\n")}`);assert.equal(r.questions.length,240);assert.equal(new Set(r.questions.map(q=>q.questionSignature)).size,240);}}});

test("Q033 validators fail closed on distance/classification tampering",()=>{const d=generateG4BU02P05F33Questions({...opts(G4B_U02_P05F33_DISTANCE_KP_ID),questionCount:1}).questions[0],c=generateG4BU02P05F33Questions({...opts(G4B_U02_P05F33_CLASSIFICATION_KP_ID),questionCount:1}).questions[0];const td=JSON.parse(JSON.stringify(d));td.geometryDiagram.perpendicularDistance=false;assert.equal(validateG4BU02P05F33Question(td).ok,false);const tc=JSON.parse(JSON.stringify(c));tc.geometryDiagram.propertyProfile.rightAngleCount=99;assert.equal(validateG4BU02P05F33Question(tc).ok,false);const ta=JSON.parse(JSON.stringify(c));ta.answerText="正方形";if(c.answerText!=="正方形")assert.equal(validateG4BU02P05F33Question(ta).ok,false);});

test("Q033 worksheet and shared renderer project both diagram subtypes into questions and answers",()=>{for(const kpId of G4B_U02_P05F33_KP_IDS){const r=buildQ033Worksheet(opts(kpId,16));assert.equal(r.ok,true,r.errors.join("\n"));assert.equal(r.worksheetDocument.questionCount,16);assert.equal(r.worksheetDocument.answerKeyItems.length,16);const html=renderWorksheetDocumentToHtml(r.worksheetDocument,{stylesheetHref:"",title:r.worksheetDocument.title});const rep=kpId===G4B_U02_P05F33_DISTANCE_KP_ID?"parallel-distance-construction-diagram":"quadrilateral-classification-diagram";assert.equal(occurrences(html,`data-representation="${rep}"`),32);assert.equal(html.includes("quadrilateral-inclusion"),false);}});

test("Q033 current top-slot bridge reaches both new worksheets while preserving explicit Q033 implementation",()=>{for(const kpId of G4B_U02_P05F33_KP_IDS){const r=buildCurrentTopSlotWorksheet(opts(kpId,8));assert.equal(r.ok,true,r.errors.join("\n"));assert.equal(r.p05f33Implemented,true);assert.equal(r.worksheetDocument.metadata.knowledgePointId,kpId);}});

test("Q033 browser current selector and binding wrappers cut over without losing prior source leaves",async()=>{globalThis.document={};try{const selector=await import(`../../site/modules/curriculum/registry/batch-a-selector-p04f33-extension.js?p05f33=${Date.now()}`),binding=await import(`../../site/modules/curriculum/public/public-ui-capability-binding-p04f33.js?p05f33=${Date.now()}`);for(const id of G4B_U02_P05F33_KP_IDS){assert.equal(selector.getVisibleBatchAKnowledgePoint(id)?.sourceId,G4B_U02_P05F33_SOURCE_ID);assert.equal(binding.resolvePublicUiCapabilityBinding(opts(id)).blocked,false);}for(const id of ["kp_g4b_u02_parallel_lines_recognition","kp_g4b_u02_perpendicular_lines_recognition"])assert.ok(selector.getVisibleBatchAKnowledgePoint(id));assert.equal(selector.getVisibleBatchAKnowledgePoint("kp_g4b_u02_quadrilateral_inclusion_relation"),null);}finally{delete globalThis.document;}});
