import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {G5B_U07_P05F40_FORMAL_MAPPING,G5B_U07_P05F40_FUTURE_KP_IDS,G5B_U07_P05F40_INCLUDED_RELATIONS,G5B_U07_P05F40_KP_ID,G5B_U07_P05F40_PATTERN_SPECS,G5B_U07_P05F40_REQUIRED_CAPABILITY_IDS,G5B_U07_P05F40_SOURCE_ID,G5B_U07_P05F40_SPEC_IDS,auditG5BU07P05F40Projection} from "../../site/modules/curriculum/registry/g5b-u07-surface-area-from-net-selector-projection-p05f40.js";
import {BATCH_A_SELECTOR_AVAILABILITY as BEFORE} from "../../site/modules/curriculum/registry/batch-a-selector-p05f39-extension.js";
import {BATCH_A_SELECTOR_AVAILABILITY as AFTER,auditP05F40PublicSelectorComposition,getVisibleBatchAKnowledgePoint,listBatchAKnowledgePointAvailabilityBySource,resolveVisiblePatternSpecIdsForKnowledgePoint} from "../../site/modules/curriculum/registry/batch-a-selector-p05f40-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p05f40.js";
import {buildBatchABrowserPlan,generateBatchABrowserQuestions,requestsP05F40} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p05f40.js";
import {G5B_U07_P05F40_MAX_QUESTION_COUNT,generateG5BU07P05F40Questions,validateG5BU07P05F40Question} from "../../site/modules/curriculum/batch-a/g5b-u07-surface-area-from-net-runtime-p05f40.js";
import {buildBatchABrowserWorksheetDocument} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f40-extension.js";
import {getBatchASourceUnit,isBatchASourceId,listBatchASourceUnits} from "../../site/modules/curriculum/batch-a/source-units.js";
import {renderCubeCuboidNetDiagram,renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";
const request=(extra={})=>({sourceId:G5B_U07_P05F40_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G5B_U07_P05F40_KP_ID],questionType:"diagram",questionMode:"diagram",questionCount:24,generationSeed:"q040-test",includeAnswerKey:true,printLayout:{columns:2,rowsPerPage:4,showAnswerKeyPage:true},...extra});

test("Q040 first public G5B-U07 source is admitted to source catalog and selector while future siblings remain pending",()=>{const before=BEFORE.bySourceId[G5B_U07_P05F40_SOURCE_ID]??null,after=listBatchAKnowledgePointAvailabilityBySource(G5B_U07_P05F40_SOURCE_ID),source=getBatchASourceUnit(G5B_U07_P05F40_SOURCE_ID);assert.equal(before,null);assert.equal(source?.sourceId,G5B_U07_P05F40_SOURCE_ID);assert.equal(source?.unitCode,"5B-U07");assert.equal(source?.title,"表面積");assert.equal(isBatchASourceId(G5B_U07_P05F40_SOURCE_ID),true);assert.ok(listBatchASourceUnits({includeW5Slice040:true}).some(row=>row.sourceId===G5B_U07_P05F40_SOURCE_ID));assert.equal(after.sourceId,G5B_U07_P05F40_SOURCE_ID);assert.equal(after.visibleCount,1);assert.equal(after.hiddenPendingCount,4);assert.equal(after.notSelectableCount,4);assert.deepEqual(after.visibleKnowledgePointIds,[G5B_U07_P05F40_KP_ID]);assert.ok(!after.hiddenPendingKnowledgePointIds.includes(G5B_U07_P05F40_KP_ID));assert.ok(!after.notSelectableKnowledgePointIds.includes(G5B_U07_P05F40_KP_ID));for(const id of G5B_U07_P05F40_FUTURE_KP_IDS){assert.ok(after.hiddenPendingKnowledgePointIds.includes(id));assert.ok(after.notSelectableKnowledgePointIds.includes(id));assert.equal(getVisibleBatchAKnowledgePoint(id),null);}assert.equal(AFTER.sourceCount,BEFORE.sourceCount+1);assert.equal(AFTER.publicSourceCount,BEFORE.publicSourceCount+1);assert.equal(AFTER.visibleCount,BEFORE.visibleCount+1);});

test("Q040 projection exposes exact frozen KP, three net-accounting patterns, and W5 capabilities",()=>{assert.equal(auditG5BU07P05F40Projection().ok,true);const audit=auditP05F40PublicSelectorComposition();assert.equal(audit.ok,true,audit.errors.join("\n"));assert.ok(getVisibleBatchAKnowledgePoint(G5B_U07_P05F40_KP_ID));assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(G5B_U07_P05F40_KP_ID,"diagram"),G5B_U07_P05F40_SPEC_IDS);assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(G5B_U07_P05F40_KP_ID,"numeric"),[]);assert.deepEqual(G5B_U07_P05F40_REQUIRED_CAPABILITY_IDS,["cap_geometry_diagram_representation","cap_geometry_domain_validator","cap_geometry_formula_evaluation","cap_geometry_property_reasoning"]);});

test("Q040 FormalMapping preserves exact outer-face accounting without taking Q048/Q054/Q059 targets",()=>{assert.equal(G5B_U07_P05F40_FORMAL_MAPPING.sourceId,G5B_U07_P05F40_SOURCE_ID);assert.deepEqual(G5B_U07_P05F40_FORMAL_MAPPING.sourcePages,[1,2]);assert.deepEqual(G5B_U07_P05F40_FORMAL_MAPPING.includedRelations,G5B_U07_P05F40_INCLUDED_RELATIONS);assert.equal(G5B_U07_P05F40_PATTERN_SPECS.length,3);assert.equal(G5B_U07_P05F40_FORMAL_MAPPING.eachOuterFaceMustBeCountedExactlyOnce,true);assert.equal(G5B_U07_P05F40_FORMAL_MAPPING.foldingAdjacencyMustPreserveFaceArea,true);assert.equal(G5B_U07_P05F40_FORMAL_MAPPING.geometryConstructionModifierApplied,false);assert.ok(G5B_U07_P05F40_PATTERN_SPECS.every(row=>row.questionMode==="diagram"&&row.requiresSixOuterFaces&&row.eachOuterFaceCountedExactlyOnce&&row.preservesFaceAreaUnderFolding&&!row.directCubeSurfaceAreaFormulaTarget&&!row.directCuboidSurfaceAreaFormulaTarget&&!row.compositeHiddenFacesAllowed&&!row.unknownDimensionAllowed&&!row.generalNetConstructionAllowed&&!row.applicationAllowed&&!row.mixedKnowledgePointAllowed));});

test("Q040 runtime is deterministic and each PatternSpec has 240 distinct valid variants",()=>{assert.equal(G5B_U07_P05F40_MAX_QUESTION_COUNT,240);for(const patternSpecId of G5B_U07_P05F40_SPEC_IDS){const a=generateG5BU07P05F40Questions({knowledgePointId:G5B_U07_P05F40_KP_ID,patternSpecIds:[patternSpecId],questionCount:240,generationSeed:`q040-${patternSpecId}`}),b=generateG5BU07P05F40Questions({knowledgePointId:G5B_U07_P05F40_KP_ID,patternSpecIds:[patternSpecId],questionCount:240,generationSeed:`q040-${patternSpecId}`});assert.equal(a.ok,true,a.errors.join("\n"));assert.equal(a.questions.length,240);assert.equal(new Set(a.questions.map(q=>q.questionSignature)).size,240,patternSpecId);assert.deepEqual(a.questions.map(q=>q.questionSignature),b.questions.map(q=>q.questionSignature));assert.ok(a.questions.every(q=>validateG5BU07P05F40Question(q).ok));const first=a.questions[0];assert.equal(validateG5BU07P05F40Question({...first,answerText:"錯誤答案"}).ok,false);assert.equal(validateG5BU07P05F40Question({...first,metadata:{...first.metadata,compositeHiddenFacesUsed:true}}).ok,false);}});

test("Q040 binding and browser generation stay single-KP diagram only",()=>{const binding=resolvePublicUiCapabilityBinding(request());assert.equal(auditPublicUiCapabilityBinding().ok,true);assert.equal(binding.blocked,false);assert.equal(binding.questionType,"diagram");assert.equal(binding.questionCount.max,240);assert.equal(binding.sourceBackedSurfaceAreaFromNet,true);assert.equal(binding.eachOuterFaceCountedExactlyOnce,true);assert.equal(binding.faceAreaPreservedUnderFolding,true);assert.equal(binding.compositeHiddenFacesAdmission,false);assert.equal(binding.unknownDimensionAdmission,false);assert.equal(binding.generalNetConstructionAdmission,false);assert.equal(binding.geometryConstructionModifierApplied,false);assert.equal(requestsP05F40(request()),true);assert.equal(requestsP05F40(request({selectionMode:"sourceUnit"})),false);const plan=buildBatchABrowserPlan(request());assert.equal(plan.sourceId,G5B_U07_P05F40_SOURCE_ID);assert.equal(plan.genericFallback,false);const generated=generateBatchABrowserQuestions(request());assert.equal(generated.ok,true,generated.errors.join("\n"));assert.equal(generated.questions.length,24);});

test("Q040 worksheet reuses existing cube/cuboid net renderer and balances three PatternSpecs",()=>{const result=buildBatchABrowserWorksheetDocument(request());assert.equal(result.ok,true,result.errors.join("\n"));const doc=result.worksheetDocument;assert.equal(doc.questionCount,24);assert.equal(doc.answerKeyItems.length,24);assert.equal(doc.summary.diagramQuestionCount,24);assert.deepEqual(Object.values(doc.summary.taskCounts),[8,8,8]);assert.ok(doc.questions.every(q=>q.geometryDiagram.faces.length===6&&q.geometryDiagram.faces.every(f=>f.visible)));const html=renderWorksheetDocumentToHtml(doc,{stylesheetHref:null,title:doc.title,debugDataAttributes:false});assert.match(html,/由展開圖求表面積/);assert.match(html,/cube-cuboid-net/);assert.doesNotThrow(()=>renderCubeCuboidNetDiagram(doc.questions[0].geometryDiagram));});

test("Q040 manifests preserve bounded validation, first-source admission, and renderer ownership",()=>{const implementation=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q040-g5b-u07-surface-area-from-net-implementation.json",import.meta.url),"utf8")),impact=JSON.parse(readFileSync(new URL("../../data/project/change-impact/P05F_W5_Q040.impact.json",import.meta.url),"utf8")),plan=JSON.parse(readFileSync(new URL("../../data/project/validation-plans/P05F_W5_Q040.validation.json",import.meta.url),"utf8"));assert.equal(implementation.status,"IMPLEMENTATION_MATERIALIZED_AWAITING_FOCUSED_CI");assert.equal(implementation.goalDistance.reduced,"D2_TO_D1");assert.equal(implementation.publicAdmission.sourceAlreadyAdmittedBeforeQ040,false);assert.equal(implementation.publicAdmission.expectedGlobalPublicSourceDelta,1);assert.equal(implementation.publicAdmission.expectedGlobalVisibleKnowledgePointDelta,1);assert.equal(implementation.productChain.publicSourceAdapter,"site/modules/curriculum/batch-a/source-units.js");assert.equal(implementation.runtimeContract.sharedNetRendererReused,true);assert.equal(implementation.runtimeContract.sharedRendererModified,false);for(const value of Object.values(implementation.scopeGuard))assert.equal(value,false);assert.equal(impact.expectedDerivedGate,"SHARED_RUNTIME_BOUNDED");assert.equal(plan.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(plan.lanes.SHARED_RUNTIME_BOUNDED[1].runtime,"PLAYWRIGHT_CHROMIUM");});
