import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {auditG5AU10A1P05F29Projection,G5A_U10A1_P05F29_KP_ID,G5A_U10A1_P05F29_REMAINING_FUTURE_KP_IDS,G5A_U10A1_P05F29_SPEC_IDS} from "../../site/modules/curriculum/registry/g5a-u10a1-cube-cuboid-net-selector-projection-p05f29.js";
import {BATCH_A_SELECTOR_AVAILABILITY as BEFORE} from "../../site/modules/curriculum/registry/batch-a-selector-p05f28-extension.js";
import {BATCH_A_SELECTOR_AVAILABILITY as AFTER,auditP05F29PublicSelectorComposition,getVisibleBatchAKnowledgePoint} from "../../site/modules/curriculum/registry/batch-a-selector-p05f29-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p05f29.js";
import {generateG5AU10A1P05F29Questions,validateG5AU10A1P05F29CubeCuboidNetQuestion} from "../../site/modules/curriculum/batch-a/g5a-u10a1-cube-cuboid-net-runtime-p05f29.js";
import {buildBatchABrowserWorksheetDocument} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f29-extension.js";
import {renderCubeCuboidNetDiagram} from "../../site/modules/renderer/cube-cuboid-net-diagram.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";
const SOURCE="g5a_u10_5a10a1";

test("Q029 projection and selector promote only cube/cuboid net while preserving later spatial reasoning hidden",()=>{assert.equal(auditG5AU10A1P05F29Projection().ok,true);assert.equal(auditP05F29PublicSelectorComposition().ok,true);const before=BEFORE.bySourceId[SOURCE],after=AFTER.bySourceId[SOURCE];for(const id of before.visibleKnowledgePointIds)assert.ok(after.visibleKnowledgePointIds.includes(id));assert.ok(after.visibleKnowledgePointIds.includes(G5A_U10A1_P05F29_KP_ID));assert.ok(getVisibleBatchAKnowledgePoint(G5A_U10A1_P05F29_KP_ID));assert.ok(!after.hiddenPendingKnowledgePointIds.includes(G5A_U10A1_P05F29_KP_ID));for(const id of G5A_U10A1_P05F29_REMAINING_FUTURE_KP_IDS){assert.ok(after.hiddenPendingKnowledgePointIds.includes(id));assert.ok(after.notSelectableKnowledgePointIds.includes(id));assert.equal(getVisibleBatchAKnowledgePoint(id),null);}assert.equal(AFTER.sourceCount,BEFORE.sourceCount);assert.equal(AFTER.visibleCount,BEFORE.visibleCount+1);});

test("Q029 public capability binding is exact, diagram-only and bounded",()=>{assert.equal(auditPublicUiCapabilityBinding().ok,true);const binding=resolvePublicUiCapabilityBinding({sourceId:SOURCE,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G5A_U10A1_P05F29_KP_ID]});assert.equal(binding.blocked,false);assert.equal(binding.questionType,"diagram");assert.equal(binding.questionCount.max,240);assert.deepEqual(binding.patternSpecIds,G5A_U10A1_P05F29_SPEC_IDS);assert.equal(binding.applicationImplementationAllowed,false);assert.equal(binding.cubeCuboidNetAdmission,true);assert.equal(binding.viewpointRepresentationAdmission,false);assert.equal(binding.sharedRuntimeScope,"SHARED_RUNTIME_BOUNDED");});

for(const specId of G5A_U10A1_P05F29_SPEC_IDS)test(`Q029 deterministic generator/validator/renderer supports 240 distinct ${specId}`,()=>{const result=generateG5AU10A1P05F29Questions({knowledgePointId:G5A_U10A1_P05F29_KP_ID,patternSpecIds:[specId],questionCount:240,generationSeed:`q029-${specId}`});assert.equal(result.ok,true,JSON.stringify(result.errors));assert.equal(result.questions.length,240);assert.equal(new Set(result.questions.map(q=>q.questionSignature)).size,240);assert.ok(result.questions.every(q=>validateG5AU10A1P05F29CubeCuboidNetQuestion(q).ok));for(const q of result.questions.slice(0,9)){const html=renderCubeCuboidNetDiagram(q.geometryDiagram);assert.match(html,/data-representation="cube-cuboid-net"/);}const original=result.questions[0],tampered={...original,geometryDiagram:{...original.geometryDiagram,solidFamily:"PRISM"}};assert.equal(validateG5AU10A1P05F29CubeCuboidNetQuestion(tampered).ok,false);});

test("Q029 foldability specs include both valid and invalid bounded topologies",()=>{for(const specId of G5A_U10A1_P05F29_SPEC_IDS.slice(0,2)){const result=generateG5AU10A1P05F29Questions({knowledgePointId:G5A_U10A1_P05F29_KP_ID,patternSpecIds:[specId],questionCount:24,generationSeed:`q029-mix-${specId}`});assert.equal(result.ok,true,JSON.stringify(result.errors));assert.ok(result.questions.some(q=>q.answerValue===true));assert.ok(result.questions.some(q=>q.answerValue===false));}});

test("Q029 completion spec exposes exactly one foldable candidate and bounded A/B/C answer",()=>{const specId=G5A_U10A1_P05F29_SPEC_IDS[2],result=generateG5AU10A1P05F29Questions({knowledgePointId:G5A_U10A1_P05F29_KP_ID,patternSpecIds:[specId],questionCount:30,generationSeed:"q029-completion"});assert.equal(result.ok,true,JSON.stringify(result.errors));for(const q of result.questions){assert.ok(["A","B","C"].includes(q.answerText));assert.equal(q.geometryDiagram.faces.filter(f=>f.visible).length,5);assert.equal(q.geometryDiagram.completion.candidates.length,3);}});

test("Q029 worksheet and shared HTML renderer materialize questions, answer key and dedicated net diagrams",()=>{const result=buildBatchABrowserWorksheetDocument({sourceId:SOURCE,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G5A_U10A1_P05F29_KP_ID],questionCount:20,generationSeed:"q029-worksheet",includeAnswerKey:true,printLayout:{columns:2,rowsPerPage:4,showAnswerKeyPage:true}});assert.equal(result.ok,true,JSON.stringify(result.errors));assert.equal(result.worksheetDocument.questionCount,20);assert.equal(result.worksheetDocument.answerKeyItems.length,20);assert.equal(result.worksheetDocument.metadata.q028SolidNetSemanticsTouched,false);const html=renderWorksheetDocumentToHtml(result.worksheetDocument,{stylesheetHref:null});assert.equal((html.match(/data-representation="cube-cuboid-net"/g)??[]).length,40);assert.match(html,/正方體長方體展開圖|展開圖/);});

test("Q029 current integration pointers advance exactly to P05F29 and preserve P05F28 predecessor",()=>{const selector=readFileSync(new URL("../../site/modules/curriculum/registry/batch-a-selector-p04f33-extension.js",import.meta.url),"utf8"),binding=readFileSync(new URL("../../site/modules/curriculum/public/public-ui-capability-binding-p04f33.js",import.meta.url),"utf8"),entry=readFileSync(new URL("../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-r2e-entry.js",import.meta.url),"utf8"),q028Renderer=readFileSync(new URL("../../site/modules/renderer/solid-net-correspondence-diagram.js",import.meta.url),"utf8");assert.match(selector,/batch-a-selector-p05f29-extension/);assert.match(binding,/public-ui-capability-binding-p05f29/);assert.match(entry,/requestsP05F29/);assert.match(entry,/requestsP05F28/);assert.ok(entry.indexOf("requestsP05F29")<entry.indexOf("requestsP05F28"));assert.match(q028Renderer,/\["PRISM","PYRAMID","CYLINDER","CONE"\]/);assert.doesNotMatch(q028Renderer,/"CUBE"/);assert.doesNotMatch(q028Renderer,/"CUBOID"/);});
