import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {G5B_U03_P05F39_FORMAL_MAPPING,G5B_U03_P05F39_FUTURE_KP_ID,G5B_U03_P05F39_INCLUDED_RELATIONS,G5B_U03_P05F39_KP_ID,G5B_U03_P05F39_PATTERN_SPECS,G5B_U03_P05F39_REQUIRED_CAPABILITY_IDS,G5B_U03_P05F39_SOURCE_ID,G5B_U03_P05F39_SPEC_IDS,auditG5BU03P05F39Projection} from "../../site/modules/curriculum/registry/g5b-u03-capacity-volume-conversion-selector-projection-p05f39.js";
import {BATCH_A_SELECTOR_AVAILABILITY as P05F38_SELECTOR_AVAILABILITY} from "../../site/modules/curriculum/registry/batch-a-selector-p05f38-extension.js";
import {BATCH_A_SELECTOR_AVAILABILITY as P05F39_SELECTOR_AVAILABILITY,auditP05F39PublicSelectorComposition,getVisibleBatchAKnowledgePoint,listBatchAKnowledgePointAvailabilityBySource,resolveVisiblePatternSpecIdsForKnowledgePoint} from "../../site/modules/curriculum/registry/batch-a-selector-p05f39-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p05f39.js";
import {buildBatchABrowserPlan,generateBatchABrowserQuestions,requestsP05F39} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p05f39.js";
import {G5B_U03_P05F39_MAX_QUESTION_COUNT,generateG5BU03P05F39Questions,validateG5BU03P05F39Question} from "../../site/modules/curriculum/batch-a/g5b-u03-capacity-volume-conversion-runtime-p05f39.js";
import {buildBatchABrowserWorksheetDocument as buildP05F39Worksheet} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f39-extension.js";
import {getBatchASourceUnit} from "../../site/modules/curriculum/batch-a/source-units.js";
import {renderCubeCuboidElementsDiagram,renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";
const request=(extra={})=>({sourceId:G5B_U03_P05F39_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G5B_U03_P05F39_KP_ID],questionType:"diagram",questionMode:"diagram",questionCount:24,generationSeed:"q039-test",includeAnswerKey:true,printLayout:{columns:2,rowsPerPage:4,showAnswerKeyPage:true},...extra});

test("Q039 selector promotes only compound conversion and keeps displacement pending",()=>{const before=P05F38_SELECTOR_AVAILABILITY.bySourceId[G5B_U03_P05F39_SOURCE_ID],after=listBatchAKnowledgePointAvailabilityBySource(G5B_U03_P05F39_SOURCE_ID);assert.ok(before.hiddenPendingKnowledgePointIds.includes(G5B_U03_P05F39_KP_ID));assert.ok(before.notSelectableKnowledgePointIds.includes(G5B_U03_P05F39_KP_ID));assert.equal(after.visibleCount,before.visibleCount+1);assert.equal(after.hiddenPendingCount,before.hiddenPendingCount-1);assert.equal(after.notSelectableCount,before.notSelectableCount-1);assert.ok(after.visibleKnowledgePointIds.includes(G5B_U03_P05F39_KP_ID));assert.ok(after.hiddenPendingKnowledgePointIds.includes(G5B_U03_P05F39_FUTURE_KP_ID));assert.ok(after.notSelectableKnowledgePointIds.includes(G5B_U03_P05F39_FUTURE_KP_ID));assert.equal(getVisibleBatchAKnowledgePoint(G5B_U03_P05F39_FUTURE_KP_ID),null);assert.equal(P05F39_SELECTOR_AVAILABILITY.sourceCount,P05F38_SELECTOR_AVAILABILITY.sourceCount);assert.equal(P05F39_SELECTOR_AVAILABILITY.visibleCount,P05F38_SELECTOR_AVAILABILITY.visibleCount+1);});

test("Q039 projection exposes exact frozen KP, six bounded patterns, and W5 capabilities",()=>{const source=getBatchASourceUnit(G5B_U03_P05F39_SOURCE_ID);assert.equal(source?.unitCode,"5B-U03");assert.equal(auditG5BU03P05F39Projection().ok,true);const audit=auditP05F39PublicSelectorComposition();assert.equal(audit.ok,true,audit.errors.join("\n"));assert.ok(getVisibleBatchAKnowledgePoint(G5B_U03_P05F39_KP_ID));assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(G5B_U03_P05F39_KP_ID,"diagram"),G5B_U03_P05F39_SPEC_IDS);assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(G5B_U03_P05F39_KP_ID,"numeric"),[]);assert.deepEqual(G5B_U03_P05F39_REQUIRED_CAPABILITY_IDS,["cap_geometry_diagram_representation","cap_geometry_domain_validator","cap_geometry_formula_evaluation","cap_geometry_property_reasoning"]);});

test("Q039 FormalMapping preserves factor-1000, equivalence bridge, and predecessor ownership",()=>{assert.equal(G5B_U03_P05F39_FORMAL_MAPPING.sourceId,G5B_U03_P05F39_SOURCE_ID);assert.deepEqual(G5B_U03_P05F39_FORMAL_MAPPING.sourcePages,[1,2]);assert.deepEqual(G5B_U03_P05F39_FORMAL_MAPPING.includedRelations,G5B_U03_P05F39_INCLUDED_RELATIONS);assert.equal(G5B_U03_P05F39_PATTERN_SPECS.length,6);assert.equal(G5B_U03_P05F39_FORMAL_MAPPING.factor1000AndEquivalentUnitRelationsMustBothHold,true);assert.equal(G5B_U03_P05F39_FORMAL_MAPPING.simpleEquivalenceFactsMayBeUsedAsPrerequisitesButNotReowned,true);assert.ok(G5B_U03_P05F39_PATTERN_SPECS.every(row=>row.questionMode==="diagram"&&row.scaleFactor===1000&&row.preservesSameQuantity&&row.unitConversionModifierApplied===false&&row.applicationAllowed===false&&row.mixedKnowledgePointAllowed===false&&row.containerFillDisplacementAllowed===false));});

test("Q039 runtime produces deterministic 240-question allocation",()=>{assert.equal(G5B_U03_P05F39_MAX_QUESTION_COUNT,240);const a=generateG5BU03P05F39Questions({knowledgePointId:G5B_U03_P05F39_KP_ID,questionCount:240,generationSeed:"q039-capacity"}),b=generateG5BU03P05F39Questions({knowledgePointId:G5B_U03_P05F39_KP_ID,questionCount:240,generationSeed:"q039-capacity"});assert.equal(a.ok,true,a.errors.join("\n"));assert.equal(a.questions.length,240);assert.equal(new Set(a.questions.map(q=>q.questionSignature)).size,240);assert.deepEqual(a.questions.map(q=>q.questionSignature),b.questions.map(q=>q.questionSignature));assert.ok(a.questions.every(q=>validateG5BU03P05F39Question(q).ok));assert.ok(a.questions.some(q=>q.metadata.equivalenceBridgeRequired));assert.ok(a.questions.some(q=>!q.metadata.equivalenceBridgeRequired));});

test("Q039 each PatternSpec has 240 distinct variants and validator fails closed",()=>{for(const patternSpecId of G5B_U03_P05F39_SPEC_IDS){const out=generateG5BU03P05F39Questions({knowledgePointId:G5B_U03_P05F39_KP_ID,patternSpecIds:[patternSpecId],questionCount:240,generationSeed:`q039-${patternSpecId}`});assert.equal(out.ok,true,`${patternSpecId}:${out.errors.join(",")}`);assert.equal(new Set(out.questions.map(q=>q.questionSignature)).size,240,patternSpecId);const first=out.questions[0];assert.equal(validateG5BU03P05F39Question({...first,answerText:"錯誤答案"}).ok,false);assert.equal(validateG5BU03P05F39Question({...first,metadata:{...first.metadata,unitConversionModifierApplied:true}}).ok,false);assert.equal(validateG5BU03P05F39Question({...first,metadata:{...first.metadata,containerFillDisplacementUsed:true}}).ok,false);}});

test("Q039 binding and browser generator remain single-KP diagram only",()=>{const binding=resolvePublicUiCapabilityBinding(request());assert.equal(auditPublicUiCapabilityBinding().ok,true);assert.equal(binding.blocked,false);assert.equal(binding.questionType,"diagram");assert.equal(binding.questionCount.max,240);assert.equal(binding.sourceBackedCapacityVolumeConversion,true);assert.equal(binding.factor1000ScalingRequired,true);assert.equal(binding.equivalenceBridgeRequired,true);assert.equal(binding.simpleEquivalenceFactsPrerequisiteOnly,true);assert.equal(binding.unitConversionModifierApplied,false);assert.equal(binding.containerFillDisplacementAdmission,false);assert.equal(binding.applicationImplementationAllowed,false);assert.equal(requestsP05F39(request()),true);assert.equal(requestsP05F39(request({selectionMode:"sourceUnit"})),false);const plan=buildBatchABrowserPlan(request());assert.equal(plan.sourceId,G5B_U03_P05F39_SOURCE_ID);assert.equal(plan.genericFallback,false);const generated=generateBatchABrowserQuestions(request());assert.equal(generated.ok,true,generated.errors.join("\n"));assert.equal(generated.questions.length,24);});

test("Q039 worksheet and existing shared renderer materialize six conversion directions",()=>{const result=buildP05F39Worksheet(request());assert.equal(result.ok,true,result.errors.join("\n"));const doc=result.worksheetDocument;assert.equal(doc.questionCount,24);assert.equal(doc.answerKeyItems.length,24);assert.equal(doc.summary.diagramQuestionCount,24);for(const count of Object.values(doc.summary.directionCounts))assert.equal(count,4);const html=renderWorksheetDocumentToHtml(doc,{stylesheetHref:null,title:doc.title,debugDataAttributes:false});assert.match(html,/容積容量複合換算/);assert.match(html,/公升換算成毫升/);assert.match(html,/毫升換算成公升/);assert.match(html,/立方公寸換算成立方公分/);assert.match(html,/立方公分換算成立方公寸/);assert.match(html,/1 公升 = 1 立方公寸/);assert.doesNotThrow(()=>renderCubeCuboidElementsDiagram(doc.questions[0].geometryDiagram));});

test("Q039 manifests preserve bounded validation and ownership guards",()=>{const implementation=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q039-g5b-u03-capacity-volume-conversion-implementation.json",import.meta.url),"utf8")),impact=JSON.parse(readFileSync(new URL("../../data/project/change-impact/P05F_W5_Q039.impact.json",import.meta.url),"utf8")),plan=JSON.parse(readFileSync(new URL("../../data/project/validation-plans/P05F_W5_Q039.validation.json",import.meta.url),"utf8"));assert.equal(implementation.status,"IMPLEMENTATION_MATERIALIZED_AWAITING_FOCUSED_CI");assert.equal(implementation.goalDistance.reduced,"D2_TO_D1");assert.equal(implementation.publicAdmission.sourceAlreadyAdmittedBeforeQ039,true);assert.equal(implementation.publicAdmission.expectedGlobalPublicSourceDelta,0);assert.equal(implementation.publicAdmission.expectedGlobalVisibleKnowledgePointDelta,1);assert.equal(implementation.runtimeContract.sharedRendererModified,false);for(const value of Object.values(implementation.scopeGuard))assert.equal(value,false);assert.equal(impact.expectedDerivedGate,"SHARED_RUNTIME_BOUNDED");assert.equal(plan.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(plan.lanes.SHARED_RUNTIME_BOUNDED[1].runtime,"PLAYWRIGHT_CHROMIUM");});
