import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {G5B_U07_P05F59_FORMAL_MAPPING as MAP,G5B_U07_P05F59_KP_ID as KP,G5B_U07_P05F59_PATTERN_GROUP_ID as GROUP,G5B_U07_P05F59_PATTERN_SPECS as PATTERNS,G5B_U07_P05F59_PRIOR_VISIBLE_KP_IDS as PRIOR,G5B_U07_P05F59_REQUIRED_CAPABILITY_IDS as REQUIRED,G5B_U07_P05F59_SOURCE_ID as SRC,G5B_U07_P05F59_SPEC_IDS as SPECS,auditG5BU07P05F59Projection} from "../../site/modules/curriculum/registry/g5b-u07-surface-area-unknown-dimension-selector-projection-p05f59.js";
import {auditP05F59PublicSelectorComposition,getVisibleBatchAKnowledgePoint,listBatchAKnowledgePointAvailabilityBySource} from "../../site/modules/curriculum/registry/batch-a-selector-p05f59-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p05f59.js";
import {generateG5BU07P05F59Questions,validateG5BU07P05F59Question} from "../../site/modules/curriculum/batch-a/g5b-u07-surface-area-unknown-dimension-runtime-p05f59.js";
import {requestsP05F59} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p05f59.js";
import {buildBatchABrowserWorksheetDocument as buildQ059} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f59-extension.js";
import {buildBatchABrowserWorksheetDocument as buildCurrent} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f32-extension.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";
import {validateLayeredCubeVolumeDiagramModel} from "../../site/modules/renderer/cubic-centimeter-unit-diagram.js";
const read=p=>JSON.parse(readFileSync(new URL(`../../${p}`,import.meta.url),"utf8"));
const preflight=read("data/curriculum/full-product/p05f/q059-g5b-u07-surface-area-unknown-dimension-source-authority-preflight.json");
const implementation=read("data/curriculum/full-product/p05f/q059-g5b-u07-surface-area-unknown-dimension-implementation.json");
const impact=read("data/project/change-impact/P05F_W5_Q059.impact.json");
const plan=read("data/project/validation-plans/P05F_W5_Q059.validation.json");
const req=(count=24)=>({sourceId:SRC,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[KP],selectedPatternGroupIds:[GROUP],patternSpecIds:[...SPECS],questionMode:"diagram",requestedQuestionType:"diagram",questionCount:count,generationSeed:"p05f59-focused-surface-area-unknown",includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showQuestionNumbers:true,showAnswerKeyPage:true}});
const occ=(t,x)=>t.split(x).length-1;

test("Q059 exact frozen identity and exact R02 wording remain locked",()=>{assert.equal(preflight.status,"PASS_SOURCE_AUTHORITY_PREFLIGHT");assert.equal(preflight.queueAuthority.queuePosition,59);assert.equal(preflight.queueAuthority.sliceId,"p05e_q059_r6_g5b_u07_5b07_profile_geometry_formula_c1");assert.deepEqual(preflight.queueAuthority.knowledgePointIds,[KP]);assert.equal(preflight.previousSliceD0Evidence.status,"PASS_E6_D0_COMPLETE");assert.equal(preflight.previousSliceD0Evidence.productPrNumber,960);assert.deepEqual(implementation.sourceAuthority.sourcePages,[1,2]);assert.equal(MAP.r04MappingId,"r04map_g5b_u07_surface_area_unknown_dimension");assert.deepEqual(MAP.sourcePages,[1,2]);assert.equal(MAP.canonicalNameZh,"表面積反求尺寸");assert.equal(MAP.capabilityStatement,"學生能由表面積與部分尺寸反求未知邊長。");assert.equal(MAP.reasoningInvariant,"未知尺寸代回各面面積總和必須重建表面積。");});

test("Q059 materializes one mapping one group and four inverse-surface-area PatternSpecs",()=>{const a=auditG5BU07P05F59Projection();assert.equal(a.ok,true,a.errors.join("\n"));assert.deepEqual(a.counts,{knowledgePoints:1,patternGroups:1,patternSpecs:4,formalMappings:1});assert.deepEqual(REQUIRED,["cap_geometry_diagram_representation","cap_geometry_domain_validator","cap_geometry_formula_evaluation","cap_geometry_property_reasoning"]);assert.deepEqual(MAP.prerequisiteFormulaKnowledgePointIds,["kp_g5b_u07_cube_surface_area","kp_g5b_u07_cuboid_surface_area"]);assert.deepEqual(MAP.appliedRuntimeModifierIds,[]);assert.deepEqual(MAP.optionalRuntimeCapabilityIds,[]);assert.deepEqual([...new Set(PATTERNS.map(x=>x.targetDimension))].sort(),["EDGE","HEIGHT","LENGTH","WIDTH"]);});

test("Q059 promotes only surface-area unknown dimension and preserves prior same-source owners",()=>{const a=auditP05F59PublicSelectorComposition();assert.equal(a.ok,true,a.errors.join("\n"));const s=listBatchAKnowledgePointAvailabilityBySource(SRC);assert.equal(s.visibleCount,5);assert.equal(s.hiddenPendingCount,0);assert.equal(s.notSelectableCount,0);for(const id of [...PRIOR,KP])assert.equal(getVisibleBatchAKnowledgePoint(id)?.sourceId,SRC,id);});

test("Q059 public binding is single-KP diagram-only with no runtime modifier escalation",()=>{const a=auditPublicUiCapabilityBinding();assert.equal(a.ok,true,a.errors.join("\n"));const b=resolvePublicUiCapabilityBinding(req());assert.equal(b.blocked,false);assert.equal(b.questionType,"diagram");assert.equal(b.questionCount.max,240);assert.equal(b.sourceBackedSurfaceAreaUnknownDimension,true);assert.equal(b.substitutionReconstructionRequired,true);assert.deepEqual(b.prerequisiteFormulaKnowledgePointIds,["kp_g5b_u07_cube_surface_area","kp_g5b_u07_cuboid_surface_area"]);assert.deepEqual(b.appliedRuntimeModifierIds,[]);assert.equal(b.q040SurfaceAreaFromNetReowned,false);assert.equal(b.q048CubeSurfaceAreaReowned,false);assert.equal(b.q048CuboidSurfaceAreaReowned,false);assert.equal(b.q054CompositeSurfaceAreaReowned,false);assert.equal(requestsP05F59(req()),true);assert.equal(requestsP05F59({...req(),selectionMode:"sourceUnit"}),false);assert.equal(requestsP05F59({...req(),selectedKnowledgePointIds:[KP,PRIOR[0]]}),false);});

test("Q059 every PatternSpec yields 240 deterministic distinct valid variants",()=>{for(const id of SPECS){const o={knowledgePointId:KP,patternSpecIds:[id],questionCount:240,generationSeed:id},a=generateG5BU07P05F59Questions(o),b=generateG5BU07P05F59Questions(o);assert.equal(a.ok,true,`${id}:${a.errors.join("\n")}`);assert.deepEqual(a.questions,b.questions);assert.equal(new Set(a.questions.map(q=>q.questionSignature)).size,240,id);assert.equal(new Set(a.questions.map(q=>q.promptText)).size,240,id);for(const q of a.questions){assert.equal(validateG5BU07P05F59Question(q).ok,true,id);assert.equal(validateLayeredCubeVolumeDiagramModel(q.geometryDiagram).ok,true,id);}const tampered=JSON.parse(JSON.stringify(a.questions[0]));tampered.answerValue+=1;tampered.answerText=`${tampered.answerValue} 公分`;assert.equal(validateG5BU07P05F59Question(tampered).ok,false);}});

test("Q059 recovered edge length width or height always reconstructs original surface area",()=>{const r=generateG5BU07P05F59Questions({knowledgePointId:KP,questionCount:240,generationSeed:"q059-reconstruction"});assert.equal(r.ok,true,r.errors.join("\n"));const targets=new Set(),counts={EDGE:0,LENGTH:0,WIDTH:0,HEIGHT:0};for(const q of r.questions){const d=q.geometryDiagram;targets.add(d.targetDimension);counts[d.targetDimension]+=1;assert.equal(d.reconstructedSurfaceAreaSquareCentimeters,d.givenSurfaceAreaSquareCentimeters);assert.equal(q.metadata.substitutionReconstructionPassed,true);assert.equal(q.answerValue,d.hiddenDimensionValueCm);assert.ok(Number.isInteger(q.answerValue)&&q.answerValue>0);if(d.solidFamily==="CUBE")assert.equal(d.givenSurfaceAreaSquareCentimeters,6*d.edge*d.edge);else assert.equal(d.givenSurfaceAreaSquareCentimeters,2*(d.length*d.width+d.length*d.height+d.width*d.height));}assert.deepEqual([...targets].sort(),["EDGE","HEIGHT","LENGTH","WIDTH"]);assert.deepEqual(counts,{EDGE:60,LENGTH:60,WIDTH:60,HEIGHT:60});});

test("Q059 worksheet current bridge renderer answer key and browser wrappers stay product-safe",async()=>{const r=buildQ059(req(24));assert.equal(r.ok,true,r.errors.join("\n"));assert.equal(r.worksheetDocument.questionCount,24);assert.equal(r.worksheetDocument.answerKeyItems.length,24);const html=renderWorksheetDocumentToHtml(r.worksheetDocument,{stylesheetHref:"",title:r.worksheetDocument.title,debugDataAttributes:false});assert.equal(occ(html,'data-representation="layered-cube-volume-diagram"'),48);assert.equal(html.includes("kp_g5b_u07_"),false);assert.equal(html.includes("ps_g5b_u07_"),false);const current=buildCurrent(req(12));assert.equal(current.ok,true,current.errors.join("\n"));assert.equal(current.p05f59Implemented,true);assert.equal(current.worksheetDocument.metadata.knowledgePointId,KP);globalThis.document={};try{const selector=await import(`../../site/modules/curriculum/registry/batch-a-selector-p04f33-extension.js?p05f59=${Date.now()}`),binding=await import(`../../site/modules/curriculum/public/public-ui-capability-binding-p04f33.js?p05f59=${Date.now()}`);for(const id of [...PRIOR,KP])assert.equal(selector.getVisibleBatchAKnowledgePoint(id)?.sourceId,SRC,id);assert.equal(binding.resolvePublicUiCapabilityBinding(req()).sourceBackedSurfaceAreaUnknownDimension,true);}finally{delete globalThis.document;}});

test("Q059 validation remains bounded and scope guard stays closed",()=>{assert.equal(impact.expectedDerivedGate,"SHARED_RUNTIME_BOUNDED");assert.equal(impact.changeImpact.affectedRoutes,"BOUNDED");assert.equal(impact.changeImpact.legalRouteSemanticsChanged,false);assert.equal(plan.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(plan.lanes.SHARED_RUNTIME_BOUNDED[0].kind,"NODE_TEST");assert.equal(plan.lanes.SHARED_RUNTIME_BOUNDED[1].runtime,"PLAYWRIGHT_CHROMIUM");assert.equal(implementation.validation.fullRepositoryRegression,"FORBIDDEN");assert.equal(implementation.validation.globalBrowserReplay,"FORBIDDEN");for(const v of Object.values(implementation.scopeGuard))assert.equal(v,false);});
