import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {buildBatchABrowserWorksheetDocument as buildQ036Worksheet} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f36-extension.js";
import {buildBatchABrowserWorksheetDocument as buildCurrentTopSlotWorksheet} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f32-extension.js";
import {generateG5AU07P05F36Questions,validateG5AU07P05F36Question} from "../../site/modules/curriculum/batch-a/g5a-u07-symmetric-point-distance-runtime-p05f36.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";
import {auditG5AU07P05F36Projection,G5A_U07_P05F36_FORMAL_MAPPING,G5A_U07_P05F36_KP_ID,G5A_U07_P05F36_PATTERN_GROUP_ID,G5A_U07_P05F36_SOURCE_ID,G5A_U07_P05F36_SPEC_IDS} from "../../site/modules/curriculum/registry/g5a-u07-symmetric-point-distance-selector-projection-p05f36.js";
import {auditP05F36PublicSelectorComposition,getVisibleBatchAKnowledgePoint,listBatchAKnowledgePointAvailabilityBySource,resolveVisiblePatternSpecIdsForKnowledgePoint} from "../../site/modules/curriculum/registry/batch-a-selector-p05f36-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p05f36.js";
const preflight=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q036-g5a-u07-symmetric-point-distance-source-authority-preflight.json",import.meta.url),"utf8"));
const implementation=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q036-g5a-u07-symmetric-point-distance-implementation.json",import.meta.url),"utf8"));
const PROTECTED=["kp_g5a_u07_line_symmetry_recognition","kp_g5a_u07_symmetry_axis_count"];
const FUTURE=["kp_g5a_u07_complete_symmetric_figure","kp_g5a_u07_coordinate_reflection"];
const opts=(count=24)=>({sourceId:G5A_U07_P05F36_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G5A_U07_P05F36_KP_ID],selectedPatternGroupIds:[G5A_U07_P05F36_PATTERN_GROUP_ID],patternSpecIds:[...G5A_U07_P05F36_SPEC_IDS],questionMode:"diagram",requestedQuestionType:"diagram",questionCount:count,generationSeed:"p05f36-focused-symmetric-point",includeAnswerKey:true,printLayout:{paperSize:"A4",columns:2,rowsPerPage:4,showQuestionNumbers:true,showAnswerKeyPage:true}});
const occurrences=(text,token)=>text.split(token).length-1;

test("Q036 exact preflight and implementation identities remain frozen",()=>{assert.equal(preflight.status,"PASS_SOURCE_AUTHORITY_PREFLIGHT");assert.equal(preflight.queueAuthority.queuePosition,36);assert.deepEqual(preflight.queueAuthority.knowledgePointIds,[G5A_U07_P05F36_KP_ID]);assert.equal(preflight.previousSliceD0Evidence.status,"PASS_E6_D0_COMPLETE");assert.equal(implementation.taskId,"P05F_W5DirectProductVerticalSlice036Implementation");assert.equal(implementation.queueAuthority.sliceId,"p05e_q036_r3_g5a_u07_5a07_profile_geometry_property_c1");assert.equal(implementation.scopeGuard.q006SemanticsModified,false);assert.equal(implementation.scopeGuard.q016SemanticsModified,false);assert.equal(implementation.scopeGuard.q037OrLaterTouched,false);});

test("Q036 materializes one mapping one group and three bounded PatternSpecs",()=>{const audit=auditG5AU07P05F36Projection();assert.equal(audit.ok,true,audit.errors.join("\n"));assert.deepEqual(audit.counts,{knowledgePoints:1,patternGroups:1,patternSpecs:3,diagram:3,application:0});assert.equal(G5A_U07_P05F36_FORMAL_MAPPING.mappingId,"fm_g5a_u07_symmetric_point_distance_p05f36");assert.deepEqual(G5A_U07_P05F36_FORMAL_MAPPING.includedRelations,preflight.q036ScopeLock.includedRelations);assert.deepEqual(G5A_U07_P05F36_FORMAL_MAPPING.optionalCapabilityIds,["cap_geometry_construction"]);});

test("Q036 selector promotes only symmetric-point distance and preserves same-source ownership",()=>{const audit=auditP05F36PublicSelectorComposition();assert.equal(audit.ok,true,audit.errors.join("\n"));const source=listBatchAKnowledgePointAvailabilityBySource(G5A_U07_P05F36_SOURCE_ID);assert.equal(source.visibleCount,3);assert.equal(source.hiddenPendingCount,2);assert.equal(source.notSelectableCount,2);for(const id of [...PROTECTED,G5A_U07_P05F36_KP_ID])assert.ok(getVisibleBatchAKnowledgePoint(id),id);for(const id of FUTURE)assert.equal(getVisibleBatchAKnowledgePoint(id),null,id);assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(G5A_U07_P05F36_KP_ID,"diagram"),G5A_U07_P05F36_SPEC_IDS);});

test("Q036 public binding exposes direct single-KP diagram path only",()=>{const audit=auditPublicUiCapabilityBinding();assert.equal(audit.ok,true,audit.errors.join("\n"));const b=resolvePublicUiCapabilityBinding(opts());assert.equal(b.blocked,false);assert.equal(b.questionType,"diagram");assert.equal(b.questionCount.max,240);assert.equal(b.symmetricPointDistanceAdmission,true);assert.equal(b.equalPerpendicularOffsetRequired,true);assert.deepEqual(b.optionalCapabilityIds,["cap_geometry_construction"]);assert.equal(b.applicationImplementationAllowed,false);assert.equal(b.fullSymmetricFigureConstructionAdmission,false);assert.equal(b.coordinateReflectionAdmission,false);assert.equal(b.genericMeasurementOrUnitConversionAdmission,false);assert.equal(b.sameUnitMixedAdmission,false);assert.equal(b.crossUnitMixedAdmission,false);});

test("Q036 generates deterministic equal-distance perpendicular corresponding-point questions",()=>{const a=generateG5AU07P05F36Questions(opts(24)),b=generateG5AU07P05F36Questions(opts(24));assert.equal(a.ok,true,a.errors.join("\n"));assert.deepEqual(a.questions,b.questions);assert.equal(a.questions.length,24);assert.equal(new Set(a.questions.map(q=>q.questionSignature)).size,24);for(const q of a.questions){assert.equal(validateG5AU07P05F36Question(q).ok,true);const d=q.geometryDiagram;assert.equal(d.equalAxisDistance,true);assert.equal(d.connectorPerpendicular,true);if(d.axis.orientation==="VERTICAL"){assert.equal(d.sourcePoint.y,d.correspondingPoint.y);assert.equal(120-d.sourcePoint.x,d.correspondingPoint.x-120);}else{assert.equal(d.sourcePoint.x,d.correspondingPoint.x);assert.equal(70-d.sourcePoint.y,d.correspondingPoint.y-70);}assert.equal(q.metadata.q006SemanticsReowned,false);assert.equal(q.metadata.q016SemanticsReowned,false);assert.equal(q.metadata.completeSymmetricFigureUsed,false);assert.equal(q.metadata.coordinateReflectionUsed,false);assert.equal(q.metadata.fullSymmetricFigureConstructionUsed,false);assert.equal(q.metadata.genericMeasurementOrUnitConversionUsed,false);assert.equal(q.metadata.applicationContextUsed,false);assert.equal(q.metadata.q037OrLaterTouched,false);}});

test("Q036 proves 240 distinct variants for every PatternSpec",()=>{for(const patternSpecId of G5A_U07_P05F36_SPEC_IDS){const r=generateG5AU07P05F36Questions({knowledgePointId:G5A_U07_P05F36_KP_ID,questionCount:240,patternSpecIds:[patternSpecId],generationSeed:`capacity-${patternSpecId}`});assert.equal(r.ok,true,`${patternSpecId}:${r.errors.join("\n")}`);assert.equal(r.questions.length,240);assert.equal(new Set(r.questions.map(q=>q.questionSignature)).size,240);}});

test("Q036 validator fails closed on diagram answer candidate and provenance tampering",()=>{const q=generateG5AU07P05F36Questions({...opts(1),patternSpecIds:[G5A_U07_P05F36_SPEC_IDS[0]]}).questions[0];for(const mutate of [x=>x.geometryDiagram.sourcePoint.x+=1,x=>x.answerText="Z",x=>x.geometryDiagram.candidatePoints.pop(),x=>x.metadata.q016SemanticsReowned=true]){const t=JSON.parse(JSON.stringify(q));mutate(t);assert.equal(validateG5AU07P05F36Question(t).ok,false);}});

test("Q036 worksheet renders symmetric-point diagrams in questions and answers",()=>{const r=buildQ036Worksheet(opts(18));assert.equal(r.ok,true,r.errors.join("\n"));assert.equal(r.worksheetDocument.questionCount,18);assert.equal(r.worksheetDocument.answerKeyItems.length,18);const html=renderWorksheetDocumentToHtml(r.worksheetDocument,{stylesheetHref:"",title:r.worksheetDocument.title,debugDataAttributes:false});assert.equal(occurrences(html,'data-representation="symmetric-point-distance-diagram"'),36);assert.equal(html.includes("kp_g5a_u07_"),false);assert.equal(html.includes("ps_g5a_u07_"),false);});

test("Q036 current top-slot bridge reaches symmetric-point worksheet",()=>{const r=buildCurrentTopSlotWorksheet(opts(9));assert.equal(r.ok,true,r.errors.join("\n"));assert.equal(r.p05f36Implemented,true);assert.equal(r.worksheetDocument.metadata.knowledgePointId,G5A_U07_P05F36_KP_ID);});

test("Q036 browser current selector and binding wrappers expose target while preserving Q006 and Q016",async()=>{globalThis.document={};try{const selector=await import(`../../site/modules/curriculum/registry/batch-a-selector-p04f33-extension.js?p05f36=${Date.now()}`),binding=await import(`../../site/modules/curriculum/public/public-ui-capability-binding-p04f33.js?p05f36=${Date.now()}`);assert.equal(selector.getVisibleBatchAKnowledgePoint(G5A_U07_P05F36_KP_ID)?.sourceId,G5A_U07_P05F36_SOURCE_ID);assert.equal(binding.resolvePublicUiCapabilityBinding(opts()).blocked,false);for(const id of PROTECTED)assert.ok(selector.getVisibleBatchAKnowledgePoint(id),id);for(const id of FUTURE)assert.equal(selector.getVisibleBatchAKnowledgePoint(id),null,id);}finally{delete globalThis.document;}});
