import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {materializeP05EW5DirectProductVerticalSliceQueue} from "../../src/curriculum/full-product/p05e-w5-direct-product-vertical-slice-queue.mjs";
import {materializeR04SharedRuntimeCapabilityMatrix} from "../../src/curriculum/global/r04-shared-runtime-capability-matrix.mjs";
import {materializeR05DeliveryWaveRebase} from "../../src/curriculum/global/r05-delivery-wave-rebase.mjs";
const read=p=>JSON.parse(readFileSync(new URL(`../../${p}`,import.meta.url),"utf8"));
const preflight=read("data/curriculum/full-product/p05f/q060-g6b-u03-triangular-composite-prism-source-authority-preflight.json");
const q049=read("data/curriculum/full-product/p05f/q049-g6b-u03-prism-surface-area-source-authority-preflight.json");
const q055=read("data/curriculum/full-product/p05f/q055-g6b-u03-prism-base-area-height-volume-source-authority-preflight.json");
const r02=read("data/curriculum/global/candidates/r02/chunks/reviewed-source-candidates-08.json");
const KPS=["kp_g6b_u03_composite_prism_volume_surface","kp_g6b_u03_triangular_prism_volume"];
const CAPS=["cap_geometry_domain_validator","cap_geometry_property_reasoning","cap_solid_geometry_representation","cap_spatial_solid_reasoning"];
const sorted=v=>[...v].sort();

test("Q060 binds exact frozen row and Q059 E6 predecessor",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),row=q.queueEntries.find(x=>x.queuePosition===60);assert.equal(q.queueFrozen,true);assert.equal(q.queueRegistryParity,true);assert.equal(q.derivedRegistrySnapshot.queueDigest,"a4dae65a1a907ba963a135fce84ba292b8486a12513ae8f1fa54fbf07a6598ae");assert.ok(row);assert.equal(row.sliceId,"p05e_q060_r6_g6b_u03_6b03_profile_spatial_solid_c1");assert.equal(row.implementationTaskId,"P05F_W5DirectProductVerticalSlice060Implementation");assert.equal(row.previousSliceId,"p05e_q059_r6_g5b_u07_5b07_profile_geometry_formula_c1");assert.equal(row.previousSliceMustBeD0Complete,true);assert.equal(row.assignedDeliveryWaveId,"R05-W5");assert.equal(row.primarySourceNodeId,"g6b_u03_6b03");assert.deepEqual(row.supportingSourceNodeIds,["g6b_u03_6b03"]);assert.equal(row.intraWavePrerequisiteRank,6);assert.equal(row.primaryRuntimeProfileId,"profile_spatial_solid");assert.equal(row.chunkIndex,1);assert.equal(row.knowledgePointCount,2);assert.deepEqual(row.knowledgePointIds,KPS);assert.deepEqual(sorted(row.requiredW5CapabilityIds),sorted(CAPS));assert.equal(row.targetEvidenceLevel,"E6_D0_COMPLETE");const p=preflight.previousSliceD0Evidence;assert.equal(p.preflightPrNumber,961);assert.equal(p.productPrNumber,962);assert.equal(p.productHeadSha,"2ef09500b889c168f64239b8622f282f6745e614");assert.equal(p.productMergeSha,"d9d6cce8566e2bc73fc903eb81dc2ab378b81d80");assert.equal(p.prGateRunId,"35101475704");assert.equal(p.pagesDeploymentRunId,"35101658365");assert.equal(p.exactPagesRunId,"35101658460");assert.equal(p.evidenceArtifactId,"10448556455");assert.equal(p.evidenceArtifactDigest,"sha256:9666fe1fc0296bce3f905dcb5cbf491e2e09334789f58ad59625a7985dafe7df");assert.equal(p.status,"PASS_E6_D0_COMPLETE");assert.equal(p.exactPagesEvidenceBoundToProductMergeSha,true);});

test("Q060 reuses exact verified G6B-U03 source identity from Q049 and Q055",()=>{const s=preflight.sourceAuthority;assert.equal(s.sourceNodeId,"g6b_u03_6b03");assert.equal(s.sourceTitle,"柱體體積與表面積");assert.equal(s.sourcePdfTitle,"meow911_6b03_source.pdf");assert.equal(s.sourcePdfDriveFileId,"10LlUyzn4WOkxHAY3S9SsZeGT0i_ixV9u");assert.equal(s.sourceMetadataDriveFileId,"166jSxr7CwhLSrHc--uSlPwCUzCk0vyr7");assert.equal(s.verificationNotesDriveFileId,"1MWLwKWehiRhekfnmf2zX1-kck2t0Azlg");assert.equal(s.sourceUrl,"https://meow911.com/6b03/");assert.deepEqual(s.reviewedPages,[1,2]);assert.equal(q049.sourceAuthority.sourcePdfDriveFileId,s.sourcePdfDriveFileId);assert.equal(q055.sourceAuthority.sourcePdfDriveFileId,s.sourcePdfDriveFileId);assert.equal(s.ocrUsedAsAuthority,false);assert.equal(s.r02AuthorityModified,false);assert.equal(s.sourceRefAmbiguity,false);assert.equal(s.manualSourceChoiceRequired,false);});

test("Q060 locks exact R02 triangular and composite prism candidates",()=>{const source=r02.sourceRecords.find(x=>x.sourceNodeId==="g6b_u03_6b03");assert.ok(source);const expected={kp_g6b_u03_composite_prism_volume_surface:{canonicalNameZh:"複合柱體體積與表面積",capabilityStatement:"學生能分割柱體求體積並扣除接合面求外表面積。",reasoningInvariant:"體積可加總，內部接合面不得計入外表面。"},kp_g6b_u03_triangular_prism_volume:{canonicalNameZh:"三角柱體積",capabilityStatement:"學生能先求三角形底面積再乘柱高。",reasoningInvariant:"底面積與柱高須互相垂直且單位一致。"}};for(const kp of KPS){const c=source.candidates.find(x=>x.knowledgePointId===kp);assert.ok(c,kp);assert.equal(c.canonicalNameZh,expected[kp].canonicalNameZh);assert.equal(c.capabilityStatement,expected[kp].capabilityStatement);assert.equal(c.reasoningInvariant,expected[kp].reasoningInvariant);assert.equal(c.category,"geometry");assert.deepEqual(c.evidencePages,[1,2]);assert.equal(c.applicationSuitability,"APPLICATION_COMPATIBLE");assert.deepEqual(preflight.r02ReviewedCandidateAuthority.knowledgePoints.find(x=>x.knowledgePointId===kp),c);}assert.deepEqual(preflight.r02ReviewedCandidateAuthority.sameSourceCandidateIds,source.candidates.map(x=>x.knowledgePointId));});

test("Q060 binds current R04 spatial-solid mappings and exact R05 closure",()=>{const r04=materializeR04SharedRuntimeCapabilityMatrix(),r05=materializeR05DeliveryWaveRebase();for(const kp of KPS){const m=r04.getMapping(kp);assert.ok(m,kp);assert.equal(m.mappingId,`r04map_${kp.replace(/^kp_/,"")}`);assert.equal(m.primaryRuntimeProfileId,"profile_spatial_solid");assert.equal(m.classificationRuleId,"rule_spatial_solid");assert.deepEqual(m.appliedModifierIds,[]);assert.deepEqual(m.optionalRuntimeCapabilityIds,["cap_geometry_construction"]);assert.deepEqual(m.forbiddenRuntimeCapabilityIds,[]);for(const cap of ["cap_pattern_spec_resolution","cap_deterministic_answer_model","cap_worksheet_document_assembly","cap_answer_key_projection","cap_html_print_renderer","cap_spatial_solid_reasoning","cap_geometry_domain_validator","cap_solid_geometry_representation"])assert.ok(m.requiredRuntimeCapabilityIds.includes(cap),`${kp}:${cap}`);const a=r05.getAssignment(kp);assert.ok(a,kp);assert.equal(a.deliveryWaveId,"R05-W5");assert.equal(a.intraWavePrerequisiteRank,6);assert.equal(a.primaryRuntimeProfileId,"profile_spatial_solid");assert.deepEqual(sorted(a.contractOnlyRequiredCapabilityIds),sorted(CAPS));}assert.deepEqual(sorted(preflight.runtimeCapabilityAuthority.exactFrozenQueueRequiredW5CapabilityIds),sorted(CAPS));assert.equal(preflight.runtimeCapabilityAuthority.mappingPolicyModifierMatchCountPerTarget,0);});

test("Q060 protects Q049 Q055 ownership and the non-W5 cylinder sibling",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue();assert.deepEqual(preflight.q060ScopeLock.includedKnowledgePointIds,KPS);for(const[kp,pos]of Object.entries({kp_g6b_u03_prism_surface_area:49,kp_g6b_u03_prism_base_area_height_volume:55})){const row=q.queueEntries.find(x=>x.knowledgePointIds.includes(kp));assert.equal(row?.queuePosition,pos,kp);assert.equal(preflight.q060ScopeLock.protectedExistingSameSourceKnowledgePointOwnership[kp],`Q${String(pos).padStart(3,"0")}`);}assert.deepEqual(preflight.q060ScopeLock.protectedNonW5SiblingCandidateIds,["kp_g6b_u03_cylinder_volume"]);assert.equal(q.queueEntries.some(x=>x.knowledgePointIds.includes("kp_g6b_u03_cylinder_volume")),false);assert.equal(preflight.q060ScopeLock.priorPrismSurfaceAreaAndVolumeFactsMayBeUsedAsPrerequisitesNotReowned,true);});

test("Q060 preflight excludes implementation mixed modes authority mutation and Q061+",()=>{for(const r of ["REOWN_PRISM_SURFACE_AREA","REOWN_PRISM_BASE_AREA_HEIGHT_VOLUME","CYLINDER_VOLUME_OR_SURFACE_AREA_AS_TARGET_KP","APPLICATION_CONTEXT_IMPLEMENTATION","SAME_UNIT_MIXED_MODE","CROSS_UNIT_MIXED_MODE","Q061_OR_LATER_SEMANTICS"])assert.ok(preflight.q060ScopeLock.excludedRelations.includes(r),r);for(const k of ["applicationImplementationAllowedByThisPreflight","implementationAllowedByThisPreflight","publicProductAdmissionAllowedByThisPreflight","sameSourceSiblingSemanticsTouched","sameUnitMixedTouched","crossUnitMixedTouched","frozenQueueAuthorityTouched","r02AuthorityTouched","r04AuthorityTouched","r05AuthorityTouched","q061OrLaterTouched"])assert.equal(preflight.q060ScopeLock[k],false,k);const b=preflight.preflightValidationBoundary;assert.equal(b.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(b.derivedLane,"SHARED_RUNTIME_BOUNDED");assert.deepEqual(b.allowedLaneGateIds,["GLOBAL_CONTRACTS","TARGETED_ROUTE_REPLAY"]);assert.equal(b.fullRepositoryRegressionAllowed,false);assert.equal(b.globalBrowserReplayAllowed,false);const d=preflight.preflightDecision;assert.equal(d.previousSliceD0Satisfied,true);assert.equal(d.r02AuthorityBoundForAllTargetKnowledgePoints,true);assert.equal(d.runtimeCapabilityContractLockedForAllTargetKnowledgePoints,true);assert.equal(d.manualSourceChoiceRequired,false);assert.equal(d.sourceRefAmbiguity,false);assert.equal(d.nextTaskRequiresNewOperatorApproval,true);assert.equal(d.nextTask,"P05F_W5DirectProductVerticalSlice060Implementation");});
