import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {G4A_U05_P05F24_FORMAL_MAPPING,G4A_U05_P05F24_KP_ID,G4A_U05_P05F24_PATTERN_SPECS,G4A_U05_P05F24_REMAINING_FUTURE_KP_IDS,G4A_U05_P05F24_SOURCE_ID,G4A_U05_P05F24_SPEC_IDS,auditG4AU05P05F24Projection} from "../../site/modules/curriculum/registry/g4a-u05-triangle-side-classification-selector-projection-p05f24.js";
import {auditP05F24PublicSelectorComposition,getVisibleBatchAKnowledgePoint,listBatchAKnowledgePointAvailabilityBySource,resolveVisiblePatternSpecIdsForKnowledgePoint} from "../../site/modules/curriculum/registry/batch-a-selector-p05f24-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p05f24.js";
import {generateG4AU05P05F24Questions,validateG4AU05P05F24Question} from "../../site/modules/curriculum/batch-a/g4a-u05-triangle-side-classification-runtime-p05f24.js";
import {buildBatchABrowserPlan,generateBatchABrowserQuestions,requestsP05F24} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p05f24.js";
import {buildBatchABrowserWorksheetDocument} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f24-extension.js";
import {buildBatchABrowserWorksheetDocument as buildStableWorksheet} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-r2e-entry.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";
const implementation=JSON.parse(readFileSync(new URL("../../data/curriculum/full-product/p05f/q024-g4a-u05-triangle-side-classification-implementation.json",import.meta.url),"utf8"));
const classify=lengths=>{const n=new Set([lengths.AB,lengths.BC,lengths.CA]).size;return n===1?"等邊三角形":n===2?"等腰三角形":"不等邊三角形";};

test("Q024 exact frozen authority and FormalMapping remain source-bound",()=>{assert.equal(implementation.queueAuthority.queuePosition,24);assert.equal(implementation.queueAuthority.sliceId,"p05e_q024_r2_g4a_u05_4a05_profile_geometry_property_c1");assert.equal(implementation.queueAuthority.sourceId,G4A_U05_P05F24_SOURCE_ID);assert.deepEqual(implementation.queueAuthority.knowledgePointIds,[G4A_U05_P05F24_KP_ID]);assert.equal(implementation.queueAuthority.runtimeProfileId,"profile_geometry_property");assert.equal(implementation.queueAuthority.targetEvidenceLevel,"E6_D0_COMPLETE");assert.equal(implementation.queueAuthority.requiredProductNodes.length,13);assert.equal(G4A_U05_P05F24_FORMAL_MAPPING.knowledgePointId,G4A_U05_P05F24_KP_ID);assert.deepEqual(G4A_U05_P05F24_FORMAL_MAPPING.includedRelations,["CLASSIFY_TRIANGLE_BY_EQUAL_SIDE_COUNT","PRESERVE_TRIANGLE_SIDE_CLASSIFICATION_UNDER_ROTATION"]);assert.equal(auditG4AU05P05F24Projection().ok,true);});

test("Q024 promotes only side classification and protects Q013 plus future same-source candidates",()=>{const audit=auditP05F24PublicSelectorComposition();assert.equal(audit.ok,true,JSON.stringify(audit));const source=listBatchAKnowledgePointAvailabilityBySource(G4A_U05_P05F24_SOURCE_ID);assert.equal(source.visibleCount,2);assert.equal(source.hiddenPendingCount,3);assert.equal(source.notSelectableCount,3);for(const id of ["kp_g4a_u05_triangle_elements_naming",G4A_U05_P05F24_KP_ID]){assert.ok(source.visibleKnowledgePointIds.includes(id));assert.ok(getVisibleBatchAKnowledgePoint(id));}for(const id of G4A_U05_P05F24_REMAINING_FUTURE_KP_IDS){assert.ok(source.hiddenPendingKnowledgePointIds.includes(id));assert.ok(source.notSelectableKnowledgePointIds.includes(id));assert.equal(getVisibleBatchAKnowledgePoint(id),null);}assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(G4A_U05_P05F24_KP_ID,"diagram"),G4A_U05_P05F24_SPEC_IDS);assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(G4A_U05_P05F24_KP_ID,"numeric"),[]);});

test("Q024 public binding admits only single-KP diagram classification",()=>{const b=resolvePublicUiCapabilityBinding({sourceId:G4A_U05_P05F24_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G4A_U05_P05F24_KP_ID]});assert.equal(b.blocked,false);assert.equal(b.questionType,"diagram");assert.equal(b.questionCount.max,240);assert.equal(b.sourceBackedTriangleSideClassification,true);assert.equal(b.equalSideCountClassification,true);assert.equal(b.rotationInvariant,true);assert.equal(b.triangleElementsNamingTargetAdmission,false);assert.equal(b.triangleAngleClassificationAdmission,false);assert.equal(b.triangleInequalityAdmission,false);assert.equal(b.congruentTriangleCorrespondenceAdmission,false);assert.equal(b.applicationImplementationAllowed,false);assert.equal(auditPublicUiCapabilityBinding().ok,true);assert.equal(requestsP05F24({sourceId:G4A_U05_P05F24_SOURCE_ID,selectionMode:"sourceUnit"}),false);assert.equal(requestsP05F24({sourceId:G4A_U05_P05F24_SOURCE_ID,selectionMode:"mixedKnowledgePointsSameUnit",selectedKnowledgePointIds:[G4A_U05_P05F24_KP_ID]}),false);});

for(const spec of G4A_U05_P05F24_PATTERN_SPECS)test(`Q024 ${spec.patternSpecId} proves 240 deterministic validated learner-visible variants`,()=>{const seed=`q024-${spec.patternSpecId}`,a=generateG4AU05P05F24Questions({patternSpecIds:[spec.patternSpecId],questionCount:240,generationSeed:seed}),b=generateG4AU05P05F24Questions({patternSpecIds:[spec.patternSpecId],questionCount:240,generationSeed:seed});assert.equal(a.ok,true,a.errors.join(","));assert.equal(a.questions.length,240);assert.equal(new Set(a.questions.map(q=>q.questionSignature)).size,240);assert.equal(new Set(a.questions.map(q=>`${q.promptText}|${q.geometryDiagram.rotationDeg}|${q.geometryDiagram.sideClass}`)).size,240);assert.deepEqual(a.questions.map(q=>q.questionSignature),b.questions.map(q=>q.questionSignature));assert.ok(a.questions.every(q=>validateG4AU05P05F24Question(q).ok));assert.deepEqual([...new Set(a.questions.map(q=>q.answerText))].sort(),["不等邊三角形","等腰三角形","等邊三角形"].sort());});

test("Q024 class is determined only by equal-side count and survives orientation changes",()=>{const generated=generateG4AU05P05F24Questions({questionCount:240,generationSeed:"q024-semantics"});assert.equal(generated.ok,true,generated.errors.join(","));assert.deepEqual([...new Set(generated.questions.map(q=>q.geometryDiagram.rotationDeg))].sort((a,b)=>a-b),Array.from({length:24},(_,i)=>i*15));for(const q of generated.questions){assert.equal(q.answerText,classify(q.geometryDiagram.sideLengthsCm));assert.equal(q.geometryDiagram.sideClass,q.answerText);assert.equal(q.geometryDiagram.classificationBasis,"EQUAL_SIDE_COUNT");assert.equal(q.geometryDiagram.rotationInvariant,true);assert.equal(q.metadata.triangleAngleClassificationTouched,false);assert.equal(q.metadata.triangleInequalityTouched,false);assert.equal(q.metadata.congruentTriangleCorrespondenceTouched,false);}});

test("Q024 validator fails closed on side-length, answer, future-scope, and application tampering",()=>{const q=generateG4AU05P05F24Questions({patternSpecIds:[G4A_U05_P05F24_SPEC_IDS[0]],questionCount:1,generationSeed:"q024-tamper"}).questions[0];assert.equal(validateG4AU05P05F24Question({...q,answerText:q.answerText==="等邊三角形"?"等腰三角形":"等邊三角形"}).ok,false);assert.equal(validateG4AU05P05F24Question({...q,geometryDiagram:{...q.geometryDiagram,sideLengthsCm:{...q.geometryDiagram.sideLengthsCm,AB:q.geometryDiagram.sideLengthsCm.AB+7}}}).ok,false);assert.equal(validateG4AU05P05F24Question({...q,knowledgePointId:"kp_g4a_u05_triangle_angle_classification"}).ok,false);assert.equal(validateG4AU05P05F24Question({...q,metadata:{...q.metadata,triangleInequalityTouched:true}}).ok,false);assert.equal(validateG4AU05P05F24Question({...q,metadata:{...q.metadata,applicationContextUsed:true}}).ok,false);});

test("Q024 browser generator, stable worksheet entry, and existing triangle renderer are bounded end-to-end",()=>{const options={sourceId:G4A_U05_P05F24_SOURCE_ID,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[G4A_U05_P05F24_KP_ID],questionCount:24,generationSeed:"q024-e2e",includeAnswerKey:true,printLayout:{columns:2,rowsPerPage:4,showAnswerKeyPage:true}};assert.equal(requestsP05F24(options),true);const plan=buildBatchABrowserPlan(options);assert.equal(plan.genericFallback,false);assert.equal(plan.questionCountMax,240);assert.deepEqual(plan.selectedKnowledgePointIds,[G4A_U05_P05F24_KP_ID]);const generated=generateBatchABrowserQuestions(options);assert.equal(generated.ok,true,generated.errors.join(","));assert.equal(generated.questions.length,24);assert.equal(new Set(generated.questions.map(q=>q.questionSignature)).size,24);const worksheet=buildBatchABrowserWorksheetDocument(options);assert.equal(worksheet.ok,true,worksheet.errors.join(","));assert.equal(worksheet.worksheetDocument.questionCount,24);assert.equal(worksheet.worksheetDocument.answerKeyItems.length,24);assert.equal(worksheet.worksheetDocument.metadata.triangleElementsNamingTargetTouched,false);assert.equal(worksheet.worksheetDocument.metadata.q025OrLaterTouched,false);const stable=buildStableWorksheet(options);assert.equal(stable.ok,true,stable.errors.join(","));assert.equal(stable.p05f24Implemented,true);const html=renderWorksheetDocumentToHtml(stable.worksheetDocument,{stylesheetHref:null});assert.match(html,/data-representation="triangle-elements-naming-diagram"/);assert.match(html,/依邊長分類/);assert.match(html,/worksheet-cell--answer-key/);});
