import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {materializeP05EW5DirectProductVerticalSliceQueue} from "../../src/curriculum/full-product/p05e-w5-direct-product-vertical-slice-queue.mjs";
import {materializeR04SharedRuntimeCapabilityMatrix} from "../../src/curriculum/global/r04-shared-runtime-capability-matrix.mjs";
import {materializeR05DeliveryWaveRebase} from "../../src/curriculum/global/r05-delivery-wave-rebase.mjs";
const read=p=>JSON.parse(readFileSync(new URL(`../../${p}`,import.meta.url),"utf8"));
const preflight=read("data/curriculum/full-product/p05f/q045-g5a-u07-complete-symmetric-figure-source-authority-preflight.json");
const r02=read("data/curriculum/global/candidates/r02/chunks/reviewed-source-candidates-03.json");
const KP="kp_g5a_u07_complete_symmetric_figure";
const CAPS=["cap_geometry_construction","cap_geometry_diagram_representation","cap_geometry_domain_validator","cap_geometry_property_reasoning"];

test("Q045 binds exact frozen row and Q044 E6 predecessor",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),row=q.queueEntries.find(x=>x.queuePosition===45);assert.equal(q.queueFrozen,true);assert.equal(q.queueRegistryParity,true);assert.equal(q.queueRegistry.queueDigest,"a4dae65a1a907ba963a135fce84ba292b8486a12513ae8f1fa54fbf07a6598ae");assert.ok(row);assert.equal(row.sliceId,"p05e_q045_r4_g5a_u07_5a07_profile_geometry_property_c1");assert.equal(row.implementationTaskId,"P05F_W5DirectProductVerticalSlice045Implementation");assert.equal(row.previousSliceId,"p05e_q044_r4_g5a_u05_5a05a_profile_geometry_property_c1");assert.equal(row.previousSliceMustBeD0Complete,true);assert.equal(row.primarySourceNodeId,"g5a_u07_5a07");assert.equal(row.intraWavePrerequisiteRank,4);assert.equal(row.primaryRuntimeProfileId,"profile_geometry_property");assert.equal(row.knowledgePointCount,1);assert.deepEqual(row.knowledgePointIds,[KP]);assert.deepEqual(row.requiredW5CapabilityIds,CAPS);const p=preflight.previousSliceD0Evidence;assert.equal(p.preflightPrNumber,930);assert.equal(p.productPrNumber,931);assert.equal(p.productHeadSha,"613bea9f00af1dbe099a2b2243ea9d4f356bbcc5");assert.equal(p.productMergeSha,"a402047b3968486a9d76276bf7f3f98b7ae2c6cb");assert.equal(p.prGateRunId,"34814132872");assert.equal(p.exactPagesRunId,"34814270789");assert.equal(p.evidenceArtifactId,"10335897854");assert.equal(p.evidenceArtifactDigest,"sha256:7d70ef5e7c3c61b40ff171fd3d92ef0764bd44170f7d427b4ba57a0cf9a509d7");assert.equal(p.status,"PASS_E6_D0_COMPLETE");});

test("Q045 reuses exact 5A07 source identity and binds reviewed completion candidate",()=>{const source=r02.sourceRecords.find(x=>x.sourceNodeId==="g5a_u07_5a07"),candidate=source?.candidates.find(x=>x.knowledgePointId===KP);assert.ok(source);assert.ok(candidate);assert.equal(preflight.status,"PASS_SOURCE_AUTHORITY_PREFLIGHT");assert.equal(preflight.sourceAuthority.sourceNodeId,"g5a_u07_5a07");assert.equal(preflight.sourceAuthority.sourcePdfTitle,"meow911_5a07_source.pdf");assert.equal(preflight.sourceAuthority.sourcePdfDriveFileId,"1JPwhBQDMYUusVKd8mWFb1ZrO05-HFIQc");assert.equal(preflight.sourceAuthority.sourceMetadataDriveFileId,"1tcwVjjjRVwJr0mVOiacOTEzkaJiDYUMQ");assert.equal(preflight.sourceAuthority.verificationNotesDriveFileId,"1f_sRdp9ASamJbRAwdMnbW4FQo90vJXUB");assert.equal(preflight.sourceAuthority.originalFileNameFromMetadata,"題型總覽-5a07-線對稱圖形.pdf");assert.equal(preflight.sourceAuthority.sourceUrlFromMetadata,"https://meow911.com/5a07/");assert.deepEqual(preflight.sourceAuthority.reviewedPages,[1]);assert.equal(preflight.sourceAuthority.semanticAuthority,"R02_REVIEWED_SOURCE_CANDIDATE");assert.equal(preflight.sourceAuthority.currentPreflightDirectTargetPanelReplayPerformed,false);assert.equal(preflight.sourceAuthority.currentPreflightDirectTargetPanelReplayRequired,false);assert.equal(preflight.sourceAuthority.driveVerificationNotesUsedAsCurrentSemanticAuthority,false);assert.equal(preflight.sourceAuthority.r02FullPageVisualReadbackIsCurrentSemanticAuthority,true);assert.equal(preflight.sourceAuthority.manualSourceChoiceRequired,false);assert.equal(preflight.sourceAuthority.sourceRefAmbiguity,false);assert.equal(candidate.canonicalNameZh,"補全線對稱圖形");assert.equal(candidate.capabilityStatement,"學生能依對稱軸畫出另一半圖形。");assert.equal(candidate.reasoningInvariant,"每個點須映射到軸另一側等距位置。");assert.equal(candidate.category,"geometry");assert.deepEqual(candidate.evidencePages,[1]);assert.equal(candidate.applicationSuitability,"APPLICATION_COMPATIBLE");assert.deepEqual(preflight.r02ReviewedCandidateAuthority.sameSourceCandidateIds,source.candidates.map(x=>x.knowledgePointId));});

test("Q045 current R04/R05 contract promotes geometry construction to required",()=>{const r04=materializeR04SharedRuntimeCapabilityMatrix(),m=r04.getMapping(KP);assert.ok(m);assert.equal(m.mappingId,"r04map_g5a_u07_complete_symmetric_figure");assert.equal(m.primaryRuntimeProfileId,"profile_geometry_property");assert.equal(m.classificationRuleId,"rule_geometry_property");assert.deepEqual(m.appliedModifierIds,["mod_geometry_construction"]);for(const cap of ["cap_geometry_property_reasoning","cap_geometry_domain_validator","cap_geometry_diagram_representation","cap_geometry_construction"])assert.ok(m.requiredRuntimeCapabilityIds.includes(cap));assert.deepEqual(m.optionalRuntimeCapabilityIds,[]);const profile=r04.profiles.find(x=>x.profileId==="profile_geometry_property");assert.ok(profile);assert.ok(profile.optionalCapabilityIds.includes("cap_geometry_construction"));const r05=materializeR05DeliveryWaveRebase(),a=r05.getAssignment(KP);assert.ok(a);assert.equal(a.deliveryWaveId,"R05-W5");assert.equal(a.intraWavePrerequisiteRank,4);assert.equal(a.primaryRuntimeProfileId,"profile_geometry_property");assert.deepEqual([...a.contractOnlyRequiredCapabilityIds].sort(),[...CAPS].sort());assert.deepEqual(preflight.runtimeCapabilityAuthority.exactFrozenQueueRequiredW5CapabilityIds,CAPS);assert.equal(preflight.runtimeCapabilityAuthority.geometryConstructionPromotedFromProfileOptionalToTargetRequiredByModifier,true);assert.equal(preflight.runtimeCapabilityAuthority.mappingPolicyModifierMatchCount,1);});

test("Q045 protects Q006 Q016 Q036 ownership and keeps coordinate reflection non-W5",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue();for(const [pos,id] of [[6,"kp_g5a_u07_line_symmetry_recognition"],[16,"kp_g5a_u07_symmetry_axis_count"],[36,"kp_g5a_u07_symmetric_point_distance"],[45,KP]]){const row=q.queueEntries.find(x=>x.queuePosition===pos);assert.ok(row);assert.equal(row.primarySourceNodeId,"g5a_u07_5a07");assert.ok(row.knowledgePointIds.includes(id));}assert.equal(q.queueEntries.some(x=>x.knowledgePointIds.includes("kp_g5a_u07_coordinate_reflection")),false);assert.deepEqual(preflight.q045ScopeLock.protectedExistingSameSourceKnowledgePointIds,["kp_g5a_u07_line_symmetry_recognition","kp_g5a_u07_symmetry_axis_count","kp_g5a_u07_symmetric_point_distance"]);assert.deepEqual(preflight.q045ScopeLock.sameSourceNonW5CandidateIds,["kp_g5a_u07_coordinate_reflection"]);assert.equal(preflight.q045ScopeLock.coordinateReflectionRemainsNonW5,true);});

test("Q045 scope is completion construction only and implementation remains approval-gated",()=>{for(const r of ["COMPLETE_MISSING_HALF_ACROSS_GIVEN_SYMMETRY_AXIS","MAP_EACH_CONTROL_POINT_TO_EQUAL_DISTANCE_OPPOSITE_SIDE","CONNECT_REFLECTED_POINTS_TO_COMPLETE_SYMMETRIC_FIGURE"])assert.ok(preflight.q045ScopeLock.includedRelations.includes(r));for(const r of ["REOWN_LINE_SYMMETRY_RECOGNITION","REOWN_SYMMETRY_AXIS_COUNT","REOWN_SYMMETRIC_POINT_DISTANCE_AS_PRIMARY_TARGET","COORDINATE_REFLECTION","COORDINATE_VALUE_ARITHMETIC","COORDINATE_MAP_REPRESENTATION_AS_PRIMARY_TARGET","APPLICATION_CONTEXT_IMPLEMENTATION","SAME_UNIT_MIXED_MODE","CROSS_UNIT_MIXED_MODE","Q046_OR_LATER_SEMANTICS"])assert.ok(preflight.q045ScopeLock.excludedRelations.includes(r));assert.equal(preflight.q045ScopeLock.givenSymmetryAxisRequired,true);assert.equal(preflight.q045ScopeLock.reflectedPointsMustRemainEquidistantFromSymmetryAxis,true);assert.equal(preflight.q045ScopeLock.fullFigureMustBeLineSymmetricAfterCompletion,true);assert.equal(preflight.q045ScopeLock.geometryConstructionRequiredForQ045,true);assert.equal(preflight.q045ScopeLock.implementationAllowedByThisPreflight,false);assert.equal(preflight.q045ScopeLock.publicProductAdmissionAllowedByThisPreflight,false);assert.equal(preflight.publicBaselineProtection.sourceAlreadyPublicFromPriorW5Slices,true);assert.equal(preflight.publicBaselineProtection.newSourceAdmissionRequiredForQ045,false);const b=preflight.preflightValidationBoundary;assert.equal(b.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(b.derivedLane,"SHARED_RUNTIME_BOUNDED");assert.equal(b.fullRepositoryRegressionAllowed,false);assert.equal(b.globalBrowserReplayAllowed,false);const d=preflight.preflightDecision;assert.equal(d.previousSliceD0Satisfied,true);assert.equal(d.geometryConstructionRequirementLocked,true);assert.equal(d.nonW5CoordinateReflectionProtected,true);assert.equal(d.manualSourceChoiceRequired,false);assert.equal(d.sourceRefAmbiguity,false);assert.equal(d.separateImplementationApprovalSatisfiedByCurrentOperatorInstruction,false);assert.equal(d.nextTaskRequiresNewOperatorApproval,true);assert.equal(d.nextTask,"P05F_W5DirectProductVerticalSlice045Implementation");});
