import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {materializeP05EW5DirectProductVerticalSliceQueue} from "../../src/curriculum/full-product/p05e-w5-direct-product-vertical-slice-queue.mjs";
import {materializeR04SharedRuntimeCapabilityMatrix} from "../../src/curriculum/global/r04-shared-runtime-capability-matrix.mjs";
import {materializeR05DeliveryWaveRebase} from "../../src/curriculum/global/r05-delivery-wave-rebase.mjs";
const read=p=>JSON.parse(readFileSync(new URL(`../../${p}`,import.meta.url),"utf8"));
const preflight=read("data/curriculum/full-product/p05f/q051-g5a-u05-polygon-diagonal-regular-properties-source-authority-preflight.json");
const r02=read("data/curriculum/global/candidates/r02/chunks/reviewed-source-candidates-02.json");
const KPS=["kp_g5a_u05a_polygon_diagonal","kp_g5a_u05a_regular_polygon_properties"];
const CAPS=["cap_geometry_diagram_representation","cap_geometry_domain_validator","cap_geometry_property_reasoning"];
const sorted=v=>[...v].sort();

test("Q051 binds exact frozen row and Q050 E6 predecessor",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),row=q.queueEntries.find(x=>x.queuePosition===51);assert.equal(q.queueFrozen,true);assert.equal(q.queueRegistryParity,true);assert.equal(q.queueRegistry.queueDigest,"a4dae65a1a907ba963a135fce84ba292b8486a12513ae8f1fa54fbf07a6598ae");assert.ok(row);assert.equal(row.sliceId,"p05e_q051_r5_g5a_u05_5a05a_profile_geometry_property_c1");assert.equal(row.implementationTaskId,"P05F_W5DirectProductVerticalSlice051Implementation");assert.equal(row.previousSliceId,"p05e_q050_r5_g4b_u07_4b07_profile_geometry_formula_c1");assert.equal(row.previousSliceMustBeD0Complete,true);assert.equal(row.assignedDeliveryWaveId,"R05-W5");assert.equal(row.primarySourceNodeId,"g5a_u05_5a05a");assert.deepEqual(row.supportingSourceNodeIds,["g5a_u05_5a05a"]);assert.equal(row.intraWavePrerequisiteRank,5);assert.equal(row.primaryRuntimeProfileId,"profile_geometry_property");assert.equal(row.chunkIndex,1);assert.equal(row.knowledgePointCount,2);assert.deepEqual(row.knowledgePointIds,KPS);assert.deepEqual(sorted(row.requiredW5CapabilityIds),sorted(CAPS));assert.equal(row.targetEvidenceLevel,"E6_D0_COMPLETE");assert.equal(preflight.queueAuthority.queueDigest,q.derivedRegistrySnapshot.queueDigest);const p=preflight.previousSliceD0Evidence;assert.equal(p.preflightPrNumber,943);assert.equal(p.productPrNumber,944);assert.equal(p.productHeadSha,"48fccf27ab300c4d4d436609af0978d3742a791f");assert.equal(p.productMergeSha,"79982e000f09f69f7aec20c17d6f01ab797e3125");assert.equal(p.prGateRunId,"34924060660");assert.equal(p.pagesDeploymentRunId,"34924151851");assert.equal(p.exactPagesRunId,"34924152764");assert.equal(p.evidenceArtifactId,"10379341343");assert.equal(p.evidenceArtifactDigest,"sha256:0b705d03d072f595891d0f1527b87b7f83f81137837f2488cfab20882e67ee44");assert.equal(p.status,"PASS_E6_D0_COMPLETE");assert.equal(p.prGateConclusion,"success");assert.equal(p.pagesDeploymentConclusion,"success");assert.equal(p.exactPagesWorkflowConclusion,"success");});

test("Q051 binds exact R02 page-3 diagonal and page-2 regular-polygon candidates",()=>{const source=r02.sourceRecords.find(x=>x.sourceNodeId==="g5a_u05_5a05a");assert.ok(source);assert.equal(source.sourceTitle,"多邊形與平面圖形");assert.equal(source.sourcePdfTitle,"meow911_5a05a_source.pdf");assert.equal(source.pageCount,3);assert.deepEqual(source.reviewedPages,[1,2,3]);const diagonal=source.candidates.find(x=>x.knowledgePointId===KPS[0]),regular=source.candidates.find(x=>x.knowledgePointId===KPS[1]);assert.deepEqual(diagonal,{knowledgePointId:KPS[0],canonicalNameZh:"多邊形對角線",capabilityStatement:"學生能辨認並畫出不相鄰頂點間的對角線。",reasoningInvariant:"對角線連接兩個不相鄰頂點且位於同一多邊形。",category:"geometry",evidencePages:[3],applicationSuitability:"APPLICATION_COMPATIBLE"});assert.deepEqual(regular,{knowledgePointId:KPS[1],canonicalNameZh:"正多邊形性質",capabilityStatement:"學生能辨認各邊等長且各角相等的正多邊形。",reasoningInvariant:"正多邊形須同時滿足等邊與等角。",category:"geometry",evidencePages:[2],applicationSuitability:"APPLICATION_COMPATIBLE"});assert.deepEqual(preflight.r02ReviewedCandidateAuthority.knowledgePoints,[diagonal,regular]);assert.deepEqual(preflight.r02ReviewedCandidateAuthority.sameSourceCandidateIds,source.candidates.map(x=>x.knowledgePointId));assert.equal(preflight.sourceAuthority.sourcePdfDriveFileId,"1FQuOHAf5-DTUS31bwBxFcWzAvCOZclbT");assert.equal(preflight.sourceAuthority.sourceMetadataDriveFileId,"1H2UqXYe-2Cfntxmp9OJDeKG4E9p2OFiO");assert.equal(preflight.sourceAuthority.verificationNotesDriveFileId,"18rwR0QbZJ-40ynpkXjexLc8Q1ZMsGVkd");assert.equal(preflight.sourceAuthority.adjacentSourceNodeConfusionRejected,"g5a_u05_5a05a1");assert.equal(preflight.sourceAuthority.ocrUsedAsAuthority,false);assert.equal(preflight.sourceAuthority.sourceRefAmbiguity,false);assert.equal(preflight.sourceAuthority.manualSourceChoiceRequired,false);});

test("Q051 current R04/R05 contracts are exact geometry-property and construction stays optional",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),row=q.queueEntries.find(x=>x.queuePosition===51),r04=materializeR04SharedRuntimeCapabilityMatrix(),r05=materializeR05DeliveryWaveRebase(),profile=r04.profiles.find(x=>x.profileId==="profile_geometry_property");assert.ok(row);assert.ok(profile);assert.deepEqual(profile.requiredCapabilityIds,["cap_geometry_property_reasoning","cap_geometry_domain_validator","cap_geometry_diagram_representation"]);assert.deepEqual(profile.optionalCapabilityIds,["cap_geometry_construction"]);for(const kp of KPS){const m=r04.getMapping(kp),a=r05.getAssignment(kp),bound=preflight.runtimeCapabilityAuthority.perKnowledgePointMappings.find(x=>x.knowledgePointId===kp);assert.ok(m,kp);assert.ok(a,kp);assert.ok(bound,kp);assert.equal(m.mappingId,`r04map_${kp.replace(/^kp_/,"")}`);assert.equal(m.primaryRuntimeProfileId,"profile_geometry_property");assert.equal(m.classificationRuleId,"rule_geometry_property");assert.deepEqual(m.appliedModifierIds,[]);assert.deepEqual(m.optionalRuntimeCapabilityIds,["cap_geometry_construction"]);assert.deepEqual(m.forbiddenRuntimeCapabilityIds,[]);assert.deepEqual(bound.requiredRuntimeCapabilityIds,m.requiredRuntimeCapabilityIds);assert.deepEqual(bound.optionalRuntimeCapabilityIds,m.optionalRuntimeCapabilityIds);assert.equal(a.deliveryWaveId,"R05-W5");assert.equal(a.intraWavePrerequisiteRank,5);assert.equal(a.primaryRuntimeProfileId,"profile_geometry_property");assert.deepEqual(sorted(a.contractOnlyRequiredCapabilityIds),sorted(CAPS));}assert.deepEqual(sorted(row.requiredW5CapabilityIds),sorted(CAPS));const c=preflight.runtimeCapabilityAuthority.geometryConstructionBoundary;assert.equal(c.profileOptionalCapabilityPreserved,true);assert.equal(c.polygonDiagonalSourceCapabilityIncludesDrawVerb,true);assert.equal(c.r04ConstructionModifierApplied,false);assert.equal(c.constructionRequiredByFrozenQueue,false);assert.equal(c.interactiveOrFreeFormConstructionCommittedByThisPreflight,false);});

test("Q051 owns exactly diagonal plus regular-polygon properties and protects Q044/Q056/non-W5 siblings",()=>{const q=materializeP05EW5DirectProductVerticalSliceQueue(),q44=q.queueEntries.find(x=>x.knowledgePointIds.includes("kp_g5a_u05a_polygon_definition_classification")),q56=q.queueEntries.find(x=>x.knowledgePointIds.includes("kp_g5a_u05a_polygon_triangulation"));assert.equal(q44?.queuePosition,44);assert.equal(q56?.queuePosition,56);assert.deepEqual(preflight.q051ScopeLock.includedKnowledgePointIds,KPS);assert.equal(preflight.q051ScopeLock.protectedExistingSameSourceKnowledgePointOwnership.kp_g5a_u05a_polygon_definition_classification,"Q044");assert.deepEqual(preflight.q051ScopeLock.deferredFrozenOwnership.Q056,["kp_g5a_u05a_polygon_triangulation"]);assert.deepEqual(preflight.q051ScopeLock.sameSourceNonW5CandidateIds,["kp_g5a_u05a_polygon_angle_sum_reasoning"]);assert.equal(q.queueEntries.some(x=>x.knowledgePointIds.includes("kp_g5a_u05a_polygon_angle_sum_reasoning")),false);assert.equal(preflight.q051ScopeLock.adjacentSourceNodeKeptSeparate,"g5a_u05_5a05a1");assert.equal(preflight.q051ScopeLock.regularPolygonMustRequireBothEqualSidesAndEqualAngles,true);assert.equal(preflight.q051ScopeLock.diagonalMustConnectTwoNonAdjacentVertices,true);assert.equal(preflight.q051ScopeLock.polygonSideMustNotBeAcceptedAsDiagonal,true);for(const r of ["POLYGON_TRIANGULATION_AS_TARGET","POLYGON_INTERIOR_ANGLE_SUM_REASONING","SECTOR_OR_CENTRAL_ANGLE_SEMANTICS","APPLICATION_CONTEXT_IMPLEMENTATION","INTERACTIVE_FREE_FORM_GEOMETRY_CONSTRUCTION_REQUIREMENT","SAME_UNIT_MIXED_MODE","CROSS_UNIT_MIXED_MODE","Q052_OR_LATER_SEMANTICS"])assert.ok(preflight.q051ScopeLock.excludedRelations.includes(r),r);});

test("Q051 preflight stays bounded and stops at implementation approval boundary",()=>{const b=preflight.preflightValidationBoundary;assert.equal(b.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(b.derivedLane,"SHARED_RUNTIME_BOUNDED");assert.deepEqual(b.allowedLaneGateIds,["GLOBAL_CONTRACTS","TARGETED_ROUTE_REPLAY"]);assert.equal(b.focusedNodeContractRequired,true);assert.equal(b.nodeOnlyReadbackRequired,true);assert.equal(b.fullRepositoryRegressionAllowed,false);assert.equal(b.globalBrowserReplayAllowed,false);assert.equal(b.productImplementationAllowed,false);assert.equal(b.publicProductAdmissionAllowed,false);for(const k of ["applicationImplementationAllowedByThisPreflight","implementationAllowedByThisPreflight","publicProductAdmissionAllowedByThisPreflight","frozenQueueAuthorityTouched","r02AuthorityTouched","r04AuthorityTouched","r05AuthorityTouched","q052OrLaterTouched"])assert.equal(preflight.q051ScopeLock[k],false,k);const d=preflight.preflightDecision;assert.equal(d.exactFrozenQueueRowResolved,true);assert.equal(d.sourceAuthoritySufficientForQ051ImplementationPlanning,true);assert.equal(d.previousSliceD0Satisfied,true);assert.equal(d.r02AuthorityBoundForBothTargetKnowledgePoints,true);assert.equal(d.runtimeCapabilityContractLockedForBothTargetKnowledgePoints,true);assert.equal(d.priorSameSourceFrozenOwnershipProtected,true);assert.equal(d.q056DeferredOwnershipProtected,true);assert.equal(d.sameSourceNonW5AngleSumProtected,true);assert.equal(d.adjacent5a05a1SourceKeptSeparate,true);assert.equal(d.manualSourceChoiceRequired,false);assert.equal(d.sourceRefAmbiguity,false);assert.equal(d.separateImplementationApprovalSatisfiedByCurrentOperatorInstruction,false);assert.equal(d.nextTaskRequiresNewOperatorApproval,true);assert.equal(d.nextTask,"P05F_W5DirectProductVerticalSlice051Implementation");});
