import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {BATCH_A_SELECTOR_AVAILABILITY,getVisibleBatchAKnowledgePoint,listBatchAKnowledgePointAvailabilityBySource} from "../../site/modules/curriculum/registry/batch-a-selector-p05f16-extension.js";

const readJson=relative=>JSON.parse(readFileSync(new URL(`../../${relative}`,import.meta.url),"utf8"));
const preflight=readJson("data/curriculum/full-product/p05f/q017-g5a-u10a-prism-pyramid-elements-source-authority-preflight.json");
const queue=readJson("data/curriculum/full-product/p05e/w5-direct-product-vertical-slice-queue.json");
const r02=readJson("data/curriculum/global/candidates/r02/chunks/reviewed-source-candidates-03.json");
const profiles=readJson("data/curriculum/global/runtime/r04/runtime-capability-profiles.json");
const capabilities=readJson("data/curriculum/global/runtime/r04/shared-runtime-capabilities.json");
const q007=readJson("data/curriculum/full-product/p05f/q007-g5a-u10a-solid-shape-classification-source-authority-preflight.json");
const TARGET="kp_g5a_u10a_prism_pyramid_elements",SOURCE="g5a_u10_5a10a",Q007="kp_g5a_u10a_solid_shape_classification";
const LATER=["kp_g5a_u10a_solid_net_correspondence","kp_g5a_u10a_solid_cross_section","kp_g5a_u10a_solid_viewpoint_representation"];
const EXACT_CAPS=["cap_geometry_domain_validator","cap_geometry_property_reasoning","cap_solid_geometry_representation","cap_spatial_solid_reasoning"];

function dependencyClosure(required){const byId=new Map(capabilities.capabilities.map(row=>[row.capabilityId,row]));const out=new Set(required),stack=[...required];while(stack.length){const id=stack.pop(),row=byId.get(id);assert.ok(row,`missing capability ${id}`);for(const dep of row.dependsOn??[]){if(!out.has(dep)){out.add(dep);stack.push(dep);}}}return [...out].sort();}

test("P05F W5 Q017 exact frozen queue row is locked",()=>{assert.equal(preflight.status,"PASS_SOURCE_AUTHORITY_PREFLIGHT");assert.equal(queue.queueVersion,preflight.queueAuthority.queueVersion);assert.equal(queue.queueDigest,preflight.queueAuthority.queueDigest);assert.equal(queue.orderedSliceIds[16],preflight.queueAuthority.sliceId);assert.equal(queue.orderedImplementationTaskIds[16],"P05F_W5DirectProductVerticalSlice017Implementation");assert.equal(queue.orderedKnowledgePointIds[18],TARGET);assert.equal(preflight.queueAuthority.queuePosition,17);assert.equal(preflight.queueAuthority.primarySourceNodeId,SOURCE);assert.equal(preflight.queueAuthority.primaryRuntimeProfileId,"profile_spatial_solid");assert.deepEqual(preflight.queueAuthority.knowledgePointIds,[TARGET]);assert.deepEqual(preflight.queueAuthority.requiredW5CapabilityIds,EXACT_CAPS);});

test("P05F W5 Q017 reuses exact Q007 source identity with no source-ref ambiguity",()=>{assert.equal(q007.sourceAuthority.sourceNodeId,SOURCE);assert.equal(preflight.sourceAuthority.sourcePdfDriveFileId,q007.sourceAuthority.sourcePdfDriveFileId);assert.equal(preflight.sourceAuthority.sourcePdfTitle,q007.sourceAuthority.sourcePdfTitle);assert.deepEqual(preflight.sourceAuthority.reviewedPages,[1,2]);assert.equal(preflight.sourceAuthority.chosenSourceRef,"R02_FULL_PAGE_VISUAL_READBACK_REUSE");assert.equal(preflight.sourceAuthority.sourceRefAmbiguity,false);assert.equal(preflight.sourceAuthority.manualSourceChoiceRequired,false);});

test("P05F W5 Q017 R02 candidate semantics are copied exactly and siblings stay excluded",()=>{const source=r02.sourceRecords.find(row=>row.sourceNodeId===SOURCE);assert.ok(source);assert.equal(source.sourceTitle,"柱體錐體和球");assert.deepEqual(source.reviewedPages,[1,2]);const candidate=source.candidates.find(row=>row.knowledgePointId===TARGET);assert.ok(candidate);assert.equal(candidate.canonicalNameZh,"柱體錐體構成要素");assert.equal(candidate.capabilityStatement,"學生能辨認立體的底面、側面、稜與頂點。");assert.equal(candidate.reasoningInvariant,"構成要素的數量與位置由底面多邊形決定。");assert.deepEqual(candidate.evidencePages,[1,2]);assert.equal(candidate.applicationSuitability,"APPLICATION_COMPATIBLE");assert.equal(preflight.r02ReviewedCandidateAuthority.canonicalNameZh,candidate.canonicalNameZh);assert.equal(preflight.r02ReviewedCandidateAuthority.capabilityStatement,candidate.capabilityStatement);assert.equal(preflight.r02ReviewedCandidateAuthority.reasoningInvariant,candidate.reasoningInvariant);assert.deepEqual(preflight.q017ScopeLock.excludedKnowledgePointIdsFromSameSource,LATER);});

test("P05F W5 Q017 spatial-solid profile plus dependency closure equals frozen W5 capability set",()=>{const profile=profiles.profiles.find(row=>row.profileId==="profile_spatial_solid");assert.ok(profile);assert.deepEqual(profile.requiredCapabilityIds,["cap_spatial_solid_reasoning","cap_geometry_domain_validator","cap_solid_geometry_representation"]);assert.deepEqual(preflight.runtimeCapabilityAuthority.profileRequiredCapabilityIds,profile.requiredCapabilityIds);assert.deepEqual(dependencyClosure(profile.requiredCapabilityIds),EXACT_CAPS);assert.deepEqual(preflight.runtimeCapabilityAuthority.exactFrozenQueueRequiredW5CapabilityIds,EXACT_CAPS);assert.deepEqual(preflight.runtimeCapabilityAuthority.dependencyClosureAddedCapabilityIds,["cap_geometry_property_reasoning"]);});

test("P05F W5 Q017 preflight leaves current public selector unchanged",()=>{assert.equal(BATCH_A_SELECTOR_AVAILABILITY.sourceCount,53);assert.equal(BATCH_A_SELECTOR_AVAILABILITY.publicSourceCount,53);assert.equal(BATCH_A_SELECTOR_AVAILABILITY.visibleCount,330);const source=listBatchAKnowledgePointAvailabilityBySource(SOURCE);assert.equal(source.visibleCount,1);assert.equal(source.hiddenPendingCount,4);assert.equal(source.notSelectableCount,4);assert.deepEqual(source.visibleKnowledgePointIds,[Q007]);assert.ok(source.hiddenPendingKnowledgePointIds.includes(TARGET));assert.ok(source.notSelectableKnowledgePointIds.includes(TARGET));assert.ok(getVisibleBatchAKnowledgePoint(Q007));assert.equal(getVisibleBatchAKnowledgePoint(TARGET),null);for(const id of LATER){assert.ok(source.hiddenPendingKnowledgePointIds.includes(id));assert.ok(source.notSelectableKnowledgePointIds.includes(id));assert.equal(getVisibleBatchAKnowledgePoint(id),null);}assert.equal(preflight.publicPreflightBaseline.publicCutoverPerformedByThisPreflight,false);});

test("P05F W5 Q017 scope contract protects Q007 sourceUnit ownership and blocks future semantics",()=>{assert.deepEqual(preflight.q017ScopeLock.includedKnowledgePointIds,[TARGET]);assert.deepEqual(preflight.q017ScopeLock.protectedExistingSameSourceKnowledgePointIds,[Q007]);assert.deepEqual(preflight.q017ScopeLock.includedRelations,["IDENTIFY_BASE_SIDE_FACE_EDGE_VERTEX","RELATE_ELEMENT_COUNT_POSITION_TO_BASE_POLYGON"]);for(const relation of ["SOLID_SHAPE_CLASSIFICATION","SOLID_NET_CORRESPONDENCE","SOLID_CROSS_SECTION","SOLID_VIEWPOINT_REPRESENTATION","APPLICATION_CONTEXT","GEOMETRY_FORMULA_OR_MEASUREMENT"])assert.ok(preflight.q017ScopeLock.excludedRelations.includes(relation));assert.equal(preflight.q017ScopeLock.reusesQ007SourceUnitContextWithoutReowningClassification,true);assert.equal(preflight.q017ScopeLock.implementationAllowedByThisPreflight,false);assert.equal(preflight.q017ScopeLock.publicProductAdmissionAllowedByThisPreflight,false);assert.equal(preflight.q017ScopeLock.q018OrLaterTouched,false);assert.equal(preflight.q017ScopeLock.frozenQueueAuthorityTouched,false);});

test("P05F W5 Q017 future implementation and validation boundary are bounded and fail-safe",()=>{assert.equal(preflight.implementationContractLock.maxQuestionCount,240);assert.equal(preflight.implementationContractLock.sharedRuntimeScope,"SHARED_RUNTIME_BOUNDED");assert.equal(preflight.implementationContractLock.genericFallbackAllowed,false);assert.equal(preflight.implementationContractLock.freeFormAIAllowed,false);assert.equal(preflight.implementationContractLock.sourceUnitActivationAllowed,false);assert.equal(preflight.implementationContractLock.mixedKnowledgePointActivationAllowed,false);assert.equal(preflight.validationBoundary.expectedDerivedGate,"SHARED_RUNTIME_BOUNDED");assert.equal(preflight.validationBoundary.fullRepositoryRegression,"FORBIDDEN_FOR_THIS_PREFLIGHT");assert.equal(preflight.validationBoundary.globalBrowserReplay,"FORBIDDEN_FOR_THIS_PREFLIGHT");assert.equal(preflight.policyBoundary.planningOnly,true);assert.equal(preflight.policyBoundary.implementationPerformed,false);assert.equal(preflight.preflightDecision.nextTaskRequiresSeparateImplementationApproval,true);assert.equal(preflight.preflightDecision.nextTask,"P05F_W5DirectProductVerticalSlice017Implementation");});
