
import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {auditG5BU11P06F12Projection,G5B_U11_P06F12_COMPARE_KP_ID as COMPARE_KP,G5B_U11_P06F12_CONSTRUCT_KP_ID as CONSTRUCT_KP,G5B_U11_P06F12_INCLUDED_RELATIONS as RELATIONS,G5B_U11_P06F12_PATTERN_SPECS as SPECS,G5B_U11_P06F12_PREDECESSOR_KP_IDS as PREV,G5B_U11_P06F12_QUEUE_REQUIRED_CAPABILITY_IDS as CAPS,G5B_U11_P06F12_SOURCE_ID as SRC,G5B_U11_P06F12_TARGET_KP_IDS as KPS,G5B_U11_P06F12_TREND_KP_ID as TREND_KP} from "../../site/modules/curriculum/registry/g5b-u11-compare-construct-trend-selector-projection-p06f12.js";
import * as preSelector from "../../site/modules/curriculum/registry/batch-a-selector-p06f11-extension.js";
import {auditP06F12PublicSelectorComposition,getVisibleBatchAKnowledgePoint,listBatchAKnowledgePointAvailabilityBySource,listVisibleBatchAKnowledgePoints,resolveVisiblePatternSpecIdsForKnowledgePoint} from "../../site/modules/curriculum/registry/batch-a-selector-p06f12-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p06f12.js";
import {buildG5BU11P06F12Question,generateG5BU11P06F12Questions,validateG5BU11P06F12Answer,validateG5BU11P06F12Question} from "../../site/modules/curriculum/batch-a/g5b-u11-compare-construct-trend-runtime-p06f12.js";
import {buildBatchABrowserPlan,generateBatchABrowserQuestions} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p05f60.js";
import {buildBatchABrowserWorksheetDocument} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f60-extension.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";

function read(p){return JSON.parse(readFileSync(new URL("../../"+p,import.meta.url),"utf8"));}
const implementation=read("data/curriculum/full-product/p06f/q012-g5b-u11-compare-construct-trend-implementation.json");
const impact=read("data/project/change-impact/P06F_W6_Q012.impact.json");
const validation=read("data/project/validation-plans/P06F_W6_Q012.validation.json");
function request(kp,extra={}){return Object.assign({sourceId:SRC,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[kp],questionMode:"numeric",questionCount:20,generationSeed:"p06f12-"+kp},extra);}

test("W6 Q012 materializes exact three chart-data KPs",function(){assert.equal(implementation.status,"IMPLEMENTATION_MATERIALIZED_AWAITING_FOCUSED_CI");assert.equal(implementation.queueAuthority.queuePosition,12);assert.deepEqual(implementation.queueAuthority.knowledgePointIds,KPS);assert.deepEqual(implementation.queueAuthority.requiredW6CapabilityIds,CAPS);assert.deepEqual(implementation.productContract.includedRelations,RELATIONS);assert.deepEqual(auditG5BU11P06F12Projection(),{ok:true,errors:[],counts:{knowledgePoints:3,patternGroups:3,patternSpecs:3,formalMappings:3}});});

test("W6 Q012 promotes exact targets while preserving Q010",function(){var before=preSelector.listBatchAKnowledgePointAvailabilityBySource(SRC);assert.ok(before);assert.ok(PREV.every(function(id){return before.visibleKnowledgePointIds.includes(id);}));assert.ok(KPS.every(function(id){return preSelector.getVisibleBatchAKnowledgePoint(id)==null&&before.hiddenPendingKnowledgePointIds.includes(id)&&before.notSelectableKnowledgePointIds.includes(id);}));var a=auditP06F12PublicSelectorComposition();assert.equal(a.ok,true,a.errors.join("\n"));var after=listBatchAKnowledgePointAvailabilityBySource(SRC),visible=listVisibleBatchAKnowledgePoints().filter(function(x){return x.sourceId===SRC;}).map(function(x){return x.knowledgePointId;});assert.ok(PREV.every(function(id){return visible.includes(id);}));assert.ok(KPS.every(function(id){return visible.includes(id)&&getVisibleBatchAKnowledgePoint(id)&&!after.hiddenPendingKnowledgePointIds.includes(id)&&!after.notSelectableKnowledgePointIds.includes(id);}));assert.ok(KPS.every(function(id){return resolveVisiblePatternSpecIdsForKnowledgePoint(id,"numeric").length===1;}));assert.equal(after.sameUnitMixedAllowed,false);});

test("W6 Q012 public bindings lock compare construct and trend semantics",function(){var a=auditPublicUiCapabilityBinding();assert.equal(a.ok,true,a.errors.join("\n"));for(const kp of KPS){var b=resolvePublicUiCapabilityBinding(request(kp));assert.equal(b.blocked,false);assert.equal(b.questionType,"numeric");assert.equal(b.questionCount.max,240);assert.deepEqual(b.requiredCapabilityIds,CAPS);assert.equal(b.q010ValueReadingReowned,false);assert.equal(b.q010BrokenAxisReowned,false);assert.equal(b.singlePointTrendInferenceAllowed,false);assert.equal(b.frozenRuntimeProfile,"profile_chart_data");}assert.equal(resolvePublicUiCapabilityBinding(request(COMPARE_KP)).commonScaleRequired,true);assert.equal(resolvePublicUiCapabilityBinding(request(CONSTRUCT_KP)).scalePointPlacementAndOrderedConnectionRequired,true);assert.equal(resolvePublicUiCapabilityBinding(request(TREND_KP)).adjacentPointChangesRequired,true);});

for(const spec of SPECS)test("W6 Q012 "+spec.patternSpecId+" has 240 deterministic unique validated variants",function(){var a=generateG5BU11P06F12Questions({knowledgePointId:spec.knowledgePointId,questionCount:240,patternSpecIds:[spec.patternSpecId],generationSeed:"stable"}),b=generateG5BU11P06F12Questions({knowledgePointId:spec.knowledgePointId,questionCount:240,patternSpecIds:[spec.patternSpecId],generationSeed:"stable"});assert.equal(a.ok,true,a.errors.join("\n"));assert.deepEqual(a.questions,b.questions);assert.equal(new Set(a.questions.map(function(q){return q.questionSignature;})).size,240);for(const q of a.questions){assert.equal(validateG5BU11P06F12Question(q).ok,true);assert.equal(validateG5BU11P06F12Answer(q,q.answerValue).ok,true);assert.equal(q.chartData.kind,"line_chart_data");assert.equal(q.metadata.q010ValueReadingReowned,false);assert.equal(q.metadata.q010BrokenAxisReowned,false);}});

test("W6 Q012 validator fails closed on series construction and trend mutations",function(){var c=buildG5BU11P06F12Question({variant:17,patternSpecId:SPECS.find(function(x){return x.knowledgePointId===COMPARE_KP;}).patternSpecId});assert.equal(validateG5BU11P06F12Answer(c,c.answerValue+1).ok,false);var changedSeries=c.chartData.series.map(function(s,si){return si?Object.assign({},s,{points:s.points.map(function(p,j){return j===c.patternRepresentation.targetIndex?Object.assign({},p,{value:p.value+c.chartData.scaleStep}):p;})}):s;});assert.equal(validateG5BU11P06F12Question(Object.assign({},c,{chartData:Object.assign({},c.chartData,{series:changedSeries})})).ok,false);var k=buildG5BU11P06F12Question({variant:29,patternSpecId:SPECS.find(function(x){return x.knowledgePointId===CONSTRUCT_KP;}).patternSpecId});assert.equal(k.chartData.points.filter(function(x){return x.masked;}).length,1);assert.equal(validateG5BU11P06F12Question(Object.assign({},k,{chartData:Object.assign({},k.chartData,{points:k.chartData.points.map(function(x){return Object.assign({},x,{masked:false});})})})).ok,false);var t=buildG5BU11P06F12Question({variant:31,patternSpecId:SPECS.find(function(x){return x.knowledgePointId===TREND_KP;}).patternSpecId});assert.equal(validateG5BU11P06F12Question(Object.assign({},t,{metadata:Object.assign({},t.metadata,{singlePointTrendInferenceUsed:true})})).ok,false);});

test("W6 Q012 browser path renders all three chart targets and preserves Q010",function(){for(const kp of KPS){var p=buildBatchABrowserPlan(request(kp,{questionCount:6}));assert.deepEqual(p.selectedKnowledgePointIds,[kp]);assert.equal(p.questionCountMax,240);var g=generateBatchABrowserQuestions(request(kp,{questionCount:6}));assert.equal(g.ok,true,g.errors.join("\n"));var w=buildBatchABrowserWorksheetDocument(request(kp,{questionCount:6,includeAnswerKey:true,printLayout:{columns:2,rowsPerPage:1,showAnswerKeyPage:true}}));assert.equal(w.ok,true,w.errors.join("\n"));var html=renderWorksheetDocumentToHtml(w.worksheetDocument,{stylesheetHref:""});assert.equal((html.match(/class="worksheet-line-chart"/g)||[]).length,12);if(kp===COMPARE_KP)assert.ok(html.includes('data-series-count="2"'));if(kp===CONSTRUCT_KP)assert.ok(html.includes("worksheet-line-chart__point--masked"));}var q10=generateBatchABrowserQuestions({sourceId:SRC,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[PREV[0]],questionMode:"numeric",questionCount:4,generationSeed:"q10-preserve"});assert.equal(q10.ok,true,q10.errors.join("\n"));assert.ok(q10.questions.every(function(x){return x.knowledgePointId===PREV[0];}));var mixed=generateBatchABrowserQuestions({sourceId:SRC,selectionMode:"mixedKnowledgePointsSameUnit",selectedKnowledgePointIds:PREV.concat(KPS),questionMode:"numeric",questionCount:4,generationSeed:"mixed-not-admitted"});assert.equal(mixed.ok,false);});

test("W6 Q012 validation contract stays SHARED_RUNTIME_BOUNDED",function(){assert.equal(impact.expectedDerivedGate,"SHARED_RUNTIME_BOUNDED");assert.equal(validation.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.deepEqual(validation.lanes.SHARED_RUNTIME_BOUNDED.map(function(x){return x.gateId;}),["GLOBAL_CONTRACTS","TARGETED_ROUTE_REPLAY"]);assert.equal(JSON.stringify(validation).includes("FULL_REPOSITORY"),false);assert.equal(JSON.stringify(validation).includes("GLOBAL_BROWSER_REPLAY"),false);});
