import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {auditG4BU05P06F07Projection,G4B_U05_P06F07_INCLUDED_RELATIONS as RELATIONS,G4B_U05_P06F07_PROTECTED_FUTURE_KP_IDS as FUTURE,G4B_U05_P06F07_QUEUE_REQUIRED_CAPABILITY_IDS as QUEUE_CAPS,G4B_U05_P06F07_SOURCE_ID as SRC,G4B_U05_P06F07_SPEC_IDS as SPECS,G4B_U05_P06F07_TARGET_KP_IDS as TARGETS} from "../../site/modules/curriculum/registry/g4b-u05-chart-read-scale-selector-projection-p06f07.js";
import * as preQ007Selector from "../../site/modules/curriculum/registry/batch-a-selector-p06f06-extension.js";
import {auditP06F07PublicSelectorComposition,getVisibleBatchAKnowledgePoint,listBatchAKnowledgePointAvailabilityBySource,listVisibleBatchAKnowledgePoints,resolveVisiblePatternSpecIdsForKnowledgePoint} from "../../site/modules/curriculum/registry/batch-a-selector-p06f07-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p06f07.js";
import {buildG4BU05P06F07Question,generateG4BU05P06F07Questions,validateG4BU05P06F07Answer,validateG4BU05P06F07Question} from "../../site/modules/curriculum/batch-a/g4b-u05-chart-read-scale-runtime-p06f07.js";
import {buildBatchABrowserPlan,generateBatchABrowserQuestions} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p05f60.js";
import {buildBatchABrowserWorksheetDocument} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f60-extension.js";
import {listBatchASourceUnits} from "../../site/modules/curriculum/batch-a/source-units.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";
const read=p=>JSON.parse(readFileSync(new URL(`../../${p}`,import.meta.url),"utf8"));
const implementation=read("data/curriculum/full-product/p06f/q007-g4b-u05-chart-read-scale-implementation.json");
const impact=read("data/project/change-impact/P06F_W6_Q007.impact.json");
const validation=read("data/project/validation-plans/P06F_W6_Q007.validation.json");
const request=(kp,extra={})=>({sourceId:SRC,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[kp],questionMode:"numeric",questionCount:20,generationSeed:"p06f07-focused",...extra});

test("W6 Q007 materializes two chart KPs with two FormalMappings and two PatternSpecs",()=>{
  assert.equal(implementation.status,"IMPLEMENTATION_MATERIALIZED_AWAITING_FOCUSED_CI");assert.equal(implementation.queueAuthority.queuePosition,7);assert.deepEqual(implementation.queueAuthority.knowledgePointIds,TARGETS);assert.deepEqual(implementation.queueAuthority.requiredW6CapabilityIds,QUEUE_CAPS);assert.deepEqual(implementation.productContract.includedRelations,RELATIONS);assert.deepEqual(implementation.productContract.patternSpecIds,SPECS);assert.deepEqual(auditG4BU05P06F07Projection(),{ok:true,errors:[],counts:{knowledgePoints:2,patternGroups:2,patternSpecs:2,formalMappings:2}});assert.equal(implementation.semanticProfileLock.barChartReadingIsCore,true);assert.equal(implementation.semanticProfileLock.nonUnitScaleMustBeSupported,true);
});
test("W6 Q007 adds G4B-U05 publicly, promotes only Q007 targets and protects Q009 successors",()=>{
  const before=preQ007Selector.listBatchAKnowledgePointAvailabilityBySource(SRC);assert.equal(before.sourceId,SRC);assert.equal(before.visibleCount,0);assert.deepEqual(before.visibleKnowledgePointIds??[],[]);assert.ok(TARGETS.every(id=>preQ007Selector.getVisibleBatchAKnowledgePoint(id)==null));const a=auditP06F07PublicSelectorComposition();assert.equal(a.ok,true,a.errors.join("\n"));const after=listBatchAKnowledgePointAvailabilityBySource(SRC),visible=listVisibleBatchAKnowledgePoints().filter(x=>x.sourceId===SRC).map(x=>x.knowledgePointId);assert.deepEqual(visible,TARGETS);assert.ok(TARGETS.every(id=>getVisibleBatchAKnowledgePoint(id)&&!after.hiddenPendingKnowledgePointIds.includes(id)&&!after.notSelectableKnowledgePointIds.includes(id)));assert.ok(FUTURE.every(id=>!visible.includes(id)&&getVisibleBatchAKnowledgePoint(id)==null&&after.hiddenPendingKnowledgePointIds.includes(id)&&after.notSelectableKnowledgePointIds.includes(id)));assert.equal(after.sameUnitMixedAllowed,false);assert.ok(listBatchASourceUnits({includeW6Slice007:true}).some(x=>x.sourceId===SRC&&x.grade===4&&x.semester==="lower"));
});
test("W6 Q007 public bindings require exact chart capability closure and keep future semantics fail-closed",()=>{
  const a=auditPublicUiCapabilityBinding();assert.equal(a.ok,true,a.errors.join("\n"));for(const kp of TARGETS){const b=resolvePublicUiCapabilityBinding(request(kp));assert.equal(b.blocked,false);assert.equal(b.questionType,"numeric");assert.equal(b.questionCount.max,240);assert.equal(b.chartDataModelRequired,true);assert.equal(b.dataDomainValidationRequired,true);assert.equal(b.chartRepresentationRequired,true);assert.equal(b.tableDataDependencyClosureRequired,true);assert.equal(b.nonUnitScaleRequired,true);assert.equal(b.chartConstructionUsed,false);assert.equal(b.multiCategoryComparisonUsed,false);assert.equal(b.missingValueTotalUsed,false);assert.equal(b.lineChartUsed,false);assert.equal(b.pieChartUsed,false);assert.equal(b.q008OrLaterTouched,false);assert.equal(b.sameUnitMixedAdmission,false);assert.equal(b.crossUnitMixedAdmission,false);assert.deepEqual(b.requiredCapabilityIds,QUEUE_CAPS);assert.equal(b.frozenRuntimeProfile,"profile_chart_data");const expected=SPECS.filter(id=>id.includes(kp===TARGETS[0]?"bar_chart":"chart_scale"));assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(kp,"numeric"),expected);}
});
for(const patternSpecId of SPECS)test(`W6 Q007 ${patternSpecId} has 240 deterministic unique validated variants`,()=>{const kp=patternSpecId===SPECS[0]?TARGETS[0]:TARGETS[1],a=generateG4BU05P06F07Questions({knowledgePointId:kp,questionCount:240,patternSpecIds:[patternSpecId],generationSeed:"stable"}),b=generateG4BU05P06F07Questions({knowledgePointId:kp,questionCount:240,patternSpecIds:[patternSpecId],generationSeed:"stable"});assert.equal(a.ok,true,a.errors.join("\n"));assert.deepEqual(a.questions,b.questions);assert.equal(new Set(a.questions.map(q=>q.questionSignature)).size,240);for(const q of a.questions){assert.equal(validateG4BU05P06F07Question(q).ok,true);assert.equal(validateG4BU05P06F07Answer(q,q.answerValue).ok,true);assert.equal(q.chartData.kind,"bar_chart_data");assert.ok(q.chartData.scaleStep>1);assert.equal(q.metadata.chartConstructionUsed,false);assert.equal(q.metadata.multiCategoryComparisonUsed,false);assert.equal(q.metadata.missingValueTotalUsed,false);assert.equal(q.metadata.q008OrLaterTouched,false);}});
test("W6 Q007 validator fails closed on wrong answers, chart mutation and future-KP leakage",()=>{const q=buildG4BU05P06F07Question({variant:17,patternSpecId:SPECS[0]});assert.equal(validateG4BU05P06F07Question(q).ok,true);assert.equal(validateG4BU05P06F07Answer(q,q.answerValue+1).ok,false);assert.equal(validateG4BU05P06F07Question({...q,chartData:{...q.chartData,scaleStep:q.chartData.scaleStep+1}}).ok,false);assert.equal(validateG4BU05P06F07Question({...q,metadata:{...q.metadata,chartConstructionUsed:true}}).ok,false);assert.equal(validateG4BU05P06F07Question({...q,metadata:{...q.metadata,multiCategoryComparisonUsed:true}}).ok,false);assert.equal(validateG4BU05P06F07Question({...q,metadata:{...q.metadata,missingValueTotalUsed:true}}).ok,false);});
test("W6 Q007 shared browser path renders source-backed bar charts and preserves Q006 generator reachability",()=>{for(const kp of TARGETS){const p=buildBatchABrowserPlan(request(kp,{questionCount:6}));assert.deepEqual(p.selectedKnowledgePointIds,[kp]);assert.equal(p.questionCountMax,240);assert.equal(p.sourceUnit.grade,4);assert.equal(p.sourceUnit.semester,"lower");const g=generateBatchABrowserQuestions(request(kp,{questionCount:6}));assert.equal(g.ok,true,g.errors.join("\n"));assert.equal(g.questions.length,6);assert.ok(g.questions.every(q=>q.knowledgePointId===kp&&q.chartData?.kind==="bar_chart_data"));const w=buildBatchABrowserWorksheetDocument(request(kp,{questionCount:6,includeAnswerKey:true,printLayout:{columns:2,rowsPerPage:2,showAnswerKeyPage:true}}));assert.equal(w.ok,true,w.errors.join("\n"));assert.equal(w.worksheetDocument.questionCount,6);assert.equal(w.worksheetDocument.answerKeyItems.length,6);assert.equal(w.worksheetDocument.metadata.q008OrLaterTouched,false);const html=renderWorksheetDocumentToHtml(w.worksheetDocument,{stylesheetHref:"",debugDataAttributes:false});assert.equal((html.match(/class="worksheet-bar-chart"/g)??[]).length,12);assert.ok(html.includes('data-representation="bar-chart"'));assert.ok(html.includes('data-scale-step="'));assert.equal(html.includes("kp_g4b_u05_"),false);assert.equal(html.includes("ps_g4b_u05_"),false);}const q6=generateBatchABrowserQuestions({sourceId:"g4a_u07_4a07",selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:["kp_g4a_u07_input_output_table_rule"],questionMode:"numeric",questionCount:4,generationSeed:"q6-preserve"});assert.equal(q6.ok,true,q6.errors.join("\n"));assert.ok(q6.questions.every(x=>x.knowledgePointId==="kp_g4a_u07_input_output_table_rule"&&x.tableData?.kind==="tabular_pattern_table"));const mixed=generateBatchABrowserQuestions({sourceId:SRC,selectionMode:"mixedKnowledgePointsSameUnit",selectedKnowledgePointIds:[...TARGETS],questionMode:"numeric",questionCount:4,generationSeed:"mixed-not-admitted"});assert.equal(mixed.ok,false);});
test("W6 Q007 validation contract stays SHARED_RUNTIME_BOUNDED",()=>{assert.equal(impact.expectedDerivedGate,"SHARED_RUNTIME_BOUNDED");assert.equal(impact.changeImpact.affectedRoutes,"BOUNDED");assert.equal(impact.scopeGuards.sameUnitMixedImplementation,false);assert.equal(validation.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.deepEqual(validation.lanes.SHARED_RUNTIME_BOUNDED.map(x=>x.gateId),["GLOBAL_CONTRACTS","TARGETED_ROUTE_REPLAY"]);assert.equal(JSON.stringify(validation).includes("FULL_REPOSITORY"),false);assert.equal(JSON.stringify(validation).includes("GLOBAL_BROWSER_REPLAY"),false);});
