import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {auditG6AU06P08F15Projection,G6A_U06_P08F15_FORMAL_MAPPING as MAP,G6A_U06_P08F15_KP_ID as KP,G6A_U06_P08F15_PATTERN_GROUP as GROUP,G6A_U06_P08F15_PATTERN_SPECS as SPECS,G6A_U06_P08F15_PRIOR_KP_IDS as PRIOR,G6A_U06_P08F15_FUTURE_KP_IDS as FUTURE,G6A_U06_P08F15_SOURCE_ID as SRC,G6A_U06_P08F15_SPEC_IDS as SPEC_IDS} from "../../site/modules/curriculum/registry/g6a-u06-sector-arc-length-selector-projection-p08f15.js";
import {generateG6AU06P08F15Questions,validateG6AU06P08F15Question,validateG6AU06P08F15Answer} from "../../site/modules/curriculum/batch-a/g6a-u06-sector-arc-length-runtime-p08f15.js";
import {requestsP08F15,buildBatchABrowserPlan} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p08f15.js";
import {buildBatchABrowserWorksheetDocument as buildQ015} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p08f15-extension.js";
import {buildBatchABrowserWorksheetDocument as buildCurrent} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f60-extension.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";
const read=p=>JSON.parse(readFileSync(new URL("../../"+p,import.meta.url),"utf8"));
const implementation=read("data/curriculum/full-product/p08f/q015-g6a-u06-sector-arc-length-implementation.json");
const preflight=read("data/curriculum/full-product/p08f/q015-g6a-u06-sector-arc-length-source-authority-preflight.json");
const impact=read("data/project/change-impact/P08F_W8_Q015.impact.json");
const plan=read("data/project/validation-plans/P08F_W8_Q015.validation.json");
const req=(count=16)=>({sourceId:SRC,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[KP],selectedPatternGroupIds:[GROUP.patternGroupId],patternSpecIds:SPEC_IDS,questionMode:"diagram",requestedQuestionType:"diagram",questionCount:count,generationSeed:"p08f15-test",includeAnswerKey:true,printLayout:{columns:2,rowsPerPage:3,showAnswerKeyPage:true}});
const occ=(s,t)=>s.split(t).length-1;

test("Q015 materializes exact preflight mapping and four sector-arc PatternSpecs",()=>{assert.equal(preflight.status,"PASS_SOURCE_AUTHORITY_PREFLIGHT");assert.equal(implementation.preflight.mergeSha,"70386ab697b5572ab05c24f16dc956206b7fbf8c");assert.equal(implementation.status,"IMPLEMENTATION_MATERIALIZED_AWAITING_FOCUSED_CI");assert.equal(implementation.queueAuthority.queuePosition,15);assert.deepEqual(implementation.queueAuthority.knowledgePointIds,[KP]);assert.equal(MAP.r04MappingId,"r04map_g6a_u06_sector_arc_length");assert.equal(MAP.semanticCore,"SECTOR_ARC_LENGTH_EQUALS_CIRCUMFERENCE_TIMES_CENTRAL_ANGLE_OVER_360");assert.equal(MAP.arcLengthFormula,"ARC_LENGTH = CIRCUMFERENCE * CENTRAL_ANGLE / 360");assert.equal(MAP.fullCircleInvariantDegrees,360);assert.deepEqual(MAP.appliedRuntimeModifierIds,["mod_integer_division"]);assert.equal(auditG6AU06P08F15Projection().ok,true);assert.equal(SPECS.length,4);assert.equal(new Set(SPEC_IDS).size,4);assert.equal(requestsP08F15(req()),true);assert.equal(requestsP08F15({...req(),selectionMode:"sourceUnit"}),false);assert.equal(requestsP08F15({...req(),selectedKnowledgePointIds:[KP,PRIOR[0]]}),false);const p=buildBatchABrowserPlan(req());assert.equal(p.questionCountMax,240);assert.equal(p.genericFallback,false);});

test("Q015 every PatternSpec yields 240 deterministic distinct valid variants",()=>{for(const id of SPEC_IDS){const a=generateG6AU06P08F15Questions({knowledgePointId:KP,patternSpecIds:[id],questionCount:240,generationSeed:id}),b=generateG6AU06P08F15Questions({knowledgePointId:KP,patternSpecIds:[id],questionCount:240,generationSeed:id});assert.equal(a.ok,true,id+":"+a.errors.join("\n"));assert.deepEqual(a.questions,b.questions);assert.equal(new Set(a.questions.map(q=>q.questionSignature)).size,240);assert.ok(a.questions.every(q=>validateG6AU06P08F15Question(q).ok));const t=JSON.parse(JSON.stringify(a.questions[0]));t.answerText="999 公分";assert.equal(validateG6AU06P08F15Question(t).ok,false);assert.equal(validateG6AU06P08F15Answer(a.questions[0],a.questions[0].answerText).ok,true);}});

test("Q015 sector arc formula consumes circumference and sector-fraction prerequisites without reownership",()=>{const r=generateG6AU06P08F15Questions({knowledgePointId:KP,questionCount:240,generationSeed:"q015-semantics"});assert.equal(r.ok,true,r.errors.join("\n"));let radius=0,diameter=0,known=0;for(const q of r.questions){const p=q.patternRepresentation;assert.equal(p.fullCircleDegrees,360);assert.ok(p.centralAngleDeg>0&&p.centralAngleDeg<=180);assert.ok(p.circumference>0);assert.ok(p.arcLength>0&&p.arcLength<=p.circumference);assert.equal(p.arcToCircumferenceRatioMatchesAngleRatio,true);assert.equal(q.geometryDiagram.markerMode,"ARC_HIGHLIGHT");assert.equal(q.metadata.q004PiCircumferenceRelationTeachingReowned,false);assert.equal(q.metadata.q006CircleCircumferenceFormulaTeachingReowned,false);assert.equal(q.metadata.q010SemicirclePerimeterTeachingReowned,false);assert.equal(q.metadata.w8CentralAngleMeasurementTeachingReowned,false);assert.equal(q.metadata.w8SectorFractionOfCircleTeachingReowned,false);assert.equal(q.metadata.compositeArcPerimeterReowned,false);if(p.inputMode==="RADIUS")radius++;else if(p.inputMode==="DIAMETER")diameter++;else known++;}assert.ok(radius>0&&diameter>0&&known>0);});

test("Q015 worksheet current bridge selector answer and print representation stay learner-facing",async()=>{const r=buildQ015(req(16));assert.equal(r.ok,true,r.errors.join("\n"));assert.equal(r.worksheetDocument.questionCount,16);assert.equal(r.worksheetDocument.answerKeyItems.length,16);const html=renderWorksheetDocumentToHtml(r.worksheetDocument,{stylesheetHref:"",title:r.worksheetDocument.title,debugDataAttributes:false});assert.equal(occ(html,'data-representation="sector-elements-diagram"'),32);assert.equal(html.includes("kp_g6a_u06_"),false);assert.equal(html.includes("ps_g6a_u06_"),false);const current=buildCurrent(req(8));assert.equal(current.ok,true,current.errors.join("\n"));assert.equal(current.p08f15Implemented,true);assert.equal(current.worksheetDocument.metadata.knowledgePointId,KP);globalThis.document={};try{const selector=await import("../../site/modules/curriculum/registry/batch-a-selector-p04f33-extension.js?p08f15="+Date.now()),binding=await import("../../site/modules/curriculum/public/public-ui-capability-binding-p04f33.js?p08f15="+Date.now());for(const id of [...PRIOR,KP])assert.equal(selector.getVisibleBatchAKnowledgePoint(id)?.sourceId,SRC,id);for(const id of FUTURE)assert.equal(selector.getVisibleBatchAKnowledgePoint(id),null,id);const b=binding.resolvePublicUiCapabilityBinding(req());assert.equal(b.sectorArcLengthRequired,true);assert.equal(b.arcLengthFormula,"ARC_LENGTH = CIRCUMFERENCE * CENTRAL_ANGLE / 360");assert.deepEqual(b.appliedRuntimeModifierIds,["mod_integer_division"]);}finally{delete globalThis.document;}});

test("Q015 bounded validation and ownership guards remain closed",()=>{assert.equal(impact.expectedDerivedGate,"SHARED_RUNTIME_BOUNDED");assert.equal(impact.changeImpact.affectedRoutes,"BOUNDED");assert.equal(impact.changeImpact.legalRouteSemanticsChanged,false);assert.equal(plan.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.equal(plan.lanes.SHARED_RUNTIME_BOUNDED[0].kind,"NODE_TEST");assert.equal(plan.lanes.SHARED_RUNTIME_BOUNDED[1].runtime,"PLAYWRIGHT_CHROMIUM");assert.deepEqual(plan.forbidden,["FULL_NODE_REGRESSION","GLOBAL_BROWSER_REPLAY"]);for(const v of Object.values(implementation.ownershipGuard))assert.equal(v,false);});
