import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {auditG4AU03P08F01Projection,G4A_U03_P08F01_KP_ID as KP,G4A_U03_P08F01_PROTECTED_FUTURE_KP_IDS as PROTECTED,G4A_U03_P08F01_SOURCE_ID as SRC,G4A_U03_P08F01_SPEC_IDS as SPECS} from "../../site/modules/curriculum/registry/g4a-u03-protractor-angle-measurement-selector-projection-p08f01.js";
import {auditP08F01PublicSelectorComposition,getVisibleBatchAKnowledgePoint,listBatchAKnowledgePointAvailabilityBySource,listVisibleBatchAKnowledgePoints,resolveVisiblePatternSpecIdsForKnowledgePoint} from "../../site/modules/curriculum/registry/batch-a-selector-p08f01-extension.js";
import {auditPublicUiCapabilityBinding,resolvePublicUiCapabilityBinding} from "../../site/modules/curriculum/public/public-ui-capability-binding-p08f01.js";
import {buildG4AU03P08F01Question as missing} from "../../site/modules/curriculum/batch-a/g4a-u03-protractor-angle-measurement-runtime-p08f01.js";
import {generateG4AU03P08F01Questions,validateG4AU03P08F01Answer,validateG4AU03P08F01Question} from "../../site/modules/curriculum/batch-a/g4a-u03-protractor-angle-measurement-runtime-p08f01.js";
import {buildBatchABrowserPlan,generateBatchABrowserQuestions} from "../../site/modules/curriculum/batch-a/batch-a-browser-generator-p05f60.js";
import {buildBatchABrowserWorksheetDocument} from "../../site/modules/curriculum/batch-a/batch-a-browser-worksheet-p05f60-extension.js";
import {renderWorksheetDocumentToHtml} from "../../site/modules/renderer/html-renderer.js";
import {getBatchASourceUnit,listBatchASourceUnits} from "../../site/modules/curriculum/batch-a/source-units.js";
const read=p=>JSON.parse(readFileSync(new URL("../../"+p,import.meta.url),"utf8"));
const implementation=read("data/curriculum/full-product/p08f/q001-g4a-u03-protractor-angle-measurement-implementation.json");
const impact=read("data/project/change-impact/P08F_W8_Q001.impact.json");
const validation=read("data/project/validation-plans/P08F_W8_Q001.validation.json");
const request=(extra={})=>({sourceId:SRC,selectionMode:"singleKnowledgePoint",selectedKnowledgePointIds:[KP],questionMode:"diagram",questionCount:20,generationSeed:"p08f01-focused",...extra});

test("W8 Q001 materializes one protractor KP with three PatternSpecs",()=>{assert.equal(implementation.status,"IMPLEMENTATION_MATERIALIZED_AWAITING_FOCUSED_CI");assert.equal(implementation.queueAuthority.queuePosition,1);assert.deepEqual(implementation.queueAuthority.knowledgePointIds,[KP]);assert.deepEqual(implementation.productContract.patternSpecIds,SPECS);assert.deepEqual(auditG4AU03P08F01Projection(),{ok:true,errors:[],counts:{knowledgePoints:1,patternGroups:1,patternSpecs:3,formalMappings:1}});});

test("W8 Q001 selector exposes only protractor measurement and protects later G4A-U03 semantics",()=>{const a=auditP08F01PublicSelectorComposition();assert.equal(a.ok,true,a.errors.join("\n"));const s=listBatchAKnowledgePointAvailabilityBySource(SRC);const visible=listVisibleBatchAKnowledgePoints().filter(x=>x.sourceId===SRC).map(x=>x.knowledgePointId);assert.deepEqual(visible,[KP]);assert.ok(getVisibleBatchAKnowledgePoint(KP));assert.deepEqual(resolveVisiblePatternSpecIdsForKnowledgePoint(KP,"diagram"),SPECS);for(const id of PROTECTED){assert.equal(visible.includes(id),false);assert.ok(s.hiddenPendingKnowledgePointIds.includes(id));assert.ok(s.notSelectableKnowledgePointIds.includes(id));}assert.equal(s.sameUnitMixedAllowed,false);assert.equal(s.w8FrozenQueueComplete,false);});

test("W8 Q001 binding locks geometry property plus scale instrument semantics",()=>{const a=auditPublicUiCapabilityBinding();assert.equal(a.ok,true,a.errors.join("\n"));const b=resolvePublicUiCapabilityBinding(request());assert.equal(b.blocked,false);assert.equal(b.questionType,"diagram");assert.equal(b.protractorCenterAlignmentRequired,true);assert.equal(b.zeroDegreeBaselineAlignmentRequired,true);assert.equal(b.correctScaleDirectionRequired,true);assert.equal(b.appliedRuntimeModifierIds.join("|"),"mod_scale_instrument");assert.equal(b.frozenRuntimeProfile,"profile_geometry_property");assert.equal(b.angleCompositionReownershipAllowed,false);assert.equal(b.rotationClockReownershipAllowed,false);});

for(const patternSpecId of SPECS)test(`W8 Q001 ${patternSpecId} has 240 deterministic unique validated variants`,()=>{const a=generateG4AU03P08F01Questions({questionCount:240,patternSpecIds:[patternSpecId],generationSeed:"stable"}),b=generateG4AU03P08F01Questions({questionCount:240,patternSpecIds:[patternSpecId],generationSeed:"stable"});assert.equal(a.ok,true,a.errors.join("\n"));assert.deepEqual(a.questions,b.questions);assert.equal(new Set(a.questions.map(q=>q.questionSignature)).size,240);for(const q of a.questions){assert.equal(validateG4AU03P08F01Question(q).ok,true);assert.equal(validateG4AU03P08F01Answer(q,q.answerText).ok,true);assert.equal(q.metadata.q002OrLaterTouched,false);}});

test("W8 Q001 validator fails closed for wrong answers and future-scope leakage",()=>{const q=generateG4AU03P08F01Questions({questionCount:1,patternSpecIds:[SPECS[0]],generationSeed:"wrong-answer"}).questions[0];assert.equal(validateG4AU03P08F01Answer(q,q.answerValue+10).ok,false);assert.equal(validateG4AU03P08F01Question({...q,metadata:{...q.metadata,angleCompositionReowned:true}}).ok,false);assert.equal(validateG4AU03P08F01Question({...q,geometryDiagram:{...q.geometryDiagram,centerAligned:false,centerOffsetPx:0}}).ok,false);});

test("W8 Q001 aggregate browser generator and worksheet route through public path",()=>{assert.equal(getBatchASourceUnit(SRC)?.title,"角度");assert.ok(listBatchASourceUnits({includeW8Slice001:true}).some(x=>x.sourceId===SRC));const p=buildBatchABrowserPlan(request({questionCount:9}));assert.deepEqual(p.selectedKnowledgePointIds,[KP]);assert.equal(p.questionCountMax,240);assert.equal(p.questionMode,"diagram");const g=generateBatchABrowserQuestions(request({questionCount:9}));assert.equal(g.ok,true,g.errors.join("\n"));assert.equal(g.questions.length,9);assert.ok(g.questions.every(q=>q.knowledgePointId===KP));const w=buildBatchABrowserWorksheetDocument(request({questionCount:9,includeAnswerKey:true,printLayout:{columns:2,rowsPerPage:3,showAnswerKeyPage:true}}));assert.equal(w.ok,true,w.errors.join("\n"));assert.equal(w.worksheetDocument.questionCount,9);assert.equal(w.worksheetDocument.answerKeyItems.length,9);assert.ok(w.worksheetDocument.questionDisplayModels.every(x=>x.geometryDiagram?.kind==="protractor_angle_measurement_diagram"));const html=renderWorksheetDocumentToHtml(w.worksheetDocument,{stylesheetHref:""});assert.match(html,/worksheet-protractor-angle-measurement-diagram/);assert.match(html,/data-representation="protractor-angle-measurement-diagram"/);assert.doesNotMatch(html,/kp_protractor_angle_measurement|P08F01/);});

test("W8 Q001 validation contract stays SHARED_RUNTIME_BOUNDED",()=>{assert.equal(impact.expectedDerivedGate,"SHARED_RUNTIME_BOUNDED");assert.equal(impact.changeImpact.affectedRoutes,"BOUNDED");assert.equal(validation.policyId,"UNIT_INCREMENTAL_VALIDATION_V1");assert.deepEqual(validation.lanes.SHARED_RUNTIME_BOUNDED.map(x=>x.gateId),["GLOBAL_CONTRACTS","TARGETED_ROUTE_REPLAY"]);assert.equal(JSON.stringify(validation).includes("FULL_REPOSITORY"),false);assert.equal(JSON.stringify(validation).includes("GLOBAL_BROWSER_REPLAY"),false);});
