import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { adaptGlobalPublicSourceUnitPlan, validateGlobalPublicSourceUnitAdapters } from "../../site/modules/curriculum/batch-a/global-public-source-unit-adapter.js";
import { G3A_U01_POSTG_TASK_ID, resolvePostGoldenSourceUnitAdapterDescriptor } from "../../site/modules/curriculum/batch-a/global-public-source-unit-adapter-registry.js";
import { generateBatchABrowserQuestions } from "../../site/modules/curriculum/batch-a/batch-a-browser-question-router.js";
import { validateBatchABrowserQuestions } from "../../site/modules/curriculum/batch-a/batch-a-browser-validator.js";
import { getVisiblePatternGroupsForKnowledgePoint, listVisibleBatchAKnowledgePoints } from "../../site/modules/curriculum/registry/batch-a-selector-extension.js";
const SOURCE_ID="g3a_u01_3a01";
const readJson=async p=>JSON.parse(await readFile(new URL(p,import.meta.url),"utf8"));
function plan(){const a=adaptGlobalPublicSourceUnitPlan({sourceId:SOURCE_ID,selectionMode:"sourceUnit",questionCount:40,ordering:"shuffleAcrossPatterns",includeAnswerKey:true,generationSeed:"postg-mig-a01-g3a-u01",goldenContractId:"G5AU08_GOLDEN_V1",goldenContractVersion:"1.0.0",goldenRuntimeMode:"shadow",postGoldenMigrationTaskId:G3A_U01_POSTG_TASK_ID});assert.equal(a.blocked,false,JSON.stringify(a.errors));return a.plan;}
test("A01 authoritative registry closes all 8 KP and 20 bindings",async()=>{const r=await readJson("../../data/curriculum/knowledge/units/g3a_u01_3a01.knowledge-operation.json");const visible=listVisibleBatchAKnowledgePoints().filter(x=>x.sourceId===SOURCE_ID);const specs=new Set(visible.flatMap(x=>getVisiblePatternGroupsForKnowledgePoint(x.knowledgePointId).flatMap(g=>g.patternSpecIds??[])));assert.equal(r.conformanceState,"GOLDEN_CONFORMANT");assert.equal(r.knowledgeRegistryState,"VALIDATED_COMPLETE");assert.equal(r.review.status,"PASS");assert.equal(r.knowledgePoints.length,8);assert.equal(r.existingQuestionBindings.length,20);assert.deepEqual(new Set(r.existingQuestionBindings.map(x=>x.questionId)),specs);});
test("A01 shared runtime still generates and validates all PatternSpecs",()=>{const g=generateBatchABrowserQuestions(plan());assert.equal(g.ok,true,JSON.stringify(g.errors));assert.equal(g.questions.length,40);assert.equal(new Set(g.questions.map(x=>x.patternSpecId)).size,20);const v=validateBatchABrowserQuestions(g.questions);assert.equal(v.ok,true,JSON.stringify(v.errors));});
test("A01 descriptor and adapter remain bounded",()=>{const d=resolvePostGoldenSourceUnitAdapterDescriptor(SOURCE_ID);assert.equal(d.expectedCounts.knowledgePoints,8);assert.equal(d.expectedCounts.patternGroups,8);assert.equal(d.expectedCounts.patternSpecs,20);const a=validateGlobalPublicSourceUnitAdapters();assert.equal(a.ok,true,JSON.stringify(a.errors));});
test("A01 remains closed while later queue items advance",async()=>{const [p,c,r,m]=await Promise.all([readJson("../../data/project/programs/POST_GOLDEN_UNIT_CONFORMANCE_MIGRATION_V1.json"),readJson("../../data/curriculum/golden/POST_GOLDEN_UNIT_CONFORMANCE_MIGRATION_V1.controller.json"),readJson("../../data/curriculum/golden/G5AU08_GOLDEN_V1.unit-conformance.json"),readJson("../../data/curriculum/knowledge/master/POST_GOLDEN_UNIT_CONFORMANCE_MIGRATION_V1.master-index.json")]);assert.ok(p.completedCount>=2);assert.ok(c.queue.completeSourceIds.includes(SOURCE_ID));const a=r.rows.find(x=>x.sourceId===SOURCE_ID);assert.equal(a.conformanceStatus,"GOLDEN_CONFORMANT");assert.equal(a.goldenProductionEligible,true);assert.ok(m.statusSummary.unitJsonExistsCount>=4);assert.ok(m.statusSummary.knowledgeRegistryCompleteCount>=4);});
test("A01 backfills three Golden anchors without changing their state",async()=>{const r=await readJson("../../data/curriculum/golden/G5AU08_GOLDEN_V1.unit-conformance.json");for(const sid of ["g3b_u04_3b04","g5a_u08_5a08","g5a_u02_5a02"]){const u=await readJson(`../../data/curriculum/knowledge/units/${sid}.knowledge-operation.json`);const row=r.rows.find(x=>x.sourceId===sid);assert.equal(u.knowledgeRegistryState,"VALIDATED_COMPLETE");assert.equal(u.review.status,"PASS");assert.equal(row.conformanceStatus,"GOLDEN_CONFORMANT");assert.equal(row.goldenProductionEligible,true);}});
