import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { adaptGlobalPublicSourceUnitPlan, validateGlobalPublicSourceUnitAdapters } from "../../site/modules/curriculum/batch-a/global-public-source-unit-adapter.js";
import { G3B_U01_POSTG_TASK_ID, resolvePostGoldenSourceUnitAdapterDescriptor, validatePostGoldenSourceUnitAdapterRegistry } from "../../site/modules/curriculum/batch-a/global-public-source-unit-adapter-registry.js";
import { generateBatchABrowserQuestions } from "../../site/modules/curriculum/batch-a/batch-a-browser-question-router.js";
import { validateBatchABrowserQuestions } from "../../site/modules/curriculum/batch-a/batch-a-browser-validator.js";
import { getVisiblePatternGroupsForKnowledgePoint, listVisibleBatchAKnowledgePoints } from "../../site/modules/curriculum/registry/batch-a-selector-extension.js";
const SOURCE_ID="g3b_u01_3b01",NEXT_SOURCE_ID="g3b_u08_3b08",NEXT_TASK_ID="POSTG-MIG-A06_G3B_U08_GoldenConformanceAndKnowledgeOperationMigration";
const KP=new Set(["kp_g3b_u01_2digit_division_place_value_cases","kp_g3b_u01_3digit_by_1digit_regroup_hundreds","kp_g3b_u01_3digit_division_place_value_cases","kp_g3b_u01_quotient_zero_cases","kp_g3b_u01_division_with_remainder","kp_g3b_u01_wp_partitive_division","kp_g3b_u01_wp_quotative_division","kp_g3b_u01_wp_division_with_remainder","kp_g3b_u01_wp_remainder_interpretation","kp_g3b_u01_wp_two_step_division"]);
const PS=new Set(["ps_g3b_u01_2digit_by_1digit_regroup_tens","ps_g3b_u01_2digit_leading_digit_insufficient","ps_g3b_u01_2digit_ones_quotient_zero","ps_g3b_u01_2digit_leading_digit_exact","ps_g3b_u01_3digit_by_1digit_regroup_hundreds","ps_g3b_u01_3digit_hundreds_insufficient","ps_g3b_u01_3digit_tens_quotient_zero","ps_g3b_u01_3digit_ones_quotient_zero","ps_g3b_u01_3digit_hundreds_exact","ps_g3b_u01_2digit_division_with_remainder","ps_g3b_u01_3digit_division_with_remainder","ps_g3b_u01_wp_partitive_equal_sharing","ps_g3b_u01_wp_partitive_unit_rate","ps_g3b_u01_wp_quotative_packaging_exact","ps_g3b_u01_wp_quotative_grouping_exact","ps_g3b_u01_wp_remainder_packaging_leftover","ps_g3b_u01_wp_remainder_calendar_weeks_days","ps_g3b_u01_wp_remainder_floor_max_groups","ps_g3b_u01_wp_remainder_ceil_min_containers","ps_g3b_u01_wp_two_step_divide_then_add","ps_g3b_u01_wp_two_step_add_then_divide","ps_g3b_u01_wp_two_step_divide_then_subtract","ps_g3b_u01_wp_two_step_subtract_then_divide"]);
const readJson=async p=>JSON.parse(await readFile(new URL(p,import.meta.url),"utf8"));
function plan(overrides={}){return{sourceId:SOURCE_ID,selectionMode:"sourceUnit",questionCount:46,ordering:"shuffleAcrossPatterns",includeAnswerKey:true,generationSeed:"postg-mig-a05-closeout",goldenContractId:"G5AU08_GOLDEN_V1",goldenContractVersion:"1.0.0",goldenRuntimeMode:"shadow",postGoldenMigrationTaskId:G3B_U01_POSTG_TASK_ID,...overrides};}
function adapted(){const r=adaptGlobalPublicSourceUnitPlan(plan());assert.equal(r.blocked,false,JSON.stringify(r.errors));assert.equal(r.applied,true);return r.plan;}
test("A05 authoritative registry closes ten KP and twenty-three bindings",async()=>{const r=await readJson("../../data/curriculum/knowledge/units/g3b_u01_3b01.knowledge-operation.json");assert.equal(r.conformanceState,"GOLDEN_CONFORMANT");assert.equal(r.knowledgeRegistryState,"VALIDATED_COMPLETE");assert.equal(r.review.status,"PASS");assert.equal(r.knowledgePoints.length,10);assert.equal(r.existingQuestionBindings.length,23);assert.deepEqual(new Set(r.knowledgePoints.map(x=>x.knowledgePointId)),KP);assert.deepEqual(new Set(r.existingQuestionBindings.map(x=>x.questionId)),PS);assert.equal(r.coverage.numeric,"COMPLETE");assert.equal(r.coverage.application,"COMPLETE");});
test("A05 descriptor resolves ten KP, ten groups and twenty-three specs",()=>{const d=resolvePostGoldenSourceUnitAdapterDescriptor(SOURCE_ID);assert.deepEqual(d.expectedCounts,{knowledgePoints:10,patternGroups:10,patternSpecs:23});assert.deepEqual(new Set(d.knowledgePointIds),KP);assert.equal(d.patternGroupIds.length,10);assert.deepEqual(new Set(d.patternSpecIds),PS);assert.equal(validatePostGoldenSourceUnitAdapterRegistry().ok,true);assert.equal(validateGlobalPublicSourceUnitAdapters().ok,true);});
test("A05 shared runtime generates and validates every unique PatternSpec",()=>{const g=generateBatchABrowserQuestions(adapted());assert.equal(g.ok,true,JSON.stringify(g.errors));assert.equal(g.questions.length,46);assert.deepEqual(new Set(g.questions.map(x=>x.patternSpecId)),PS);const v=validateBatchABrowserQuestions(g.questions);assert.equal(v.ok,true,JSON.stringify(v.errors));});
test("A05 adapter remains fail-closed without exact task authorization",()=>{for(const id of [undefined,"POSTG-MIG-A06_WRONG_TASK"]){const r=adaptGlobalPublicSourceUnitPlan(plan({postGoldenMigrationTaskId:id}));assert.equal(r.applied,false);assert.equal(r.blocked,true);assert.ok(r.errors.includes("GS05_GOLDEN_UNIT_NOT_REGISTERED"));}});
test("A05 selector has one canonical lineage per question identity",()=>{const visible=listVisibleBatchAKnowledgePoints().filter(x=>x.sourceId===SOURCE_ID);assert.deepEqual(new Set(visible.map(x=>x.knowledgePointId)),KP);const refs=visible.flatMap(x=>getVisiblePatternGroupsForKnowledgePoint(x.knowledgePointId).flatMap(g=>g.patternSpecIds??[]));assert.equal(refs.length,23);assert.deepEqual(new Set(refs),PS);});
test("A05 preserves division semantic distinctions",async()=>{const r=await readJson("../../data/curriculum/knowledge/units/g3b_u01_3b01.knowledge-operation.json");const b=Object.fromEntries(r.existingQuestionBindings.map(x=>[x.questionId,x]));assert.notEqual(b.ps_g3b_u01_wp_partitive_equal_sharing.operationModelId,b.ps_g3b_u01_wp_quotative_packaging_exact.operationModelId);assert.notEqual(b.ps_g3b_u01_wp_remainder_packaging_leftover.operationModelId,b.ps_g3b_u01_wp_remainder_floor_max_groups.operationModelId);assert.equal(b.ps_g3b_u01_2digit_ones_quotient_zero.knowledgePointId,"kp_g3b_u01_quotient_zero_cases");});
test("A05 closeout advances exactly one queue item and reduces D9 to D8",async()=>{const [program,controller,registry,master]=await Promise.all([readJson("../../data/project/programs/POST_GOLDEN_UNIT_CONFORMANCE_MIGRATION_V1.json"),readJson("../../data/curriculum/golden/POST_GOLDEN_UNIT_CONFORMANCE_MIGRATION_V1.controller.json"),readJson("../../data/curriculum/golden/G5AU08_GOLDEN_V1.unit-conformance.json"),readJson("../../data/curriculum/knowledge/master/POST_GOLDEN_UNIT_CONFORMANCE_MIGRATION_V1.master-index.json")]);assert.equal(program.lastCompletedTask,G3B_U01_POSTG_TASK_ID);assert.equal(program.activeTask,NEXT_TASK_ID);assert.equal(program.completedCount,6);assert.equal(program.remainingCount,8);assert.equal(program.goalDistance,"D8_POST_GOLDEN_MIGRATION_G3BU01_CONFORMANT_G3BU08_ACTIVE");assert.equal(controller.queue.activeSourceId,NEXT_SOURCE_ID);assert.ok(controller.queue.completeSourceIds.includes(SOURCE_ID));const closed=registry.rows.find(x=>x.sourceId===SOURCE_ID),next=registry.rows.find(x=>x.sourceId===NEXT_SOURCE_ID);assert.equal(closed.conformanceStatus,"GOLDEN_CONFORMANT");assert.equal(closed.queueState,"COMPLETE");assert.equal(closed.goldenProductionEligible,true);assert.equal(next.conformanceStatus,"IN_PROGRESS_GOLDEN_NATIVE");assert.equal(next.queueState,"ACTIVE");assert.equal(master.statusSummary.unitJsonExistsCount,8);assert.equal(master.statusSummary.knowledgeRegistryCompleteCount,8);const row=master.rows.find(x=>x.sourceId===SOURCE_ID);assert.equal(row.knowledgePointCount,10);assert.equal(row.operationModelCount,10);assert.equal(row.existingQuestionBindingCount,23);assert.equal(row.schemaValidationStatus,"PASS");});
