import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { adaptGlobalPublicSourceUnitPlan, validateGlobalPublicSourceUnitAdapters } from "../../site/modules/curriculum/batch-a/global-public-source-unit-adapter.js";
import { G3A_U06_POSTG_TASK_ID, resolvePostGoldenSourceUnitAdapterDescriptor, validatePostGoldenSourceUnitAdapterRegistry } from "../../site/modules/curriculum/batch-a/global-public-source-unit-adapter-registry.js";
import { generateBatchABrowserQuestions } from "../../site/modules/curriculum/batch-a/batch-a-browser-question-router.js";
import { validateBatchABrowserQuestions } from "../../site/modules/curriculum/batch-a/batch-a-browser-validator.js";
import { getVisiblePatternGroupsForKnowledgePoint, listVisibleBatchAKnowledgePoints } from "../../site/modules/curriculum/registry/batch-a-selector-extension.js";

const SOURCE_ID="g3a_u06_3a06";
const NEXT_SOURCE_ID="g3b_u01_3b01";
const NEXT_TASK_ID="POSTG-MIG-A05_G3B_U01_GoldenConformanceAndKnowledgeOperationMigration";
const EXPECTED_KP_IDS=new Set(["kp_g3a_u06_exact_division_check","kp_g3a_u06_divisibility_exact_check","kp_g3a_u06_division_with_remainder","kp_g3a_u06_quotative_division_packaging","kp_g3a_u06_partitive_division_equal_sharing","kp_g3a_u06_parity_range_missing_digit"]);
const EXPECTED_SPEC_IDS=new Set(["ps_g3a_u06_exact_division_check","ps_g3a_u06_divisibility_exact_check","ps_g3a_u06_division_with_remainder","ps_g3a_u06_quotative_division_packaging","ps_g3a_u06_partitive_division_equal_sharing","ps_g3a_u06_parity_range_missing_digit"]);
const readJson=async p=>JSON.parse(await readFile(new URL(p,import.meta.url),"utf8"));
function closeoutPlan(overrides={}){return{sourceId:SOURCE_ID,selectionMode:"sourceUnit",questionCount:42,ordering:"shuffleAcrossPatterns",includeAnswerKey:true,generationSeed:"postg-mig-a04-g3a-u06-closeout",goldenContractId:"G5AU08_GOLDEN_V1",goldenContractVersion:"1.0.0",goldenRuntimeMode:"shadow",postGoldenMigrationTaskId:G3A_U06_POSTG_TASK_ID,...overrides};}
function adaptedPlan(overrides={}){const adapted=adaptGlobalPublicSourceUnitPlan(closeoutPlan(overrides));assert.equal(adapted.blocked,false,JSON.stringify(adapted.errors));assert.equal(adapted.applied,true);return adapted.plan;}

test("A04 authoritative registry closes all six effective capabilities",async()=>{const registry=await readJson("../../data/curriculum/knowledge/units/g3a_u06_3a06.knowledge-operation.json");assert.equal(registry.conformanceState,"GOLDEN_CONFORMANT");assert.equal(registry.knowledgeRegistryState,"VALIDATED_COMPLETE");assert.equal(registry.review.status,"PASS");assert.equal(registry.knowledgePoints.length,6);assert.equal(registry.existingQuestionBindings.length,6);assert.deepEqual(new Set(registry.knowledgePoints.map(row=>row.knowledgePointId)),EXPECTED_KP_IDS);assert.deepEqual(new Set(registry.existingQuestionBindings.map(row=>row.questionId)),EXPECTED_SPEC_IDS);assert.equal(registry.coverage.numeric,"COMPLETE");assert.equal(registry.coverage.application,"COMPLETE");});
test("A04 descriptor remains bounded to six KP, groups and PatternSpecs",()=>{const descriptor=resolvePostGoldenSourceUnitAdapterDescriptor(SOURCE_ID);assert.ok(descriptor);assert.deepEqual(descriptor.expectedCounts,{knowledgePoints:6,patternGroups:6,patternSpecs:6});assert.deepEqual(new Set(descriptor.knowledgePointIds),EXPECTED_KP_IDS);assert.equal(descriptor.patternGroupIds.length,6);assert.deepEqual(new Set(descriptor.patternSpecIds),EXPECTED_SPEC_IDS);assert.equal(validatePostGoldenSourceUnitAdapterRegistry().ok,true);const aggregate=validateGlobalPublicSourceUnitAdapters();assert.equal(aggregate.ok,true,JSON.stringify(aggregate.errors));});
test("A04 existing shared runtime generates and validates all six PatternSpecs",()=>{const generated=generateBatchABrowserQuestions(adaptedPlan());assert.equal(generated.ok,true,JSON.stringify(generated.errors));assert.equal(generated.questions.length,42);assert.deepEqual(new Set(generated.questions.map(row=>row.patternSpecId)),EXPECTED_SPEC_IDS);const validation=validateBatchABrowserQuestions(generated.questions);assert.equal(validation.ok,true,JSON.stringify(validation.errors));});
test("A04 adapter remains fail-closed without exact task authorization",()=>{for(const taskId of [undefined,"POSTG-MIG-A05_WRONG_TASK"]){const result=adaptGlobalPublicSourceUnitPlan(closeoutPlan({postGoldenMigrationTaskId:taskId}));assert.equal(result.applied,false);assert.equal(result.blocked,true);assert.ok(result.errors.includes("GS05_GOLDEN_UNIT_NOT_REGISTERED"));}});
test("A04 effective selector remains the exact formal projection",()=>{const visible=listVisibleBatchAKnowledgePoints().filter(row=>row.sourceId===SOURCE_ID);assert.deepEqual(new Set(visible.map(row=>row.knowledgePointId)),EXPECTED_KP_IDS);const specs=new Set(visible.flatMap(row=>getVisiblePatternGroupsForKnowledgePoint(row.knowledgePointId).flatMap(group=>group.patternSpecIds??[])));assert.deepEqual(specs,EXPECTED_SPEC_IDS);});
test("A04 preserves distinct quotative and partitive application semantics",async()=>{const registry=await readJson("../../data/curriculum/knowledge/units/g3a_u06_3a06.knowledge-operation.json");const bindings=Object.fromEntries(registry.existingQuestionBindings.map(row=>[row.questionId,row]));assert.equal(bindings.ps_g3a_u06_quotative_division_packaging.questionType,"application");assert.equal(bindings.ps_g3a_u06_partitive_division_equal_sharing.questionType,"application");assert.notEqual(bindings.ps_g3a_u06_quotative_division_packaging.operationModelId,bindings.ps_g3a_u06_partitive_division_equal_sharing.operationModelId);});
test("A04 closeout advances exactly one queue item and reduces program distance",async()=>{const [program,controller,registry,master]=await Promise.all([readJson("../../data/project/programs/POST_GOLDEN_UNIT_CONFORMANCE_MIGRATION_V1.json"),readJson("../../data/curriculum/golden/POST_GOLDEN_UNIT_CONFORMANCE_MIGRATION_V1.controller.json"),readJson("../../data/curriculum/golden/G5AU08_GOLDEN_V1.unit-conformance.json"),readJson("../../data/curriculum/knowledge/master/POST_GOLDEN_UNIT_CONFORMANCE_MIGRATION_V1.master-index.json")]);assert.equal(program.lastCompletedTask,G3A_U06_POSTG_TASK_ID);assert.equal(program.activeTask,NEXT_TASK_ID);assert.equal(program.completedCount,5);assert.equal(program.remainingCount,9);assert.equal(program.goalDistance,"D9_POST_GOLDEN_MIGRATION_G3AU06_CONFORMANT_G3BU01_ACTIVE");assert.equal(controller.queue.activeSourceId,NEXT_SOURCE_ID);assert.ok(controller.queue.completeSourceIds.includes(SOURCE_ID));const closed=registry.rows.find(row=>row.sourceId===SOURCE_ID);const next=registry.rows.find(row=>row.sourceId===NEXT_SOURCE_ID);assert.equal(closed.conformanceStatus,"GOLDEN_CONFORMANT");assert.equal(closed.queueState,"COMPLETE");assert.equal(closed.goldenProductionEligible,true);assert.equal(next.conformanceStatus,"IN_PROGRESS_GOLDEN_NATIVE");assert.equal(next.queueState,"ACTIVE");assert.equal(master.statusSummary.unitJsonExistsCount,7);assert.equal(master.statusSummary.knowledgeRegistryCompleteCount,7);const row=master.rows.find(item=>item.sourceId===SOURCE_ID);assert.equal(row.knowledgePointCount,6);assert.equal(row.operationModelCount,6);assert.equal(row.existingQuestionBindingCount,6);assert.equal(row.schemaValidationStatus,"PASS");});
