import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { adaptGlobalPublicSourceUnitPlan, validateGlobalPublicSourceUnitAdapters } from "../../site/modules/curriculum/batch-a/global-public-source-unit-adapter.js";
import { G3A_U06_POSTG_TASK_ID, resolvePostGoldenSourceUnitAdapterDescriptor, validatePostGoldenSourceUnitAdapterRegistry } from "../../site/modules/curriculum/batch-a/global-public-source-unit-adapter-registry.js";
import { generateBatchABrowserQuestions } from "../../site/modules/curriculum/batch-a/batch-a-browser-question-router.js";
import { validateBatchABrowserQuestions } from "../../site/modules/curriculum/batch-a/batch-a-browser-validator.js";
import { getVisiblePatternGroupsForKnowledgePoint, listVisibleBatchAKnowledgePoints } from "../../site/modules/curriculum/registry/batch-a-selector-extension.js";
const SOURCE_ID="g3a_u06_3a06";
const EXPECTED_KP_IDS=new Set(["kp_g3a_u06_exact_division_check","kp_g3a_u06_divisibility_exact_check","kp_g3a_u06_division_with_remainder","kp_g3a_u06_quotative_division_packaging","kp_g3a_u06_partitive_division_equal_sharing","kp_g3a_u06_parity_range_missing_digit"]);
const EXPECTED_SPEC_IDS=new Set(["ps_g3a_u06_exact_division_check","ps_g3a_u06_divisibility_exact_check","ps_g3a_u06_division_with_remainder","ps_g3a_u06_quotative_division_packaging","ps_g3a_u06_partitive_division_equal_sharing","ps_g3a_u06_parity_range_missing_digit"]);
const readJson=async p=>JSON.parse(await readFile(new URL(p,import.meta.url),"utf8"));
function plan(overrides={}){return{sourceId:SOURCE_ID,selectionMode:"sourceUnit",questionCount:42,ordering:"shuffleAcrossPatterns",includeAnswerKey:true,generationSeed:"postg-mig-a04-history",goldenContractId:"G5AU08_GOLDEN_V1",goldenContractVersion:"1.0.0",goldenRuntimeMode:"shadow",postGoldenMigrationTaskId:G3A_U06_POSTG_TASK_ID,...overrides};}
function adapted(){const r=adaptGlobalPublicSourceUnitPlan(plan());assert.equal(r.blocked,false,JSON.stringify(r.errors));assert.equal(r.applied,true);return r.plan;}
test("A04 authoritative registry remains closed",async()=>{const r=await readJson("../../data/curriculum/knowledge/units/g3a_u06_3a06.knowledge-operation.json");assert.equal(r.conformanceState,"GOLDEN_CONFORMANT");assert.equal(r.knowledgeRegistryState,"VALIDATED_COMPLETE");assert.equal(r.review.status,"PASS");assert.deepEqual(new Set(r.knowledgePoints.map(x=>x.knowledgePointId)),EXPECTED_KP_IDS);assert.deepEqual(new Set(r.existingQuestionBindings.map(x=>x.questionId)),EXPECTED_SPEC_IDS);});
test("A04 descriptor and shared runtime remain bounded",()=>{const d=resolvePostGoldenSourceUnitAdapterDescriptor(SOURCE_ID);assert.deepEqual(d.expectedCounts,{knowledgePoints:6,patternGroups:6,patternSpecs:6});assert.equal(validatePostGoldenSourceUnitAdapterRegistry().ok,true);assert.equal(validateGlobalPublicSourceUnitAdapters().ok,true);const g=generateBatchABrowserQuestions(adapted());assert.equal(g.ok,true,JSON.stringify(g.errors));assert.equal(g.questions.length,42);assert.deepEqual(new Set(g.questions.map(x=>x.patternSpecId)),EXPECTED_SPEC_IDS);assert.equal(validateBatchABrowserQuestions(g.questions).ok,true);});
test("A04 adapter remains fail-closed without exact authorization",()=>{for(const id of [undefined,"POSTG-MIG-A05_WRONG_TASK"]){const r=adaptGlobalPublicSourceUnitPlan(plan({postGoldenMigrationTaskId:id}));assert.equal(r.applied,false);assert.equal(r.blocked,true);}});
test("A04 historical closeout remains in every later queue state",async()=>{const [program,controller,registry,master]=await Promise.all([readJson("../../data/project/programs/POST_GOLDEN_UNIT_CONFORMANCE_MIGRATION_V1.json"),readJson("../../data/curriculum/golden/POST_GOLDEN_UNIT_CONFORMANCE_MIGRATION_V1.controller.json"),readJson("../../data/curriculum/golden/G5AU08_GOLDEN_V1.unit-conformance.json"),readJson("../../data/curriculum/knowledge/master/POST_GOLDEN_UNIT_CONFORMANCE_MIGRATION_V1.master-index.json")]);assert.ok(program.taskOrder.indexOf(program.lastCompletedTask)>=program.taskOrder.indexOf(G3A_U06_POSTG_TASK_ID));assert.ok(controller.queue.completeSourceIds.includes(SOURCE_ID));const row=registry.rows.find(x=>x.sourceId===SOURCE_ID);assert.equal(row.conformanceStatus,"GOLDEN_CONFORMANT");assert.equal(row.queueState,"COMPLETE");assert.equal(row.goldenProductionEligible,true);const m=master.rows.find(x=>x.sourceId===SOURCE_ID);assert.equal(m.knowledgePointCount,6);assert.equal(m.operationModelCount,6);assert.equal(m.existingQuestionBindingCount,6);assert.equal(m.schemaValidationStatus,"PASS");});
