import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { adaptGlobalPublicSourceUnitPlan, validateGlobalPublicSourceUnitAdapters } from "../../site/modules/curriculum/batch-a/global-public-source-unit-adapter.js";
import { G3A_U02_POSTG_TASK_ID, resolvePostGoldenSourceUnitAdapterDescriptor, validatePostGoldenSourceUnitAdapterRegistry } from "../../site/modules/curriculum/batch-a/global-public-source-unit-adapter-registry.js";
import { generateBatchABrowserQuestions } from "../../site/modules/curriculum/batch-a/batch-a-browser-question-router.js";
import { validateBatchABrowserQuestions } from "../../site/modules/curriculum/batch-a/batch-a-browser-validator.js";
import { getVisiblePatternGroupsForKnowledgePoint, listVisibleBatchAKnowledgePoints } from "../../site/modules/curriculum/registry/batch-a-selector-extension.js";
const SOURCE_ID="g3a_u02_3a02";
const EXPECTED_KP_IDS=new Set(["kp_g3a_u02_add_multi_carry","kp_g3a_u02_sub_multi_borrow","kp_g3a_u02_estimate_nearest_thousand","kp_g3a_u02_word_problem_estimation_add_sub","kp_g3a_u02_add_missing_digit_operand","kp_g3a_u02_sub_missing_digit_operand","kp_g3a_u02_add_missing_digit_equation","kp_g3a_u02_sub_missing_digit_equation","kp_g3a_u02_sub_middle_missing_digit","kp_g3a_u02_continuous_borrow_zero"]);
const EXPECTED_SPEC_IDS=new Set(["ps_g3a_u02_4digit_add_multi_carry","ps_g3a_u02_4digit_sub_multi_borrow","ps_g3a_u02_estimate_nearest_thousand","ps_g3a_u02_word_problem_estimation_add_sub","ps_g3a_u02_add_missing_digit_operand","ps_g3a_u02_sub_missing_digit_operand","ps_g3a_u02_add_missing_digit_equation","ps_g3a_u02_sub_missing_digit_equation","ps_g3a_u02_sub_middle_missing_digit","ps_g3a_u02_continuous_borrow_zero"]);
const readJson=async p=>JSON.parse(await readFile(new URL(p,import.meta.url),"utf8"));
function closeoutPlan(overrides={}){return{sourceId:SOURCE_ID,selectionMode:"sourceUnit",questionCount:40,ordering:"shuffleAcrossPatterns",includeAnswerKey:true,generationSeed:"postg-mig-a02-g3a-u02-closeout",goldenContractId:"G5AU08_GOLDEN_V1",goldenContractVersion:"1.0.0",goldenRuntimeMode:"shadow",postGoldenMigrationTaskId:G3A_U02_POSTG_TASK_ID,...overrides};}
function adaptedPlan(overrides={}){const a=adaptGlobalPublicSourceUnitPlan(closeoutPlan(overrides));assert.equal(a.blocked,false,JSON.stringify(a.errors));assert.equal(a.applied,true);return a.plan;}
test("A02 authoritative registry closes the complete effective selector projection",async()=>{const r=await readJson("../../data/curriculum/knowledge/units/g3a_u02_3a02.knowledge-operation.json");assert.equal(r.conformanceState,"GOLDEN_CONFORMANT");assert.equal(r.knowledgeRegistryState,"VALIDATED_COMPLETE");assert.equal(r.review.status,"PASS");assert.equal(r.knowledgePoints.length,10);assert.equal(r.existingQuestionBindings.length,10);assert.deepEqual(new Set(r.knowledgePoints.map(x=>x.knowledgePointId)),EXPECTED_KP_IDS);assert.deepEqual(new Set(r.existingQuestionBindings.map(x=>x.questionId)),EXPECTED_SPEC_IDS);assert.equal(r.coverage.numeric,"COMPLETE");assert.equal(r.coverage.application,"COMPLETE");});
test("A02 descriptor remains bounded to ten KP, groups and PatternSpecs",()=>{const d=resolvePostGoldenSourceUnitAdapterDescriptor(SOURCE_ID);assert.ok(d);assert.deepEqual(d.expectedCounts,{knowledgePoints:10,patternGroups:10,patternSpecs:10});assert.deepEqual(new Set(d.knowledgePointIds),EXPECTED_KP_IDS);assert.equal(d.patternGroupIds.length,10);assert.deepEqual(new Set(d.patternSpecIds),EXPECTED_SPEC_IDS);assert.equal(validatePostGoldenSourceUnitAdapterRegistry().ok,true);const a=validateGlobalPublicSourceUnitAdapters();assert.equal(a.ok,true,JSON.stringify(a.errors));});
test("A02 existing shared runtime generates and validates all ten PatternSpecs after closeout",()=>{const g=generateBatchABrowserQuestions(adaptedPlan());assert.equal(g.ok,true,JSON.stringify(g.errors));assert.equal(g.questions.length,40);assert.deepEqual(new Set(g.questions.map(x=>x.patternSpecId)),EXPECTED_SPEC_IDS);const v=validateBatchABrowserQuestions(g.questions);assert.equal(v.ok,true,JSON.stringify(v.errors));});
test("A02 adapter remains fail-closed without exact task authorization",()=>{for(const task of [undefined,"POSTG-MIG-A03_WRONG_TASK"]){const a=adaptGlobalPublicSourceUnitPlan(closeoutPlan({postGoldenMigrationTaskId:task}));assert.equal(a.applied,false);assert.equal(a.blocked,true);assert.ok(a.errors.includes("GS05_GOLDEN_UNIT_NOT_REGISTERED"));}});
test("A02 effective selector uses the formal source path and contains no bridge source",()=>{const visible=listVisibleBatchAKnowledgePoints().filter(x=>x.sourceId===SOURCE_ID);assert.deepEqual(new Set(visible.map(x=>x.knowledgePointId)),EXPECTED_KP_IDS);const specs=new Set(visible.flatMap(x=>getVisiblePatternGroupsForKnowledgePoint(x.knowledgePointId).flatMap(g=>g.patternSpecIds??[])));assert.deepEqual(specs,EXPECTED_SPEC_IDS);assert.equal(visible.some(x=>x.sourceId==="g3a_u02_3a02_context_estimate_runtime"),false);});
test("A02 remains closed and authoritative after later queue advances",async()=>{const [p,c,r,m]=await Promise.all([readJson("../../data/project/programs/POST_GOLDEN_UNIT_CONFORMANCE_MIGRATION_V1.json"),readJson("../../data/curriculum/golden/POST_GOLDEN_UNIT_CONFORMANCE_MIGRATION_V1.controller.json"),readJson("../../data/curriculum/golden/G5AU08_GOLDEN_V1.unit-conformance.json"),readJson("../../data/curriculum/knowledge/master/POST_GOLDEN_UNIT_CONFORMANCE_MIGRATION_V1.master-index.json")]);assert.ok(p.taskOrder.indexOf(G3A_U02_POSTG_TASK_ID)>=0);assert.ok(p.completedCount>=3);assert.ok(c.queue.completeSourceIds.includes(SOURCE_ID));const closed=r.rows.find(x=>x.sourceId===SOURCE_ID);assert.equal(closed.conformanceStatus,"GOLDEN_CONFORMANT");assert.equal(closed.goldenProductionEligible,true);assert.equal(closed.queueState,"COMPLETE");assert.ok(m.statusSummary.unitJsonExistsCount>=5);assert.ok(m.statusSummary.knowledgeRegistryCompleteCount>=5);const row=m.rows.find(x=>x.sourceId===SOURCE_ID);assert.equal(row.knowledgePointCount,10);assert.equal(row.operationModelCount,10);assert.equal(row.existingQuestionBindingCount,10);assert.equal(row.schemaValidationStatus,"PASS");});
