import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import {classifyUnitValidationImpact} from "../../tools/governance/classify-unit-validation-impact.mjs";

const policy=JSON.parse(fs.readFileSync(new URL("../../.github/ci/unit-validation-policy.json",import.meta.url),"utf8"));
const template=JSON.parse(fs.readFileSync(new URL("../../data/project/governance/kp-leaf-canonical-validation-template.json",import.meta.url),"utf8"));
const substitutions={TASK_ID:"P04F30_Q030_PREFLIGHT",UNIT_ID:"g4a_u09_4a09",KNOWLEDGE_POINT_ID:"kp_example_q030",VALIDATION_PLAN_PATH:"data/project/validation-plans/P04F30_Q030_PREFLIGHT.validation.json",FOCUSED_NODE_TEST_PATH:"tests/curriculum/p04f-slice030-preflight.test.js",TARGETED_BROWSER_RUNNER_PATH:"tools/curriculum/render-p04f-slice030-product-acceptance.mjs"};
function instantiate(value){if(Array.isArray(value))return value.map(instantiate);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value).map(([key,val])=>[instantiate(key),instantiate(val)]));if(typeof value!=="string")return value;return Object.entries(substitutions).reduce((text,[key,val])=>text.replaceAll(`{{${key}}}`,val),value);}

test("KP leaf canonical template contains the complete classifier metadata contract",()=>{const manifest=instantiate(template.impactManifestTemplate);assert.equal(manifest.currentScope,"KP_LEAF");assert.equal(manifest.currentKnowledgePointId,substitutions.KNOWLEDGE_POINT_ID);assert.deepEqual(manifest.unitExpectedKnowledgePointIds,[substitutions.KNOWLEDGE_POINT_ID]);assert.deepEqual(manifest.unitKnowledgePointGateStatus,{[substitutions.KNOWLEDGE_POINT_ID]:"PENDING"});assert.equal(manifest.expectedDerivedGate,"KP_FOCUSED");assert.equal(manifest.changeImpact.affectedRoutes,"BOUNDED");assert.equal(manifest.changeImpact.sharedExecutableChange,false);assert.equal(manifest.changeImpact.publicAuthorityCutover,false);});

test("instantiated KP leaf canonical template classifies as KP_FOCUSED without full regression or global replay",()=>{const manifest=instantiate(template.impactManifestTemplate),result=classifyUnitValidationImpact({policy,changedFiles:["data/curriculum/example-q030-authority.json","data/project/change-impact/P04F30_Q030_PREFLIGHT.impact.json"],manifest});assert.equal(result.policyConformance,"PASS");assert.equal(result.currentScope,"KP_LEAF");assert.equal(result.derivedGate,"KP_FOCUSED");assert.equal(result.runFullRegression,false);assert.equal(result.runGlobalReplay,false);assert.equal(result.validationPlanPath,substitutions.VALIDATION_PLAN_PATH);});

test("template validation plan names every required KP_FOCUSED gate and uses only allowed step kinds",()=>{const plan=instantiate(template.validationPlanTemplate),steps=plan.lanes.KP_FOCUSED,gateIds=new Set(steps.map(step=>step.gateId));for(const gateId of policy.lanes.KP_FOCUSED.requiredGates)assert.equal(gateIds.has(gateId),true,`missing ${gateId}`);for(const step of steps){assert.equal(policy.validationPlan.allowedStepKinds.includes(step.kind),true);if(step.runtime)assert.equal(policy.validationPlan.allowedRuntimes.includes(step.runtime),true);}assert.equal(steps.some(step=>step.gateId==="TARGETED_BROWSER_E2E"&&step.runtime==="PLAYWRIGHT_CHROMIUM"),true);});

test("classifier still fails closed if expected KP ids are removed from an instantiated template",()=>{const manifest=instantiate(template.impactManifestTemplate);delete manifest.unitExpectedKnowledgePointIds;assert.throws(()=>classifyUnitValidationImpact({policy,changedFiles:["data/curriculum/example-q030-authority.json","data/project/change-impact/P04F30_Q030_PREFLIGHT.impact.json"],manifest}),error=>error?.code==="UIV_UNIT_EXPECTED_KP_IDS_INVALID");});
